- src/components/Skeletons/DataOverview.vue
- src/views/Entities/EntityDataplanes.vue
This was caused when the number of tags exceeded the number of colors available in an array for the tags. The tags were originally going to be different colors but instead were simplified to one color. I've removed the unused code and simplified the tag handling in `DataOverview` and this fixes the error [seen here](https://github.com/Kong/kuma/issues/618).
I admittedly overlooked this because none of my test DPs had more than 8 tags.
Now we can have more than 8 tags with no errors: [screenshot](https://share.getcloudapp.com/qGuovYoG).
> Dataplanes tags error fix

- vue.config.js
This addresses a use case where a user proxies the GUI to a folder, e.g. something like `/kuma-cp/`, inside of a Kubernetes container. By default, Vue's asset path is absolute, which makes all assets 404 in this context. This would resolve that.
> added publicPath to Vue config that sets all public assets to be relative

- src/services/kuma.js
Prevents errors where the GUI can't find Kuma.
> Added an absolute root path to the getStatus() API function

- src/components/Global/Header.vue
- src/views/Overview.vue
- src/views/Wizard/components/StepSkeleton.vue
* [Fix] Left edge of the arrow on the Wizard step indicator did not align in Chrome. Only seems to appear on certain screen resolutions/densities, and/or different browser scales (I was able to trigger it when I scaled Chrome's content to 110%)
* [Fix] Logo scaled improperly width-wise. Chrome is finicky with SVG dimensions
> Chrome bugfixes

- src/store/index.js
This branch should be used in conjunction with [#723](https://github.com/Kong/kuma/pull/723) in the Kuma repo.
This change updates each total count method in the VueX actions to use the `total` parameter from the HTTP API. Each request is also modified to only use a `size` parameter of `1` so that we are not also needlessly fetching a list of entities when we only need the total. This helps reduce API request sizes.
Running Kuma in Universal mode with 20,000 Meshes:
- Size: 100 (the default max) - 17.24kb, ~8ms
- Size: 1 - 256b, ~4ms
_(the above was tested in Firefox)_
> Switch the count in each VueX method for getting entity totals

- src/views/Entities/Dataplanes.vue
There were some old computed values still in place that needed to be replaced. The titles were being derived from them. This PR matches their behavior to the new approach used in other views.
> Undefined titles in tab view of Dataplanes

- .env.development
- src/components/Sidebar/menu.js
- src/components/Utils/OnboardingCheck.vue
- src/router.js
- src/services/kuma.js
- src/services/mock.js
- src/store/index.js
- src/views/Entities/Meshes.vue
- src/views/Overview.vue
- src/views/Policies/CircuitBreakers.vue
This is a new view for handling Circuit Breakers ([#781](https://github.com/Kong/kuma/pull/781)) in Kuma.
After running `yarn serve`, you can access Circuit Breakers at `http://localhost:8080/#/default/circuit-breakers`.
This also adds 3 new Circuit Breaker endpoints:
1. `getAllCircuitBreakers` - This gets all CBs across all Meshes
2. `getAllCircuitBreakersFromMesh` - Gets all CBs from a specific Mesh
3. `getCircuitBreaker` - Get a specific CB from a specific Mesh
> Circuit Breakers

- package.json
- src/assets/styles/components.css
- src/assets/styles/variables.css
- src/components/Global/Header.vue
- src/components/Skeletons/CardSkeleton.vue
- src/components/Utils/UpgradeCheck.vue
- tailwind.config.js
- yarn.lock
This will alert the user if they are running a version of Kuma that is older than the latest version available. It also handles situations where the internet might not be accessible.
* If the internet is accessible from the GUI, this will simply get the version from https://kuma.io/latest_version, compare it to the current version the user is running, and determine whether or not the notice should display
* If the internet is NOT accessible from the GUI, the component will store today's date in localStorage (for accessing it later) and 3 months from that date, it will display the notice
In the offline scenario, the GUI assumes there will be new releases within that 3 month span. We can adjust this gap in the future if needed. While having access to the internet makes this simple, we can …
> Upgrade notice

- .env.development
- src/App.vue
- src/assets/styles/components.css
- src/components/Utils/OnboardingCheck.vue
- src/main.js
- src/router.js
- src/services/mock.js
- src/views/Entities/Dataplanes.vue
- src/views/Wizard/components/StepSkeleton.vue
- src/views/Wizard/components/Switcher.vue
- src/views/Wizard/mixins/updateQuery.js
- src/views/Wizard/views/DataplaneKubernetes.vue
- vue.config.js
This PR covers a list of fixes and improvements for the 0.5.1 release.
* **Fix:** K8s DP wizard: the "Next" control is no longer appearing when selecting a Mesh -- this was caused by missing variable that was commented out but not reintroduced in this single view.
* **Change:** disable the "selected" effect when clicking on a row overview -- in the KTabs component, the tab content has an outline around it when clicked on. This change hides the outline.
* **Fix:** the Expiration Time on the Certificate Insights tab needs to be displayed as a regular date/time, not a human-readable relative one -- in all other instances of time and date being displayed, it's human-readable and relative. For this instance it simply needed to be the date/time itself with no additional modification.
* **Fix / …
> v0.5.1 Fixes

- .env.development
- src/components/Skeletons/DataOverview.vue
- src/components/Utils/EntityURLControl.vue
- src/components/Utils/OnboardingCheck.vue
- src/components/Utils/Tabs.vue
- src/services/kuma.js
- src/services/mock.js
- src/store/index.js
- src/views/Entities/Dataplanes.vue
- src/views/Policies/CircuitBreakers.vue
- src/views/Policies/FaultInjections.vue
- src/views/Policies/HealthChecks.vue
- src/views/Policies/ProxyTemplates.vue
- src/views/Policies/TrafficLogs.vue
- src/views/Policies/TrafficPermissions.vue
- src/views/Policies/TrafficRoutes.vue
- src/views/Policies/TrafficTraces.vue
This PR adds a new feature where users can copy a URL that displays a specific entity's information, vs displaying a list of entities.
On all policy views and the Dataplanes view, there is a new button for copying a link for the selected entity - [screenshot](https://share.getcloudapp.com/2Nu5555P). When clicked it will provide a URL like this:
```
http://localhost:8080#/default/traffic-traces?ns=tt-1
```
The `ns` query stands for `namespace`. When viewing a single item, the view changes slightly and provides a "View All" button to go back to the full list of items from that mesh - [screenshot](https://share.getcloudapp.com/E0uzzzZN)
> Entity routes

- .env.development
- src/components/Skeletons/YamlView.vue
- src/services/mock.js
- src/views/Policies/TrafficPermissions.vue
When viewing Traffic Permissions, there is now a warning when the selected Mesh does not have mTLS enabled. It checks that `mtls` is present in the Mesh entity, as well as if there is a selected backend in `enabledBackend`. If those conditions aren't met, the warning is displayed at the top of the Traffic Permissions page.
If the user is viewing information for all Meshes, this warning doesn't appear since it's specific to the Mesh itself.
> mTLS warning on Traffic Permissions

- .env
- .env.development
- src/App.vue
- src/components/Global/Header.vue
- src/components/Sidebar/MenuList.vue
- src/components/Sidebar/SidebarMenu.vue
- src/components/Sidebar/menu.js
- src/components/Skeletons/DataOverview.vue
- src/components/Skeletons/YamlView.vue
- src/components/Utils/EntityURLControl.vue
- src/components/Utils/Status.vue
- src/router.js
- src/services/kuma.js
- src/services/mock.js
- src/services/restClient.js
- src/store/index.js
- src/views/Entities/Dataplanes.vue
- src/views/Entities/GatewayDataplanes.vue
- src/views/Entities/IngressDataplanes.vue
- src/views/Entities/LocalCPs.vue
- src/views/Entities/Meshes.vue
- src/views/Entities/RemoteCP.vue
- src/views/Onboarding/GetStarted.vue
- src/views/Overview.vue
- src/views/Policies/ProxyTemplates.vue
- src/views/Wizard/components/StepSkeleton.vue
- src/views/Wizard/views/DataplaneKubernetes.vue
This PR adds multiple items to take advantage of Multicluster mode when it's enabled, and offers new views for LocalCPs, Ingresses, etc. [Here is a list](https://gist.github.com/bloqhead/cf3745030c3328e3d926774bb2efbfff) of other items this PR will also encompass.
> Multicluster features

- .env.development
- .env.production
- src/main.js
This PR changes the location from which the API endpoint is fetched. This PR depends on [#915](https://github.com/kumahq/kuma/pull/915) in the Kuma repository.
Prior to this change, we were fetching the Kuma GUI config from `:5683`. This condenses things down so that the GUI and the API are fetched from the same location, with the GUI being served from `:5681/gui/` and the API being fetched from `:5681/`.
> Kuma API location revisions

- .env.development
- src/services/kuma.js
- src/services/mock.js
- src/views/Entities/RemoteCP.vue
This is dependent upon [#921](https://github.com/kumahq/kuma/pull/921) in the Kuma repository.
I've renamed the REST API commands so that they're more in line with the naming in Kuma. I've also added 2 mock endpoints so that these changes can be tested locally if there are no zones created in Kuma (mocks can be disabled in `.env.development` -- the app must be restarted for this change to take effect).
Right now, the Remote CPs page is only fetching data from `http://localhost:5681/status/zones`.
> Remote CP endpoint revisions

- src/components/Skeletons/DataOverview.vue
- src/services/mock.js
- src/views/Wizard/views/DataplaneKubernetes.vue
- src/views/Wizard/views/DataplaneUniversal.vue
This PR depends on [#910](https://github.com/kumahq/kuma/pull/910) in the Kuma repository.
This PR makes the following changes to the native Kuma tags:
* `service` -> `kuma.io/service`
* `protocol` -> `kuma.io/protocol`
Both the Universal and Kubernetes Wizards are also updated to reflect these changes.
> Prefixing Kuma native tags with `kuma.io`

- .env.development
- src/components/Global/Header.vue
- src/components/Metrics/MetricGrid.vue
- src/components/Sidebar/MenuList.vue
- src/components/Sidebar/menu.js
- src/components/Skeletons/DataOverview.vue
- src/helpers.js
- src/router.js
- src/services/mock.js
- src/store/index.js
- src/views/Entities/Dataplanes.vue
- src/views/Entities/GatewayDataplanes.vue
- src/views/Entities/IngressDataplanes.vue
- src/views/Entities/Meshes.vue
- src/views/Entities/Zones.vue
- src/views/Overview.vue
- src/views/Policies/CircuitBreakers.vue
- src/views/Policies/FaultInjections.vue
- src/views/Policies/HealthChecks.vue
- src/views/Policies/ProxyTemplates.vue
- src/views/Policies/TrafficLogs.vue
- src/views/Policies/TrafficPermissions.vue
- src/views/Policies/TrafficRoutes.vue
- src/views/Policies/TrafficTraces.vue
This PR contains some updates and improvements for the Dataplanes view, as well as adds some helpers and updates for other views.
> Various Dataplane view revisions

- src/App.vue
- src/main.js
- src/services/restClient.js
- src/views/Entities/Zones.vue
This fix addresses an issue where the `next` parameter in the Zones endpoint wasn't being handled properly.
* Changed the way `mode` is fetched so that it aligns with the API changes to Kuma (`mode` used to be nested in `mode.mode` but this has changed to simply be `mode`)
* Added a check for development mode so that the GUI serves properly from `http://localhost:8080/` in this repo, but defaults to `http://[user-ip]/gui/` in production mode (from within Kuma itself)
> Zones `next` handling

- src/views/Entities/Dataplanes.vue
- src/views/Entities/GatewayDataplanes.vue
- src/views/Entities/IngressDataplanes.vue
It was being inserted as a String when it should've been an Integer. Fixes [#954](https://github.com/kumahq/kuma/issues/954) on Kuma.
> totalUpdates Type fix

- src/components/Skeletons/DataOverview.vue
- src/components/Utils/LoaderCard.vue
- src/helpers.js
- src/services/mock.js
- src/views/Entities/Dataplanes.vue
- src/views/Entities/Zones.vue
These changes expand on the Zones view considerably. On the Zones page (`http://localhost:8080/#/zones` -- must be running Kuma in Multi-Zone mode to test), there is now a new tab titled "Zone Insights" that shows subscription information, global instance ID, connect and disconnect times, etc.
The amount of information displayed can be scaled back accordingly.
> Zone Insights

- src/views/Entities/IngressDataplanes.vue
Removed Mesh column since Ingress should be in default mesh anyways and works with many meshes. Added public address and port columns
> feat(ingress) add columns with coordinates

- .eslintrc.js
- src/components/Sidebar/Sidebar.vue
This change makes it so that the subnav items are visible at all times and not just when the user clicks the parent item. This no longer relies on a localStorage value.
> Sidebar flyout state revision

- .eslintrc.js
- src/services/mock.js
- src/views/Policies/TrafficPermissions.vue
The problem was that I was not looking inside of `spec` for `mtls` when fetching from the Traffic Permissions endpoint in Kubernetes mode. So the warning was working properly on Universal, but not on Kubernetes. This change makes it now conditionally aware of where to look.
> mTLS warning fix for the Traffic Permissions view

- src/dataplane.js
- src/helpers.js
- src/views/Entities/Dataplanes.vue
- src/views/Entities/GatewayDataplanes.vue
- src/views/Entities/IngressDataplanes.vue
- src/views/Entities/StandardDataplanes.vue
I noticed that tags in Ingress tab are broken so I looked into algorithm and noticed a couple of problems
* Ingress does not have tags in `networking.ingress.tags`, we should just list from the inbounds
* We cannot just take `inbound[0].tags` because they might be more tags
* There were two algorithms to display tags spread across 3 files, I created one function in `src/dataplane.js`
Some additional small stuff
* In ingress there should be no Certificate Insights in overview
* restored this one https://github.com/kumahq/kuma-gui/pull/82 because it was lost for some reason
> fix: display dp tags

- src/views/Wizard/views/DataplaneKubernetes.vue
After done with the k8's data plane setup there is a link to redirect to `/dataplanes`, the redirection URL has an additional `namespace` paramwhich upon redirection fails to load data on the data plane page. so, removed the param
> fix dataplane to view url in k8's onboarding

- src/components/Sidebar/menu.js
- src/router.js
- src/services/kuma.js
- src/views/Entities/ExternalServices.vue
- src/views/Entities/InternalServices.vue
I did not implement `All` because
1) We don't have an endpoint to aggregate ServiceInsights and ExternalServices and support pagination etc.
2) What would be the columns in the list? "Online dataplanes" does not make sense on external services and address does not make sense for internal services
Overall it can be done but with much work which I'd argue give not that much value.
Views are essentially copy paste with renaming with this modification
```
this.tableData.data = this.tableData.data.map(entity => {
entity.address = entity.networking.address
entity.tlsEnabled = entity.networking.tls.enabled ? 'Enabled' : 'Disabled'
return entity
})
```
```
this.tableData.data = this.tableData.data.map(entity => {
// API can skip the field if there is no stat
entity.offline = entity.offline || 0 …
```
> feat(services) Internal and External services in the GUI

- src/components/Metrics/MetricGrid.vue
- src/components/Sidebar/menu.js
- src/store/index.js
- src/views/Overview.vue
- yarn.lock
Added cards with numbers of internal and external services in dataplane
overviews + moved services block at top of `DATA PLANE PROXIES` section
in the sidebar.
Here are the screens reflecting the changes:
> feat(*) add services to overview

- src/components/Sidebar/Subnav.vue
So far if your screen was not able to show all elements and you needed
scroll, last elements were "cut" and not visible in the menu (even if
you tried to scroll to them)
This fix is not perfect as there is too much trickery/calculations going
on and to properly fix that it would involve full rewrite of sidebar
components, but it should work for now.
> fix(*) missing last items in sidebar

- .env.development
- src/components/Skeletons/DataOverview.vue
- src/services/mock.js
This change adds horizontal scrolling on the DataOverview table container for instances where they are super wide. This will prevent the tables from jutting out of their parent container.
> Table overflow fix

- src/components/OverviewCharts.vue
- Removed `ticks` (as I learned they are called) below the labels
in charts
- If charts is redirecting somewhere after the click, I changed
the cursor on `hover` to `pointer`
- Lowered a little bit opacity on active chharts (the ones with
the data inside), and after hovering over them if they are
redirecting somewhere the opacity is increasing to 1 again
- Removed unnecessary tooltips as the same data are currently
displayed in the labels
- As there are no animations, I removed unnecessary `inert`
property
TODO:
- In the future we should add the tooltip which follows the mouse
cursor if we are hovering over the charts which after clicking
on will redirect us somewhere, with the example message:
`Go to Dataplanes...`
https://user-images.githubusercontent.com/11655498/105574411-ad449d80-5d64 …
> style() overview charts style improvements

- src/mixins/PieChart.js
If there is a license for amcharts provided, there is no `this.chart.logo` present
> fix(charts) check if there is chart logo before

- src/dataplane.ts
With this changes, API endpoint with supported versions can return not only explicitly specified full versions, but also things like:
```
"1.1.*": {
"envoy": "~1.17.0"
}
```
> feat(*) allw use of patterns in supported versions

- src/services/restClient.ts
According to specification of `fetch` API (in refs), field
`statusText` will be empty in `HTTP 2`, and it was causing problems
as there is inconsistency and everything was working fine
in Firefox, as it looks like they are not following
very strictly this part of the specification and even in `HTTP 2`
this field was equal `OK`, but it was not working on Chrome
refs.
https://fetch.spec.whatwg.org/#concept-response-status-message
> fix(restClient) status fetching

- .env
- src/components/Resources.vue
- src/components/Utils/EnterpriseBox.vue
- src/components/Utils/UpgradeCheck.vue
- src/views/Onboarding/Complete.vue
- src/views/Overview.vue
- src/views/Wizard/views/Mesh.vue
I've added the UTM strings `utm_source` and `utm_medium` to URLs that go to the Kuma website from within the GUI so that we can track these events accordingly in Google Analytics.
> UTM strings for Google Analytics

- src/components/Skeletons/YamlView.vue
- src/views/Entities/Zones.vue
As we are in the process of renaming `Remote CP` to `Zone CP` for the new release, this PR reflects these changes in our GUI
> chore(*) rename remote-cp to zone-cp

- src/views/Onboarding/Complete.vue
- src/views/Wizard/views/Mesh.vue
As html section of view components doesn't have access to global
variable `process`, we have to provide it as a part of stadard
data flow
> fix(*) onboarding and wizard view fix

- src/views/Entities/ExternalServices.vue
GUI was crashing when received response with external service
without specified (even empty) `networking.mtls` block
> fix(*) ExternalServices view when empty mtls block

- src/views/Wizard/views/DataplaneUniversal.vue
Fix the dataplane token command. The `--dataplane` flag ought to be
`--name`.
This fixes #168.
Signed-off-by: James Peach <james.peach@konghq.com>
> chore(*) fix dataplane token command

- src/views/Entities/GatewayDataplanes.vue
- src/views/Entities/StandardDataplanes.vue
- src/views/Entities/partial/Dataplanes.vue
The issue was because we weren't passing `dataplane` param into the function. After it has been provided, the issue is gone.
Also, it will remove `getDataplaneType` from being a prop as we have a generic function that is handling that behaviour properly.
Also removed `addDataFields` as it was doing nothing and did a small refactor following the boy scout rule.
Screenshots:
> fix(*) fix wrong dp type

- DEVELOPER.md
- package.json
- public/mockServiceWorker.js
- src/main.ts
- src/services/kuma.ts
- src/services/mock.ts
- src/services/restClient.ts
- yarn.lock
In this PR we are going to replace `axios-mock-adapter` with [msw](https://github.com/mswjs/msw).
The reason behind that decision is whats written in FAQ of MSW [link](https://mswjs.io/docs/faq)
> most solutions provide requests interception on the application level, while Mock Service Worker intercepts requests on the network level. It also allows you to use the same mock definition not only for testing but for development and debugging as well.
Also with `axios-mock-adapter` it was impossible to see the whole flow, as it was mocking request before it was called ane because of that there was no request in the network which makes it harder to follow from where the data comes.
> feat(*) add msw as mock for requests

- src/assets/styles/main.scss
It fixes a bug reported in: https://github.com/kumahq/kuma-gui/issues/183
Because tailwind set default appearance in Safari we need to disable it to allow us doing changes to how buttons look like.
> bug(*) fix issue on safari with wrongly displayed buttons

- src/components/KLoader.spec.ts
- src/components/KLoader.vue
- src/components/__snapshots__/KLoader.spec.ts.snap
It fixes an issue presented in #135  by disabling the possibility of width in the loader to exceed 100%.
Also, it adds a test that checks the behavior.
> bug(*) fix wrong loading values

- src/views/Overview.vue
In https://github.com/kumahq/kuma-gui/pull/179 when routes have been changed, we didn't update routes in overview. This PR fixes that issue.
> bug(*) fix wrong urls in overview

- src/App.vue
- src/main.ts
- src/router.ts
- src/store/index.ts
- src/views/Shell.vue
We no longer want to display onboarding for users which already have fulfilled the condition to display onboarding popup. 
So we are redirecting into onboarding view only if the user has default mesh and no dataplanes and did not seen already the onboarding view. In any other case we are no longer redirecting into onboarding and if user try to open that page it will be redirected into global overview.
As right now we have to wait in the router to make sure we can check condition if the page should be displayed or not (so we need to wait till all bootstrap action will be resolved, and `globalLoading` will change into `false`) it caused a flash of the blank screen after loading is finished (movie below). To avoid that I provided a delay on change on loading in `App.vue` to make sure that …
> feat(*) disable onboarding when no requirement fulfilled to display it

- src/components/Sidebar/NavItem.spec.ts
- src/components/Sidebar/NavItem.vue
- src/components/Sidebar/__snapshots__/NavItem.spec.ts.snap
- src/components/Utils/MeshSelector.vue
When we open a page on "zones" or "zone ingress" and then refresh and change from "all meshes" into a different one and try to access some other page - we will be redirected to overview with URL pointing to "all" instead of specific mesh and with wrong data displayed.
https://user-images.githubusercontent.com/16152347/129707151-d800757c-eaf1-450a-9ff7-7b2b24213b03.mov
https://user-images.githubusercontent.com/16152347/129707535-91b1f1f1-64a7-46d2-8b7f-df8938d2d568.mov
> bug(*) set proper route on click

- src/store/index.ts
- src/store/reducers/mesh-insights.ts
- src/views/Entities/Meshes.vue
As we introduced `mesh-insights` some time ago, there is no longer a need to request for each policy/dataplanes etc. independently, as we can retrieve it from aggregated data.
Because of that, it allows us to remove a lot of code and simplify the logic.
> refactor(*) cleanup of vuex store

- src/services/mock/responses/external-services.json
- src/views/Entities/partial/Services.vue
In https://github.com/kumahq/kuma/issues/2728 it was reported that external services are not displayed properly.
The reason behind it was the part of refactoring which was done in https://github.com/kumahq/kuma-gui/pull/193 where the typo made it call the wrong endpoint. This PR fixes that issue.
> bug(*) missing service info

- package.json
To have an option to use netlify and build an app we need to have a build which contains service worker which provides `msw` option to mock request.
That's the reason why this PR provides new command `build:ci` which builds an app in development mode.
> feat(*) add new command to package.json

- src/views/Entities/ZoneIngresses.spec.ts
- src/views/Entities/Zones.spec.ts
- src/views/Entities/__snapshots__/ZoneIngresses.spec.ts.snap
- src/views/Entities/__snapshots__/Zones.spec.ts.snap
- src/views/Entities/components/MultizoneInfo.vue
Zone and ZoneIngresses both had hardcoded (and broken) docs links. Fixed these by grabbing the current version (similar to the way other components did).
Signed-off-by: John Harris john.harris@konghq.com
> Fix hardcoded docs links.

- src/components/Skeletons/DataOverview.spec.ts
- src/components/Skeletons/DataOverview.vue
- src/components/Skeletons/__snapshots__/DataOverview.spec.ts.snap
Previously when we wanted to add a custom "display" for any key, we had to add it into DataOverview which caused enormous growth of that component. The change will allow passing slot through it - so instead of having all in DataOverview we will be able to leave dependency in a place where it's needed.
> feat(dataoverview) Add possibility to add custom slots into dataoverview

- src/components/EntityTag/EntityTag.spec.ts
- src/components/EntityTag/EntityTag.vue
- src/components/EntityTag/__snapshots__/EntityTag.spec.ts.snap
- src/components/Skeletons/DataOverview.vue
- src/components/Skeletons/__snapshots__/DataOverview.spec.ts.snap
Previously we had tags hardcoded in DataOverview component. This PR will extract it, reducing size of that component and making it reusable in other places.
> refactor(dataoverview) extract tags

- src/components/Utils/EntityURLControl.spec.ts
- src/components/Utils/EntityURLControl.vue
- src/components/Utils/__snapshots__/EntityURLControl.spec.ts.snap
- src/views/Entities/Meshes.vue
- src/views/Entities/partial/Dataplanes.vue
- src/views/Entities/partial/Services.vue
- src/views/Policies/CircuitBreakers.vue
- src/views/Policies/FaultInjections.vue
- src/views/Policies/HealthChecks.vue
- src/views/Policies/ProxyTemplates.vue
- src/views/Policies/RateLimits.vue
- src/views/Policies/Retries.vue
- src/views/Policies/Timeouts.vue
- src/views/Policies/TrafficLogs.vue
- src/views/Policies/TrafficPermissions.vue
- src/views/Policies/TrafficRoutes.vue
- src/views/Policies/TrafficTraces.vue
Previously when clicked on  copy url (attachment) it copied wrong URL (http://localhost:5681#/mesh/default/circuit-breakers?ns=circuit-breaker-all-default)
Right now it should copy the proper URL which allows sharing link to a specific resource.
> fix(*) properly create share url

- src/components/NotificationManager/NotificationManager.vue
- src/views/Shell.vue
- src/views/__snapshots__/Shell.spec.ts.snap
Fix bug which doesn't allow to open notification when onboarding alert displayed. 
> fix(*) allow to open notification modal when onboarding enabled

- src/components/Sidebar/menu.ts
- src/dataplane.ts
- src/services/kuma.ts
- src/store/index.ts
- src/store/modules/sidebar/sidebar.ts
- src/utils/tableDataUtils.spec.ts
- src/utils/tableDataUtils.ts
- src/utils/tableDataUtils.types.ts
- src/views/Entities/Meshes.vue
- src/views/Entities/ZoneIngresses.vue
- src/views/Entities/Zones.vue
- src/views/Entities/partial/Dataplanes.vue
- src/views/Entities/partial/Services.vue
- src/views/Policies/CircuitBreakers.vue
- src/views/Policies/FaultInjections.vue
- src/views/Policies/HealthChecks.vue
- src/views/Policies/ProxyTemplates.vue
- src/views/Policies/RateLimits.vue
- src/views/Policies/Retries.vue
- src/views/Policies/Timeouts.vue
- src/views/Policies/TrafficLogs.vue
- src/views/Policies/TrafficPermissions.vue
- src/views/Policies/TrafficRoutes.vue
- src/views/Policies/TrafficTraces.vue
- src/views/Wizard/views/DataplaneKubernetes.vue
- src/views/Wizard/views/DataplaneUniversal.vue
- src/views/Wizard/views/Mesh.vue
The reason of this refactor is to align the format of parameters in API calls.
This will allow to easy access a single entity (in case of share-url or one entity table view) no matter if it's mesh-related or not, whereas previously we were limited to mesh-related resources.
> refactor(api) change format

- src/components/PolicyConnections/PolicyConnections.spec.ts
- src/components/PolicyConnections/PolicyConnections.vue
- src/components/PolicyConnections/__snapshots__/PolicyConnections.spec.ts.snap
- src/services/kuma.ts
- src/services/mock/responses/policy-connections.json
- src/services/mocks.ts
- src/views/Entities/Meshes.vue
- src/views/Entities/partial/Dataplanes.vue
- src/views/Entities/partial/Services.vue
- src/views/Policies/CircuitBreakers.spec.ts
- src/views/Policies/CircuitBreakers.vue
- src/views/Policies/FaultInjections.vue
- src/views/Policies/HealthChecks.vue
- src/views/Policies/ProxyTemplates.vue
- src/views/Policies/RateLimits.vue
- src/views/Policies/Retries.vue
- src/views/Policies/Timeouts.vue
- src/views/Policies/TrafficLogs.vue
- src/views/Policies/TrafficPermissions.vue
- src/views/Policies/TrafficRoutes.vue
- src/views/Policies/TrafficTraces.vue
Provide a new tab "Affected DPPs" for every policy which contains all dpps (and direct link to them) which are affected by the selected policy.
> feat(policies) add Affected DPPs tab for every policy

- src/components/DocumentationLink/DocumentationLink.spec.ts
- src/components/DocumentationLink/DocumentationLink.vue
- src/components/DocumentationLink/__snapshots__/DocumentationLink.spec.ts.snap
- src/views/Policies/CircuitBreakers.vue
- src/views/Policies/FaultInjections.vue
- src/views/Policies/HealthChecks.vue
- src/views/Policies/ProxyTemplates.vue
- src/views/Policies/RateLimits.vue
- src/views/Policies/Retries.vue
- src/views/Policies/Timeouts.vue
- src/views/Policies/TrafficLogs.vue
- src/views/Policies/TrafficPermissions.vue
- src/views/Policies/TrafficRoutes.vue
- src/views/Policies/TrafficTraces.vue
It will finish #273 and provide a button that opens documentation related to selected policy in the new window.
> feat(policies) add documentation link

- src/views/Wizard/views/Mesh.vue
Remove ca option from wizzard which is not available.
> fix(wizzard) remove ca option from wizzard

- src/components/DataplanePolicies/DataplanePolicies.spec.ts
- src/components/DataplanePolicies/DataplanePolicies.vue
- src/components/DataplanePolicies/__snapshots__/DataplanePolicies.spec.ts.snap
- src/services/mock/responses/dataplane-policies.json
Instead of cryptic listeners addresses, we added `service` field to API so we can display it in the GUI. I pushed inbound/outbound address to subtitle.
Also, `dataplane` type of attachment was not handled. Name and Service, in this case, is empty, so we want to just display `Dataplane`.
> feat(policies): more user friendly inspection of policies

- src/views/Entities/Zones.vue
- src/views/Entities/__snapshots__/Zones.spec.ts.snap
Add a `Egress` column to the Zone Overview page analagous to the `Ingress` column.
Closes #307
> feat(zoneegress): add Egress column to Zone overview

- src/views/Entities/ZoneEgresses.spec.ts
- src/views/Entities/ZoneEgresses.vue
- src/views/Entities/__snapshots__/ZoneEgresses.spec.ts.snap
Zone Egress can be deployed in standalone mode, but GUI doesn't present data if the mode is different than multizone. Removed part of the code that was responsible for that and now the user is allowed to see zone egress instances in standalone mode.
> fix(zoneegress): show zoneegress instances in standalone mode

- src/components/Sidebar/Sidebar.spec.ts
- src/components/Sidebar/__snapshots__/Sidebar.spec.ts.snap
- src/components/Sidebar/menu.ts
- src/consts.ts
- src/services/mock/responses/config.json
- src/store/modules/config/config.ts
- src/store/modules/config/config.types.ts
- src/views/Entities/Meshes.vue
- src/views/Entities/__snapshots__/Meshes.spec.ts.snap
- src/views/__snapshots__/Shell.spec.ts.snap
As meshgateway is now available without the need of experimental
flag (flag was even removed) we should display routes related
to it by default
Closes https://github.com/kumahq/kuma-gui/issues/328
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits): 👍 
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)?: 👍
> chore: remove meshgateway experimental flag

- package.json
- yarn.lock
Updates the node-sass package (for its breaking changes, see: https://github.com/sass/node-sass/releases/tag/v7.0.0).
Changes the required Node.js/npm versions in the package.json to more modern versions (Node.js: >=4 to >=14, npm: >=3 to >=7).
Supersedes #302. See also https://github.com/kumahq/kuma-gui/issues/339.
> chore(deps): update node-sass

- package.json
- src/components/EnvoyClusters/EnvoyClusters.vue
- src/components/EnvoyStats/EnvoyStats.vue
- src/components/Global/Header.vue
- src/components/NotificationManager/components/SingleMeshNotifications.vue
- src/components/Utils/Tabs.vue
- src/components/XdsConfiguration/XdsConfiguration.vue
- src/dataplane.ts
- src/helpers.ts
- src/main.ts
- src/router.ts
- src/services/restClient.ts
- src/store/modules/config/config.ts
- src/store/modules/notifications/notifications.ts
- src/store/modules/sidebar/sidebar.ts
- src/utils/tableDataUtils.ts
- src/views/Entities/Meshes.vue
- src/views/Entities/ZoneEgresses.vue
- src/views/Entities/ZoneIngresses.vue
- src/views/Entities/Zones.vue
- src/views/Entities/partial/Dataplanes.vue
- src/views/Onboarding/AddNewServicesCode.vue
- src/views/Onboarding/MultiZone.vue
- src/views/Onboarding/Welcome.vue
- src/views/Wizard/views/DataplaneUniversal.vue
- yarn.lock
Updates `@vue/cli-*` and `webpack-bundle-analyzer` (breaking change only drops support for older Node.js versions, see https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/CHANGELOG.md) packages. Reduces the number of critical vulnerabilities being reported by 17 (from 20).
Fixes incorrect import orders. The import order rule was affected by the update to the `@vue/cli-*` packages.
> chore(deps): upgrade critically vulnerable dependencies

- src/utils/tableDataUtils.spec.ts
- src/utils/tableDataUtils.ts
- src/utils/tableDataUtils.types.ts
- src/views/Policies/PolicyView.vue
Fixes a bug with not calling endpoints retrieving all entities correctly. The query parameters for the endpoints wouldn’t always be passed to the underlying request library leading to issues like showing all dataplanes instead of just those of a specific type.
Fixes #352.
> fix: not calling all entities endpoints correctly

- src/components/DataplanePolicies/DataplanePolicies.vue
- src/services/mock/responses/dataplane-policies.json
Changes the dataplane policies tab to not crash when receiving data associated to mesh gateway dataplanes whose API responses use a wholly different format than what the current code is able to process.
Related to #351.
> chore: avoid crash in dataplane policies tab

- .github/workflows/create-gui-pr.yml
- .github/workflows/main.yml
Adds a new GitHub Actions workflow which automatically creates a pull request in Kuma for updating Kuma GUI.
Limits the main workflow’s triggers for pushes to the project’s default branch.
Implements #367.
> feat: adds Kuma GUI update PR job

- package.json
- src/components/BreadcrumbsMenu.vue
- src/components/NotificationManager/NotificationManager.vue
- src/components/PolicyConnections/PolicyConnections.vue
- src/components/Sidebar/NavItem.spec.ts
- src/components/Sidebar/NavItem.vue
- src/components/Sidebar/__snapshots__/NavItem.spec.ts.snap
- src/components/Sidebar/menu.ts
- src/components/Utils/MeshSelector.vue
- src/helpers.ts
- src/views/Entities/MeshesView.vue
- src/views/Entities/ZoneEgresses.vue
- src/views/Entities/ZoneIngresses.vue
- src/views/Entities/ZonesView.vue
- src/views/Entities/partial/DataplanesView.vue
- src/views/Entities/partial/ServicesView.vue
- src/views/Onboarding/components/OnboardingNavigation.vue
- src/views/Policies/PolicyView.vue
- src/views/Wizard/components/StepSkeleton.vue
- src/views/Wizard/views/DataplaneKubernetes.vue
- yarn.lock
Fixes an issue with not resetting a component’s boolean states when switching between meshes.
Fixes an issue with setting route params for links whose target routes don’t have params. This is no longer working (see https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#414-2022-08-22).
Updates vue-router explicitly to incorporate the breaking change from https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#414-2022-08-22.
Removes the params from route navigations in the onboarding components as the respective routes don’t actually have this param declared or use it.
Removes some dead code.
Changes the permitted version ranges for TypeScript to only patch versions because apparently TypeScript isn’t semantically versioned (see …
> fix: not resetting state when switching between meshes

- .github/workflows/create-gui-pr.yml
Moves the skip CI marker into the commit message to actually skip all CircleCI checks.
> chore(ci): moves skip ci marker into commit message

- src/views/Wizard/views/Mesh.vue
- src/views/Wizard/views/__snapshots__/Mesh.spec.ts.snap
Fixes an issue with the mesh creation wizard creating an incorrect traffic tracing policy with the `sampling` property being under `conf`.
Fixes #334.
> fix: tracing having wrong sampling property location

- src/views/Entities/ZonesView.vue
- src/views/Entities/__snapshots__/ZonesView.spec.ts.snap
Renames the “Backend” table header in the Zones CPs table to “Storage type”.
Fixes #306.
> chore: renames backend table header to storage type

- vite.config.js
Fixes an issue with bundles being injected in the resulting index.html relative to the document root (`/`) which breaks the GUI when served from a path that’s not the document root (e.g. being served on `/gui`).
> fix: bundles being referenced relative to document root

- src/data-planes/components/DataPlaneDetails.vue
- src/data-planes/views/DataPlaneListView.vue
- src/dataplane.ts
- src/views/Entities/components/WarningDefault.vue
- src/views/Entities/components/WarningEnvoyIncompatible.vue
- src/views/Entities/components/WarningUnsupportedKumaDPVersion.vue
- src/views/Entities/components/WarningZoneAndGlobalCPSVersionsIncompatible.vue
- src/views/Entities/components/WarningZoneAndKumaDPVersionsIncompatible.vue
Fixes an issue with making repeated (and often duplicated) requests to the `zones+insights/:zone` API endpoint in the data plane list view. This happened because of version incompatibility checks. <del>Now, the the general zones overview is fetched before processing individual data planes which is generally better because data planes, if they are associated to a zone, don’t often have unique zones making the size of the response of the `zones+insights` endpoint smaller than the the added sizes of one `zones+insights/:zone` response **per data plane** (which often have the same zone)</del><ins>The API requests to the zone insights endpoint have been removed completely because the data plane insight data already contains knowledge of CP version incompatibilities which we now rely on</ins>. …
> fix: making repeated requests to zones+insights

- src/app/AppSidebar.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/services/views/ServiceListView.vue
- src/store/index.ts
Fixes a bug with accessing the `items` field in a response which is now omitted if empty.
Fixes the polling interval accidentally being set to 2 seconds from testing.
> fix: accessing omitted items field

- src/app/data-planes/views/DataPlaneListView.vue
- src/app/data-planes/views/__snapshots__/DataPlaneListView.spec.ts.snap
- src/types/index.d.ts
- src/utilities/dataplane.ts
Fixes an issue where one of the gateway types was called "provided" instead of "delegated".
Fixes #437.
> fix(data-planes): calling gateway type provided

- src/api/mock-data/policies.json
- src/app/__snapshots__/AppSidebar.spec.ts.snap
- src/app/policies/views/PolicyView.vue
- src/store/reducers/__snapshots__/mesh-insights.spec.ts.snap
- src/store/reducers/mesh-insights.ts
Fixes an issue where internal route data was rendered as part of configurations.
Updates the mock data for policies.
> fix: route data being shown in configurations

- package.json
- src/app/App.spec.ts
- src/app/AppHeader.vue
- src/app/__snapshots__/App.spec.ts.snap
- yarn.lock
Adds a standard GH star button next to the Kuma logo in the header
Probably worth noting this doesn't actually star the project only links to the repo on GH
Fixes https://github.com/kumahq/kuma-gui/issues/428 
> feat: Add a GH Star button

- src/app/wizard/views/Mesh.spec.ts
- src/app/wizard/views/Mesh.vue
- src/app/wizard/views/__snapshots__/Mesh.spec.ts.snap
Makes the command dynamic depending on which tab you have selected, plus
adds some data-test-* attributes for testing purposes
Fixes https://github.com/kumahq/kuma-gui/issues/451
> fix: Show correct 'ctl command in mesh wizard code block

- src/api/mock-data/meshes/default/circuit-breakers.json
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/policies/views/PolicyView.vue
- src/app/services/views/ServiceListView.vue
- src/app/zones/views/ZoneEgresses.vue
- src/app/zones/views/ZoneIngresses.vue
- src/app/zones/views/ZonesView.vue
- src/router/getLastParameter.ts
- src/router/router.ts
Fixes pagination not working correctly on some pages.
Adds the logic for persisting the pagination offset in the URL so reloading reloads the page the user was on.
Fixes #441.
> fix: pagination not working correctly

- src/app/data-planes/constants.ts
- src/app/data-planes/views/DataPlaneListView.spec.ts
- src/app/data-planes/views/__snapshots__/DataPlaneListView.spec.ts.snap
- src/app/policies/views/PolicyView.vue
- src/app/services/views/ServiceListView.vue
Removes the `Mesh` column from all list views (Dataplane Proxies, Services and Policies)
Fixes https://github.com/kumahq/kuma-gui/issues/472
> feat: Remove mesh column from all list views 

- .github/dependabot.yml
Provides dependabot configuration to keep npm and github-actions up-to-date.
This is based on [kuma configuration](https://github.com/kumahq/kuma/blob/master/.github/dependabot.yml) 
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
> chore(deps): setup dependabot

- src/app/data-planes/components/DataPlaneDetails.vue
- src/app/data-planes/components/DataPlaneEntitySummary.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/types/index.d.ts
- src/utilities/dataplane.ts
Fixes a premature access to the `dataplaneInsight` property which can be absent.
Fixes #475.
> fix: accessing dataplaneInsight prematurely

- package.json
- src/app/common/UpgradeCheck.spec.ts
- src/app/common/UpgradeCheck.vue
- yarn.lock
Removes semver-compare in favor of using the semver provided compare function. We had both packages installed and only used semver-compare. The latter has last been updated 8 years ago and its source code is no longer available.
> chore(deps): removes semver-compare

- .github/workflows/main.yml
- package.json
- src/app/common/charts/DonutChart.vue
- src/app/data-planes/components/DataplanePolicies.spec.ts
- src/app/onboarding/components/OnboardingNavigation.spec.ts
- src/app/policies/components/PolicyConnections.spec.ts
- src/app/policies/components/PolicyConnections.vue
- src/app/policies/views/PolicyView.spec.ts
- src/app/services/components/ServiceDetails.spec.ts
- src/types/index.d.ts
- yarn.lock
Adds `vue-tsc` and adds a run of that to CI so tests break/merging is blocked if the types are incorrect.
When I brought this in there were a few little problems unrelated to what I'm working on, so I just fixed those up real quick so we are passing from the start. Going forwards this will catch any Vue related TS errors in CI and consequently any related JS errors that we don't have tests around as yet.
---
Unrelated: I noticed we were using mostly `yarn` in the GH action, with one reference to `npm` so I changed that up while I was there, ah plus I fixed a little typo I noticed while I was there.
> ci: Lint Vue Typescript

- src/app/__snapshots__/App.spec.ts.snap
- src/app/common/DataOverview.vue
- src/app/common/DocumentationLink.vue
- src/app/common/NotificationIcon.vue
- src/app/common/PaginationWidget.vue
- src/app/common/__snapshots__/DocumentationLink.spec.ts.snap
- src/app/common/__snapshots__/PaginationWidget.spec.ts.snap
- src/app/data-planes/views/__snapshots__/DataPlaneListView.spec.ts.snap
- src/app/wizard/components/StepSkeleton.vue
- src/app/wizard/views/__snapshots__/DataplaneUniversal.spec.ts.snap
- src/app/wizard/views/__snapshots__/Mesh.spec.ts.snap
Uses dedicated icon components instead of HTML entities and sets standard button icon sizes.
> chore: uses dedicated icons instead of HTML entities

- src/store/storeConfig.spec.ts
- src/store/storeConfig.ts
Fixes an issue with using a stored value for the `selectedMesh` state when that value doesn’t represent an existing mesh. Then, we’d still let users navigate to routes associated to this resource. This happens more commonly for developers frequently switching around their data during development.
> fix: using non-existing mesh from local storage

- src/api/setupMockWorker.ts
- src/app/App.vue
- src/app/services/views/ServiceDetailView.vue
- src/router/router.ts
- src/shims-vue-router.d.ts
Fixes an issue with not loading the service data when switching between different services while on a service detail view. This happened because our router doesn’t trigger a re-render in these cases.
> fix(service): not loading correct data when switching service

- src/utilities/dataplane.ts
If `zoneInsight.subscriptions` is undefined then this means we are we are `offline`
Related https://github.com/kumahq/kuma-gui/pull/476
Fixes https://github.com/kumahq/kuma-gui/issues/517
> fix(zones): Add a guard for insight.subscriptions

- src/app/policies/views/PolicyView.vue
Previously we assumed the policy count was always `0` or greater, but it could be `undefined`.
With fix:
Fixes https://github.com/kumahq/kuma-gui/issues/524
> fix(policies): Ensure empty policies are greyed out in the policy selector

- src/app/data-planes/components/DataPlaneDetails.vue
- src/app/data-planes/components/DataPlaneEntitySummary.vue
- src/app/data-planes/components/DataPlaneList.vue
- src/utilities/dataplane.spec.ts
- src/utilities/dataplane.ts
Whilst fixing https://github.com/kumahq/kuma-gui/issues/517 with https://github.com/kumahq/kuma-gui/pull/523 we realized that the type naming didn't quite make sense:
https://github.com/kumahq/kuma-gui/issues/517#issuecomment-1371985785
So we tweaked the types slightly so that things didn't look as weird.
Whilst I was there we noticed a couple of other things we could do regarding `getItemStatusFromInsight` and `getStatus` which led to being able to compose those two functions to DRY things out a little, simplifying the innards of them slightly and a rename of `getStatus`
@lahabana could you double check the changes in the second to last commit (https://github.com/kumahq/kuma-gui/commit/50fb7d99ef5d98f8eb94300e4502d6e0a14dd882), a tweaked it a little more following our catch up and it …
> refactor(insight): rename and refactor status related functions

- package.json
- src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
- src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
- src/app/data-planes/components/__snapshots__/DataplanePolicies.spec.ts.snap
- src/app/data-planes/views/__snapshots__/DataPlaneListView.spec.ts.snap
- src/app/onboarding/views/__snapshots__/AddNewServicesCode.spec.ts.snap
- src/app/wizard/views/__snapshots__/DataplaneUniversal.spec.ts.snap
- src/app/wizard/views/__snapshots__/Mesh.spec.ts.snap
- yarn.lock
See https://github.com/kumahq/kuma-gui/pull/529. Tests were failing there due to snapshots changing
> chore(deps): Bump @kong/kongponents from 8.12.0 to 8.14.2

- public/mockServiceWorker.js
Seems like this gets updated whenever you yarn install a new version
I noticed this whilst working on something else and it weirdly/unexpectedly ended up in my changeset, needs committing at somepoint, ideally would have been done as part of https://github.com/kumahq/kuma-gui/pull/512
> chore(deps): Update msw comment

- src/app/common/StatusBadge.vue
- src/app/data-planes/components/DataPlaneList.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/policies/views/PolicyView.vue
- src/app/services/components/ServiceDetails.vue
- src/app/services/views/ServiceDetailView.vue
- src/app/services/views/ServiceListView.vue
- src/app/zones/views/ZoneEgresses.vue
- src/app/zones/views/ZoneIngresses.vue
- src/app/zones/views/ZonesView.vue
- src/router/router.ts
Reworks slightly how selected rows are persisted in DPP and service tables. The associated props and query parameters were given more accurate names to avoid conflicts and give a clearer indication of what they’re representing.
Also fixes one or two instances of persisting selected rows not actually working.
> refactor: streamlines selected table row persisting

- src/app/data-planes/components/DataplanePolicies.vue
- src/app/policies/views/PolicyView.vue
- src/main.ts
- src/router/router.ts
Previously we were looping through all possible policyTypes and generating static routes for each of them.
This PR changes that to use a dynamic route for all of them instead `/policies/:policyType` instead. All policies now live under `/policies/*` instead of just `/*` meaning clashes are less likely.
Setting the title is a little hacky here, and setting the page title does seems to be possible via a `store.dispatch` to the data layer. But when I looked at setting the breadcrumb, it didn't seem possible with the current code without setting the route.meta.title within the route, ideally breadcrumbs I'd vote for breadcrumbs (and titles) being set within the *View.vue, but I didn't want to go about changing too much just for this - either via that alternative or a different one.
I think I …
> feat(policy): Add dynamic policy route instead of generating static ones

- src/app/services/components/ServiceDetails.vue
- src/app/services/views/ServiceDetailView.vue
Services can have gateways, but we currently ask for non-gateways when requesting the dataplane proxies for a service.
This PR removes that filter and makes sure that the table displays the correct columns depending on what the first item in the list is. Whilst it's theoretically possible that this list can be a mix of the 2 types its highly unlikely, and could potentially be validated to be impossible in the future.
There has been some discussion on whether we do want to cope properly for mixed lists, but if we did want to do that we would need to decide whether to:
- Show everything in the same table/list (seems strange seeing as we recently changed things elsewhere not to do this)
- Show a tabbed interface with a tab for each type
- Other ideas...
In the meantime this PR makes it so …
> fix(services): don't filter a services proxies by non-gateways

- src/api/kumaApi.ts
- src/app/AppSidebar.spec.ts
- src/app/common/PolicyTypeTag.vue
- src/app/data-planes/components/DataPlaneDetails.spec.ts
- src/app/data-planes/components/DataplanePolicies.spec.ts
- src/app/data-planes/components/DataplanePolicies.vue
- src/app/data-planes/components/PolicyTypeEntryList.spec.ts
- src/app/mesh-overview/views/MeshOverviewView.vue
- src/app/policies/views/PolicyView.spec.ts
- src/app/policies/views/PolicyView.vue
- src/main.ts
- src/router/router.ts
- src/store/storeConfig.ts
- src/types/index.d.ts
Renames state and other variables related to policy types to distinguish the concepts of policy types (e.g. CircuitBreaker) from policies (e.g. one specific instance of a policy type).
Removes all uses of the policy type fields `singularDisplayName` and `pluralDisplayName` to be consistent with how we refer to these entities in the docs.
> refactor: streamlines naming of policy type

- src/app/App.vue
- src/app/__snapshots__/App.spec.ts.snap
Switches the UI to always use full-width layouts instead of doing so only for some views.
Resolves #550.
> feat: always uses full width layout

- src/app/common/TabsWidget.vue
- src/app/data-planes/components/DataPlaneDetails.vue
- src/app/data-planes/components/DataplanePolicies.vue
- src/app/policies/views/PolicyView.vue
- src/app/zones/views/ZoneEgresses.vue
- src/app/zones/views/ZoneIngresses.vue
- src/app/zones/views/ZonesView.vue
Persists a selected tab of the `TabsWidget` component in the URL.
Resolves #544.
> feat: persist selected tab in URL

- src/app/mesh-overview/views/MeshOverviewView.vue
I missed this one as part of https://github.com/kumahq/kuma-gui/pull/543
> fix(policy): Fix up old policy link in MeshOverview

- src/store/modules/notifications/notifications.spec.ts
- src/store/modules/notifications/notifications.ts
Previously we only checked the `mesh.logging` property to decide whether to show a notification to remind you to set up logging, this PR also adds checking to see if there are a MeshAccessLog or MeshTrace policies.
Note, I originally just accessed `rootState.meshInsight.policies` instead of using the getter, but I kinda assumed using the getter would be preferable/was more the done thing (even though this lost the type) - if this is the wrong assumption lemme know!
Fixes https://github.com/kumahq/kuma-gui/issues/549
> fix(notifications): Additionally check for MeshAccessLog/MeshTrace before showing notice

- .env
- src/api/kumaApi.ts
- src/app/common/subscriptions/SubscriptionDetails.vue
- src/app/common/subscriptions/SubscriptionHeader.vue
- src/app/common/warnings/WarningsWidget.vue
- src/app/onboarding/components/ItemStatus.vue
- src/app/onboarding/components/graphs/KubernetesGraph.vue
- src/app/onboarding/components/graphs/MemoryGraph.vue
- src/app/onboarding/components/graphs/MultizoneGraph.vue
- src/app/onboarding/components/graphs/PostgresGraph.vue
- src/app/onboarding/components/graphs/StandaloneGraph.vue
- src/app/onboarding/views/MultiZoneView.spec.ts
- src/app/onboarding/views/ShellEmpty.vue
- src/app/zones/components/MultizoneInfo.vue
- src/app/zones/views/ZoneEgresses.vue
- src/app/zones/views/ZoneIngresses.vue
- src/app/zones/views/ZonesView.vue
- src/app/zones/views/__snapshots__/ZoneEgresses.spec.ts.snap
- src/app/zones/views/__snapshots__/ZoneIngresses.spec.ts.snap
- src/app/zones/views/__snapshots__/ZonesView.spec.ts.snap
- src/shims-env.d.ts
- src/types/index.d.ts
- src/utilities/dataplane.ts
Migrates all zone-related (and a few simple ones) to composition API.
This aids in providing better type system support for component code which is lackluster for components written in Options API style.
> refactor(zones): migrate components to composition API

- src/app/data-planes/components/DataPlaneList.vue
- src/app/data-planes/views/DataPlaneListView.spec.ts
- src/app/data-planes/views/DataPlaneListView.vue
- src/router/routes.ts
This PR adds the selection of gatewayType to the query params in the Gateway Listing view.
Additionally:
- I removed the doubled up data structure (`GATEWAY_TYPES`, `dataPlaneTypes`)
- I moved the select element to use label/values (values being lowercased 'machine' values, the labels being capitalized human words), the machine value is then what is used in the code and in the query parameters.
> chore(gateways): Adds gateway type selection to queryParams

- src/app/mesh-overview/views/MeshOverviewView.vue
Fixes a small issue with links to specific policy views using the route name for the general policies route and a `policyType` param which doesn’t exist.
> fix: policy route using wrong name/param

- jest/jest-setup-after-env.ts
- src/api/kumaApi.ts
- src/api/mocks.ts
- src/api/setupMockServer.ts
- src/app/App.spec.ts
- src/app/__snapshots__/App.spec.ts.snap
- src/app/common/UpgradeCheck.spec.ts
- src/services/development.ts
- src/services/env/Env.ts
- src/services/index.ts
- src/services/production.ts
- src/services/utils.ts
This PR adds a new `KUMA_VERSION_URL` (replacing/using `VITE_VERSION_URL`) and then mocks that out using `msw`. 
This prevents us actually called out to the `VERSION_URL` during development. During tests it looks like this was originally mocked out using a similar approach (but did not read `VITE_VERSION_URL`)
I noticed that App.spec tested for no upgrade available, and we already have a test for when an upgrade is available (in `UpgradeCheck.spec`) and wanted to keep both these types of test, so I injected a super big version in `App.spec` that is higher than the currently hardcoded mocked version. I probably could have gone the other way around and mocked out the response from the endpoint also, and I'll possibly do something similar to this at a later date, this PR is already going a …
> chore: Adds latest version retrieval to the mocks

- src/app/common/subscriptions/SubscriptionDetails.vue
- src/app/zones/views/__snapshots__/ZoneEgresses.spec.ts.snap
- src/app/zones/views/__snapshots__/ZoneIngresses.spec.ts.snap
- src/app/zones/views/__snapshots__/ZonesView.spec.ts.snap
- src/utilities/helpers.spec.ts
- src/utilities/helpers.ts
Fixes a small issue with the `camelCaseToWords` utility not handling words with subsequent uppercase letter correctly (e.g. MeshOPAPolicy).
> fix: incorrectly turning camel case into words

- vite.config.ts
Turns off the `build.modulePreload` option in the Vite configuration because it interferes with our tests and isn’t strictly necessary.
> chore: turns off module preload option

- src/app/services/components/ServiceDetails.vue
- src/types/index.d.ts
Fixes an issue with the DPP filters when used as part of the service detail view on account of them accidentally propagating a `gateway=true` parameter.
> fix: dpp filters no working correctly for service detail view

- .github/workflows/codeql.yml
- .github/workflows/create-gui-pr.yml
- .github/workflows/main.yml
Adds the necessary logic to allow merging into a release branch (e.g. release-2.1) for the purpose of creating corresponding PRs against the release branch of the host repository (i.e. kumahq/kuma).
> ci: support merges into release branches

- src/app/AppSidebar.vue
- src/services/production.ts
- src/utilities/index.ts
This PR moves `getNavItems` into our service container.
> chore: Move navItems into the container

- jest/jest-setup-after-env.ts
- src/app/App.spec.ts
- src/app/main-overview/components/OverviewCharts.vue
- src/app/main-overview/views/MainOverviewView.vue
- src/components/index.ts
Moves the MainOverview DoughnutCharts into their own separate component.
Tiny note: I had to move the jest mock for `vue-github-button` into a place where it would get mocked for all tests as it now gets imported in other places.
> chore: OverviewCharts component

- src/app/onboarding/views/MultiZoneView.vue
I noticed some dead code in MultizoneView, probably should have been removed as part of https://github.com/kumahq/kuma-gui/pull/466
> chore: Remove old docs link from MultizoneView

- src/app/App.vue
- src/app/onboarding/views/AddNewServices.vue
- src/router/router.ts
- src/store/modules/onboarding/onboarding.ts
- src/store/modules/onboarding/onboarding.types.ts
- src/store/storeConfig.ts
Moves `shouldSuggestOnboarding` getter into global state as it only accesses global state.
Stops using store setter in component.
Stops setting computed property in component (they should be read-only).
> refactor: cleans up onboarding store

- src/app/__snapshots__/App.spec.ts.snap
- src/app/common/__snapshots__/UpgradeCheck.spec.ts.snap
- src/app/main-overview/views/__snapshots__/MainOverviewView.spec.ts.snap
- src/app/notification-manager/components/__snapshots__/LoggingNotification.spec.ts.snap
- src/app/notification-manager/components/__snapshots__/MetricsNotification.spec.ts.snap
- src/app/notification-manager/components/__snapshots__/MtlsNotification.spec.ts.snap
- src/app/notification-manager/components/__snapshots__/TracingNotification.spec.ts.snap
- src/app/onboarding/views/__snapshots__/MultiZoneView.spec.ts.snap
- src/app/wizard/views/__snapshots__/MeshWizard.spec.ts.snap
- src/app/zones/views/__snapshots__/ZoneIngresses.spec.ts.snap
- src/app/zones/views/__snapshots__/ZonesView.spec.ts.snap
- src/services/env/Env.ts
There's always the possibility that the product name could contain a space, if that happens make sure its 'url friendly'
> chore: Ensure utm values are url friendly

- .github/workflows/create-gui-pr.yml
Uses a branch name that’s unique between the target branches (e.g. when merging into a release branch).
> ci: creates unique branch name

- .github/workflows/create-gui-pr.yml
Uses a branch name that’s unique between the target branches (e.g. when merging into a release branch).
> ci: creates unique branch name (backport)

- src/app/onboarding/components/OnboardingHeading.vue
- src/app/onboarding/views/WelcomeView.vue
This fixes an issue where the headers during onboarding would appear as a colored bar:
> fix(onboarding): Fixes missing header text during onboarding

- src/app/zones/views/ZonesView.vue
- src/types/index.d.ts
- src/utilities/helpers.ts
Fixes an issue of accessing a zone insight’s subscriptions too early when briefly after creating a zone, the zoneInsight object is not available, yet.
Fixes #585.
> fix: reading subscriptions too early

- src/store/reducers/__snapshots__/mesh-insights.spec.ts.snap
- src/store/reducers/mesh-insights.ts
Policies are pluggable so we can't refer to them statically in the code.
If you could give this one an extra look that'd be great, whilst I'm gaining more context on the application, I probably still don't have enough to be totally sure there isn't somewhere where we are trying to do `undefined + 0`. Pretty sure what is here is fine after following the code paths I could find through, but would be good for a second opinion on that.
> chore(policies): Remove hardcoded policy listing

- src/app/onboarding/components/ItemStatus.vue
- src/app/onboarding/components/OnboardingHeading.spec.ts
- src/app/onboarding/components/OnboardingHeading.vue
- src/app/onboarding/components/OnboardingNavigation.vue
- src/app/onboarding/components/OnboardingPage.vue
- src/app/onboarding/components/ServiceBox.vue
- src/app/onboarding/components/WelcomeAnimationSvg.vue
- src/app/onboarding/components/__snapshots__/OnboardingHeading.spec.ts.snap
- src/app/onboarding/components/__snapshots__/OnboardingNavigation.spec.ts.snap
- src/app/onboarding/views/AddNewServices.vue
- src/app/onboarding/views/AddNewServicesCode.vue
- src/app/onboarding/views/CompletedView.vue
- src/app/onboarding/views/ConfigurationTypes.vue
- src/app/onboarding/views/CreateMesh.vue
- src/app/onboarding/views/DataplanesOverview.vue
- src/app/onboarding/views/DeploymentTypes.vue
- src/app/onboarding/views/MultiZoneView.vue
- src/app/onboarding/views/WelcomeView.vue
- src/app/onboarding/views/__snapshots__/AddNewServices.spec.ts.snap
- src/app/onboarding/views/__snapshots__/AddNewServicesCode.spec.ts.snap
- src/app/onboarding/views/__snapshots__/CompletedView.spec.ts.snap
- src/app/onboarding/views/__snapshots__/ConfigurationTypes.spec.ts.snap
- src/app/onboarding/views/__snapshots__/CreateMesh.spec.ts.snap
- src/app/onboarding/views/__snapshots__/DataplanesOverview.spec.ts.snap
- src/app/onboarding/views/__snapshots__/DeploymentTypes.spec.ts.snap
- src/app/onboarding/views/__snapshots__/MultiZoneView.spec.ts.snap
- src/app/onboarding/views/__snapshots__/WelcomeView.spec.ts.snap
Migrates all onboarding-related child components to composition API.
Fixes an issue of the onboarding heading not being visible in Chrome on account of Chrome only supporting a vendor-prefixed CSS property we didn’t use.
Replaces a few Tailwind styles in migrated components.
> refactor: migrates onboarding child components to composition api

- src/assets/styles/main.scss
See title. If `node_modules` isn't where you would think it is (say in a workspace'd setup) this should resolve the packages more reliably.
> chore: Use node package resolution for some CSS paths

- src/services/env/Env.ts
- src/services/env/env.spec.ts
Kuma GUI reads a config value to understand where to find the API endpoints, generally these are just `/`, but they are user configurable using a `KUMA_API_SERVER_GUI_ROOT_URL` environment variable (https://github.com/kumahq/kuma/blob/be5122db4e3377164b3e2e12c641112b08009ce6/pkg/config/api-server/config.go#L30).
If a user configures this value to be anything other than the default, this setting was not being respected in the GUI.
There is a related bug here where `KUMA_API_SERVER_GUI_BASE_PATH` could was also partly not being respected within the GUI code, although when chasing this down, ignoring this value in the GUI code seems to have no clear affect. Therefore whilst this is theoretically wrong, there is no immediately apparent bug.
It all boils down to the difference between `??` and …
> fix(api): Fixes an issue where KUMA_API_BASE_PATH was not being respected

- vite.config.development.ts
I noticed our preview site weren't working due to a change in https://github.com/kumahq/kuma-gui/pull/625, we figured elsewhere that this was due to a difference to how vite deals with aliasing during dev and build, so I changed things to use regex here also.
> chore: Use regexes for vite aliasing

- src/services/env/Env.ts
- src/services/env/env.spec.ts
See https://github.com/kumahq/kuma-gui/pull/639
Additionally for the backport, I had to add the `-GUI` string back in for the tests, as on 2.1 we still have that in the UTM codes whereas in `master` we don't
> fix(api): Backport: Fixes an issue where KUMA_API_BASE_PATH was not being respected

- src/app/common/EnvoyData.vue
- src/app/common/ErrorBlock.vue
- src/app/common/StatusInfo.vue
- src/app/common/__snapshots__/EnvoyData.spec.ts.snap
- src/app/data-planes/components/DataPlaneList.vue
Adds a refresh button to the envoy data tabs for xDS, stats, and clusters. On activation, the loading routine for this data is run again.
Streamlines handling of error objects in a few components.
Resolves #419.
> feat: adds refresh button to xDS/stats/clusters tabs

- .github/workflows/dispatch-merged-pr-notification.yml
Adds a workflow for dispatching a merged PR notification which triggers a corresponding workflow in the notify repo.
(Note that the workflow won’t work on this branch as it exists on my fork of Kuma GUI and so it doesn’t actually have access to kumahq/kuma-gui secrets.)
> ci: adds dispatch merged PR notification workflow

- jest/jest-setup-after-env.ts
- package.json
- src/index.ts
- src/main.ts
- src/router/router.ts
- src/services/production.ts
This PR re-arranges `initializeVue` slightly to no longer use `get(TOKENS.*)` and use parameter/constructor injection instead. This is partly to further hide our service container from the actual application code, partly to move the injections to the very root of the application (`main.ts`) and partly to allow us to inject `App` if we ever need to make use of that. We continue to do the majority of our application wiring in `@/services` and import that into `main` so we can `get` the 'application' and call it.
I also added `"main": "index.ts"` to the `package.json` meaning `kuma-gui` can now be used as a real dependency/sub-package.
> chore: Makes App injectable, moves injections to composition root/main

- .github/workflows/create-gui-pr.yml
- .github/workflows/main.yml
Replaces all project-specific environment variables with repository variables so that their values aren’t part of the workflow file.
> ci: moves project specific env variables to repository variables

- src/app/App.vue
- src/components/index.ts
- src/index.ts
- src/router/router.ts
- src/router/routes.ts
Moves AppHeader and AppSidebar to our component container.
I also removed the `readonly` routes here as that seems to be unnecessary.
> chore: Makes AppHeader and AppSidebar injectable

- .github/workflows/create-gui-pr.yml
Changes the workflow trigger for the "Create GUI update PR" workflow to only run on successful workflow runs of the "Tests & build" workflow (provided that workflow run happened on the default or a release branch).
> ci: runs create GUI PR workflow only on successful CI

- .github/workflows/create-gui-pr.yml
- .github/workflows/main.yml
Looks like this is supported but not listed on https://github.com/actions/setup-node.
> ci: uses .nvmrc file for node

- .eslintrc.js
- jest/jest-setup-after-env.ts
- vite.config.ts
I noticed that I occasionally miss a space between `:` and type (i.e. `var:Type`). I much prefer the `var: Type` style (with a space after the colon), and it also seems by far to be the style already existing informally in the application.
This PR adds this style to our CI/package scripts so its applied for for any/all contributors.
Couple of corrections included.
> chore: Adds type-annotation-spacing spacing lint rule

- src/api/kumaApi.ts
- src/app/AppErrorMessage.vue
- src/app/common/EnvoyData.vue
- src/app/common/UpgradeCheck.vue
- src/app/data-planes/components/DataplanePolicies.vue
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/mesh-overview/views/MeshOverviewView.vue
- src/app/onboarding/views/AddNewServicesCode.spec.ts
- src/app/onboarding/views/AddNewServicesCode.vue
- src/app/onboarding/views/DataplanesOverview.vue
- src/app/onboarding/views/MultiZoneView.spec.ts
- src/app/onboarding/views/MultiZoneView.vue
- src/app/policies/components/PolicyConnections.vue
- src/app/policies/views/PolicyView.vue
- src/app/services/views/ServiceDetailView.spec.ts
- src/app/services/views/ServiceDetailView.vue
- src/app/services/views/ServiceListView.vue
- src/app/wizard/views/DataplaneKubernetes.vue
- src/app/wizard/views/DataplaneUniversal.vue
- src/app/wizard/views/MeshWizard.vue
- src/app/zones/views/ZoneEgresses.vue
- src/app/zones/views/ZoneIngresses.vue
- src/app/zones/views/ZonesView.vue
- src/services/kuma-api/README.md
- src/utilities/index.ts
Addresses part of https://github.com/kumahq/kuma-gui/issues/660
This PR removes  `@api/kumaApi` in favour of a `useKumaApi`, `@api/kumaApi` was a simple shim over our service container to avoid a bunch of churn whilst this was shaking out. This goes back (now everything has shaken out a bit) to keep the codebase consistent.
As a sidenote I also noticed that the only things left in `@/api` now are the mock api related files which are soon to be improved as part of https://github.com/kumahq/kuma-gui/issues/522
> chore: Removes `@api/kumaApi` in favour of `useKumaApi`

- jest/jest-setup-after-env.ts
- src/app/App.spec.ts
- src/app/AppNavItem.spec.ts
- src/app/AppSidebar.spec.ts
- src/app/data-planes/components/DataPlaneDetails.spec.ts
- src/app/data-planes/components/DataplanePolicies.spec.ts
- src/app/data-planes/components/PolicyTypeEntryList.spec.ts
- src/app/notification-manager/components/NotificationManager.spec.ts
- src/app/onboarding/components/OnboardingNavigation.spec.ts
- src/app/onboarding/views/ConfigurationTypes.spec.ts
- src/app/onboarding/views/CreateMesh.spec.ts
- src/app/onboarding/views/WelcomeView.spec.ts
- src/app/policies/views/PolicyView.spec.ts
- src/app/wizard/views/DataplaneUniversal.spec.ts
- src/app/wizard/views/MeshWizard.spec.ts
- src/app/zones/views/ZoneEgresses.spec.ts
- src/app/zones/views/ZoneIngresses.spec.ts
- src/app/zones/views/ZonesView.spec.ts
- src/store/store.ts
- src/utilities/index.ts
Throughout our application all store access goes via `useStore` whereas in our tests we needed an extra `store` export to access the store.
This PR adds a `useStore` that's accessible for tests also. Resulting in the code in the application and in the tests setup being almost the same.
This addresses the second half of https://github.com/kumahq/kuma-gui/issues/660 i.e. accessing the same stuff in the same way everywhere and removing as many references to `get` and `TOKENS` from the application code as possible, therefore hiding the service container completely. (first half is https://github.com/kumahq/kuma-gui/pull/663)
Note: There'll be a follow up PR at some point after this removing the last instance of `store` related `getting` in `store/store.ts`, I figured it would be better to …
> chore: Remove 'bare' store access

- src/pathConfigDefault.ts
- src/services/env/Env.ts
- src/services/env/env.spec.ts
- src/services/kuma-api/KumaApi.ts
- src/services/kuma-api/RestClient.spec.ts
- src/services/kuma-api/RestClient.ts
- vite.config.ts
Fixes RestClient not using `env` for its base URL.
> fix: env not using base URL

- src/services/kuma-api/KumaApi.ts
- src/services/kuma-api/RestClient.ts
Adds a `setHeader` method to `RestClient` and `KumaApi` so that headers can be configured.
> feat: adds setHeader method to RestClient and KumaApi

- src/services/kuma-api/KumaApi.ts
- src/services/kuma-api/RestClient.spec.ts
- src/services/kuma-api/RestClient.ts
Adds a way to set default options for `RestClient` and removes the ability to set headers specifically as they can be set using options. This is useful for changing the credentials option for example.
> feat: adds options setter for rest client

- src/index.ts
- src/main.ts
Moves the call to `app.mount` into the entry point file so that consuming applications can make further `app.use` calls **before** the application is being rendered. This is especially relevant for registering components before trying to render them.
> refactor: extracts app mounting into entry point

- src/app/App.spec.ts
- src/index.ts
- src/main.ts
- src/store/storeConfig.ts
Changes the main entry point of the application to only make API calls after the application is ready as indicated by a custom `app:ready` event fired on the `document`.
> refactor: runs post mount operations on custom event

- package.json
- src/app/policies/views/PolicyView.vue
- yarn.lock
Fixes a type error in the policy view component caused by KSelect now having a more specific type that doesn’t allow additional properties to be used on its items.
> chore: fix type error

- src/services/env/Env.ts
- src/services/env/env.spec.ts
- src/services/kuma-api/RestClient.spec.ts
- src/services/kuma-api/RestClient.ts
Fixes an issue with the base API URL being set incorrectly. To fix this issue, the logic for ensuring the API base URL is indeed an absolute URL and not just a path segment relative to the origin was moved into the Env.ts file where the Kuma config object is being fetched. `RestClient` now always expects an absolute URL without any trailing slashes.
> fix: base API URL being set incorrectly

- src/index.ts
- src/main.ts
- src/services/env/Env.ts
- src/services/env/env.spec.ts
- src/services/kuma-api/MockKumaApi.ts
- src/services/production.ts
In https://github.com/kumahq/kuma-gui/pull/684 we added a custom event to separate application 'creation' from 'bootstrapping'.
Events are usually used for "one-to-many" operations, i.e. you fire an event and any number of things can be listening to that, or you fire multiple times. I don't think we need either of those characteristics right now at least. More importantly, we were passing dependencies used for 'bootstrapping' through to the creation 'service' only to then pass them through to the bootstrapping function when the custom event was fired.
This change adds a 'useBootstrap' function, so we can just call this function after project creation as you usually would, removing the indirection, it's dependencies being provided via our service container.
```javascript
const app = await …
```
> chore: add useBootstrap for bootstrapping the application separately

- package.json
- src/app/AppHeader.vue
- src/app/__snapshots__/App.spec.ts.snap
- src/app/common/UpgradeCheck.vue
- src/services/env/Env.ts
Loosens up our version related things so we can use string based versions if we need to. The rule it uses is "if major doesn't parse as a number, then its a 'string version'". String versions will never ask for updates as they are more likely to be dev versions and suchlike.
I switched a couple of old store-type things to use env vars whilst I was here.
The entire thing assumes that we never deal with actual full semvers, only 3 numbers i.e. we never need to be aware of carets and tildes, only 3 numbers joined by dots `~3.0.0` vs `3.0.0`.
This PR makes it so we only need to be aware of "3 numbers joined by dots" and "full strings" - we still don't need to be aware of `~` or `^` prefixed semvers.
> feat: Accept "string only" versions

- src/utilities/helpers.ts
Avoids an infinite request loop in the `fetchAllResources` utility that occurs when the `next` URL in the response is present but doesn’t change.
> fix: infinite requests when next URL doesn't change

- jest/jest-setup-after-env.ts
- src/app/App.spec.ts
- src/components/index.ts
- src/services/development.ts
- src/services/index.ts
- src/services/kuma-api/MockKumaApi.ts
- src/services/logger/DisabledLogger.ts
- src/services/production.ts
- src/services/utils.ts
- src/utilities/useEnv.spec.ts
This PR is an evolution/iteration of our service container configuration and favours a 2 step "define and then build" approach rather than "build as you go". Consequently we remove `set` and `injected` and set/inject it all in one place, whilst making things more self explanatory ("this is the service, these are its arguments")
---
This PR is "I think" as close as I can get to what I actually want whilst maintaining the types.
Just declarative configuration:
```yaml
env:
service: Env
arguments:
- EnvVars
kumaApi:
service: KumaApi
arguments:
- Env
labels:
- api
```
We can then merge/compose configurations as we want, and `build` as a final step.
Notes:
- We are currently building both in prod and dev (so twice in dev). This isn't an issue right now as it's just resetting everything again …
> chore: Move to a 2 step "define then build" process

- src/index.ts
- src/main.ts
- src/services/production.ts
Moves setting the Kuma API base URL out of the bootstrap function so that it doesn’t get overridden when setting it before bootstrap elsewhere.
> refactor: moves setting base URL out of bootstrap

- .eslintrc.js
- package.json
- src/app/common/TagList.vue
- yarn.lock
* **chore: adds eslint-import-resolver-alias**
Allows ESLint to know which aliases for paths belong to the same group.
* **chore: runs linter script**
> chore: adds eslint-import-resolver-alias

- src/api/setupMockWorker.ts
- src/services/development.ts
- src/services/kuma-api/MockKumaApi.ts
- src/services/production.ts
Changes `setupMockWorker` to take `apiName` and `handlers` parameters. The function now keeps a record of which handlers belong to which API (as identified by `apiName`). This way, we can store independent handlers per API which might need to be constructed in different ways.
Makes sure to stop the mock worker before starting it again which seems to be necessary despite a logged warning indicating the opposite. Without it, newly added handlers have no effect.
> feat: enables mock worker to handle multiple api instances

- src/app/AppBreadcrumbs.vue
- src/shims-vue-router.d.ts
Adds a feature to the breadcrumbs component for programmatically determining an entry’s title. This can be used to resolve a resource’s name from, for example, a given ID.
> feat: determines breadcrumb title dynamically

- .env
- src/services/kuma-api/RestClient.spec.ts
- src/services/kuma-api/RestClient.ts
- src/services/kuma-api/makeRequest.spec.ts
- src/services/kuma-api/makeRequest.ts
Adds support for `delete`, `post`, `put`, and `patch` methods on `RestClient` as our APIs are involving.
Sets the `credentials` option to default to `'include'` for all instances of `RestClient`. Environments in which no session state is transferred via cookies aren’t affected as there wouldn’t be any cookie stored to send with requests. Environments which do need to transfer such session state in turn will benefit from not needing to set `credentials: 'include'` on all the individual API instances.
Ensures URLs are consistently constructed without a trailing slash and adds test cases for that edge case.
> feat: adds support for more request methods

- src/assets/styles/_fonts.scss
Fixes an issue with file-relative asset references not being resolved correctly in some dev server contexts.
> fix: file-relative font asset references

- src/services/kuma-api/RestClient.spec.ts
- src/services/kuma-api/RestClient.ts
Fixes stripping trailing slashes from absolute URLs in the RestClient. Generally, our APIs don’t require a trailing slash. But we make one request for getting the latest Kuma version to our docs site and depending on the web server configuration, requesting without a trailing slash can fail because the server responds with a redirect.
> fix: stripping slash from absolute URL

- src/app/App.vue
- src/app/AppHeader.vue
- src/index.ts
- src/router/router.ts
- src/store/storeConfig.ts
Streamlines how general pieces of the UI may show up. Only if their respective entry in `state.defaultVisibility` is `true` become any of their other specific checks relevant.
> feat: allows hiding alerts

- src/app/common/TagList.vue
- src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
- src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
- src/app/data-planes/components/__snapshots__/DataplanePolicies.spec.ts.snap
Fixes `TagList` not always being able to correctly determine tag routes. Specifically, when used on a page where no mesh parameter is in a route, it can’t know which one to use for routes that need it. Adding it explicitly fixes this.
> fix: not always determining tag links correctly

- src/app/common/AccordionItem.vue
- src/app/common/EnvoyData.vue
- src/app/common/LabelList.vue
- src/app/common/TabsWidget.vue
- src/app/common/__snapshots__/EnvoyData.spec.ts.snap
- src/app/common/__snapshots__/TabsWidget.spec.ts.snap
- src/app/common/warnings/WarningsWidget.vue
- src/app/data-planes/components/DataPlaneDetails.vue
- src/app/data-planes/components/DataPlaneEntitySummary.vue
- src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
- src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
- src/app/data-planes/components/__snapshots__/DataplanePolicies.spec.ts.snap
- src/app/data-planes/views/__snapshots__/DataPlaneListView.spec.ts.snap
- src/app/mesh-overview/views/MeshOverviewView.vue
- src/app/policies/components/PolicyConnections.vue
- src/app/policies/components/__snapshots__/PolicyConnections.spec.ts.snap
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/services/components/ServiceSummary.vue
- src/app/wizard/views/__snapshots__/MeshWizard.spec.ts.snap
- src/app/zones/views/ZoneEgresses.vue
- src/app/zones/views/ZoneIngresses.vue
- src/app/zones/views/ZonesView.vue
- src/app/zones/views/__snapshots__/ZoneEgresses.spec.ts.snap
- src/app/zones/views/__snapshots__/ZoneIngresses.spec.ts.snap
- src/app/zones/views/__snapshots__/ZonesView.spec.ts.snap
- src/assets/styles/_components.scss
- src/assets/styles/_variables.scss
Removes the built-in KCard from LabelList so that it can be (1) nested and (2) used where no card styles are necessary (e.g. in a context where this already a wrapping KCard).
Integrates a default KCard into the `TabsWidget` tabs and removes all instances where one was explicitly added. This cuts down on quite a bit of redundant code.
Uses KCard in some place where we were previously achieving a similar look with class-based padding. Overall, these changes achieve a much more consistent padding of panel-like boxes in the UI.
Removes some unused actions columns from some tables.
> refactor: streamlines LabelList and KCard usage

- src/app/AppNavItem.vue
- src/app/__snapshots__/App.spec.ts.snap
- src/app/__snapshots__/AppNavItem.spec.ts.snap
- src/app/__snapshots__/AppSidebar.spec.ts.snap
- src/app/getNavItems.ts
**fix: amount sometimes being incorrectly positioned**
Removes the absolute positioning from the nav item amount which caused it to be pulled down with an increase in bottom padding.
**chore: removes border bottom from nav items**
Removes the functionality for adding a bottom border to certain nav items and tweaks the space between groups of nav items a little to account for it.
> fix: amount sometimes being incorrectly positioned

- src/app/__snapshots__/App.spec.ts.snap
- src/app/common/ContentWrapper.vue
- src/app/common/FrameSkeleton.vue
- src/app/common/MeshResources.vue
- src/app/common/charts/DoughnutChart.vue
- src/app/data-planes/components/DataPlaneEntitySummary.vue
- src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/__snapshots__/DataPlaneListView.spec.ts.snap
- src/app/diagnostics/views/DiagnosticsView.vue
- src/app/main-overview/components/OverviewCharts.vue
- src/app/main-overview/views/MainOverviewView.vue
- src/app/main-overview/views/__snapshots__/MainOverviewView.spec.ts.snap
- src/app/mesh-overview/components/MeshCharts.vue
- src/app/mesh-overview/views/MeshOverviewView.vue
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/services/components/ServiceDetails.vue
- src/app/services/components/ServiceSummary.vue
- src/app/zones/views/ZoneEgresses.vue
- src/app/zones/views/ZoneIngresses.vue
- src/app/zones/views/ZonesView.vue
- src/app/zones/views/__snapshots__/ZoneEgresses.spec.ts.snap
- src/app/zones/views/__snapshots__/ZoneIngresses.spec.ts.snap
- src/app/zones/views/__snapshots__/ZonesView.spec.ts.snap
- src/assets/styles/_components.scss
- src/assets/styles/_variables.scss
**refactor: uses cards consistently**
Makes use of `KCard` with default border variant as much as possible only resorting to `div.kcard-border` where necessary.
Separates lists of resources and a summary of one selected resource (i.e. the common layout found in list views) visually by placing both blocks in their own frames.
Makes the spacing between some cards/panels consistently use `--spacing-md` (note, this is largely superseded by the following commit).
**refactor: uses consistent gaps between cards**
Adds two new classes for managing the horizontal and vertical grouping of card-like elements (e.g. a list of `KCard`s) and uses it in place of custom listing/stacking logic and manual use of utility classes (like `mt-4`). …
> refactor: uses cards consistently

- src/app/App.vue
- src/app/common/ContentWrapper.vue
- src/app/common/MeshResources.vue
- src/app/common/subscriptions/SubscriptionDetails.vue
- src/app/main-overview/views/__snapshots__/MainOverviewView.spec.ts.snap
- src/app/zones/views/__snapshots__/ZoneEgresses.spec.ts.snap
- src/app/zones/views/__snapshots__/ZoneIngresses.spec.ts.snap
- src/app/zones/views/__snapshots__/ZonesView.spec.ts.snap
- src/assets/styles/_components.scss
- src/assets/styles/_variables.scss
**chore: tweaks kcard-list usage**
Renames `kcard-list` to `kcard-switcher` and tweaks its threshold to be more applicable to our use cases (e.g. for wrapping the mesh resources items).
Adds a new `columns` class for laying out a list of items using a preferred number of columns (3 by default). These items will wrap one by one (as opposed to all at the same time with `kcard-switcher`) when their space requirements are no longer met.
**fix(zones): showing empty entry**
Fixes showing an empty entry in the zone ingress insights if its data is `{}` (this manifested in showing an empty "rds" entry using mock data).
**refactor: uses AppGap property for consistent gaps**
Introduces a global `--AppGap` property (with value `--spacing-lg`) and uses it for gaps between cards and general "top-level" …
> chore: tweaks kcard-list usage

- .github/workflows/create-gui-pr.yml
- .github/workflows/main.yml
Updates the create-gui-pr.yml workflow to use a correct reference branch instead of the branch associated with the workflow file used for execution (i.e. `master` in the case of the workflow being triggered via `workflow_run`). Without this changes, triggering this workflow from a release branch leads to running it in a default branch context instead.
> ci: updates workflows to use correct reference branch

- .github/workflows/codeql.yml
Updates the CodeQL workflow to match the one in `master` and `release-2.2` which includes a fix to the `on.pull_request` syntax being incorrect currently causing the workflow to fail.
> ci: fixes CodeQL workflow in release-2.1

- jest/jest-setup-after-env.ts
- src/main.ts
- src/services/development.ts
- src/services/production.ts
- src/services/testing.ts
- src/services/utils.ts
- src/store/store.ts
- src/utilities/index.ts
- vite.config.development.ts
This PR moves our service config to use composition rather than inheritance.
We we began using a service container approach it was a lot quicker to get where we wanted to get to by having a pretty linear "inheritance-like" reuse structure of config (a development file would import the production file)
As we've moved forwards and added distinct `main`/wiring roots, expanded our usage and new usecases have appeared (using the parts of the same service config for our Cypress tests/mocks). We've kind of begun to outgrow the inheritance approach
This PR therefore does the following:
- Changes service config to be composable via `...services(TOKENS)` functions. This means we can pick and choose sets of config we need rather than using an "all or nothing" approach.
- Adds decorators for service …
> chore: Composable Service Config

- src/main.ts
Uses `import.meta.env.MODE !== 'production' ?` rather than just `import.meta.env.DEV ?`
This makes sure that our development service config is included in "everything apart from prod" instead of "only dev", which makes sure the config is included for our PR preview sites.
I did a quick check on the prod build again to ensure that the development service config wasn't being included there.
Also see https://github.com/kumahq/kuma-gui/pull/818
> ci: Use mode !== 'production' to decide whether to use development env

- cypress.config.ts
- cypress/support/e2e.ts
- cypress/support/services/index.ts
- cypress/support/step_definitions/index.ts
- cypress/support/step_definitions/visit.ts
- package.json
- src/app/data-planes/views/DataPlaneListView.feature
- src/test-support/index.ts
- src/test-support/intercept.ts
- src/test-support/mocks/src/dataplanes+insights.ts
- yarn.lock
This PR uses Cypress as a browser based test runner to run our more e2e-like tests. Additionally it does this by using cucumber as a thin layer over test assertions etc. Before explaining further, I just wanted to point out that when I say 'e2e', I mean 'frontend e2e' i.e. these tests should not use any backend infrastructure for testing (at least for the moment) These are 'e2e' tests, but without testing the things that we don't own.
We have a longish running desire to run our e2e-like tests in a browser rather than using Node/CLI via Jest, this PR is an approach to that task.
I've used the existing CLI based e2e-like tests from DataPlaneListView.spec (https://github.com/kumahq/kuma-gui/blob/1c7311e7d093397b853ce7f50dd224f7daf13493/src/app/data-planes/views/DataPlaneListView.spec.ts) as …
> feat: Adds cypress based fakeAPI mocking plus cucumber usage example

- src/app/onboarding/views/AddNewServicesCode.spec.ts
Ensures that the API always returns a reliable `total` value that fits the test expectation to make this test stable.
> chore: fixes flaky AddNewServicesCode tests

- cypress.config.ts
- cypress/support/step_definitions/index.ts
- cypress/support/step_definitions/visit.ts
- features/application/Index.feature
- features/application/Loading.feature
- features/application/MainNavigation.feature
- features/application/Titles.feature
- features/mesh/Index.feature
- src/app/App.vue
- src/app/AppHeader.vue
- src/test-support/fake.ts
- src/test-support/intercept.ts
Replaces some old style CLI tests with full in-browser production E2E tests.
> chore: Expands Cypress e2e tests

- src/router/routes.ts
chore: removes isWizard prop from old-style wizards
fix: determining wrong policy type route to redirect to
Makes sure that a policy type for which no property exists on `store.state.sidebar.insights.mesh.policies` isn’t actually returned as the policy type to redirect to.
Also makes sure that, in the unlikely case that the policies redirect is triggered before `store.state.policyTypes` is populated, no error happens on account of accessing `item.path`: the redirect will then go to the home route. Technically, application logic should ensure that the policy types are present at that point, so this is just a safety measure.
> fix: determining wrong policy type route to redirect to

- cypress.config.ts
- cypress/support/step_definitions/index.ts
- src/services/e2e.ts
- src/test-support/fake.ts
- src/test-support/intercept.ts
1. Starts to integrate .env/process.env into Cypress.env and then `env`, note we aren't running in `vite` here but we are re-using the `VITE_` prefixed values from `.env`. In the application itself this is hidden and they remain `KUMA_` prefixed.
2. Uses `includes('://')` instead of `https://` which is a more reliable catch for "anything with a base url already"
3. Adds `req.method` for when we need to start mocking/testing on methods as well as other HTTP things.
4. Added some more steps
This remains a work in progress and the more we can use the same code for everything the easier things will be. I've tried to keep the things that are additional code as close to the places where we do similar.
> chore: Small Cypress additions

- features/application/Titles.feature
- src/app/data-planes/components/DataplanePolicies.vue
- src/app/policies/components/PolicyConnections.spec.ts
- src/app/policies/components/PolicyConnections.vue
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicyListView.spec.ts
- src/app/policies/views/PolicyListView.vue
- src/router/routes.ts
- src/services/kuma-api/KumaApi.ts
- src/store/storeConfig.ts
**fix: prematurely accessing policy types**
Fixes some premature accesses of the current policy type in `PolicyListView`. Some instances were replaces with `route.params.policyPath` (i.e. when specifically the policy path was required). Other instances received additional type guard checks.
**chore: renames some incorrect references to policy types**
Renames some instances where the policy (type) path (e.g. circuit-breakers) was incorrectly referred to as policy type (e.g. CircuitBreaker).
**test(e2e): switches to more accurate title test case**
> fix: prematurely accessing policy types

- src/app/AppBreadcrumbs.vue
- src/app/AppNavItem.vue
- src/app/getNavItems.ts
- src/router/routes.ts
Fixes a few edge cases where the breadcrumbs component couldn’t properly resolve unnamed routes. For some reason that’s unclear to me, routes that are definitely defined and loaded only resolve to a proper route location with a resolved `path` property (e.g. the actual mesh name instead of `:mesh`) if they have a name. For this reason, I’ve added a `name` property to all routes that didn’t have one, yet.
Furthermore, changes how breadcrumbs create route targets so that instead of `{ name: '...' }`, they now use `{ path: '...' }` as navigating to, for example, `{ name: 'zone-abstract-view' }` will **only** navigate to that particular route without further resolving children routes for any routes with empty path. However, this _does_ happen when navigating to paths which is what we want …
> fix: not correctly resolving unnamed routes

- src/services/development.ts
- src/services/testing.ts
- src/test-support/fake.ts
- src/test-support/index.ts
- src/test-support/intercept.ts
Several code improvements to mocking functions. Basically - "now I'm pretty much done for the moment with the e2e stuff, clean a few things up that I never got around to doing":
1. Splits and combines code in relation to `fakeAPI` and `mocker`, both of which used to do the almost the same thing with different code. As of this PR, they are split up enough to both use the same code. The aim being to use the same code for Cypress also (therefore they may still change shape slightly once we come to do that)
2. Removes `mswFakeHandlers` token. This was only here so we could support "collecting" both types of mock endpoints at the same time, the old static ones and the new dynamic ones. We no longer need this so there's slight reworking here to remove. This generally reduces the code in the …
> chore: Merge mock and fakeApi

- cypress.config.ts
- cypress/support/step_definitions/visit.ts
- package.json
All of our e2e tests run against a production build. This PR makes it easier to run our e2e/cypress tests against a running dev server for better local DX.
Since only dev builds have the "read env from cookies" enabled, this only effects dev builds. Prod builds mostly have no MSW available anyway.
Exact package script naming etc, I'm not super keen on but just went with something for now. I mentioned in a recent PR I wanted to get all the scripts we needed in first and then if we want to switch naming a little once they are all there we can.
> chore: Enables using Cypress/intercept against a running dev instance

- src/test-support/index.ts
Sometimes when testing things out locally or on the PR preview sites its nice to introduce a little latency.
This lets you add a little HTTP latency by adding a `KUMA_LATENCY=1000` cookie (value is millis) to any build that has our mocks enabled (usually local dev and PR previews)
I added this whilst reviewing a PR locally but it would be nice to have it for PR preview sites also.
> chore: Adds the ability to add some latency to dev/preview via KUMA_LATENCY

- features/application/MainNavigation.feature
- src/app/getNavItems.ts
Fixes zone egress not being available in the navigation when in standalone mode.
Resolves #771.
> fix(zones): zone egress not generally being available

- src/utilities/useI18n.ts
Fixes the indentation for Yaml configs being incorrect.
Also adds missing `zone` key in `kuma.multizone.kds.auth.cpTokenInline` (it should be `kuma.multizone.zone.kds.auth.cpTokenInline`).
> fix: wrong Yaml indentation

- features/application/Titles.feature
- src/app/meshes/views/MeshListView.vue
- src/router/routes.ts
- src/store/modules/sidebar/util.spec.ts
- src/store/reducers/mesh-insights.spec.ts
- src/test-support/FakeKuma.ts
- src/test-support/mocks/src/mesh-insights.ts
- src/types/index.d.ts
- src/utilities/useI18n.ts
**chore: updates mesh-insights mock**
Updates the mesh-insights mock to have a bunch more random status values.
**chore(types): matches MeshInsight close to backend**
Updates the `MeshInsight` type and some related types to be close to the backend.
**refactor: nests mesh routes to match usual structure**
Splits the `/mesh/:mesh` route record into a `/mesh` record with only one children route record which is the `:mesh` route record which allows for adding routes _next_ to `:mesh` without inheriting the `mesh` route parameter (e.g. for the mesh list view route).
Adds the Meshes breadcrumbs item when on a page under or directly on `/mesh`. Adds the current mesh (e.g. default) when on a page under `/mesh`.
**feat: adds mesh list view**
Adds a MeshListView component at `/mesh`.
Resolves #892. …
> feat: adds mesh list view

- src/services/development.ts
- src/services/env/CookiedEnv.ts
TLDR; Uses a decorator for cookied env rather than overwriting, which prevents our development "additionally check the cookies for env vars" from overwriting any different implementation of Env that might be different upstream.
---
Longer form:
A while back we added very basic decorator functionality to our service config. This means we can stop overwriting services and instead configure a decorator for it if we are just adding extra functionality we also can decorate a service that might not even exist yet, or a service that might be overwritten in another environment. Generally avoiding service configuration ordering issues.
Whilst we added that functionality, we didn't go back and update the services that should really have been using decorators rather than overwriting. This means …
> fix: Uses a decorator for cookied env rather than overwriting

- src/services/kuma-api/KumaApi.ts
- src/test-support/mocks/fs.ts
- src/test-support/mocks/src/provision-zone.ts
- src/test-support/mocks/src/zones.ts
Changes zone creation to use `/provision-zone` rather than just `/zones`
> chore: Changes zone creation to use `/provision-zone` rather than just `/zones`

- src/app/zones/views/ZoneCreateView.vue
Changes how the Zone creation flow detects a Zone to be connect to read its status and waiting for it to be `'online'`.
> fix: not waiting for correct Zone connection signal

- src/app/common/EmptyBlock.vue
- src/app/common/EnvoyData.vue
- src/app/common/ErrorBlock.vue
- src/app/common/StatusInfo.vue
Wraps the title content of our block components in a default slot so you can set the content from the consumer side.
> feat: adds default slot to block components

- src/index.ts
- src/main.ts
Fixes triggering the global loading state when re-running the bootstrap function.
> fix: triggering global loading when re-running bootstrap

- src/app/zones/components/ZoneCreateKubernetesInstructions.vue
- src/app/zones/components/ZoneCreateUniversalInstructions.vue
- src/app/zones/views/ZoneCreateView.vue
- src/services/kuma-api/KumaApi.ts
- src/types/index.d.ts
Stops reading Zone name from the `/provision-zone` endpoint.
> fix: reading Zone name from provision response

- src/app/meshes/views/MeshView.vue
I noticed that following https://github.com/kumahq/kuma-gui/pull/922, the looping of multiple RouteViews inside the Tabs component caused the TabPanel not to update as quickly as it needed to. 
This PR moves to just use a single RouterView making for a better/less-flickery experience.
Part of https://github.com/kumahq/kuma-gui/issues/893
> fix(mesh): Places RouteView outside of tabs

- src/index.ts
- src/services/development.ts
- src/services/env/Env.ts
- src/services/kuma-api/Api.ts
- src/services/kuma-api/KumaApi.ts
- src/services/logger/DatadogLogger.ts
- src/services/logger/DisabledLogger.ts
- src/services/production.ts
We noticed that things that weren't decorators (but should have been) were overwriting services completely due to a change in ordering of service config (see https://github.com/kumahq/kuma-gui/pull/924 for more info). These weren't written as decorators originally just due to timings of things and how things have shaken out.
Decorators avoid this problem by decorating/augmenting services rather than overwriting them completely.
We should use decorators for development only modifications/augmentation over completely overwriting. So I've changed our remaining non-decorator service here - the logging disabling. This one specifically didn't really matter that it completely overwrites any other implementations as its a "disable logger completely, no matter what it is", but I prefer …
> chore: Turn disabled logger into a proper decorator instead of overwrite

- src/app/common/DefinitionListItem.vue
- src/app/common/subscriptions/SubscriptionDetails.vue
- src/app/data-planes/components/DataPlaneDetails.vue
- src/app/data-planes/components/DataPlaneEntitySummary.vue
- src/app/meshes/routes.ts
- src/app/meshes/views/MeshOverviewView.vue
- src/app/policies/views/PolicyDetailView.vue
- src/app/zones/components/ZoneDetails.vue
- src/app/zones/components/ZoneEgressDetails.vue
- src/app/zones/components/ZoneIngressDetails.vue
- src/app/zones/views/__snapshots__/ZoneEgressListView.spec.ts.snap
- src/app/zones/views/__snapshots__/ZoneIngressListView.spec.ts.snap
- src/app/zones/views/__snapshots__/ZoneListView.spec.ts.snap
- src/locales/en-us/http/index.yaml
Part of https://github.com/kumahq/kuma-gui/issues/843 i.e. the work to use `core/i18n` instead of our own custom 'machine to human' mapping functions.
This PR concentrates on unravelling `t` from `DefinitionListItem`. I've tried to only move the dynamic lookup things to use `t`. Any hardcode/static `term=""` instances I've left as is unless I saw an opportunity to move multiple occurrences to use a single source of truth (e.g. `controlPlaneInstanceId`)
I think this comment mostly explains it:
https://github.com/kumahq/kuma-gui/pull/826#discussion_r1173637069
But this was also called out in the MADR.
I thought of some other things we should probably change around DefinitionListItem, such as I noticed you wouldn't be able to do something like:
```html
<dl>
<dt></dt>
<dd></dd>
<dd></dd> …
```
> chore: Refactor DefinitionListItem and usage to use `t` from The Outside

- src/app/data-planes/components/DataPlaneDetails.vue
- src/app/data-planes/components/DataPlaneEntitySummary.vue
- src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
- src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
- src/app/meshes/views/MeshOverviewView.vue
- src/app/services/components/ServiceSummary.vue
Removes some redundant fields from the UI as they’re either very clear from the page’s context or shown right beneath it in a resource code block. Removes type, name, and mesh from DPP details. Removes mesh from DPP and service summaries. Removes type from mesh details.
Resolves #753.
> chore: removes redundant fields

- src/store/storeConfig.ts
Fixes two `commit` calls that weren’t passing any arguments to their respective mutation implementations which would lead to an exception.
> fix: passing invalid data to mutations

- src/app/zones/components/ZoneCreateKubernetesInstructions.vue
- src/app/zones/components/ZoneCreateUniversalInstructions.vue
Adds the CP ID to the Zone connection command if it’s present. This enables us to update the commands in `src/app/zones/locales/en-us/index.yaml` to use the CP ID if needed.
I’m not happy with this approach. Maybe we could add a small service to our DI layer (or actually a constant?) that lets us inject arbitrary additional placeholders depending on environment which, if present, would automatically be picked up in our i18n utility and added to the provided placeholders of the `i18n.t` call (if any).
```js
const additionalPlaceholders = {
'zones.form.kubernetes.connectZone.config': /* a custom function returning `Record<string, string>` perhaps? */,
}
```
> feat: adds CP ID to Zone connection command

- src/app/App.vue
**chore: replaces pointless isLoading variables**
Replaces the `isLoading` variable with direct access to the underlying state as `isLoading` isn’t used for anything else.
**refactor: moves is-wizard-page class to body**
Moves the `is-wizard-page` class to the body element where can it affect more elements in the DOM.
> refactor: moves is-wizard-page class to body

- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneCreateView.vue
Adds an error block at the start of the form content area that’s populated if an error occurs during Zone provisioning.
> fix: inadequate error handling of Zone creation flow

- src/app/data-planes/routes.ts
- src/app/gateways/routes.ts
- src/app/meshes/locales/en-us/index.yaml
- src/app/meshes/views/MeshView.vue
- src/app/policies/routes.ts
- src/app/services/routes.ts
- src/utilities/index.ts
This PR makes it so the new tabs in a Mesh view are auto generated from the routes, this means that as we add new routes they will automatically be added to the tab bar.
---
Notes:
The routing changes here are just as a consequence of making it easier to get closer to a more generic "find the routes we want" i.e. I just removed an empty nest. I 'think' this was here from https://github.com/kumahq/kuma-gui/pull/922 where I found it really difficult to get our current breadcrumbs setup to work:
> One thing I will note is that it took me quite a while to organize the routing configurations to get the breadcrumbs correct, for a long while I could get it to link to meshes properly (the URL would look literally like /mesh/:mesh). I don't know how I managed to get it to print it properly, but it …
> chore: Makes mesh tabs autogenerated

- cypress/support/step_definitions/visit.ts
The PR removes a check for an empty not existing on every test that is run.
This was originally added as a bit of a sledgehammer test to make sure we actually got something on the page. But we are getting to the point now that we need to test and assert that the empty state should actually be there, and in order to do that that this can't exist in this step anymore.
> chore: Removes a check for empty states from all tests

- src/locales/en-us/http/index.yaml
- src/test-support/mocks/src/meshes/_/dataplanes+insights/_.ts
- src/types/index.d.ts
- src/utilities/dataplane.ts
Fixes the issue of not showing the mTLS certificates data correctly and also takes that moment to move the label text into the i18n layer.
> fix: certificates not showing correctly

- src/index.ts
- src/main.ts
- src/services/logger/Logger.ts
- src/services/production.ts
**refactor: moves logger setup into main.ts**
Moves the logger setup call to a place where it can’t happen multiple times.
**chore: removes logger.log method**
Removes the log method as it’s not very useful with an `info` method already present.
> refactor: logger setup

- features/application/MainNavigation.feature
- features/application/Titles.feature
- features/zones/Index.feature
- src/app/AppNavItem.vue
- src/app/AppSidebar.vue
- src/app/common/DataOverview.spec.ts
- src/app/common/TagList.vue
- src/app/common/__snapshots__/DataOverview.spec.ts.snap
- src/app/data-planes/components/DataPlaneList.vue
- src/app/getNavItems.ts
- src/app/meshes/views/MeshView.vue
- src/app/zones/components/ZoneDetails.vue
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/routes.ts
- src/app/zones/views/ZoneCreateView.vue
- src/app/zones/views/ZoneDetailView.vue
- src/app/zones/views/ZoneIndexView.vue
- src/app/zones/views/ZoneListView.vue
- src/app/zones/views/__snapshots__/ZoneEgressListView.spec.ts.snap
- src/app/zones/views/__snapshots__/ZoneIngressListView.spec.ts.snap
- src/app/zones/views/__snapshots__/ZoneListView.spec.ts.snap
- src/store/storeConfig.ts
**feat: moves zones into tabs**:
Renames the routes associated to the Zone CP views to include the `-cp` bit to make it more clear this is a view of Zone CPs.
Moves the Zone sidebar items into a Zones page with navigational tabs which shows the Zone CPs view by default (i.e. like we’ve done for mesh-related items).
**chore: removes sidebar item counts**:
Removes the sidebar item counts as they’re really not useful anymore.
> feat: moves zones into tabs

- src/app/App.vue
Avoids issues with adding Vue directives to a router view rendering this component which only works if a component has a single root element.
> chore: ensures root component has single element

- src/app/common/StatusBadge.vue
- src/app/common/__snapshots__/DataOverview.spec.ts.snap
- src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
- src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
- src/app/onboarding/views/__snapshots__/DataplanesOverview.spec.ts.snap
- src/app/services/views/ServiceListView.vue
- src/app/zones/views/__snapshots__/ZoneEgressListView.spec.ts.snap
- src/app/zones/views/__snapshots__/ZoneIngressListView.spec.ts.snap
- src/app/zones/views/__snapshots__/ZoneListView.spec.ts.snap
- src/locales/en-us/http/index.yaml
**fix: not showing status in services list view**
Fixes not showing a service’s status in the service list view at all.
**feat: changes wording for "not_available" status**
Changes the wording for the `not_available` status from "not available" to "information not available". (I’ve added both camel-cased and snake-cased variants to the messages file as we sometimes use one, sometimes the other. If we change this, we can drop one.)
Resolves #643.
> feat: change wording of status not available

- src/app/zones/components/ZoneDetails.vue
Zone is shown as offline but in green color
this PR should fix it, status is lowercase but we compare it uppercase https://github.com/kumahq/kuma-gui/blob/master/src/types/index.d.ts#L58
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits) yes
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)? yes
> fix(zone-status): fix zone status badge variant when zone is offline

- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/diagnostics/views/DiagnosticsView.vue
- src/app/meshes/views/MeshItemView.vue
- src/app/policies/views/PolicyDetailView.vue
- src/app/services/views/ServiceDetailView.vue
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneDetailView.vue
- src/app/zones/views/ZoneEgressDetailView.vue
**chore: fix providing superfluous route parameters**
Specifies the exact route parameters in the new breadcrumbs to avoid the vue-router warning about discarding invalid parameters.
**fix: zone egress breadcrumb using wrong route name**
**fix: zones not having correct breadcrumb title**
Adds the missing messages that are used zone detail view.
> fix: zones not having correct breadcrumb title

- src/app/data-planes/routes.ts
- src/app/meshes/routes.ts
- src/app/zones/routes.ts
- src/router/routes.ts
~I spotted a few missing i18n problems probably following rebasing shenanigans that I guess I messed up on.~
~I wondered why this wasn't brought up in tests so I had this in draft with an eye to finding out why and making sure these things hard error for us during tests. When looking into this, it began to become a little bit of a rabbit hole that isn't just a simple "oh look, it because this particular page didn't have a test yet", so I've decided to take this out of draft to fix the issue first, and then continue down the rabbit hole separately to eventually fix the larger issue.~
This is no longer about that ^ as it was included in here https://github.com/kumahq/kuma-gui/pull/1034, but I have added tests for the original purpose of the PR here …
> chore: Remove unused meta data

- features/application/Titles.feature
- src/services/i18n/I18n.ts
Firstly, the tests in this PR should fail without https://github.com/kumahq/kuma-gui/pull/1032 and therefore requires that in first.
I've added a hard error for when we are missing translation keys here which will fail the tests (by default formatjs only `console.error`s), this is possibly temporary as I'd rather not do this in our own i18n service but instead rely on configuring formatjs. I'm looking into that separately and I'd like to get these tests in.
Additionally the tests here are probably temporary or at least temporary in this file. There are several reasons why this is so:
1. Ideally we would have separate files for absolutely every page, with way more e2e tests in them. Right now its easy to bung all these in one file and loop through them, eventually we will have all the …
> chore: Hard errors on missing i18n key, tmp adds tests for all titles

- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneIndexView.vue
Following https://github.com/kumahq/kuma-gui/pull/1034/files#diff-b74e52e340de40ac28d9f03911b3150dd6e2a60629b55351d4d160735bda2fcbL22, we then fixed this the wrong way around in https://github.com/kumahq/kuma-gui/pull/1039, resulting in:
`Zone CPs > Zone CPs`
This PR put it all back to how it should be, resulting in:
`Zones > Zone CPs`
Closes https://github.com/kumahq/kuma-gui/issues/1043
> fix(zones): Put the parent "Zone" breadcrumb back

- src/app/application/components/route-view/RouteView.vue
- src/app/data-planes/routes.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/gateways/routes.ts
- src/app/meshes/locales/en-us/index.yaml
- src/app/meshes/routes.ts
- src/app/meshes/views/MeshOverviewView.vue
- src/app/meshes/views/MeshView.vue
- src/app/policies/routes.ts
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/services/routes.ts
- src/app/services/views/ServiceDetailView.vue
- src/app/services/views/ServiceListView.vue
- src/shims-vue-router.d.ts
Ideally I would have split this up into 2 separate PRs as there are two things here:
1. We originally decided that detail pages would not have tabs, we've since decided that they should have tabs, so this PR puts the Mesh Service, Dataplane, Gateway, Policy detail pages back underneath the tabs.
2. Instead of hardcoding more and more potential "this route means that this tabs should be selected". I'd rather do something more automatic, i.e. because of nested routing/route views we know that this thing is related to this tab (its a child of the route the tab is linked to), so select it. <= This is the bit I would rather have worked on first, and is "this is fine for now" so we can move on with this. e.g. child removal probably needs adding plus some other things. The eventual plan is this …
> chore: Moves Mesh detail pages back underneath tabs

- src/app/zones/components/ZoneCreateKubernetesInstructions.vue
- src/app/zones/components/ZoneCreateUniversalInstructions.vue
- src/app/zones/locales/en-us/index.yaml
**chore: removes token from k8s instructions**
**chore: change universal instructions to use token from file**
Changes the universal instructions for the Zone creation flow to store the secret in a file and to refer to that file in the CP config.
> chore: update zone creation instructions for secrets

- src/app/application/components/app-view/AppView.vue
- src/app/application/components/route-view/RouteTitle.vue
Moves to use `onBeforeUnmount` rather than `onUnmounted` in both `AppView` and `RouteTitle`
> fix: onUnmounted > onBeforeUnmount

- cypress/support/step_definitions/index.ts
- features/home/Index.feature
- src/app/common/charts/DoughnutChart.vue
- src/app/main-overview/components/OverviewCharts.vue
- src/app/main-overview/views/__snapshots__/MainOverviewView.spec.ts.snap
We noticed that clicking in the middle of a chart (instead of the ring itself) would cause a JS error to be thrown. This fixes that up.
---
Notes:
I added what usually would be a "debug" step, but I used it here to say "I click this and everything is still ok!", I kept the short form `ok`, as I sometimes use this for debug, but in this case it reads better in the long form seeing as we are keeping it in the test permanently.
The reason there is nothing really to assert after it, is because kinda luckily if you use Cypress to click on the `canvas` it reproduces the error. As these charts use `canvas` and not SVG it wasn't immediately clear to me how I could select the ring of the chart separately, guessing we would need to provide something in the application code, which I'm not keen on if …
> fix(charts): Avoid throwing an error when clicking the middle of a chart

- src/app/common/charts/DoughnutChart.vue
Handle division by zero cases for doughnut chart hover tooltip
> fix(charts): avoid NaN error on hover

- cypress/support/step_definitions/index.ts
- features/mesh/Index.feature
- features/zones/Create.feature
- src/app/meshes/views/MeshView.vue
TLDR; Tweaks Cypress click and adds some tests for Mesh Tabs
---
This PR began as adding further tests to our Mesh page/Tabs, but led to something else.
I've left the tests in here that led to these changes to provide context and easier repro of the issue if thats something people want to do.
More info:
Whilst writing a test click through multiple tabs in a single page (see https://github.com/kumahq/kuma-gui/pull/1070/files#diff-b0fab4bf9af5f7083dc7f148815082ea223aaeab7f5a7785d5889c4368ee086aR32) I came across a Cypress error related to the element that was selected having changed between it being selected and then trying to click on it.
I believe this is related to 2 issues, one of which I can fix relatively easily here. (The other is potentially related to how our application is built …
> chore: Adds tests for Mesh plus some tweaks to Cypress steps

- src/app/App.vue
- src/app/application/components/route-view/RouteView.vue
- src/app/zones/views/ZoneCreateView.vue
- src/assets/styles/_utilities.scss
- src/assets/styles/_variables.scss
Adds functionality to be able to set top-level class names from our `RouteView` component
Previously we were doing this on a per-class basis i.e. `setWizardPageClass`. This PR does pretty much the same thing just at a more generic/reusable level and handily from our `RouteView` component which is available in every single view/route component.
At an application level, I went with `is-fullscreen` which better describes what the required CSS here does.
Notes:
- Whilst the plan is to be able to set any attrs on the root node, I haven't done this yet as we don't currently need it. This only currently works for `class`
- As all this code is centralized in `RouteView` I went with "I'm happy with the interface, lets get the thing working" whilst not worrying to much about the fact that RouteView …
> chore: Set top-level classes from RouteView

- .github/workflows/main.yml
See title, uses a more descriptive name resulting in clearer code, and brings this in sync with other things.
Note: Once this is approved the GH UIs branch protection rule will need to be tweaked as a result of this and then, once merged, all currently open PRs will need rebasing.
> chore: Updates name of branch protection rule

- features/application/MainNavigation.feature
- features/zones/PageNavigation.feature
- src/app/common/NavTabs.vue
- src/test-support/mocks/src/zoneingresses+insights.ts
**refactor(e2e): names and formats MainNavigation test**
**chore(e2e): expands page navigation tests in zones**
Adds a new test file for page navigation tests in zone pages.
> chore(e2e): expands page navigation tests in zones

- .eslintrc.js
- src/services/kuma-api/Api.ts
- src/services/kuma-api/RestClient.spec.ts
- src/services/kuma-api/RestClient.ts
- src/services/production.ts
1. Removes `credentials: include` from all our HTTP requests
2. Makes RestClient injectable.
Additionally we no longer need to tweak `options` for HTTP requests so I removed that code also, and the tests for it. If we find we need it again at a later date we can bring it back.
There is probably a certain amount of refactoring I would like to do here, but I would rather do this with as little code change as possible and come back to address any refactoring/noodling later.
Closes https://github.com/kumahq/kuma-gui/issues/799
> chore: Make RestClient injectable, removes credentials: include

- src/app/common/NavTabs.vue
- src/assets/styles/_components.scss
Fixes cards often missing the intended border radius on account of a custom property being set incorrectly.
Also adds a bottom margin to `NavTabs` as the double-border issue would now look particularly bad.
Before:
After:
> fix: not cards missing border radius

- src/services/env/CookiedEnv.ts
Previously, during dev, you would have to refresh the page for `env` to read changed cookies, i.e. it would only read the cookies at init.
This amends it so `env` reads cookies on the fly without a browser refresh making it handier for debugging.
> chore: Ensures dev cookie changes don't require a refresh

- src/services/development.ts
- src/services/production.ts
Disables the logger service in prod. Enables the logger service in dev.
Note: Let’s wait with merging this until the release of 2.3 is complete to not interfere with that.
> chore: disables logger in prod, enables console logger in dev (#1102)

- src/app/data-planes/locales/en-us/index.yaml
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/gateways/locales/en-us/index.yaml
- src/app/meshes/locales/en-us/index.yaml
- src/app/policies/locales/en-us/index.yaml
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/services/locales/en-us/index.yaml
- src/app/services/views/ServiceDetailView.vue
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneDetailView.vue
- src/app/zones/views/ZoneEgressDetailView.vue
- src/app/zones/views/ZoneIngressDetailView.vue
- src/store/storeConfig.ts
I saw some bits of the old store based titling still existed but didn't really do anything anymore, so I went through and cleaned up.
While I was there I made it so all "detail" pages use the form `name-of-the-specific-thing Type of thing` (e.g. `program-0 Data plane proxy`) consistently. The shouldn't/doesn't require test amends seeing as we check titles contain the text rather than equals the text.
Just to note I much like the fact that we are getting rid of more code here and its much easier and more obvious how to set the title of the page, a small thing but all these little small improvements will gradually add up.
> chore: Removes last vestiges of old store based titling

- src/app/meshes/components/MeshCharts.vue
- src/app/meshes/views/MeshOverviewView.vue
- src/store/modules/notifications/notifications.spec.ts
- src/store/modules/notifications/notifications.ts
- src/store/reducers/mesh-insights.ts
- src/store/storeConfig.ts
- src/types/index.d.ts
refactor: internalizes data management for mesh charts
Moves all the data fetching and chart data computation out of storeConfig and into MeshCharts as there is no advantage in having handled via the Vuex store.
Depends on (and includes) https://github.com/kumahq/kuma-gui/pull/997.
> refactor: internalizes data management for mesh charts

- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/meshes/components/MeshCharts.vue
- src/app/meshes/views/MeshListView.vue
- src/app/meshes/views/MeshOverviewView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/services/views/ServiceDetailView.vue
- src/app/services/views/ServiceListView.vue
- src/app/zones/views/ZoneDetailView.vue
- src/app/zones/views/ZoneEgressDetailView.vue
- src/app/zones/views/ZoneEgressListView.vue
- src/app/zones/views/ZoneIngressDetailView.vue
- src/app/zones/views/ZoneIngressListView.vue
- src/app/zones/views/ZoneListView.vue
**chore: removes unnecessary watchers from Meshes views**
Removes some unnecessary watches from Zone views as there is never a condition where these parameters can change while on such a view.
**chore: removes unnecessary watchers from Meshes views**
> chore: removes unnecessary route watchers

- src/types/api.d.ts
See https://github.com/kumahq/kuma/issues/6639 (specifically https://github.com/kumahq/kuma/issues/6639#issuecomment-1527731778) and https://github.com/kumahq/kuma/pull/6648
I'm guessing there are a load of places where we no longer need null guards anymore. I haven't gone through and amended if there are as I'm guessing these will eventually be removed during natural tech debt work.
> fix: Remove the fact that `items` in HTTP responses can be `null`

- package.json
- src/app/common/__snapshots__/DataOverview.spec.ts.snap
- yarn.lock
See https://github.com/Kong/kongponents/pull/1501
Longer term we need to stop using any `dist/*.scss` files from `@kong/kongponents` (see https://github.com/kumahq/kuma-gui/issues/1160)
> fix(deps): Includes fix for kongponents sass issue

- src/app/main-overview/components/OverviewCharts.vue
The code around loading our data for the overview charts has javascript loading states, but those states are **_not_** used to block the visibility/rendering of the rendered vue components.
You can see the javascript loading state here.
https://github.com/kumahq/kuma-gui/blob/39a4d9bb85f7ef29889622e0d29467acbbd7e635/src/app/main-overview/components/OverviewCharts.vue#L319
You'll notice that we don't actually then use this state in the Vue template at all.
In OSS this doesn't cause issues, but when trying elsewhere it does. It seems as though this, along with some sort of additional strange-ness in the Chart plugin we use that it can result in charts with no coloring.
Theoretically, this should all work due to Vue's reactive state but for some reason Vue's reactiveness doesn't seem to be …
> fix(charts): Make sure charts have some sort of loading state

- features/application/Loading.feature
- src/app/App.vue
- src/app/AppHeader.vue
- src/index.ts
- src/main.ts
- src/services/production.ts
- src/store/modules/config/config.spec.ts
- src/store/modules/config/config.ts
- src/store/storeConfig.spec.ts
- src/store/storeConfig.ts
This PR began as removing the last HTTP API call to `/` that we have. Whilst doing this I noticing that we just invisibly failed on any errors in our 'bootstrapping' HTTP calls. I decided it was finally time to move our bootstrapping functionality into `App.vue` where we could catch any errors and show a proper error state.
---
Previous to this PR we would make a call to `/` to see if that call was successful, if it wasn't successful we would just do nothing and miss out a bunch of HTTP calls we depend on further into the application, not great.
If we were successful, we wouldn't use any of the data from the API call, but instead make another bunch of API calls. Then if any of those failed, do nothing, and therefore be missing a bunch of data we then depend on further into the …
> chore: Removes last HTTP call to `/` and moves bootstrapping

- yarn.lock
After a bunch of dependabot upgrades, I was testing everything out locally and noticed that we still get a `yarn.lock` update on `master` when running `yarn` locally, this commit adds that missing change.
I'm unclear as to why this is necessary but I would rather use the local output of `yarn` and commit it rather than not.
> fix(deps): update lock file

- features/zones/Create.feature
- src/app/zones/views/ZoneCreateView.vue
Stops disabling the zone submit button on error.
We show a warning as to why there was an error, and you _could_ resolve that error using something other than the browser you are currently using, so it doesn't make sense to stop the user from hitting the button again. We show an error message, if the user wants to keep trying (maybe they've deleted the zone via other means) then thats up to them.
Note: I think if anything a completely _invalid_ zone name makes more sense to use as a signal to disable the button more than anything, but this should probably be done via frontend validation (that's guessing we know the rules for invalid names and we can recreate that validation on the frontend)
See https://github.com/kumahq/kuma-gui/pull/1104#discussion_r1241910208
Signed-off-by: John Cowen …
> fix(zones): Don't disable the submit button on duplicate name

- src/app/application/components/app-view/README.md
- src/app/application/components/route-view/README.md
- src/app/application/components/route-view/RouteTitle.vue
- src/app/application/components/route-view/RouteView.vue
- src/app/application/components/route-view/index.ts
- src/app/application/utilities/index.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/meshes/views/MeshOverviewView.vue
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/services/views/ServiceDetailView.vue
- src/app/services/views/ServiceListView.vue
The `RouteView`/`RouteTitle` and `AppView` components were initially made in a closed manner to PoC the different concept and then roll it out across the applications.
I'd always planned on coming back to tidy things up inside the components and add some documentation to help any external contributors or anyone unfamiliar with our codebase. This PR does that.
There was the initial concept of automatic navigation building/navigation selecting in `RouteView`, which we were using but pulled out and therefore we aren't using just yet. I decided to remove this entirely in this the clean up and add afresh at a later date. In the PR you will see things related to `children` and `module=""` being removed, this deletion is related to this.
> refactor: Cleans up RouteView code and adds basic docs

- cypress.config.ts
- cypress/support/e2e.ts
- package.json
- yarn.lock
Adds the cypress-fail-fast plugin which will cause the entire Cypress test run to fail fast after 1 failed retry.
> ci: adds cypress-fail-fast plugin

- .github/workflows/main.yml
- cypress.config.ts
Uploads Cypress screenshots and videos on failure of the test run.
Workflow run summary in failure case (has uploaded artifacts): https://github.com/kumahq/kuma-gui/actions/runs/5552202267
Workflow run summary in success case (doesn't have uploaded artifacts): https://github.com/kumahq/kuma-gui/actions/runs/5552247266?pr=1178
> ci: uploads Cypress screenshots and videos on failure

- src/app/application/components/app-collection/AppCollection.vue
- src/app/application/components/app-collection/README.md
- src/app/application/components/data-source/DataSource.vue
- src/app/application/components/route-view/RouteView.vue
- src/app/application/services/data-source/index.ts
- src/app/application/utilities/index.ts
Adds a thin wrapper around `KTable` that is more specific for our application. Also an easily accessible function for updating query params on the current route.
This new component is much smaller in scope than our current `DataOverview` component, and will eventually be used for all of our listing views. I've defaulted a lot of `KTable` props to what I think makes sense for our project.
> chore: Add AppCollection component and RouteView.update function

- src/app/common/charts/DoughnutChart.vue
- src/app/main-overview/components/OverviewCharts.vue
- src/app/meshes/components/MeshCharts.vue
- src/types/index.d.ts
Removes the feature making charts link to related pages which people were generally surprised existed in the first place and doesn't seem to serve much purpose.
Note: This removes one of the last uses of `store.state.selectedMesh`. The last one will be removed in a follow up in which I’m dropping the sidebar store module (its main purpose no longer exists and we only use a bit of its state).
> chore: removes charts being clickable

- src/app/common/warnings/WarningsWidget.vue
- src/app/main-overview/views/MainOverviewView.vue
- src/app/meshes/views/MeshListView.vue
- src/app/meshes/views/MeshOverviewView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/zones/views/ZoneEgressListView.vue
- src/app/zones/views/ZoneIngressListView.vue
- src/app/zones/views/ZoneListView.vue
- src/assets/styles/_components.scss
Renames `kcard-stack` to `stack` to avoid the implication that it somehow needs to be used with KCards only.
> refactor: renames kcard-stack to stack

- src/assets/styles/_base.scss
Defines the user agent style default font sizes explicitly in our code. Most notably this avoids user agent styles of the style `:any(section, ...) h1` to apply to our headings.
> chore: defines standard heading font sizes

- package.json
- public/mockServiceWorker.js
- yarn.lock
Removes esbuild as we don’t explicitly use it ourselves.
> chore(deps-dev): removes esbuild

- features/mesh/Index.feature
- features/mesh/policies/Data.feature
- features/mesh/policies/Index.feature
- features/mesh/services/Index.feature
- src/app/meshes/views/MeshListView.vue
- src/app/meshes/views/MeshView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/services/views/ServiceListView.vue
**chore(meshes): address linter warning**
**fix(services): table column styles leaking to other tables**
**fix(meshes): table column styles leaking to other tables**
**fix(policies): table column styles leaking to other tables**
> fix: table column styles leaking to other tables

- src/app/common/charts/DoughnutChart.vue
Adds a type guard around a ChartJS default assignment to address `tooltip` now having `false |` in its type.
> chore: fix chart.js type breaking

- cypress/support/step_definitions/index.ts
- features/application/MainNavigation.feature
- features/application/Titles.feature
- features/zones/ListViewContent.feature
- features/zones/PageNavigation.feature
- features/zones/zone-cps/Item.feature
- package.json
- src/app/services/views/ServiceListView.vue
- src/app/zones/index.ts
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/routes.ts
- src/app/zones/sources.ts
- src/app/zones/views/ZoneEgressListView.vue
- src/app/zones/views/ZoneIndexView.vue
- src/app/zones/views/ZoneIngressListView.vue
- src/app/zones/views/ZoneListView.spec.ts
- src/app/zones/views/ZoneListView.vue
- src/locales/en-us/common/index.yaml
- src/services/production.ts
**refactor: migrates Zone CP list to use DataSource**
Migrates Zone CP list view to use `DataSource` and `AppCollection`.
**refactor: migrates Zone Ingress list to use DataSource**
Migrates Zone Ingress list view to use `DataSource` and `AppCollection`.
**refactor: migrates Zone Egress list to use DataSource**
Migrates Zone Egress list view to use `DataSource` and `AppCollection`.
> refactor: migrates zone lists to use DataSource

- src/app/common/CopyButton.vue
- src/app/common/DeleteResourceModal.vue
- src/app/meshes/views/MeshOverviewView.vue
Removes some calls to `console.error` where the error is already adequately handled.
> chore: removes console.error for some handled scenarios

- features/mesh/dataplanes/Index.feature
- features/mesh/gateways/Index.feature
- features/mesh/services/Index.feature
- src/app/data-planes/components/DataPlaneList.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/services/views/ServiceListView.vue
Moves the status column in list views (if present) towards the end so it is the last column, but before warnings and actions columns.
> chore: moves status column towards the end

- src/app/policies/views/PolicyListView.vue
> fix: moves experimental alert into card

- src/app/__snapshots__/AppOnboardingNotification.spec.ts.snap
- src/app/common/__snapshots__/DataOverview.spec.ts.snap
- src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
- src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
- src/app/data-planes/components/__snapshots__/DataplanePolicies.spec.ts.snap
- src/app/onboarding/components/__snapshots__/OnboardingNavigation.spec.ts.snap
- src/app/onboarding/views/__snapshots__/AddNewServices.spec.ts.snap
- src/app/onboarding/views/__snapshots__/AddNewServicesCode.spec.ts.snap
- src/app/onboarding/views/__snapshots__/CompletedView.spec.ts.snap
- src/app/onboarding/views/__snapshots__/ConfigurationTypes.spec.ts.snap
- src/app/onboarding/views/__snapshots__/CreateMesh.spec.ts.snap
- src/app/onboarding/views/__snapshots__/DataplanesOverview.spec.ts.snap
- src/app/onboarding/views/__snapshots__/DeploymentTypes.spec.ts.snap
- src/app/onboarding/views/__snapshots__/MultiZoneView.spec.ts.snap
- src/app/onboarding/views/__snapshots__/WelcomeView.spec.ts.snap
- src/app/policies/components/__snapshots__/PolicyConnections.spec.ts.snap
- src/index.ts
- src/services/kuma-api/Api.ts
- src/services/kuma-api/RestClient.spec.ts
- src/services/kuma-api/RestClient.ts
- src/services/production.ts
This PR does 2 things:
---
Back in https://github.com/kumahq/kuma-gui/pull/765 I added an injectable `$.router` specifically for our CLI tests, but I'd always planned to then use that for our main application see (https://github.com/kumahq/kuma-gui/pull/765/files#r1151912562).
I also corrected it here to use our base path, hence the snapshot update.
We now feed the `$.router` into `useApp` just like the other Vue plugins, eventually we'll be able to add these sorts of plugins with some DI labelling.
---
I made baseUrl just pull straight from `env('KUMA_API_URL')` meaning we don't have to keep setting it in certain places, meaning we can remove a bunch of code elsewhere.
> chore: Make router injectable and pullable baseURL 

- src/app/application/components/app-collection/AppCollection.vue
- src/app/common/KFilterBar.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/gateways/views/GatewayListView.vue
- src/app/services/views/ServiceDetailView.vue
**chore: makes filter bar take up full width in toolbar**
**chore: makes toolbar action items take up same height**
**chore: removes incorrect padding from toolbar**
The toolbar shouldn’t have additional padding according to the designs.
Before:
After:
> chore: makes filter bar take up full width in toolbar

- src/app/application/components/route-view/README.md
- src/app/application/components/route-view/RouteView.vue
- src/index.ts
Exposes `t` and `env` from RouteView as we pretty much always need these in Route components and we want to default to 'generally' not using them anywhere but Route components (we will need to occasionally use them in non-route components, so want to stress the 'generally')
Also installs Kongponents as a Vue plugin.
> chore: Expose some commonly used utilities/components

- features/zones/ListViewContent.feature
- src/app/services/views/ServiceListView.vue
- src/app/zones/views/ZoneListView.vue
- src/test-support/mocks/src/meshes/_/service-insights.ts
- src/test-support/mocks/src/zones+insights.ts
**fix(zones): handling of empty table cells**
Fixes empty cells not rendering the right content.
Fixes the warnings cell showing `false` instead of nothing.
**fix(services): handling of empty table cells**
Randomizes presence of certain fields on service mocks and only sets dataplanes if the service is an external one.
Makes sure to always show a status badge.
> fix: handling of empty table cells

- src/router/router.ts
- src/services/production.ts
Takes 1 of a few steps to enable us to disable onboarding entirely i.e. not even compile it in if we wanted to do that.
~Currently awaiting merge of some other PRs (specifically https://github.com/kumahq/kuma-gui/pull/1221) but I wanted to get this up for visibility for the moment, it's likely to change a little.~
> chore: Make route guards injectable

- src/pathConfigDefault.ts
- src/services/env/Env.ts
- src/services/env/env.spec.ts
- src/types/index.d.ts
Adds some new static env vars that are sourced form the index.html file.
As yet this PR doesn't use them, but they will be used in a subsequent PR in place of variables sourced from a HTTP request.
> chore: Adds some new environment variables for `env`

- features/zones/ListViewContent.feature
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneIndexView.vue
- src/app/zones/views/ZoneListView.vue
**feat(zones): replaces store type column with type column**
Removes the store type column from the Zone Control Plane list view.
Adds a type column to the Zone Control Plane list view showing the environment ("universal" or "kubernetes").
**chore(zones): moves Create Zone button into title bar**
Moves the "Create Zone" button into the top-level title bar.
**feat(zones): adds tooltip to warning icons**
Adds a tooltip with the label "Version mismatch" to the warning icons in the Zone Control Plane list view.
> chore: cleans up zone control plane list view

- src/app/application/components/app-collection/AppCollection.vue
- src/app/data-planes/components/DataPlaneList.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/gateways/views/GatewayListView.vue
- src/app/meshes/views/MeshListView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/services/views/ServiceDetailView.vue
- src/app/services/views/ServiceListView.vue
- src/app/zones/views/ZoneEgressListView.vue
- src/app/zones/views/ZoneIngressListView.vue
- src/app/zones/views/ZoneListView.vue
- src/assets/styles/_kongponents-overrides.scss
- src/locales/en-us/common/index.yaml
**chore: uses non-breaking space for empty table cells**
**chore(meshes): uses i18n message for actions**
**chore: evenly spreads out columns of smallish tables**
Adds logic for evenly spreading out the columns of small-ish tables (i.e. column count lower than 5). Such tables will now have equally-sized columns with the two special columns (if present) taking up a fixed amount of space each.
> chore: clean up general table styles

- src/app/common/KFilterBar.vue
- src/app/services/views/ServiceDetailView.vue
- src/app/services/views/ServiceListView.vue
**feat(services): adds copy button to address cells**
**fix: data plane list toolbar items misalignment**
**fix(services): data plane proxy list layout**
Fixes the DPP list within the service detail view for external services missing its wrapping KCard.
Before:
After:
> chore: clean up DPP list in service view

- .eslintrc.js
> chore: turns on TS-specific useless constructor rule

- cypress/support/step_definitions/index.ts
Adds the `cy.wait` call we had in the title assertion step back in as tests are still notably flaky without it.
> chore(e2e): adds title assertion wait again

- src/app/data-planes/components/DataPlaneDetails.spec.ts
- src/app/data-planes/components/DataPlaneDetails.vue
- src/app/data-planes/components/DataplanePolicies.spec.ts
- src/app/data-planes/components/DataplanePolicies.vue
- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
Uses DataSource for data fetching purposes in the DPP detail view.
Also changes the child components slightly to no longer require a `Dataplane` object. All the data we need is already available on the `DataplaneOverview` object so we can save a request here.
> refactor: uses DataSource for DPP detail view

- src/app/policies/components/PolicyConnections.spec.ts
- src/app/policies/components/PolicyConnections.vue
- src/app/policies/components/__snapshots__/PolicyConnections.spec.ts.snap
- src/app/policies/sources.ts
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicyListView.vue
- src/services/kuma-api/KumaApi.ts
- src/types/index.d.ts
**refactor: uses DataSource for policy connections**
**chore(policies): cleans up list view**
**chore: cleans up policy detail view, adds name to route view**
> refactor: use DataSource for policy detail view

- src/app/data-planes/sources.ts
- src/app/meshes/components/MeshCharts.vue
- src/app/meshes/components/MeshDetails.vue
- src/app/meshes/sources.ts
- src/app/meshes/views/MeshDetailView.vue
- src/app/services/sources.ts
- src/app/zones/sources.ts
Changes MeshOverviewView to use DataSource and to solely be responsible for fetching data. All further presentational purposes where moved into the new MeshDetails and the existing MeshCharts components.
Adds the new MeshDetails component for the presentational purposes of the mesh detail view. Its pretty much a copy of what used to be in MeshOverviewView.
Changes MeshCharts to receive `meshInsight` as a prop instead of fetching the data itself. The mesh detail view always loads that data anyway, so this removes an unnecessary request from this view.
> refactor: uses DataSource for mesh detail view

- src/app/application/components/route-view/RouteView.vue
**fix: browser back navigation not working**
Navigate from the home page to a list view (e.g. via one of the "view all" links) and press the Back button in the browser. You will stay in the list view when you should move back to the initial page.
> fix: browser back navigation not working

- src/app/common/TabsWidget.vue
- src/app/common/__snapshots__/TabsWidget.spec.ts.snap
- src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/policies/components/PolicyDetails.vue
- src/app/zones/components/ZoneDetails.vue
- src/app/zones/components/ZoneEgressDetails.vue
- src/app/zones/components/ZoneIngressDetails.vue
- src/app/zones/views/ZoneDetailView.vue
- src/app/zones/views/ZoneEgressDetailView.vue
- src/app/zones/views/ZoneIngressDetailView.vue
- src/assets/styles/_components.scss
Standardizes the usage of the TabsWidget component to not include a KCard as the new detail view designs don’t have a card around all of their content (though sometimes parts of it).
Removes a bunch of code from the TabsWidget component that we were already not using anymore.
- The biggest contributor to the number of lines changed is a regenerated snapshot for a snapshot test. When I’ll work on implementing a new design for Data Plane Proxies, I’ll add some tests and remove the snapshot test for that component.
> refactor: standardizes TabsWidget usage

- features/zones/ListViewContent.feature
- src/app/common/StatusBadge.vue
- src/app/main-overview/components/ZoneControlPlanesDetails.vue
- src/app/zones/components/ZoneDetails.vue
- src/app/zones/views/ZoneListView.vue
- src/locales/en-us/http/index.yaml
- src/test-support/mocks/src/zones+insights.ts
Treats a Zone Control Plane's `zone.enabled` field as a signal to show its status as "disabled" when its value is `false`.
> feat: handles Zone Control Plane `zone.enabled` field

- features/zones/Create.feature
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneCreateView.vue
**chore(zones): handles validation errors on /provision-zone**
**chore(zones): adds tooltip detailing naming rules**
> chore: handles /provision-zone validation errors

- features/zones/zone-cps/Item.feature
- src/app/common/DefinitionCard.vue
- src/app/common/ResourceStatus.vue
- src/app/common/subscriptions/SubscriptionHeader.vue
- src/app/main-overview/components/ControlPlaneDetails.vue
- src/app/zones/components/ZoneDetails.vue
- src/app/zones/components/ZoneEgressDetails.vue
- src/app/zones/components/ZoneIngressDetails.vue
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneEgressListView.vue
- src/app/zones/views/ZoneIngressListView.vue
- src/app/zones/views/ZoneListView.vue
- src/assets/styles/_components.scss
- src/assets/styles/_variables.scss
- src/locales/en-us/http/index.yaml
- src/test-support/mocks/src/zones+insights.ts
- src/test-support/mocks/src/zones+insights/_.ts
Moves the config and warnings tab content of the Zone Control Plane detail view into the overview tab.
**Before**:
**After**:
> feat: implements new zone details designs

- src/app/main-overview/components/ZoneControlPlanesDetails.vue
- src/app/zones/components/ZoneDetails.vue
- src/app/zones/getZoneControlPlaneStatus.ts
- src/app/zones/views/ZoneListView.vue
- src/types/index.d.ts
Extracts the logic for determining the status of a Zone Control Plane to avoid duplicating its logic.
Fixes an issue with a Zone being shown as `offline` when it should be `disabled`.
> fix(zones): not always marking Zone CP as disabled

- src/app/data-planes/components/DataPlaneDetails.vue
- src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
- src/app/policies/components/PolicyDetails.vue
- src/app/zones/components/ZoneDetails.vue
- src/app/zones/components/ZoneEgressDetails.vue
- src/app/zones/components/ZoneIngressDetails.vue
- src/app/zones/views/ZoneEgressListView.vue
- src/app/zones/views/ZoneIngressListView.vue
- src/app/zones/views/ZoneListView.vue
Fixes an issue with the background color of the page leaking through to content if it’s not wrapped in a `KCard` (which has a background color).
Note: the number of lines changed is blown out of proportion mainly through the regeneration of one snapshot and because wrapping markup in another element inadvertently causes indentation changes in otherwise unchanged lines.
> fix: background color leaking through to content

- package.json
- yarn.lock
`@bahmutov/cypress-esbuild-preprocessor` has a peer dependency on esbuild. Us no longer having it installed sometimes leads to dependency updates like https://github.com/kumahq/kuma-gui/pull/1324 to fail.
> chore: adds esbuild to satisfy peer dependency need of @bahmutov/cypress-esbuild-preprocessor

- package.json
- src/assets/styles/main.scss
- yarn.lock
Adding this now so we can start using variables from the design-tokens package.
> refactor: adds @kong/design-tokens

- src/app/services/views/ServiceDetailView.vue
Causes a rendering error in the service detail view’s DPP list if the DPP list is empty.
> fix: premature access of empty dataplane list

- src/app/common/ResourceCodeBlock.vue
- src/app/services/components/ServiceSummary.vue
Removes the resource code block for internal `ServiceInsight`s as they don’t actually represent a resource.
> chore: removes resource code block for internal service insights

- src/store/storeConfig.ts
Fixes another instance of premature object access of `meshInsight.policies`. We missed this when fixing a very similar issue recently because Vuex mutations can’t be properly type-checked.
> fix(meshes): premature access of meshInsight.policies

- cypress/support/step_definitions/index.ts
- features/application/MainNavigation.feature
- src/app/application/components/app-collection/AppCollection.vue
- src/app/application/components/route-view/RouteView.vue
- src/test-support/fake.ts
Fixes a few issues related to browser navigation through history. Specifically, it implements a hack around a shortcoming of KTable to observe external page number changes.
In the UI, navigate to a page with a list view and use its pagination. Then use the browser’s back button to navigate back. This will behave incorrectly (i.e. it will skip a page and navigate back two steps)
> fix: browser navigation through history

- src/app/application/components/route-view/RouteView.vue
- src/app/application/index.ts
- src/app/application/services/can/README.md
- src/app/application/services/can/index.ts
- src/app/gateways/views/GatewayListView.vue
- src/app/zones/features.ts
- src/app/zones/index.ts
- src/services/production.ts
Adds a `can` utility for querying user access (potentially based on permissions) or user abilities, i.e. can a user `use zones`.
---
- `can` can only ever return a boolean (unlike `env` which should only ever return strings)
- `can` can centralize these sorts of decisions within the 'module' meaning we don't mistakenly have these sorts of decisions made differently in different places by accident.
- `can` can have "features" injected from The Outside and "features" are composable so we can switch things in and out if we need to.
We purposefully return `false` if a "feature" is not defined i.e. we don't throw an error. Therefore identifiers are purposefully arbitrary strings and human readable/declarative-like. We should stick to `use/create/read/write/update/delete moduleName` semantics …
> feature: Adds `can` utility for querying user access/ability.

- src/assets/styles/_variables.scss
280 is not a multiple of 60 which it the header height therefore this was making things unpleasing
> fix(sidebar): make the width 240px

- features/mesh/services/Item.feature
- src/app/services/views/ServiceDetailView.vue
Fixes an issue with the Data Plane Proxies table missing for service detail views.
> fix(services): data plane proxies missing

- src/app/data-planes/components/DataPlaneDetails.vue
- src/app/data-planes/locales/en-us/index.yaml
- src/test-support/FakeKuma.ts
- src/test-support/mocks/src/dataplanes+insights.ts
- src/test-support/mocks/src/dataplanes.ts
- src/test-support/mocks/src/meshes/_/dataplanes+insights.ts
- src/test-support/mocks/src/meshes/_/dataplanes+insights/_.ts
- src/test-support/mocks/src/meshes/_/dataplanes/_.ts
Moves the content of the mTLS certificate insights tab into the DPP overview tab.
Updates DPP mocks to have more realistic (read: long) DPP and service names.
> chore: moves certificate insights into dpp overview

- features/application/Titles.feature
- features/mesh/dataplanes/DetailViewContent.feature
- features/mesh/services/Index.feature
- features/zones/DetailViewContent.feature
- features/zones/PageNavigation.feature
- features/zones/zone-cps/Item.feature
- src/app/data-planes/locales/en-us/index.yaml
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/gateways/locales/en-us/index.yaml
- src/app/meshes/locales/en-us/index.yaml
- src/app/meshes/views/MeshDetailIndexView.vue
- src/app/meshes/views/MeshTabsView.vue
- src/app/policies/locales/en-us/index.yaml
- src/app/policies/views/PolicyDetailView.vue
- src/app/services/locales/en-us/index.yaml
- src/app/services/views/ServiceDetailView.vue
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneEgressListView.vue
- src/app/zones/views/ZoneIngressListView.vue
**chore: removes suffixes from page titles in detail views**
Removes the suffixes from page titles in detail views (e.g. the service detail view will now only include the service name and not "{name} Service").
**chore(meshes): updates breadcrumbs and heading levels**
Removes the Mesh name from the breadcrumbs for the list views Services, Gateways, Data Plane Proxies, and Policies.
Removes the Mesh name heading from the detail views Service, Gateway, Data Plane Proxy, and Policy. Instead, their respective resource name is now the level 1 heading (used to be level 2).
> chore: updates breadcrumbs and page titles

- src/app/application/services/data-source/DataSourcePool.ts
- src/services/production.ts
Adds a small DI service for retrieving a cache key prefix for DataSource.
> chore: adds data source cache key prefix service

- src/app/common/DefinitionCard.vue
- src/app/common/ResourceStatus.vue
- src/app/data-planes/components/DataPlaneDetails.vue
- src/app/main-overview/components/ControlPlaneDetails.vue
- src/app/meshes/components/MeshDetails.vue
- src/app/services/components/ExternalServiceDetails.vue
- src/app/services/components/ServiceInsightDetails.vue
- src/app/zones/components/ZoneDetails.vue
- src/app/zones/components/ZoneEgressDetails.vue
- src/app/zones/components/ZoneIngressDetails.vue
**chore: makes definition card font size smaller**
Makes the font size used for definition cards smaller overall as we often get long resource names, etc. and it starts to look jarring.
**chore: removes self-referencing links from detail views**
Removes the links for the resource name cards as they’re not useful.
**chore: uses equal width columns for definition card lists**
> fix: too large font sizes on definition cards

- src/app/common/KumaLogo.vue
- src/app/common/UpgradeCheck.vue
- src/app/zones/components/ZoneCreateKubernetesInstructions.vue
Once we got a `i18n` layer and `t` into the application we started to use this for most strings over using environment variables. I spotted `KUMA_PRODUCT_NAME` being used so decided to get rid of the last remaining ones in the project.
Note: This does not make this environment variable unavailable yet (you will see I didn't remove the code for this), but this should be removed in a future update.
> chore: Remove usages of KUMA_PRODUCT_NAME

- src/app/application/components/app-collection/AppCollection.vue
- src/app/common/DocumentationLink.vue
- src/app/common/EmptyBlock.vue
- src/app/data-planes/components/DataPlaneList.vue
- src/app/data-planes/locales/en-us/index.yaml
- src/app/main-overview/components/ControlPlaneDetails.vue
- src/app/main-overview/components/MeshesDetails.vue
- src/app/main-overview/components/ZoneControlPlanesDetails.vue
- src/app/main-overview/locales/en-us/index.yaml
- src/app/meshes/locales/en-us/index.yaml
- src/app/meshes/views/MeshListView.vue
- src/app/policies/components/PolicyConnections.spec.ts
- src/app/policies/components/PolicyList.vue
- src/app/services/views/ServiceListView.vue
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneCreateView.vue
- src/app/zones/views/ZoneEgressListView.vue
- src/app/zones/views/ZoneIngressListView.vue
- src/app/zones/views/ZoneListView.vue
- src/locales/en-us/common/index.yaml
**chore: standardizes empty state usage**
Makes AppCollection accept our standard empty state component and passes it on to KTable. This way, each list view can easily customize the empty state with enriched UI elements like a "Create Zone" button. By default, our own empty state component will also be used (again) in list views.
**chore: uses primary appearance for creation buttons**
**chore: adds Create Zone button to overview**
**Before**:
**After**:
> chore: standardizes empty state usage

- features/mesh/dataplanes/DetailViewContent.feature
- features/zones/DetailViewContent.feature
- features/zones/zone-cps/Item.feature
- src/app/common/EnvoyData.vue
- src/app/common/subscriptions/SubscriptionDetails.vue
- src/app/common/subscriptions/SubscriptionHeader.vue
- src/app/data-planes/components/DataPlaneDetails.vue
- src/app/data-planes/locales/en-us/index.yaml
- src/app/zones/components/ZoneEgressDetails.vue
- src/app/zones/components/ZoneIngressDetails.vue
- src/app/zones/locales/en-us/index.yaml
- src/locales/en-us/common/index.yaml
- src/locales/en-us/http/index.yaml
- src/test-support/mocks/src/dataplanes+insights.ts
- src/test-support/mocks/src/meshes/_/dataplanes+insights.ts
- src/test-support/mocks/src/meshes/_/dataplanes+insights/_.ts
- src/test-support/mocks/src/zoneegressoverviews.ts
- src/test-support/mocks/src/zoneegressoverviews/_.ts
- src/test-support/mocks/src/zoneingresses+insights.ts
- src/test-support/mocks/src/zoneingresses+insights/_.ts
- src/test-support/mocks/src/zones+insights/_.ts
**feat: only queries envoy data if resource is online**
Changes EnvoyData to only query envoy data if the corresponding resource is online.
**chore(zones): moves subscriptions into overview tab for ingress/egress details**
**chore(subscriptions): collapses responses sent and acknowledged, adds total**
Collapses the responses sent and acknowledged entries.
Adds the total number of responses sent and acknowledged.
Renames the "Insights" tab to "Subscriptions".
> chore: updates zone details and subscriptions

- src/app/onboarding/views/WelcomeView.spec.ts
- src/app/onboarding/views/WelcomeView.vue
- src/app/onboarding/views/__snapshots__/WelcomeView.spec.ts.snap
- src/app/zones/views/ZoneIngressListView.vue
- src/app/zones/views/ZoneListView.vue
- src/app/zones/views/ZoneTabsView.vue
- vite.config.preview.ts
Uses `can` for checking whether we can do zone type things in all `*View.vue` files (where we export `can` from RouteView).
There will be a follow up for the components. I've split this into separate PRs as I would rather look to see how straightforwards it is to pass down whether we can do zone type things into the components rather than using can in the component directly.
> chore: Uses can for zone abilities/features in all *View.vue files

- features/zones/DetailViewContent.feature
- src/app/common/DefinitionCard.vue
- src/app/common/TextWithCopyButton.vue
- src/app/common/subscriptions/SubscriptionHeader.vue
- src/app/zones/components/ZoneEgressDetails.vue
- src/app/zones/components/ZoneIngressDetails.vue
- src/app/zones/views/ZoneEgressListView.vue
- src/app/zones/views/ZoneIngressListView.vue
- src/types/index.d.ts
Adds networking data (Ingress: address and port, advertised address and port; Egress: address and port) to the Ingress/Egress detail and list views.
Implements one part of https://github.com/kumahq/kuma-gui/issues/1388.
> feat: adds networking data to ingress/egress detail and list views

- cypress/support/step_definitions/index.ts
- features/onboarding/Index.feature
- src/app/onboarding/guards.ts
- src/app/onboarding/index.ts
- src/services/production.ts
Continuation of https://github.com/kumahq/kuma-gui/pull/1236
Moves onboarding route guards into their own 'module'
Also:
- Adds exact URL asserting so we can test for `/` (`contains` isn't enough for `/`)
- Temporarily moves our custom `createRouter` into `production.ts`, so we can then delete `router.ts` (this will be moved elsewhere later). We no longer have our own distinct createRouter/router setup function.
- Permanently deletes the old `#/url` style route guard. I don't think nowadays this is needed anymore (happy to put back if need be)
> chore(onboarding): Makes onboarding route guards injectable/modular

- src/app/application/components/data-source/DataSource.vue
- src/app/application/services/data-source/DataSourcePool.ts
- src/app/diagnostics/views/DiagnosticsView.vue
- src/app/main-overview/components/MainOverview.vue
- src/app/meshes/views/MeshDetailView.vue
- src/app/policies/views/PolicyDetailView.vue
- src/app/services/views/ServiceDetailTabsView.vue
- src/app/services/views/ServiceDetailView.vue
Fixes the order of loading and error blocks and makes them consistently check for `data` being `undefined`.
> fix: order of loading and error blocks

- features/diagnostics/DetailViewContent.feature
- features/main-overview/DetailViewContent.feature
- features/mesh/dataplanes/DetailViewContent.feature
- features/mesh/dataplanes/Index.feature
- features/zones/Create.feature
- features/zones/DetailViewContent.feature
- features/zones/ListViewContent.feature
- features/zones/PageNavigation.feature
- features/zones/zone-cps/Item.feature
chore(zones): adds test for lack of create zone button
chore(dataplanes): adds test for Zone column
> chore: expands standalone test coverage

- src/app/application/index.ts
- src/app/diagnostics/views/DiagnosticsView.vue
- src/index.ts
- src/services/production.ts
- src/services/tokens.ts
- src/utilities/index.ts
Moves some of our very commonly used components to be global.
Not only does this ease using these components, but it should also make certain components a lot easier to inject when/if we need to (instead of them only being injectable if they are used via `useComponentName`)
I've moved the imports/headers to the top of the template file here as it kinda make sense for 'headers' to be at the top of the file.
> chore: Make some app components global

- src/app/common/CopyButton.vue
- src/app/common/ResourceCodeBlock.vue
Adds a bordered style to the "Copy as Kubernetes" button to visually separate it from the default copy button a bit better.
Adds a tooltip to the "Copy as Kubernetes" button to explain its purpose.
> chore: tweaks copy as k8s button appearance

- features/zones/Create.feature
- src/app/zones/components/EntityScanner.vue
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneCreateView.vue
Validates the name field on the client-side in addition to processing the already handled service-side validation error.
Makes sure errors are cleared correctly when clicking "Create Zone" after showing a service-side error.
> feat(zones): improves handling of validation errors

- features/zones/Create.feature
- src/app/zones/components/EntityScanner.vue
- src/app/zones/components/ZoneCreateKubernetesInstructions.vue
- src/app/zones/components/ZoneCreateUniversalInstructions.vue
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneCreateView.vue
- src/assets/styles/_forms.scss
**feat(zones): shows confirm modal when exiting zone creation mid process**
Shows a confirmation modal when exiting the Zone creation process while (1) a Zone with a token was already create and (2) the Zone wasn’t connected, yet.
**feat: updates Create Zone wizard layout**
Updates the layout of the Create Zone wizard to split the form into sections for Zone name, configuration, connecting a Zone, and waiting for a Zone to be connected.
> feat: updates create zone appearance

- features/zones/Create.feature
- src/app/zones/components/ZoneCreateKubernetesInstructions.vue
- src/app/zones/components/ZoneCreateUniversalInstructions.vue
- src/app/zones/views/ZoneCreateView.vue
- src/store/storeConfig.ts
Moves globalAddress to use DataSource instead of the store.
---
Notes:
1. At this point **we should make a point of not adding anything else to the Vuex store**. Only onboarding is using the store, which whilst not a huge priority, would be good to remove also so we can then remove Vuex entirely. If there is a need for some sort of more in-depth frontend context/infinite state store then we should consider other alternatives via either provide/inject or Pinia. TLDR; If you need to add something to the Vuex store, please reach out to discuss first.
2. I noticed a number of things whilst doing this, and even started on a slightly bigger refactor. Some of the things I noticed shouldn't really be in here so whilst I pulled back for the moment to make this more isolated, a slightly larger …
> chore: Use DataSource for KDS address

- cypress/support/step_definitions/index.ts
- features/mesh/dataplanes/DetailViewContent.feature
- src/test-support/index.ts
See https://github.com/kumahq/kuma-gui/pull/1316#discussion_r1293326627
We had a bit of discussion a while back on the inability to omit a property from a merge (i.e. mark it as undefined). This adds a `!!js/undefined` YAML tag to let you do that.
I don't think we'll ever need the ability to specify between omitted vs set to `undefined` but if we do we can just add a new tag to cope for that.
> chore: Adds YAML undefined type to aid testing

- features/mesh/gateways/PageNavigation.feature
- src/app/data-planes/views/DataPlaneDetailTabsView.vue
- src/app/data-planes/views/DataPlanePoliciesView.vue
- src/app/gateways/locales/en-us/index.yaml
- src/app/gateways/views/GatewayPoliciesView.vue
fix: using incorrect route parameter for DPP/gateway policies
fix(gateways): detail view tabs linking to data plane routes
Note: I’ll be adding a test for the second issue later, but I’m busy with other things right now.
> fix: dataplane policies api url containing undefined

- features/mesh/Item.feature
- src/app/meshes/components/MeshDetails.vue
- src/app/meshes/views/MeshDetailView.vue
When viewing a mesh detail page, this PR ignores any errors coming from the `/mesh-insights/:name` endpoint. Instead we'd just show zeros if we get an error from that endpoint for the relevant stats.
There's probably more we could do here, and I almost made a lot more change to alter this slightly (for instance I didn't really want to use a zero when mesh-insights is loading/erroring), but I didn't want to get too involved at the moment.
Let me know if its worth making an issue to improve this so its clearer that loading/erroring is happening to prevent any confusion over the `0`.
> fix: Ignores mesh-insights errors

- package.json
- yarn.lock
Adds `@kong/icons` package so we can start using the new icons.
> chore(deps): adds @kong/icons package

- cypress/support/step_definitions/index.ts
I noticed that our exact URL assertions would wait on the URL being set but no on the value being equal, probably just due to how we initially did the plumbing for the base URL.
I've done this in a "lets just try improve the flake" for now. There is a larger "work on test" effort happening and I'll be working a lot in this area so I plan to do a better clean up then. Some initial things I noticed:
1. We have unfortunate naming happening we have `KUMA_BASE_URL` and `KUMA_BASE_PATH` depending on whether you are in the app or in the Cypress code (there might have been reasons for this I don't remember but I'll find out when I dive in here)
2. Using our `env` utility consistently in Cypress code was left as a TODO, this is also related to consistently getting env vars and having defaults, …
> fix(e2e): Uses `url.should` to assert URL exactness instead of `url.then`

- package.json
- src/app/common/CodeBlock.vue
- src/app/onboarding/views/__snapshots__/AddNewServicesCode.spec.ts.snap
- src/utilities/highlightElement.ts
- yarn.lock
Changes the CodeBlock component to use the KCodeBlock component’s dark theme.
Changes the syntax highlighting theme we use to its dark variant.
> chore: switches code blocks to dark theme

- src/app/zones/components/ZoneCreateKubernetesInstructions.vue
- src/app/zones/components/ZoneCreateUniversalInstructions.vue
- src/app/zones/views/ZoneCreateView.vue
- src/assets/styles/_base.scss
- src/assets/styles/_forms.scss
- src/assets/styles/_variables.scss
Changes the base ul and ol padding so that it doesn’t overflow its content container narrowly.
Overrides the KCard body font size specifically for forms where we expect general body text to have the same font size (`$kui-font-size-40`).
Tweaks the gaps between various form elements and groups to make it more clear which elements belong together in some way or another.
Stops using `k-input-label` as a styling utility as it will be removed in a future version of Kongponents.
**Before**:
**After**:
> chore(zones): tweaks create UI content formatting

- features/zones/DetailViewContent.feature
- src/services/kuma-api/KumaApi.ts
- src/test-support/mocks/fs.ts
- src/test-support/mocks/src/zone-ingresses/_.ts
- src/test-support/mocks/src/zoneegresses/_.ts
- src/types/index.d.ts
Note: Zone Egress looks correct according to https://kuma.io/docs/2.4.x/reference/http-api/#get-zone-egress (i.e. `/zoneegresses/:zoneEgress`)
> fix: zone ingress single resource API endpoint being wrong

- package.json
- public/mockServiceWorker.js
- yarn.lock
Pins vue-tsc to 1.8.11 because 1.8.12 has a regression that prevents it from inferring custom event types.
> chore(deps-dev): pins vue-tsc to 1.8.11

- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneCreateView.vue
- src/locales/en-us/common/index.yaml
Switches to using a KAlert at the top of the page in the Zone Create View instead of ErrorBlock.
**Before**:
**After**:
> chore(zones): switches to alert for error in create view

- cypress.config.ts
- cypress/support/step_definitions/index.ts
- cypress/support/step_definitions/visit.ts
- features/application/MainNavigation.feature
Mostly makes any "negative" assertions use `4000` for a timeout, for if we extend "positive" assertions to a `10000` timeout. This will mean "positive" will pass as soon as possible, but "negative" ones won't wait a full `10000` until they fail.
(plus a few tiny amends detailed in the inlines)
> chore(e2e): Adds a negative timeout defaulting to 4000

- src/services/i18n/I18n.ts
Uses the new `onError` configuration option of `core/i18n` to throw errors rather than `console.error` them. This means these errors will fail tests.
Note: For the minute I've just done a simple approach as I have some tests that require this elsewhere that use this.
We can come back and refactor soon, plus there is an issue already to do this https://github.com/kumahq/kuma-gui/issues/1478
> chore(e2e): Directly throw i18n errors with onError vs console.error

- .gitignore
- .vitepress/config.mts
**chore: fixes vitepress build**
Renames config.ts to config.mts to address `"vitepress" resolved to an ESM file.` error.
Adds `ignoreDeadLinks` config for the dead link checker matching on localhost references.
**chore: address vitepress config type issues**
> chore: fixes vitepress build

- cypress/support/step_definitions/visit.ts
All "positive" assertions should use the default timeout for the project
> fix(e2e): Removes hardcoded timeout from visit

- features/mesh/dataplanes/DetailViewContent.feature
- features/mesh/dataplanes/NoSubscriptions.feature
- src/utilities/dataplane.ts
Fix for:
> TypeError: Cannot read properties of undefined (reading 'length')
when using `getVersions`.
Test added that was failing before the fix. I also noticed a few strange things in the existing dataplane detail view tests to do with the name `ddp-1` being not just in the name of the dataplane, so I tweaked that here too.
> fix(dpps): Fix for undefined subscriptions access

- features/application/Loading.feature
- features/application/MainNavigation.feature
- features/mesh/dataplanes/DetailViewContent.feature
- features/mesh/policies/Data.feature
- features/onboarding/add-new-services-code/Index.feature
- features/onboarding/dataplanes-overview/Index.feature
- features/onboarding/multi-zone/Index.feature
- features/zones/Create.feature
- features/zones/Delete.feature
- features/zones/DetailViewContent.feature
- features/zones/ListViewContent.feature
- features/zones/zone-cps/Item.feature
- src/test-support/FakeKuma.ts
- src/test-support/mocks/src/dataplanes+insights.ts
- src/test-support/mocks/src/meshes/_/dataplanes+insights.ts
- src/test-support/mocks/src/meshes/_/dataplanes+insights/_.ts
- src/test-support/mocks/src/zoneegressoverviews.ts
- src/test-support/mocks/src/zoneegressoverviews/_.ts
- src/test-support/mocks/src/zoneingresses+insights.ts
- src/test-support/mocks/src/zoneingresses+insights/_.ts
- src/test-support/mocks/src/zones+insights.ts
- src/test-support/mocks/src/zones+insights/_.ts
- src/types/index.d.ts
This began as a clean up of e2e test code following improvements in:
- https://github.com/kumahq/kuma-gui/pull/1482
- https://github.com/kumahq/kuma-gui/pull/1417
- https://github.com/kumahq/kuma-gui/pull/1452
I also noticed some areas mainly around subscription counts that felt a little strange, and began to tweak those a little, and then as I delved deeper I started to go down a bit of a rabbit hole:
- I started to make all mock instances of subscriptions used the `KUMA_SUBSCRIPTION_COUNT` variable.
- Started making all mock instances of subscriptions as consistent as possible, and decided to make a `fake.kuma.connection` for providing `connectTime`/`disconnectTime`, which I _think_ is more realistic, would be good for a second pair of eyes on that. The intention is that only the last …
> chore(e2e): general e2e test improvements

- jest/jest-setup-after-env.ts
- src/services/development.ts
- src/services/e2e.ts
- src/services/testing.ts
The fact that our MSW `worker.start` has never been awaited has made me double, triple think that many times now or led to a wild goose chase that I decided to push this up after _yet again_ realizing that we don't use MSW in our e2e tests 😆 
See https://github.com/kumahq/kuma-gui/issues/952
While it's "technically incorrect" it hasn't affected anything for years now. (I have noticed that very very occasionally if you have no other browser window open and only on your first visit to the application on a fresh start, MSW sometimes won't get installed in time leading to a stuck loader, this is only during development or I suppose possibly PR previews).
While I was here I tweaked a few names of things and moved a tiny bit of stuff now that our DI layer has taken way more shape since this bit …
> chore(test): Asyncify MSW initializing

- features/mesh/services/Item.feature
- src/app/services/sources.ts
- src/services/kuma-api/KumaApi.ts
- src/types/api.d.ts
Removes the workaround for `/meshes/:mesh/external-services` not being filterable by service names (i.e. the name of a `ServiceInsight` object, not necessarily the `ExternalService`).
Note: I’ll leave this open for a while and only merge once the necessary API changes have rolled out everywhere.
> chore(services): remove external service filtering workaround

- package.json
- src/app/AppHeader.vue
- src/app/application/components/app-collection/AppCollection.vue
- src/app/application/components/app-view/AppView.vue
- src/app/common/DocumentationLink.vue
- src/app/common/EnvoyData.vue
- src/app/common/ErrorBlock.vue
- src/app/common/KFilterBar.vue
- src/app/common/LoadingBlock.vue
- src/app/common/PolicyTypeTag.vue
- src/app/common/ResourceDateStatus.vue
- src/app/common/WarningIcon.vue
- src/app/common/subscriptions/SubscriptionDetails.vue
- src/app/data-planes/components/DataPlaneList.vue
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/main-overview/components/MainOverview.vue
- src/app/meshes/views/MeshListView.vue
- src/app/onboarding/views/WelcomeView.vue
- src/app/policies/components/PolicyList.vue
- src/app/services/views/ServiceListView.vue
- src/app/zones/components/EntityScanner.vue
- src/app/zones/components/MultizoneInfo.vue
- src/app/zones/views/ZoneCreateView.vue
- src/app/zones/views/ZoneEgressListView.vue
- src/app/zones/views/ZoneIngressListView.vue
- src/app/zones/views/ZoneListView.vue
- src/assets/styles/_variables.scss
- yarn.lock
Replaces most Kongponents icons with @kong/icons. This includes cases where we used a component’s `icon` prop as that functionality will be removed from Kongponents. There is one instance of KIcon left in CopyButton that we can’t replace, yet because we’d otherwise have two slightly different copy icons in resource code blocks.
This PR is a preparation for https://github.com/kumahq/kuma-gui/pull/1532. I decided to pull it out of that PR because it’s a change we can make before switching to Kongponents’ alpha branch.
> refactor: switches to @kong/icons

- features/mesh/gateways/PageNavigation.feature
- src/app/common/NavTabs.vue
I spotted one last now unnecessary `wait` (since https://github.com/kumahq/kuma-gui/pull/1493)  in a gateway test. While I was removing it I spotted I could also change the selectors to use `data-testid`s.
The only `wait`s we have left now are these ones in this single file:
https://github.com/kumahq/kuma-gui/blob/d4c6fdc3cfd13e63d298176509dc4285ddc58c83/features/mesh/services/Item.feature#L59-L64
These ones are due to Cypress thinking that `input` elements are disabled (even though when you check they aren't disabled, they are not) and not letting you type into them unless you wait a little bit first. No idea what the issue is on those ones, but that one is for another day.
> chore(tests): Remove wait from gateway test

- .vitepress/config.mts
- .vitepress/theme/style.css
- DEVELOPER.md
- README.md
- RELEASE.md
- docgen.config.js
- docs/ComponentIndex.vue
- docs/components.md
- docs/getting-started.md
- docs/modules.md
- docs/releasing.md
- docs/routing.md
- index.md
- package.json
- vite.config.ts
- yarn.lock
**chore: installs glob types**
**docs: expands dev documentation**
Adds new documentation pages on modules and routing. Adds README.md as the home page of the documentation site.
Makes DEVELOPER.md be up-to-date. Removes section on releasing a new version Kuma (found in RELEASE.md now).
Creates RELEASE.md with the release documentation previously found in DEVELOPER.md.
**docs: adds basic component docs setup**
- I’m leaving the setup for component docs relatively unfinished as I’m not totally clear what’s best here. It would be nice to have a table of contents-style component index that links to the generated component docs.
- The code doc generation isn’t hooked up to anything yet. For now, run `yarn docs:generate` to regenerate …
> docs: expand dev documentation

- src/app/application/components/app-view/AppView.vue
- src/test-support/mocks/src/meshes/_/dataplanes+insights.ts
- src/test-support/mocks/src/meshes/_/dataplanes+insights/_.ts
**chore: replaces deprecated faker methods**
**refactor: avoids duplicating title bar template**
Changes AppView so that the title bar template doesn’t have to be duplicated.
> refactor: avoids duplicating title bar template

- src/app/common/LoadingBlock.vue
...by adding an inline-block
Before:
After:
> fix: make sure spinners in LoadingBlock are centered

- src/app/zones/views/IndexView.vue
Adds online / total counts in the Zone Listing for the Zone's Ingresses and Egresses.
Using the `page=1&size=100` assumption here for the moment, with the knowledge that there are backend API additions coming to support this.
Again this one is in semi-draft as I'd like to add tests, but I wanted to get something up as I wanted to ask for any ideas around generalising / reusing the getIngresses/getEgresses functions here. I tried various generic type things, but they all turned out a bit weird / non-worky. Let me know if you have any suggestions, if not we can stick with this if there are no issues with it.
Closes https://github.com/kumahq/kuma-gui/issues/1608
> feat(zones): adds ingress/egress online/total counts to zone listing

- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/main-overview/components/MainOverview.vue
- src/app/meshes/components/MeshDetails.vue
- src/app/services/components/ExternalServiceDetails.vue
- src/app/services/components/ServiceInsightDetails.vue
- src/app/zone-egresses/views/item/DetailView.vue
- src/app/zone-ingresses/views/item/DetailView.vue
- src/app/zones/views/item/DetailView.vue
- src/assets/styles/_components.scss
**refactor: simplifies columns component**
Simplifies the CSS columns component to not require setting `--columns` anymore.
**chore: removes unused variable-columns component**
> refactor: simplifies columns component

- src/app/App.vue
- src/app/common/NavTabs.vue
Allows NavTabs to overflow using a scroll container.
Prevents NavTabs items from wrapping.
> chore: allows NavTabs to overflow

- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/item/DetailView.vue
Changes text from `Authentication Type` to `Dataplane authentication type` only in Zones, which I think is the only change required here.
Please see below issue though incase I've misunderstood.
Closes https://github.com/kumahq/kuma-gui/issues/424
> chore(zones): Alter text for authentication types

- src/services/env/CliEnv.ts
Removes last runtime-code reference to VITE_ var (we only use this one in tests).
There's one more I found but thats in the vite build config, so not only is that fine because its in `VITE` but also we don't have our `env` etc available there, nor should we.
Closes https://github.com/kumahq/kuma-gui/issues/666 😬
> chore(tests): Removes last in-application reference to VITE_ vars

- src/app/App.vue
- src/app/application/components/app-collection/AppCollection.vue
- src/app/application/components/app-view/AppView.vue
- src/app/application/components/route-view/RouteView.vue
- src/app/common/TrayView.vue
- src/locales/en-us/common/index.yaml
Contains all the non-module specific changes needed for adding service trays (like for services https://github.com/kumahq/kuma-gui/pull/1611).
**chore: cleans up AppView**
Moves the `.app-main-content` styles into AppView (where the `.app-main-content` element is).
**feat: adds TrayView component**
**chore: always styles first AppCollection row item**
**chore: removes explicit name parameters from RouteView method**
Removes the `name` parameter from the `router.push` call in RouteView. They’re currently not necessary and cause issues when using tray routes for list views (specifically, they prevent a cold navigation to a summary route).
**refactor: switches to KSlideout**
- Follow up to #1601 and #1604.
> feat: adds tray view

- features/mesh/services/Item.feature
- src/app/data-planes/components/DataPlaneList.vue
- src/app/services/views/ServiceDataPlaneProxiesView.vue
**fix(services): check for gateway being inverted**
Fixes the service detail view’s DPP list passing `props.gateways` as `true` when the first item **isn’t** a gateway and as `false` when the first item **is** a gateway. This view is still flawed, but it’s less broken now.
**fix(services): dpp list linking to wrong views**
Fixes the service detail view’s DPP list linking to the wrong views depending. This change makes it so that the links in this list are always correct and independent from `props.gateways`.
Addresses some of the issues related to #1443.
> fix: service dpp list linking to wrong views

- .eslintrc.js
- cypress/support/step_definitions/index.ts
- src/app/application/components/route-view/RouteView.vue
- src/app/application/services/data-source/SharedPool.ts
- src/app/data-planes/components/DataPlaneList.vue
- src/app/onboarding/components/ServiceBox.vue
- src/services/kuma-api/KumaApi.ts
- src/test-support/FakeKuma.ts
- src/test-support/client.ts
- src/test-support/fake.ts
- src/types/index.d.ts
> chore(linters): applies consistent TS delimiter rules

- src/app/zones/views/IndexView.vue
See title
Note: I would like to move this code elsewhere (to the `data` folder). I didn't put it there when I originally did it because it was crossing over with other PRs I think, and I didn't do it here, as it would probably appear like lots of change. So I'm PRing this fix, and I'll move the code later.
> fix(zones): Catch zoneEgressInsight/zoneIngressInsight being undefined

- .eslintrc.js
Avoids the mistaken `data-test-id` instead of `data-testid` which I've almost done on more than one occasion.
> chore: Adds data-test-id restricted eslint rule

- .eslintrc.js
- src/app/main-overview/views/MainOverviewView.vue
- src/app/zone-ingresses/views/item/ServicesView.vue
Adds a linter rule for erroring on undefined Vue components which is an easy mistake to make.
Fixes three instances of undefined components this rule caught.
> chore(linter): error on undefined Vue components

- features/mesh/dataplanes/DataplaneSummary.feature
- features/mesh/dataplanes/Index.feature
- features/mesh/gateways/GatewaySummary.feature
- features/mesh/gateways/Index.feature
- features/mesh/services/Item.feature
- src/app/data-planes/components/DataPlaneList.vue
- src/app/data-planes/components/DataPlaneSummary.vue
- src/app/data-planes/locales/en-us/index.yaml
- src/app/data-planes/routes.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/data-planes/views/DataPlaneSummaryView.vue
- src/app/gateways/routes.ts
- src/app/gateways/views/GatewayListView.vue
- src/app/services/routes.ts
- src/app/services/views/ServiceDataPlaneProxiesView.vue
Adds a summary tray to the DPP and Gateway list views and the DPP table in the service detail view.
Resolves #1637.
- I decided to move the "Last updated" column into the summary trays (and out of the tables). Let’s discuss this.
- There is an issue with KSlideout: content that overflows the tray area is clipped off because the content area has `overflow-y: auto` which implies that `overflow-x` _also_ computes to `auto` (and cannot be changed to `visible`). This can be observed in service trays that have a StatusBadge with a tooltip: the tooltip content will be only partially visible.
- The arrangement of the summary trays in the DPP listing of a service detail view is a little awkward right now. In order to link to the correct …
> feat(data-planes): adds summary tray

- src/app/services/views/ServiceSummaryView.vue
Moves the summary content into the view so we’re able to control the layouting mechanisms more precisely. Generally, summary views are different from detail views anyway.
> refactor(services): moves summary content into view

- features/mesh/MeshSummary.feature
- features/mesh/services/ServiceSummary.feature
- features/zones/zone-cps/ZoneSummary.feature
- src/app/meshes/views/MeshListView.vue
- src/app/services/views/ServiceListView.vue
- src/app/zones/views/IndexView.vue
Disables the summary trays for Zone CPs, Meshes, and Services.
> chore: disable summary trays for some views

- src/app/common/subscriptions/SubscriptionDetails.vue
- src/app/common/subscriptions/SubscriptionList.vue
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/item/DetailView.vue
Adds a short sentence to the top of the subscription stats on the zone cp detail page.
Note: I did this in 'feature' mode, I would imagine a follow up soon to reorg this UI widget to make it a little more flexible and move it into a `subscriptions` module, I can do that later as more of a refactor/follow up PR.
> feat(zones): add intro message describing data in subscription lists

- features/mesh/dataplanes/Index.feature
- src/app/data-planes/components/DataPlaneList.vue
I moved the relevant into the data transformation function because that has types that would prevent that sort of mistake.
This broke in https://github.com/kumahq/kuma-gui/pull/1670/files#diff-82dda41d4ed9d37e3744cb3d5df6be752b1f5eefaa6da07331be40f5ca83cea5L175. There wasn’t a test covering it so I added one.
Resolves #1713.
> fix(dataplanes): certificate not showing in list view

- src/app/gateways/views/GatewayPoliciesView.vue
- src/types/index.d.ts
Changes the gateway detail view’s policy tab to treat delegated gateways the same as regular Data Plane Proxies (i.e. the same as the DPP detail view’s policy tab).
Resolves #1720.
> fix(gateways): treating delegated gateways as builtin gateways

- cypress/support/step_definitions/index.ts
- features/diagnostics/DetailViewContent.feature
- src/app/common/CodeBlock.vue
- src/app/common/EnvoyData.vue
- src/app/common/ResourceCodeBlock.vue
- src/app/data-planes/views/DataPlaneClustersView.vue
- src/app/data-planes/views/DataPlaneConfigView.vue
- src/app/data-planes/views/DataPlaneStatsView.vue
- src/app/data-planes/views/DataPlaneXdsConfigView.vue
- src/app/diagnostics/views/DiagnosticsView.vue
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicySummaryView.vue
- src/app/services/views/ServiceConfigView.vue
- src/app/services/views/ServiceSummaryView.vue
- src/app/zone-egresses/views/item/ClustersView.vue
- src/app/zone-egresses/views/item/ConfigView.vue
- src/app/zone-egresses/views/item/StatsView.vue
- src/app/zone-egresses/views/item/XdsConfigView.vue
- src/app/zone-ingresses/views/item/ClustersView.vue
- src/app/zone-ingresses/views/item/ConfigView.vue
- src/app/zone-ingresses/views/item/StatsView.vue
- src/app/zone-ingresses/views/item/XdsConfigView.vue
- src/app/zones/views/item/ConfigView.vue
chore: uses TS syntax for props
fix(codeblock): secondary-actions slot not being optional
chore: removes props.queryKey uses
feat(codeblock): preserves queries using URL parameter
refactor: moves code block query storing logic into views
Resolves #1441.
* Still considering whether it’s worth it to do all the work of `refactor: moves code block query storing logic into views` just so we can feed the route parameters through from the view components.
> feat: preserve code block queries using url parameters

- cypress/support/step_definitions/index.ts
- features/diagnostics/DetailViewContent.feature
It looks like it can happen that with the following structure:
```ts
$(selector).then(($el) => {
const chainer = $el[0].tagName === 'INPUT' ? 'have.value' : 'contain'
cy.wrap($el).should(chainer, value)
})
```
... interactions like browser navigation can happen between getting the element with `$(selector)` and asserting against it inside the `then` callback. This can break tests.
There probably are other solutions to this, but this is the simplest thing I could think of for now.
> chore(e2e): split input and element value assertion commands

- src/app/App.vue
Removes the transition on App.vue’s router view. The linter for https://eslint.vuejs.org/rules/require-toggle-inside-transition.html started to go off and that made me wonder if we even really use this transition. I’m not sure what effect it actually has on our pages. Does it have any?
> chore: removes unused transition

- src/app/application/components/app-view/AppView.vue
Sometimes we will need the `<div class="actions">` in AppView to always be in the DOM for if we need to inject something into it via Vue's Teleport functionality.
Teleport uses a CSS selector to target where to teleport its DOM to, and from what I can see there is no way to know whether a Teleport has been added to the page to decide whether to include `<div class="actions">` or not.
We probably only want to make one `<div class="actions">` be available for injecting into using Teleport probably using something similar to the parent/ancestor lookup we do for breadcrumbs, but this probably needs thinking about some more. In the meantime for the single instance we currently would like to use this for, the contents of this PR are fine and can be improved at a later date.
> chore: add actions div always

- src/app/common/ResourceCodeBlock.vue
- src/app/common/SummaryView.vue
- src/app/data-planes/components/DataPlaneSummary.vue
**fix(summary-view): content being taller than viewport**
Fixes the summary view being taller than the viewport.
Note: This will be removed again with Kongponents v9 where the underlying issue was fixed.
**fix: tooltips being cut-off**
> fix: small summary view issues

- cypress/support/step_definitions/index.ts
- features/zones/Create.feature
- src/app/application/services/data-source/CallableEventSource.ts
- src/app/application/services/data-source/index.ts
- src/app/zones/data/index.ts
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/sources.ts
- src/app/zones/views/CreateView.vue
- src/test-support/intercept.ts
- src/test-support/mocks/src/zones/_/_overview.ts
Back in https://github.com/kumahq/kuma-gui/pull/1634 we changed the functionality of checking for a connected zone by additionally catching a 404 error and retrying the request, which I'd wrongly assumed how this functioned.
The endpoint only ever returns a 404 if the zone is deleted (i.e. doesn't exist). It doesn't 404 if the zone exists but is not connected.
Due to the change, it was possible to create a zone, without connecting it, and then in say another tab, delete the zone, and the scanner would continue to spin due to the 404s.
I've removed the 404 retries, and also added further testing for making sure a 404 shows the error page when the scanner is waiting to connect, and I also updated the mocks so that they are closer to the real responses.
We decided that we should check for a …
> fix(zones): Zone creation should error normally on 404 responses

- features/onboarding/Index.feature
- src/app/control-planes/views/ControlPlaneDetailView.vue
- src/app/onboarding/components/OnboardingNotification.vue
- src/test-support/mocks/src/mesh-insights.ts
The long story:
During https://github.com/kumahq/kuma-gui/pull/1728 a DataSource source was removed (https://github.com/kumahq/kuma-gui/pull/1728/files#diff-8c51094d188779df11ec5a418503cf5a77c088bb12581335955952e7deef4c3dL50-L65), and replaced by https://github.com/kumahq/kuma-gui/pull/1728/files#diff-8c51094d188779df11ec5a418503cf5a77c088bb12581335955952e7deef4c3dR100-R122
Then, as well as this usage:
https://github.com/kumahq/kuma-gui/pull/1728/files#diff-9d4c2f48081cf9b206eb208a8f15ad06ede0411df7c550dbd938e1926d89b2d9L21
... there is another usage of this DataSource for onboarding which, if you only have 1 mesh called `default` would use this DataSource to figure out if you had added any dataplanes yet, if not we would show you the onboarding notification.
Since the source was removed, …
> fix(onboarding): Fixes error with onboarding when detecting new install

- features/zones/Create.feature
- features/zones/Delete.feature
- package.json
- src/app/common/CodeBlock.vue
- src/app/common/CopyButton.vue
- src/app/common/NavTabs.vue
- src/app/common/ResourceCodeBlock.vue
- src/app/common/StatusBadge.vue
- src/app/common/SummaryView.vue
- src/app/common/TagList.vue
- src/app/common/UpgradeCheck.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/kuma/components/ApplicationShell.vue
- src/app/onboarding/components/OnboardingNavigation.vue
- src/app/services/views/ServiceDataPlaneProxiesView.vue
- src/app/zone-ingresses/views/ZoneIngressServicesView.vue
- src/app/zones/components/ZoneActionMenu.vue
- src/app/zones/views/ZoneCreateView.vue
- src/app/zones/views/ZoneListView.vue
- src/assets/styles/_utilities.scss
- src/assets/styles/_variables.scss
- yarn.lock
Kongponents v9 migration guide: https://alpha--kongponents.netlify.app/guide/migrating-to-version-9.html
- **chore(deps): updates @kong/kongponents to v9.0.0-alpha.N**
- **refactor(codeblock): switches to @kong/icons**
Replaces all the copy KIcon.
- **chore: addresses KBadge changes**
- **chore: addresses KButton changes**
Appearance: renames outline to tertiary.
Size: removes some instances of `size="small"` as we don’t need it anymore in most cases.
Adds `icon-only` to icon-only buttons.
- **chore: addresses KCard changes**
- **chore: addresses KCodeBlock changes**
- **chore: addresses KDropdownMenu changes**
Removes unnecessary `props.buttonAppearance`.
Renames `props.label` to `props.triggerText`.
Updates related test selector usage.
- **chore: addresses KInput changes**
- **chore: …
> refactor: switches to kongponents v9 alpha

- src/app/common/EnvoyData.vue
- src/app/data-planes/views/DataPlaneClustersView.vue
- src/app/data-planes/views/DataPlaneStatsView.vue
- src/app/data-planes/views/DataPlaneXdsConfigView.vue
- src/app/zone-egresses/views/ZoneEgressClustersView.vue
- src/app/zone-egresses/views/ZoneEgressStatsView.vue
- src/app/zone-egresses/views/ZoneEgressXdsConfigView.vue
- src/app/zone-ingresses/views/ZoneIngressClustersView.vue
- src/app/zone-ingresses/views/ZoneIngressStatsView.vue
- src/app/zone-ingresses/views/ZoneIngressXdsConfigView.vue
- src/locales/en-us/common/index.yaml
Removes the online check from the EnvoyData component. It wasn’t correctly implemented for ZoneIngress and ZoneEgress where we would need to check for the status of the Zone not the ZoneIngress/ZoneEgress.
- This is one half of #1565. The other half will be ensuring that we correctly surface information from the error responses added in https://github.com/kumahq/kuma/issues/5216.
> chore: remove online check for envoy data

- src/app/application/components/route-view/RouteView.vue
- src/app/zones/views/ZoneCreateView.vue
This is pretty much the code I originally added https://github.com/kumahq/kuma-gui/pull/1634/commits/230027097451b272a162889e87f918d5723339f9 and then removed during review, apart from: I found that vue-router also has a `.back()`, so I preferred to use that, although I still need to access window to check to see if we came straight to the URL of the modal.
Closes https://github.com/kumahq/kuma-gui/issues/1706
> fix(zones): Make sure the exit the modal doesn't take you elsewhere

- .eslintrc.js
- src/app/application/services/data-source/DataSourcePool.ts
- src/app/application/services/data-source/index.ts
- src/app/data-planes/sources.ts
~I've had various iterations of this sat around for a little while now, and I think this is one I could be happy merging, so whilst I'm still not 100% I want to I wanted to put it up for review to see what feedback there was. So, this is currently in draft but~ looking for feedback.
---
This PR adds automatic types to the `"/services/:name": (params) => { params.name }` sources. The one little tiny downside is that currently you have to use `defineSources`, but you do maintain the key names (or the URIs) in the result type, which is important and why a simpler type definition wouldn't have been good enough for me.
Notes:
- We maintain the keys in the resulting definition, I don't want to lose these by doing something simpler like `Record<string,...>`
- `params` are now automatically …
> chore: Add automatic typing to source internals

- src/test-support/FakeKuma.ts
chore: add tags mock utility
chore(dataplanes): inline mock utilities in networking utility
- Related conversation: https://github.com/kumahq/kuma-gui/pull/1803#discussion_r1404323972
We currently use `dataplaneNetworking` in five mocks (of which one isn’t strictly necessary because we don’t use the associated endpoint). For the remaining four mocks, I don’t want to repeat the contents of `dataplaneNetworking`. Ideally we had a generator method for an entire Dataplane object and an entire DataplaneOverview object. That would cut it down to two mocks (i.e. tolerable repetition) and the effect to see the entire object structure in one place. For now, `dataplaneNetworking` is a relatively good compromise because of how far up it …
> chore(dataplanes): tweak mocks

- src/app/control-planes/sources.ts
- src/services/env/Env.ts
For the moment at least I've just moved the hardcoded string into Env.
We only use this value (well, not even this value) in one place/environment anyway so I've not moved the string to `.env` or anything, partly because it probably we only use this value in the single environment anyway, and partly because I think I would like to get rid of all the `.env` stuff pretty soon anyway.
Lastly, we still expose this to the application via a `DataSource` so whilst this is currently an `env` we can change it do a runtime API driven value at a later date if we want to.
> chore: Move kds URL to env

- package.json
- src/app/common/SummaryView.vue
- yarn.lock
See https://github.com/Kong/kongponents/blob/alpha/CHANGELOG.md.
> chore(deps): Bump @kong/kongponents from 9.0.0-alpha.55 to 9.0.0-alpha.63

- src/app/data-planes/components/DataPlaneList.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/services/views/ServiceDataPlaneProxiesView.vue
- src/test-support/FakeKuma.ts
- I’ve made this change specific to the DPP list for now. We could consider generalizing this to all list views, but I think this should be a good first step.
- I’ve updated the logic for DPP name generation in our mocks to be a bit more realistic. This isn’t quite complete, yet. Ideally, the DPP mocks would have the same zone prefix in the name as they have a zone tag in somewhere in `networking`. Another day.
> chore(dataplanes): truncate name column

- src/app/data-planes/components/DataPlaneList.vue
- src/app/data-planes/components/DataPlaneSummary.vue
- src/app/data-planes/data/index.spec.ts
- src/app/data-planes/data/index.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/onboarding/views/OnboardingDataplanesView.vue
- src/app/subscriptions/data/index.spec.ts
- src/app/subscriptions/data/index.ts
- src/app/zones/data/index.ts
- src/utilities/dataplane.spec.ts
- src/utilities/dataplane.ts
Follow up to https://github.com/kumahq/kuma-gui/pull/1800. Follow up PRs to this one: https://github.com/kumahq/kuma-gui/pull/1834 and https://github.com/kumahq/kuma-gui/pull/1835.
Moves the `getStatusAndReason` dataplane utility into its data transformation file.
> refactor(dataplanes): move getStatusAndReason into data transformation file

- .github/dependabot.yml
Ignores the Kongponents updates in Dependabot for the time being. Dependabot currently tries to update Kongponents’ alpha prerelease to PR prerelease versions which we definitely need to prevent.
- See example PR we don’t want: https://github.com/kumahq/kuma-gui/pull/1831
> chore(deps): ignore Kongponents in Dependabot

- features/diagnostics/DetailViewContent.feature
- src/app/application/components/route-view/RouteView.vue
- src/app/application/utilities/index.ts
- src/app/common/CodeBlock.vue
- src/app/common/EnvoyData.vue
- src/app/common/ResourceCodeBlock.vue
- src/app/data-planes/views/DataPlaneClustersView.vue
- src/app/data-planes/views/DataPlaneConfigView.vue
- src/app/data-planes/views/DataPlaneStatsView.vue
- src/app/data-planes/views/DataPlaneXdsConfigView.vue
- src/app/diagnostics/views/DiagnosticsDetailView.vue
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicySummaryView.vue
- src/app/services/views/ServiceConfigView.vue
- src/app/services/views/ServiceSummaryView.vue
- src/app/zone-egresses/views/ZoneEgressClustersView.vue
- src/app/zone-egresses/views/ZoneEgressConfigView.vue
- src/app/zone-egresses/views/ZoneEgressStatsView.vue
- src/app/zone-egresses/views/ZoneEgressXdsConfigView.vue
- src/app/zone-ingresses/views/ZoneIngressClustersView.vue
- src/app/zone-ingresses/views/ZoneIngressConfigView.vue
- src/app/zone-ingresses/views/ZoneIngressStatsView.vue
- src/app/zone-ingresses/views/ZoneIngressXdsConfigView.vue
- src/app/zones/views/ZoneConfigView.vue
Persists both the filter and regexp mode state of the code block in the URL alongside the already persisted query.
Resolves #1752.
- Noticed a bug (https://github.com/Kong/kongponents/issues/1868) while working on this
> feat: persist code block modes in URL

- features/mesh/dataplanes/DataplaneDetailsBuiltinGateway.feature
- features/mesh/dataplanes/DataplaneDetailsDelegatedGateway.feature
- features/mesh/dataplanes/DataplaneDetailsStandardProxy.feature
- src/app/data-planes/components/DataPlaneList.vue
- src/app/data-planes/components/DataPlaneSummary.vue
- src/app/data-planes/data/index.spec.ts
- src/app/data-planes/data/index.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/types/index.d.ts
- src/utilities/dataplane.spec.ts
- src/utilities/dataplane.ts
Follow up to https://github.com/kumahq/kuma-gui/pull/1834.
---
chore(dataplanes): fix rare flake
Fixes a rare flake that is caused by the mocked API endpoint for Dataplane details not removing the mTLS object. There was a negative assertion trying make sure that’s not the case, but it was executed before any content even rendered most of the times. When it didn’t _and_ the mock data rolled the dice for an expired cert, the flake happened.
**refactor(dataplanes): move warnings and cert expired utilities into data transformation file**
Moves the warnings and cert expired functionality into the dataplanes data transformation file in the form of the new `getIsCertExpired` and `getWarnings` utilities.
Adds new `getDataplaneType` utility.
**refactor(dataplanes): make all data transformers take …
> refactor(dataplanes): move warnings and cert expired utilities into data transformation file

- src/locales/en-us/common/index.yaml
Fix the UI not rendering at all in zone mode on account of the mode not being listed in our translation files. This is just a small fix to make the UI work in Kuma again. More work is needed to actually support zone mode.
> fix: ui not rendering in zone mode

- src/app/data-planes/features.ts
- src/app/data-planes/index.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/services/env/Env.ts
- src/services/env/env.spec.ts
Enables dataplane traffic view behind a feature flag.
Pretty much a copy/paste of https://github.com/kumahq/kuma-gui/pull/1839 behind a feature flag but there are a couple of additional type casts.
Note: there is still placeholder code in here that is not rendered via corresponding the slot as the comment is commented out. 
Also, I hit the same CSS lint issue as in https://github.com/kumahq/kuma-gui/pull/1839 here. I'll bring the issue up at a later date.
Make sure you have a cookie set to `KUMA_TRAFFIC_ENABLED=1` to view. The view only shows on non-gateways.
> feat: add feature flagged dataplane traffic view

- .env
- docs/frames/default.md
- src/app/common/UpgradeCheck.vue
- src/app/kuma/components/ApplicationShell.vue
- src/locales/en-us/common/index.yaml
- src/services/e2e.ts
- src/services/env/Env.ts
- src/services/env/env.spec.ts
- src/services/production.ts
- src/shims-env.d.ts
Moves some old `env` based URLs to use `t` instead
There are a few more strings we can move here, but they are ever so slightly more involved than these ones so I did the ones in this PR separately.
> chore: move some URLs from env to t

- features/zones/Create.feature
- src/app/zones/views/ZoneCreateView.vue
> fix(zones): create error being associated with current zone name

- src/app/application/components/app-collection/AppCollection.vue
- src/app/common/CopyButton.vue
- src/app/common/TagList.vue
- src/app/common/TextWithCopyButton.vue
- src/app/data-planes/components/DataPlaneList.vue
- src/app/services/views/ServiceListView.vue
**feat(services): add copy button to service name in list view**
**refactor(CopyButton): use type syntax for props**
**feat(dataplanes): show copy button for services in list view**
Add support for showing a copy button to the TagList component.
Resolves #1747.
> feat: allow copying service name from service/dataplane list views

- src/app/application/components/app-view/AppView.vue
- src/app/common/DefinitionCard.vue
- src/app/common/data-card/DataCard.vue
- src/app/onboarding/components/OnboardingHeading.vue
- src/app/onboarding/components/OnboardingPage.vue
- src/assets/styles/_base.scss
- src/assets/styles/_forms.scss
I keep noticing several bits of weirdness to do with line-heights and font-sizes. This PR deals mainly with line-heights and centralizes them using relative units in our base stylesheet. I also noticed setting `--kui-line-height` also solves some issues mainly with k-cards.
The font-size addition was a late amend when I noticed some weirdness there also. At least for the moment, this amend means we can control our base font size, which is important for us seeing as we use `rems` quite a bit. I guess there are other places where we might change our `rem` usage to use `--kui-font-size` more, but still I guess there will be places where we might use `rem`.
This PR originally grew out of https://github.com/kumahq/kuma-gui/pull/1807#pullrequestreview-1748060631
I'm still a little unsure about …
> chore: Reduce line-height overwrites, add base font-size

- src/app/common/CopyButton.vue
Use a neutral text color for the CopyIcon to de-emphasize it in our UI.
Remove `KUI_ICON_SIZE_30` from CopyIcon (it has no effect as it’s inside a KButton which enforces a standard icon size).
> chore(CopyButton): tweak appearance

- package.json
- yarn.lock
Manually bumped to replace https://github.com/kumahq/kuma-gui/pull/1822 which is failing, possibly due to this being added:
https://github.com/kumahq/kuma-gui/pull/1822/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR8018
> chore(deps-dev): Manually bump @badeball/cypress-cucumber-preprocessor from 19.1.0 to 19.2.0

- src/app/application/components/app-collection/AppCollection.vue
- src/app/policies/components/PolicyList.vue
See https://github.com/kumahq/kuma-gui/pull/1867#discussion_r1422437766
There's an additional commit I wasn't expecting to have to do here, but it seems to fix up another possible 'accessing a property of undefined' issue. I made the smallest quickest fix I could to address the typescript error as I don't have much context on this area, but please let me know if something else is required.
> chore: make AppCollection rows typed

- src/app/kuma/components/ApplicationShell.vue
I noticed a bit of weirdness with our help menu:
I tried to use KDropdownItem as much as possible instead of continuing to use anchors and then overwriting padding/colors etc, but I wanted to keep the text in the textContent rather than an attribute. At which point I noticed that the `:to` attribute requires a `label` but it doesn't use it hence the `""`. I noticed its like this in the kongponent documentation also (they just add placeholder values for the `label`) so I might file an issue over there abut this.
I also noticed that in using only KDropdownItem extra attributes such as `target` and `rel` get added to the `li`s aswell as the anchor tags, but all in all I think not having the CSS overwrites is preferable, if I file an issue over in kongponents I'll mention this also.
> fix: use plain KDropdownItems instead of nested anchors in the help menu

- features/mesh/dataplanes/DataplanePolicies.feature
- src/app/data-planes/components/RuleEntryList.vue
- src/app/data-planes/components/StandardDataplanePolicies.vue
**chore(dataplanes): add empty state to policies tab**
**chore(dataplanes): tweak new rules API-based policies**
Change table layout to always have fixed column widths.
Make sure that table cell content that becomes too long can wrap onto new lines.
Explicitly place each matcher’s individual expressions on a separate line (after the `and`).
Resolves #1883.
> chore(dataplanes): tweak new rules API-based policies

- features/mesh/dataplanes/DataplanePolicies.feature
- src/app/data-planes/components/DataPlaneList.vue
- src/app/data-planes/components/DataPlaneSummary.vue
- src/app/data-planes/data/index.spec.ts
- src/app/data-planes/data/index.ts
- src/app/data-planes/index.ts
- src/app/data-planes/locales/en-us/index.yaml
- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/data-planes/views/DataPlanePoliciesView.vue
- src/app/data-planes/views/DataPlaneSummaryView.vue
- src/app/onboarding/views/OnboardingDataplanesView.vue
- src/app/services/views/ServiceDataPlaneProxiesView.vue
- vite.config.production.ts
Hooks up data transformation utilities to all dataplane data sources (except anything releated to the "Policies" tab).
> refactor(dataplanes): hook-up data transformations to data sourcing

- src/app/zone-ingresses/components/ZoneIngressSummary.vue
- src/app/zone-ingresses/data/index.ts
- src/app/zone-ingresses/sources.ts
- src/app/zone-ingresses/views/ZoneIngressConfigView.vue
- src/app/zone-ingresses/views/ZoneIngressDetailView.vue
- src/app/zone-ingresses/views/ZoneIngressListView.vue
- src/app/zone-ingresses/views/ZoneIngressSummaryView.vue
- src/test-support/mocks/src/zone-ingresses/_/_overview.ts
- src/test-support/mocks/src/zone-ingresses/_overview.ts
- src/test-support/mocks/src/zones/_overview.ts
Reduces the majority of our ZoneIngress related reshaping functions.
This is pretty much the same approach as https://github.com/kumahq/kuma-gui/pull/1854 but has the additional weirdness of two types of ZoneIngress depending one whether its the root object or the child object. For the moment I'm copy/pasta'ing around this, but I a better approach would be to apply `Entity` conditionally, but I don't want to do that (or something else) here yet.
See https://github.com/kumahq/kuma-gui/issues/1264
Related https://github.com/johncowen/kuma-gui/commit/b11e78a5484df618da0b89dac585b81eaab8ea74 which aren't PRed yet as I also want to do ZoneEgress and then at least reduce repetition some more.
Oh I also updated some mocks here to:
1. replicate the fact that `subscriptions` never seems to be an …
> chore(zones): ZoneIngress data layer pt1 

- src/app/zone-egresses/data/index.ts
- src/app/zone-egresses/sources.ts
- src/app/zone-egresses/views/ZoneEgressConfigView.vue
- src/app/zone-egresses/views/ZoneEgressDetailView.vue
- src/app/zone-egresses/views/ZoneEgressListView.vue
- src/app/zone-egresses/views/ZoneEgressSummaryView.vue
- src/test-support/mocks/src/zoneegresses/_/_overview.ts
- src/test-support/mocks/src/zoneegresses/_overview.ts
Reduces the majority of our ZoneEgress related reshaping functions, copy/pasta'ed from https://github.com/kumahq/kuma-gui/pull/1867 with `availableServices` and `advertisedSocketAddress` removed.
This is pretty much the same approach as https://github.com/kumahq/kuma-gui/pull/1854 but has the additional weirdness of two types of ZoneEgress depending one whether its the root object or the child object. For the moment I'm copy/pasta'ing around this, but I a better approach would be to apply `Entity` conditionally, but I don't want to do that (or something else) here yet.
See https://github.com/kumahq/kuma-gui/issues/1264 and https://github.com/kumahq/kuma-gui/pull/1867
No tests here yet, or even a branch this time, I just copy pasted it from https://github.com/kumahq/kuma-gui/pull/1867 and …
> chore(zones): ZoneEgress data layer pt1

- src/app/data-planes/components/DataPlaneSummary.vue
- src/app/data-planes/data/index.spec.ts
- src/app/data-planes/data/index.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
Follow up to #1871.
Add data transformations for inbounds.
> refactor(dataplanes): add data transformations for inbounds

- src/app/policies/data/index.ts
I looked into an lint rule to prevent/auto-fix this, but it was a bit of a can of worms. At a minimum it seems, it would mean that our lint command will take much longer to lint, but it might be worth it anyway.
Figured I'd get the PR up with the fix before thinking more/considering making some lint changes.
Just to note, I was surprised this got through our CI but it's only visible during development and has no impact on production. The visible error is that the development build fails with a cannot find export type of error in the browser console.
> fix: add missing type export for policy type

- src/app/data-planes/components/BuiltinGatewayPolicies.vue
- src/app/data-planes/components/PolicyTypeEntryList.vue
- src/app/data-planes/components/RuleEntryList.vue
- src/app/data-planes/components/StandardDataplanePolicies.vue
- src/app/data-planes/data/index.ts
- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlanePoliciesView.vue
- src/types/index.d.ts
Follow up to #1871.
Move all data transformations happening in the Dataplane Policies tab components into the data layer.
> refactor(dataplanes): add data transformations for dataplane policies

- features/onboarding/dataplanes-overview/Index.feature
- src/app/data-planes/index.ts
- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/onboarding/views/OnboardingDataplanesView.vue
- src/app/services/views/ServiceDataPlaneProxiesView.vue
Migrates the OnboardingDataplanesView component to use DataSource. This is necessary in order to remove the access of the data layer transformation utility in this file.
> refactor(onboarding): use DataSource for dataplanes view

- src/app/data-planes/components/data-plane-traffic/DataPlaneTraffic.vue
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/test-support/mocks/src/meshes/_/dataplanes/test-dataplane/stats.ts
Adds refresh button to the Dataplane viz by way of a new 'actions' slot for the ServiceTraffic component.
[Direct Link](https://deploy-preview-1919--kuma-gui.netlify.app/gui/meshes/default/data-planes/redis-7dc86bbf7a-yidcd.firewall.kuma-system-proxy-3/overview) (ensure you enable `KUMA_TRAFFIC_ENABLED=true` for this host)
Notes:
- I copied the static `stats` mock endpoint over to `test-dataplane/stats.ts` so we can keep that static real world example data.
- I started making the `stats` endpoint we use dynamic, as we move forwards with this we will no longer have a `stats()` function in this file and instead the entire mock endpoint will use faker to be completely dynamic. At the moment I only did enough so you can see the refresh button working.
> feat(dataplanes): add refresh button to dataplane viz

- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- Adds `meshtrace_zipkin` to excluded list
- Switches tx/rx to the reverse on all cards as we are using `downstreams` for everything. (I'm guessing I need to do it for everything and not just outbounds, please let me know if not)
> chore: minor amends to dataplane viz

- src/app/data-planes/components/DataPlaneSummary.vue
- src/app/data-planes/data/index.spec.ts
- src/app/data-planes/data/index.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/test-support/FakeKuma.ts
- src/types/index.d.ts
This PR is a bit of a prequel to some other work I will be doing on the DataPlane viz, in that we would like to match the inbound `localhost_8080` inbound name with the service name of the inbound. In order to do that this PR first adds a `service` property/field to our DataplaneInbounds derived from the `kuma.io/service` tag.
I noticed that this reshape was almost already there but only for unhealthyInbounds, and unhealthyInbounds only contain the `service` and `port` and have all their other properties removed.
I've changed the reshaping to:
1. Add a `service` field to all inbounds and outbounds (derived from the `kuma.io/service` tag)
2. I moved things around a little as I realised I could remove the `getStatus` and `getUnhealthyInbounds` functions which where doubling/tripling up …
> chore: apply service names to all types of inbounds/outbounds

- src/app/common/data-card/DataCard.vue
- src/app/data-planes/components/data-plane-traffic/ServiceTrafficCard.vue
- src/app/data-planes/data/stats.spec.ts
- src/app/data-planes/data/stats.ts
- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/test-support/mocks/src/meshes/_/dataplanes/_/_overview.ts
- src/test-support/mocks/src/meshes/_/dataplanes/_/stats.ts
There's a few things going on here, but I mainly wanted to get something up for a PR preview to get some feedback on what we are rendering here.
Please make sure you have `KUMA_TRAFFIC_ENABLED=true` before previewing:
[Preview](https://deploy-preview-1932--kuma-gui.netlify.app/gui/meshes/default/data-planes/frontend-ac58fd4fbc-hjaqs.firewall.kuma-system-proxy-1/overview)
Additionally:
- There is also a fix in here for showing the aggregate passthrough traffic correctly.
- Overall there is quite a lot of work here in beginning to flesh out the mock for the `stats` endpoint which includes making sure our stateless mocks use "fake state" by setting the seed used for randomization based on the stateful URL, therefore making sure the randomness produces the same results on two different API …
> feat(dataplanes): Use service name for naming the inbounds instead of localhost

- src/app/data-planes/components/data-plane-traffic/ServiceTrafficCard.vue
- src/app/data-planes/locales/en-us/index.yaml
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/locales/en-us/common/index.yaml
- src/test-support/FakeKuma.ts
- src/test-support/mocks/src/meshes/_/dataplanes/_/_overview.ts
- src/test-support/mocks/src/meshes/_/dataplanes/_/stats.ts
User facing additions/changes:
1. We only show a 'traffic card' if the traffic is non-zero for a service.
2. For `http` services we no longer show bytes received/sent
3. For `http` services we no longer show a total of requests, instead we show 1xx, 2xx, 3xx, 4xx, 5xx (for 1xx and 3xx we only show totals if its non-zero)
---
Code changes:
1. Most changes are around making the mocks into something that randomly shows us lots of different combinations i.e. zero requests, requests with and without 1xx's or 3xx's.
2. I moved the code which decides exactly what data to show depending on the protocol from the Route/View into the ServiceTrafficCard component - eventually this will need to show more protocols, each displaying something slightly different so I figured it was best to move this sort …
> chore(dataplanes): More iteration on Dataplane traffic viz

- src/app/application/services/data-source/DataSourcePool.ts
- src/app/application/services/data-source/index.ts
- src/app/common/ResourceCodeBlock.vue
- src/app/meshes/sources.ts
- src/app/meshes/views/MeshConfigView.vue
This PR is a path to do several things:
1. Move all our data re-shaping to use our new data layer
2. Remove all `kumaApi` usage from the application (something we've wanted to do for a while)
Seeing as we are doing point 1 at the moment, it seemed like a good moment to look into this.
---
Please note this is a step one, the next step will be moving the data reshaping form within ResourceCodeBlock into the data layer and making the copy functionality take a string rather than an `Entity`, probably also worth noting that this will completely decouple the component from `?format=kubernetes` so we can use this approach for other things if we like.
Oh I also noticed that copying doesn't seem to work in Safari, which I 'think' is a kongponent thing, but even then we should consider either …
> chore: Move ResourceCodeBlock to use DataSource

- src/app/common/UpgradeCheck.vue
- src/app/control-planes/sources.ts
Moves UpgradeCheck to use DataSource.
The DataSource now gets the latest version, and then we check in the template to see if that version is the same as the version we are running using `KUMA_VERSION`. I used all the same logic sort of code in the DataSource `sources.ts` file.
---
I will probably remove the `UpgradeCheck.vue` component entirely in a later PR seeing as it doesn't really contain anything anymore and we only use it once in `ApplicationShell` here https://github.com/kumahq/kuma-gui/blob/b4ff4d670eab3d349ff1524014f9ff423fab3ec3/src/app/kuma/components/ApplicationShell.vue#L25. `ApplicationShell` itself is also only used once, so it makes sense to just put the code from `UpgradeCheck.vue` into it so the code is all front and center.
> chore: refactor UpgradeCheck to use DataSource

- src/app/data-planes/components/data-plane-traffic/DataPlaneTraffic.vue
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/services/env/CookiedEnv.ts
[Preview](https://deploy-preview-1958--kuma-gui.netlify.app/gui/meshes/default/data-planes/frontend-ac58fd4fbc-hjaqs.firewall.kuma-system-proxy-1/overview#KUMA_TRAFFIC_ENABLED=true)
Adds a "Show inactive" toggle so you can toggle between either showing the viz with services that have no traffic/not showing services that have no traffic.
Note: We decided to put a straightforwards toggle at the top of the list instead of a card at the bottom with the thinking that when you have lots of services you won't want to scroll to the bottom of the list every time you want to use the toggle.
---
I added some unrelated work here to make it possible to set feature flags via a deeplink (dev and PR previews only), I split that off into a separate commit.
---
This PR doesn't persist the setting into the …
> feat(dataplanes): add showInactive toggle for dataplane traffic view

- src/app/data-planes/components/StandardDataplanePolicies.vue
- src/app/data-planes/locales/en-us/index.yaml
- src/app/data-planes/views/DataPlanePoliciesView.vue
**chore(dataplanes): tweak policies hierarchy**
Moves the legacy policies below the new-style ones based on the `/_rules` API and adds a heading to them.
**fix(dataplanes): querying legacy policies when not used**
Fixes querying the legacy `/policies` endpoint when not using its data (i.e. when in global mode).
Resolves #1934.
> fix(dataplanes): querying legacy policies when not used

- package.json
- yarn.lock
Updates `@kong-ui-public/i18n`, `@kong/icons`, and `@kong/kongponents`.
---
Dependabot wasn’t able to update the icons and i18n package for some reason (see https://github.com/kumahq/kuma-gui/network/updates/772380338):
```
updater | 2024/01/10 10:49:29 INFO <job_772380338> Checking if @kong/icons 1.8.8 needs updating
updater | 2024/01/10 10:49:30 INFO <job_772380338> Latest version is 1.8.10
updater | 2024/01/10 10:50:22 INFO <job_772380338> Requirements to unlock update_not_possible
updater | 2024/01/10 10:50:22 INFO <job_772380338> Requirements update strategy bump_versions
updater | 2024/01/10 10:50:22 INFO <job_772380338> No update possible for @kong/icons 1.8.8
updater | 2024/01/10 10:50:24 INFO <job_772380338> Checking if …
```
> chore(deps): update Kong dependencies

- src/app/zone-egresses/views/ZoneEgressDetailTabsView.vue
- src/app/zone-egresses/views/ZoneEgressListView.vue
- src/app/zone-egresses/views/ZoneEgressSummaryView.vue
- src/app/zone-ingresses/views/ZoneIngressDetailTabsView.vue
- src/app/zone-ingresses/views/ZoneIngressListView.vue
- src/app/zone-ingresses/views/ZoneIngressSummaryView.vue
**fix(zones): ingresses and egresses breadcrumbs links**
Fixes the Ingress and Egresses breadcrumb links.
**fix(zones): summary tray detail links**
Fixes the Ingress and Egress summary detail links.
Resolves #1963.
> fix(zones): breadcrumb and summary links

- cypress/main.ts
- src/app/application/components/debug-k-clipboard-provider/DebugKClipboardProvider.vue
- src/app/application/components/debug-k-clipboard-provider/README.md
- src/app/vue/index.ts
- src/services/development.ts
- src/test-support/mocks/src/meshes/_.ts
- src/test-support/mocks/src/meshes/_/circuit-breakers/_.ts
- src/test-support/mocks/src/meshes/_/dataplanes/_.ts
- src/test-support/mocks/src/meshes/_/external-services/_.ts
- src/test-support/mocks/src/meshes/_/fault-injections/_.ts
- src/test-support/mocks/src/meshes/_/health-checks/_.ts
- src/test-support/mocks/src/meshes/_/meshfaultinjections/_.ts
- src/test-support/mocks/src/meshes/_/meshgatewayroutes/_.ts
- src/test-support/mocks/src/meshes/_/meshgateways/_.ts
- src/test-support/mocks/src/meshes/_/proxytemplates/_.ts
- src/test-support/mocks/src/meshes/_/traffic-logs/_.ts
- src/test-support/mocks/src/meshes/_/traffic-permissions/_.ts
- src/test-support/mocks/src/meshes/_/traffic-traces/_.ts
- src/test-support/mocks/src/zone-ingresses/_.ts
- src/test-support/mocks/src/zoneegresses/_.ts
- test-support/index.ts
Adds a dev only console logger for clipboard copying by decorating `KClipboardProvider::copyToClipboard` via our `development.ts` service container config.
Also added a single K8s property to relevant mocks (I figured this was enough to be able to tell if you'd copying the k8s format or not without having to be super realistic with the K8s formatted mock)
All in all this PR helps testing/debugging our copy buttons
---
Totally non-urgent, I did this while I was trying and figure out what was going on with https://github.com/kumahq/kuma-gui/issues/1967 and thought I may as well PR it.
> chore: add clipboard debug

- features/mesh/dataplanes/DataplaneDetailsBuiltinGateway.feature
- features/mesh/dataplanes/DataplaneDetailsDelegatedGateway.feature
- features/mesh/dataplanes/DataplaneDetailsStandardProxy.feature
- features/mesh/policies/Index.feature
- src/app/policies/views/PolicyListView.vue
- src/app/policies/views/PolicySummaryView.vue
**chore(policies): fix flaky test**
Fixes a flaky policy test caused by sourcing a route parameter from a prop (see https://github.com/kumahq/kuma-gui/pull/1993#discussion_r1447134988 for details).
Avoids double navigations (specifically in the "Clicking the link goes to the detail page and back again" and "Clicking policy types in the sidebar switches listing" tests).
**chore(dataplanes): fix flaky test**
Fixes a flaky test by avoiding quick double navigations (specifically in the "Clusters tab has expected content" and "Policies tab has expected content" tests).
> chore: fix flaky tests

- features/application/MainNavigation.feature
- features/application/Titles.feature
- features/main-overview/DetailViewContent.feature
- features/mesh/dataplanes/DataplanePolicies.feature
- features/zones/zone-cps/Item.feature
- features/zones/zone-cps/egresses/Index.feature
- src/services/env/Env.ts
- src/services/env/env.spec.ts
- src/test-support/mocks/src/config.ts
- src/types/config.d.ts
Deprecates standalone mode in favor of zone mode. This is a change only affecting our tests as our code already only checks for "is global mode" or "is not global mode".
Updates the /config mock to use `zone` instead of `standalone`. Also adds `multizone.zone.globalAddress` (indicates whether KDS is enabled) and `multizone.zone.name` (indicates the Zone name in zone mode).
Resolves #1686.
> feat(zones): support zone mode

- .github/workflows/create-gui-pr.yml
- .github/workflows/dispatch-merged-pr-notification.yml
Adds very restrictive workflow-level permissions to create-gui-pr.yml and dispatch-merged-pr-notification.yml. There’s a good chance other permissions are needed (like `id-token: write`), but it’s hard to determine this exactly. I plan to achieve the most restrictive set of permissions possible so which is why I’m starting with pretty much no permissions at all. If more permissions turn out to be necessary, I’ll add them in a follow-up PR.
Docs: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
> ci: add restrictive permissions to some workflows

- .github/workflows/codeql.yml
- .github/workflows/create-gui-pr.yml
- .github/workflows/lifecycle.yml
- .github/workflows/main.yml
ci: add restrictive permissions to remaining workflows
Adds very restrictive workflow-level permissions to the codeql.yml, lifecycle.yml, and main.yml workflow files.
ci: fix always skipping create-gui-pr workflow if manually triggering it
> ci: add restrictive permissions to remaining workflows

- src/test-support/FakeKuma.ts
- src/test-support/mocks/src/meshes/_/dataplanes/_/stats.ts
This PR does two things:
1. `partitionInto`: I'd originally used `NaN` as a place holder to say "fill this value in with an actual number", but I realized I could also use `Number` which would read better. Note: `partitionInto` is an approach to keep the names of the properties getting mocked front and center in the mock itself, hence the use of these 'placeholders'. I also had fun with `NaN` and typescript 😅 .
2. Adds stats entries for grpc servers, both inbound and outbound. Just to note here, I know the mock here is a little verbose this is because:
- The mock should look as much as possible like the API response
- I didn't want to try and reduce duplication too early without having all of the functionality mock we needed. I 'think' we now have all that so I may do another PR later to …
> chore: add mock grpc entries for stats

- src/app/data-planes/components/data-plane-traffic/ServiceTrafficCard.vue
- src/app/data-planes/data/stats.ts
- src/app/data-planes/locales/en-us/index.yaml
- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/test-support/mocks/src/meshes/_/dataplanes/_/stats.ts
[Preview](https://deploy-preview-2005--kuma-gui.netlify.app/gui/meshes/default/data-planes/frontend-d28f6bc67c-tjqee.system.kuma-system-proxy-6/overview#KUMA_TRAFFIC_ENABLED=true)
Adds specific data for grpc traffic.
> feat(dataplanes): add grpc traffic to dataplane connections viz

- src/services/development.ts
I noticed we were getting warnings for re-registering a component due to https://github.com/kumahq/kuma-gui/pull/1981
This happens both in browser development environments (PR previews and locally) and also CLI based unit tests.
The unit test ones are noisier than the browser ones, seeing as the browser ones need to be looked for.
This PR only does the re-registration if we don't have a `process` meaning it doesn't happen in anything CLI based.
Longer term, if I can't find a documented way to un-register components or overwrite them without causing this warning I might put this functionality behind one of our dev cookies so you have to explicitly enable it if you are looking at copy/paste things. In the meantime this silences the CLI based warnings.
> fix(test): avoid component re-registration warning during unit tests

- package.json
- src/app/common/SummaryView.vue
- src/app/data-planes/components/data-plane-traffic/ServiceTrafficCard.vue
I took this out inplace of a different approach in https://github.com/kumahq/kuma-gui/pull/1997#issuecomment-1885100683 but I found that the newer approach had at least a couple of user facing issues.
1. When a summary was open clicking a port in the case of inbounds or the service name in the case of outbounds (which are `a` tags, would cause the summary drawer to close instead of switching to the newly clicking inbound/outbound.
2. Clicking the service tag link in the top right corner of the card would navigate to the correct place but produce an error in the JS console about `dataPlane` not being defined on a route (one of the hard to trace vue-router ones).
After playing with it a while, and trying several tweaks to the different approach I decided to just revert back to my original …
> fix(dataplanes): clicking links in ServiceTraffic cards
