kumahq/kuma-gui

.env.development
src/components/Sidebar/menu.js
src/components/Skeletons/DataOverview.vue
src/router.js
src/services/kuma.js
src/services/mock.js
src/store/index.js
src/views/Entities/EntityOverview.vue
src/views/Entities/TestOverview.vue
src/views/Onboarding/Complete.vue
src/views/Policies/FaultInjection.vue
src/views/Policies/FaultInjectionDetail.vue

Add support for the new FaultInjection entity

feat(kuma-gui) add fault injection entity

---

src/assets/styles/utilities.css
src/components/Skeletons/YamlView.vue
src/components/Utils/Tabs.vue
src/services/mock.js
src/views/Entities/Dataplanes.vue
src/views/Policies/CircuitBreakers.vue
src/views/Policies/FaultInjections.vue
src/views/Policies/HealthChecks.vue
src/views/Policies/ProxyTemplates.vue
src/views/Policies/TrafficLogs.vue
src/views/Policies/TrafficPermissions.vue
src/views/Policies/TrafficRoutes.vue
src/views/Policies/TrafficTraces.vue

The YAML view on pages now has tabs for Universal and Kubernetes. The selected tab is determined by the user's environment.

YAML view improvements

---

src/router.js
src/views/Diagnostics.vue

A simple page for displaying the Kuma config in a readable manner.

Diagnostics page

---

src/main.js

Signed-off-by: Nikolay Nikolaev <nikolay.nikolaev@konghq.com>

fix(*) API server URL handling

---

src/views/Wizard/schemas/DataplaneKubernetes.js
src/views/Wizard/views/DataplaneKubernetes.vue

This is a fix for [#972](https://github.com/kumahq/kuma/issues/972) in the Kuma repo.

Changed labels to annotations in the Kubernetes Dataplane Wizard

---

.env.development
src/components/Breadcrumbs.vue
src/components/Resources.vue
src/components/Skeletons/DataOverview.vue
src/helpers.js
src/services/mock.js
src/views/Entities/Dataplanes.vue
src/views/Overview.vue

This PR:
- Improves the DataOverview tables on mobile by adding touch actions for horizontal scrolling when the tables contain a lot of data that forces them to stretch to a point where they can't be contained
- Revises the way that tags in Dataplanes are collected and displayed in both the table and tabbed views in the DataOverview component
- Adds a helper function that will remove duplicate objects from the tag lists when collecting them (bug brought to my attention by @jakubdyszkiewicz 👍🏻 )

Data Overview and Dataplanes view fixes

---

.env.production
.eslintrc.js
.prettierrc
babel.config.js
src/components/Skeletons/DataOverview.vue
src/components/Utils/LoaderCard.vue
src/configUrl.js
src/helpers.js
src/main.js
src/services/mock.js
src/views/Entities/Dataplanes.vue
src/views/Entities/Zones.vue
src/views/Onboarding/GetStarted.vue

Addresses an issue where the `/config` endpoint could not be found when the user has a custom path for the API and GUI.

Config path

---

.env.development
src/assets/styles/components.scss
src/components/Skeletons/ApiErrorMessage.vue
src/views/Onboarding/Complete.vue
src/views/Onboarding/GetStarted.vue

The recent [Kongponents](https://kongponents.netlify.app/style-guide/) updates made a lot of changes to class names, colors, type, etc. This PR fixes them, as well as adds some subtle improvements to the onboarding process verbiage and conditional handling.

Fixes for Wizard and Onboarding components

---

.circleci/config.yml
README.md

configured circleci `workflows` with jobs for commits and master changes.

Added ci for kuma-gui

---

.postcssrc.js
src/components/Global/Footer.vue
src/components/Utils/Pill.vue
src/mixins/EntityMixin.js
src/mixins/FormPage.js
src/pdk/components/ExternalLink.vue
src/pdk/components/PageHeader.vue
src/pdk/components/TimeFramePicker.vue
src/pdk/mixins/StateMachine.js
tests/e2e/.eslintrc.js
tests/e2e/plugins/index.js
tests/e2e/specs/test.js
tests/e2e/support/index.js
tests/unit/.eslintrc.js
tests/unit/example.spec.js

chore(*) fix lints

---

src/components/Sidebar/menu.js
src/router.js
src/views/Entities/Dataplanes.vue
src/views/Entities/GatewayDataplanes.vue
src/views/Entities/IngressDataplanes.vue
src/views/Entities/StandardDataplanes.vue

I've completely rewritten and simplified the tag handling for all existing Dataplane views. 
This change is tied to [this branch](https://github.com/kumahq/kuma/tree/chore/dp_pagination) on the Kuma repository.

Duplicated Dataplane tags fix

---

src/views/Entities/Meshes.vue

added locality aware load balancing in mesh overview tab

---

src/views/Wizard/views/DataplaneUniversal.vue

Fixed universal data plane onboarding as per recent changes to `kuma-dp`(https://github.com/kumahq/kuma/pull/999)
Fixes #93

fix(univeral) dataplane onboarding

---

src/views/Entities/Zones.vue

Zone overview should not contain Mesh

fix(zones) mesh should be absent in zone overview

---

src/views/Policies/CircuitBreakers.vue
src/views/Policies/FaultInjections.vue
src/views/Policies/HealthChecks.vue
src/views/Policies/ProxyTemplates.vue
src/views/Policies/TrafficLogs.vue
src/views/Policies/TrafficPermissions.vue
src/views/Policies/TrafficRoutes.vue
src/views/Policies/TrafficTraces.vue

Pagination was not shown in Policies

fix(policies) show pagination

---

src/components/Skeletons/YamlView.vue

Two things
* K8S YAML should contain a mesh (if there is a Mesh, some objects are global scoped)
* K8S YAML should contain a namespace if the name is `name.namespace` from Kuma API

fix(yaml) K8S YAML should contain mesh and namespace

---

src/views/Entities/Dataplanes.vue
src/views/Entities/GatewayDataplanes.vue
src/views/Entities/IngressDataplanes.vue
src/views/Entities/StandardDataplanes.vue

feat(dataplanes) add dp and envoy column

---

src/components/Sidebar/menu.js
src/router.js
src/services/kuma.js
src/store/index.js
src/views/Overview.vue
src/views/Policies/Retries.vue

feat(retries) introduce retry polices

---

src/assets/styles/components.scss
src/components/Skeletons/DataOverview.vue
src/dataplane.js
src/views/Entities/Dataplanes.vue
src/views/Entities/GatewayDataplanes.vue
src/views/Entities/IngressDataplanes.vue
src/views/Entities/StandardDataplanes.vue

- Extract function for calculating Dataplane status - `getStatus`
- Take `inbound.health` into account when calculating Dataplane status
- Introduce new status `Partially degraded` if some of inbounds are not ready:
- In case of `Offline/Partially degraded` show the reasons in Overview tab:

fix(dataplane) take into account application status as well

---

src/views/Entities/InternalServices.vue

New column for `Internal Services`:

feat(services) new 'status' column

---

src/dataplane.js
src/store/index.js

fix(charts)

---

src/components/OverviewCharts.vue
src/main.js
src/store/index.js
src/views/Overview.vue

Introduced chart for `Zones` and replaced by it element from
the data table below charts
https://user-images.githubusercontent.com/11655498/105711541-fa697080-5f18-11eb-8356-a250452c6362.mov

feat(*) add zones chart

---

README.md

Fixed `readme` with latest gui info.

update readme content with latest info

---

src/components/Global/Header.vue
src/components/Utils/EnterpriseBox.vue

- Missing proper message
- Missing proper link

feat: added box with link to enterprise in header

---

.env
src/components/Global/Header.vue

Introduce new env `VUE_APP_SHOW_ENTERPRISE_BUTTON` for displaying EnterpriseBox button

feat(services) show enterprise button depending on env

---

src/services/mock.js
src/store/index.js

fix(*) fix zone-insighhts response parsing

---

src/views/Entities/Zones.vue

Fixes https://github.com/kumahq/kuma/issues/1364

Add remote cp version in zones

---

src/assets/styles/components.scss

feat(services) change color for 'Partially degraded'

---

src/components/Resources.vue
src/components/Utils/EnterpriseBox.vue
src/components/Utils/UpgradeCheck.vue
src/views/Onboarding/Complete.vue
src/views/Overview.vue
src/views/Wizard/views/Mesh.vue

This is for SEO and analytics. We'll now be able to see when users arrive at the website from within the GUI.

Adds utm_source values to all external links

---

src/services/mock/responses/service-insights.json
src/store/index.js

As API for service insights changed, these changes reflect
that fact

feat(*) update service insights api

---

src/services/mock.ts
src/services/mock/responses/dataplanes+insights.json
src/services/mock/responses/meshes/default/dataplanes+insights/no-subscriptions.json
src/views/Entities/partial/Dataplanes.vue

Fixing issue with Dataplanes view when dataplane insights returns insights without any subscriptions in it

fix(dataplanes) fix view when no subscriptions

---

src/views/Entities/Zones.vue

fix(*) zones view zoneInsight tab regression

---

src/store/index.ts

fix(charts) zones chart statuses fix in Overview

---

src/components/Sidebar/menu.ts

feat(*) sort policies in menu alphabetically

---

OWNERS.md

Signed-off-by: Nikolay Nikolaev <nikolay.nikolaev@konghq.com>

docs(*) update OWNERS

---

src/components/Sidebar/menu.ts
src/router.ts
src/services/kuma.ts
src/store/index.ts
src/store/reducers/mesh-insights.ts
src/views/Entities/Meshes.vue
src/views/Overview.vue
src/views/Policies/RateLimits.vue

Signed-off-by: Nikolay Nikolaev <nikolay.nikolaev@konghq.com>

chore(*) introduce RateLimit

---

src/services/mock/responses/service-insights.json

refactor(*) refactor the structure of service insights mock

---

src/views/Wizard/views/DataplaneUniversal.vue

It is fixing an issue with not needed flags, that was described here: https://github.com/kumahq/kuma-gui/issues/169

fix(*) Remove --mesh and --name flags

---

src/services/mock/responses/dataplanes.json
src/services/mock/responses/meshes/default/dataplanes+insights/dataplane-test-456.json
src/services/mock/responses/meshes/default/dataplanes+insights/ingress-dp-test-123.json
src/services/mock/responses/zoneingresses+insights.json
src/services/mock/responses/zoneingresses+insights/zone-1.json
src/services/mocks.ts

Previously we had no mock for `zoneingresses+insights.json `, it will be added as a part of this PR.
Also some adjustments of other mocks.

refactor(*) adjust mocks

---

package.json
src/main.ts
src/views/Entities/Meshes.vue
src/views/Entities/partial/Dataplanes.vue
yarn.lock

In this PR we are going to add datadog tracking on errors and on some user behavior.

feat(*) add datadog

---

OWNERS.md

Signed-off-by: Pan-Bubr <adrian.golawski@gmail.com>

docs(*) add Adrian G to owners

---

src/services/mock/responses/mesh-insights.json
src/services/mock/responses/mesh-insights/default.json
src/services/mock/responses/mesh-insights/hello-world.json
src/services/mock/responses/meshes.json
src/services/mock/responses/meshes/default/retries.json
src/services/mock/responses/meshes/default/service-insights/ingress.json
src/services/mock/responses/meshes/default/timeouts.json
src/services/mock/responses/meshes/default/traffic-routes.json
src/services/mock/responses/meshes/hello-world.json
src/services/mock/responses/meshes/kong-mania-12.json
src/services/mock/responses/retries.json
src/services/mock/responses/service-insights.json
src/services/mock/responses/status/zones.json
src/services/mock/responses/traffic-logs.json
src/services/mock/responses/traffic-routes.json
src/services/mocks.ts

As we were missing some mocks, this PR is about to provide them. Also it updates some of the mocks when data changed.

chore(*) update mocks

---

src/utils/tableDataUtils.spec.ts
src/utils/tableDataUtils.ts
src/utils/tableDataUtils.types.ts
src/views/Policies/CircuitBreakers.vue
src/views/Policies/FaultInjections.vue
src/views/Policies/HealthChecks.vue
src/views/Policies/ProxyTemplates.vue
src/views/Policies/RateLimits.vue
src/views/Policies/Retries.vue
src/views/Policies/Timeouts.vue
src/views/Policies/TrafficLogs.vue
src/views/Policies/TrafficPermissions.vue
src/views/Policies/TrafficRoutes.vue
src/views/Policies/TrafficTraces.vue

It will align the way how the data is retrieved from API to be displayed in the GUI. Right now we have a lot of duplication of code. This is one of many steps to make sure we can better manage the data/duplication of code.

refactor(*) create common function for fetching data

---

package.json
src/App.spec.ts
src/__snapshots__/App.spec.ts.snap
src/components/Skeletons/ApiErrorMessage.vue
src/jest-setup.ts
src/services/mocks.ts
src/services/restClient.ts
src/store/index.ts
src/store/modules/config/config.ts
tsconfig.json

When working in standalone we weren't displaying version of cp.

Bug missing version zone standalone

---

.env
package.json
src/configUrl.ts
src/main.ts
src/shim-enviroment.d.ts
yarn.lock

This PR introduces datadog rum which will allow us better track user behavior/problems which they encounter.
Also small cleanup of env variables.

feat(*) add datadog-rum

---

src/components/Skeletons/DataOverview.spec.ts
src/components/Skeletons/DataOverview.vue
src/components/Skeletons/__snapshots__/DataOverview.spec.ts.snap
src/helpers.ts
src/services/kuma.ts
src/store/index.ts
src/utils/tableDataUtils.spec.ts
src/utils/tableDataUtils.ts
src/views/Entities/Meshes.vue
src/views/Entities/ZoneIngresses.vue
src/views/Entities/Zones.vue
src/views/Entities/partial/Dataplanes.vue
src/views/Entities/partial/Services.vue
src/views/Policies/CircuitBreakers.vue
src/views/Policies/FaultInjections.vue
src/views/Policies/HealthChecks.vue
src/views/Policies/ProxyTemplates.vue
src/views/Policies/RateLimits.vue
src/views/Policies/Retries.vue
src/views/Policies/Timeouts.vue
src/views/Policies/TrafficLogs.vue
src/views/Policies/TrafficPermissions.vue
src/views/Policies/TrafficRoutes.vue
src/views/Policies/TrafficTraces.vue

Previously we had in every view separate Pagination and logic which was handling it. 
But when I went over the application I realized that in every place we are repeating one pattern, so instead of having it repeated I decided to move Pagination and logic related to that inside `DataOverview` component which reduces the amount of duplicated code and will make code cleaner and easier to manage.
Also created a common event which I attached to reload.
Also provided tests which check if Pagination works fine.

refactor(*) systematise pagination

---

src/components/Skeletons/DataOverview.spec.ts
src/components/Skeletons/DataOverview.vue
src/components/Skeletons/__snapshots__/DataOverview.spec.ts.snap

In previous PR https://github.com/kumahq/kuma-gui/pull/212 we changed the behavior of refresh - so it returns back to the first page. This PR fixes that issue.

bug(*) refresh page on which you are

---

src/services/kuma.ts
src/services/mock/responses/mesh-insights.json
src/services/mock/responses/mesh-insights/default.json
src/services/mock/responses/mesh-insights/kong-mania-12.json
src/services/mock/responses/meshes.json
src/services/mock/responses/meshes/default.json
src/services/mock/responses/meshes/default/dataplanes+insights.json
src/services/mock/responses/meshes/default/dataplanes+insights/dataplane-test-456.json
src/services/mock/responses/meshes/default/dataplanes+insights/ingress-dp-test-123.json
src/services/mocks.ts
src/utils/tableDataUtils.ts
src/utils/tableDataUtils.types.ts

It contains an upgrade of outdated mocks and some minor adjustments for the rest of code.

chore(*) upgrade mocks

---

src/components/Skeletons/YamlView.vue
src/store/index.ts
src/views/Entities/Meshes.vue
src/views/Overview.vue
src/views/Policies/TrafficPermissions.vue

It will fix some minor bugs which appear in-app
- error on TrafficPermissions on k8s when no mtls
- error on yamlfile
- error on overview when missing some policies
- and minor fixes

bug(*) wrong conditions && missing data

---

netlify.toml
src/components/Utils/UpgradeCheck.vue
src/views/Entities/__snapshots__/ZoneIngresses.spec.ts.snap
src/views/Entities/__snapshots__/Zones.spec.ts.snap
src/views/Entities/components/MultizoneInfo.vue

~~It will resolve issues with CORS on firefox and also~~ Fix minor issues (fix the case when null may be provided to semver or wrong icon size)

fix(*) Minor adjustrments

---

src/consts.ts
src/helpers.spec.ts
src/helpers.ts
src/services/mocks.ts
src/store/index.ts
src/types.ts

Previously when we want to request all resources we wrongly increment the value of offset which caused hundreds of unnecessary calls and wrong results. This fix will resolve that issue.

fix(*) properly fetch all resources

---

src/components/NotificationManager/components/OnboardingNotification.spec.ts
src/testUtils/renderWithVuex.ts
src/views/Entities/Meshes.spec.ts
src/views/Entities/Meshes.vue
src/views/Entities/__snapshots__/Meshes.spec.ts.snap
src/views/Wizard/views/DataplaneUniversal.spec.ts
src/views/Wizard/views/Mesh.spec.ts

In https://github.com/kumahq/kuma-gui/pull/238/files in Meshes was introduced bug which disable the possbility to use "Resource" tab. That PR fixes that and provides test which check if its working.

fix(meshes) policies bug

---

src/components/Accordion/Accordion.spec.ts
src/components/Accordion/AccordionItem.vue
src/components/Accordion/__snapshots__/Accordion.spec.ts.snap
src/components/NotificationManager/__snapshots__/NotificationManager.spec.ts.snap
src/views/Entities/__snapshots__/ZoneIngresses.spec.ts.snap
src/views/Entities/__snapshots__/Zones.spec.ts.snap

Add possibility to use keyboard to open accordion items.

feat(accordion) add possibility to use keyboard to open accordion item

---

src/services/mock/responses/global-insights.json
src/store/modules/sidebar/sidebar.ts

Adjustment to reflect changes in https://github.com/kumahq/kuma/pull/3094/files

refactor(insights) adjsut to API response

---

src/components/NotificationManager/NotificationManager.spec.ts
src/components/NotificationManager/NotificationManager.vue
src/components/NotificationManager/__snapshots__/NotificationManager.spec.ts.snap
src/components/NotificationManager/components/AllMeshesNotifications.vue
src/components/NotificationManager/components/LoggingNotification.vue
src/components/NotificationManager/components/MetricsNotification.vue
src/components/NotificationManager/components/MtlsNotification.vue
src/components/NotificationManager/components/TracingNotification.vue
src/components/NotificationManager/components/__snapshots__/LoggingNotification.spec.ts.snap
src/components/NotificationManager/components/__snapshots__/MetricsNotification.spec.ts.snap
src/components/NotificationManager/components/__snapshots__/MtlsNotification.spec.ts.snap
src/components/NotificationManager/components/__snapshots__/TracingNotification.spec.ts.snap

Shorten and adjust notification manager texts related to specific fields.

feat(notifications) change texts)

---

src/components/NotificationManager/NotificationManager.vue
src/components/NotificationManager/__snapshots__/NotificationManager.spec.ts.snap
src/components/NotificationManager/components/AllMeshesNotifications.vue
src/views/Entities/partial/Dataplanes.vue
src/views/Shell.vue
src/views/__snapshots__/Shell.spec.ts.snap

It contains upgrade of text in Notification Manager when action available.
Also fix of share-url.

fix(*) adjustment of notification/url-share/onboarding alert

---

src/datadog.ts
src/main.ts

It will disable reporting by default and do it based on the flag from config. #240 

feat(datadog) set reporting based on flag

---

src/components/Sidebar/NavItem.vue
src/components/Sidebar/Subnav.vue

Adjustment of how insights are presented in sidebar.

style(sidebar) adjust css

---

src/services/mock/responses/zones+insights.json
src/services/mock/responses/zones+insights/zone-1.json
src/services/mock/responses/zones+insights/zone-2.json
src/services/mock/responses/zones+insights/zone-3.json
src/services/mock/responses/zones.json
src/types.ts
src/views/Entities/Zones.vue
src/views/Entities/__snapshots__/Zones.spec.ts.snap
tests/unit/examples/Example.spec.ts

It will provide information about if ingress has been associated with the zone
.

feat(zones) ingress info

---

src/components/Skeletons/YamlView.vue
src/views/Entities/Meshes.vue
src/views/Entities/ZoneIngresses.vue
src/views/Entities/Zones.vue
src/views/Entities/__snapshots__/Meshes.spec.ts.snap
src/views/Entities/partial/Dataplanes.vue
src/views/Entities/partial/Services.vue
src/views/Policies/CircuitBreakers.vue
src/views/Policies/FaultInjections.vue
src/views/Policies/HealthChecks.vue
src/views/Policies/ProxyTemplates.vue
src/views/Policies/RateLimits.vue
src/views/Policies/Retries.vue
src/views/Policies/Timeouts.vue
src/views/Policies/TrafficLogs.vue
src/views/Policies/TrafficPermissions.vue
src/views/Policies/TrafficRoutes.vue
src/views/Policies/TrafficTraces.vue

It will unify way how we display the name of the entity on table pages.

refactor(*) unify names

---

src/services/mock/responses/dataplanes+insights.json
src/services/mock/responses/meshes/default/dataplanes+insights/backend.json
src/views/Entities/ZoneIngresses.vue
src/views/Entities/Zones.vue
src/views/Entities/__snapshots__/ZoneIngresses.spec.ts.snap
src/views/Entities/__snapshots__/Zones.spec.ts.snap
src/views/Entities/components/SubscriptionDetails.vue
src/views/Entities/components/SubscriptionHeader.vue
src/views/Entities/partial/Dataplanes.vue
src/views/Entities/partial/__snapshots__/Dataplanes.spec.ts.snap

It will provide insights into the data plane proxy in the new tab. Also, adjust insights for ZoneIngresses
Related to: https://github.com/kumahq/kuma-gui/issues/269

feat(dpp) add insights

---

src/services/mock/responses/zoneingresses+insights.json
src/services/mock/responses/zoneingresses+insights/zone-ingress-1.json
src/views/Entities/ZoneIngresses.spec.ts
src/views/Entities/Zones.vue
src/views/Entities/__snapshots__/ZoneIngresses.spec.ts.snap

Fixes #280 and properly display ingress when associated with the zone.

fix(zones) properly detect ingress when associated

---

src/views/Overview.spec.ts
src/views/Overview.vue
src/views/__snapshots__/Overview.spec.ts.snap

It will resolve the issue #200 
https://user-images.githubusercontent.com/16152347/148754425-91734600-e3eb-4d51-b002-3a13159a02e7.mov
https://user-images.githubusercontent.com/16152347/148754459-dfbf965d-1c99-4c93-b805-191756a66e7d.mov

fix(overview) set same height for boxes

---

src/components/Sidebar/__snapshots__/Sidebar.spec.ts.snap
src/components/Sidebar/menu.ts
src/router.ts
src/services/kuma.ts
src/services/mock/responses/global-insights.json
src/services/mock/responses/zoneegress-overviews.json
src/services/mock/responses/zoneegress-overviews/zone-egress-1.json
src/services/mock/responses/zoneegresses+insights.json
src/services/mock/responses/zoneegresses+insights/zone-egress-1.json
src/services/mocks.ts
src/store/modules/sidebar/sidebar.spec.ts
src/store/modules/sidebar/sidebar.ts
src/store/modules/sidebar/sidebar.types.ts
src/views/Entities/ZoneEgresses.spec.ts
src/views/Entities/ZoneEgresses.vue
src/views/Entities/ZoneIngresses.spec.ts
src/views/Entities/ZoneIngresses.vue
src/views/Entities/__snapshots__/ZoneEgresses.spec.ts.snap
src/views/__snapshots__/Shell.spec.ts.snap

This PR adds zone-egress to GUI

feat(zone-egress) add zone egress

---

DEVELOPER.md

docs(development) adjust DEVELOPMENT.md

---

src/components/Sidebar/menu.ts
src/store/modules/sidebar/sidebar.spec.ts
src/store/modules/sidebar/sidebar.ts
src/store/modules/sidebar/util.spec.ts
src/store/modules/sidebar/utils.ts
src/types.ts

It will simplify logic related to calculating sidebar insights and get rid of issues when we try to access non-existing resources.

chore(sidebar) simplify logic

---

src/store/modules/sidebar/sidebar.ts
src/store/modules/sidebar/sidebar.types.ts

fix(sidebar) wrong types

---

src/components/DataplanePolicies/DataplanePolicies.vue
src/components/DataplanePolicies/__snapshots__/DataplanePolicies.spec.ts.snap
src/views/Onboarding/DataplanesOverview.vue

This PR will adjust description of tooltip and also do refetch of DPPs during onboarding if any is offline.

fix(*) adjust dataplane fetching & wrong tooltip info

---

src/components/Sidebar/Sidebar.spec.ts
src/consts.ts
src/services/mock/responses/config.json
src/store/modules/config/config.ts
src/store/modules/config/config.types.ts

fix(meshGateway): rename gateway to meshGateway

---

src/components/Global/Header.vue
src/services/mocks.ts

We will now release binaries with `v` prefix

chore(*): remove v prefix in version header

---

src/components/Sidebar/menu.ts

fix(sidebar): fix counters for egress/ingress

---

src/components/XdsConfiguration/XdsConfiguration.vue

xref https://github.com/kumahq/kuma/pull/4301

feat(*): unlock xds configuration on global cp

---

src/views/Entities/ZoneEgresses.vue
src/views/Entities/__snapshots__/ZoneEgresses.spec.ts.snap

Adds the missing border to the zone egresses view.
Fixes #356.

fix: zone egresses not having usual border

---

.github/workflows/main.yml

Migrates from CircleCI to GitHub Actions.
In preparation for #367.

refactor: migrates from CircleCI to GitHub Actions

---

.github/workflows/create-gui-pr.yml

IMO the date in the PR title is too noisy

chore(.github): don't add date to kuma-gui upgrade PR title, look more like dependabot

---

.github/workflows/create-gui-pr.yml

This includes a link to the repo which is always useful

ci: add ci/skip-test label to upgrade PR and better message

---

package.json
src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
src/app/data-planes/views/__snapshots__/DataPlaneListView.spec.ts.snap
src/views/Onboarding/__snapshots__/AddNewServicesCode.spec.ts.snap
src/views/Wizard/views/__snapshots__/DataplaneUniversal.spec.ts.snap
src/views/Wizard/views/__snapshots__/Mesh.spec.ts.snap
yarn.lock

Updates Kongponents to include a bug fix for the KCodeBlock components.

chore(deps): update @kong/kongponents to 8.0.1

---

src/api/mocks.ts
src/app/App.spec.ts
src/app/App.vue
src/app/common/AccordionItem.vue
src/app/common/CodeBlock.vue
src/app/common/UpgradeCheck.spec.ts
src/app/data-planes/components/DataPlaneDetails.spec.ts
src/app/data-planes/components/DataPlaneDetails.vue
src/app/data-planes/components/DataPlaneEntitySummary.spec.ts
src/app/data-planes/components/MeshGatewayDataplanePolicyList.vue
src/app/data-planes/components/SidecarDataplanePolicyList.vue
src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
src/app/data-planes/components/__snapshots__/DataplanePolicies.spec.ts.snap
src/app/data-planes/views/DataPlaneListView.spec.ts
src/app/data-planes/views/__snapshots__/DataPlaneListView.spec.ts.snap
src/app/onboarding/views/AddNewServicesCode.spec.ts
src/app/onboarding/views/__snapshots__/AddNewServicesCode.spec.ts.snap
src/app/policies/components/PolicyConnections.vue
src/app/policies/views/PolicyView.vue
src/app/wizard/views/DataplaneUniversal.spec.ts
src/app/wizard/views/Mesh.spec.ts
src/app/zones/views/__snapshots__/ZoneEgresses.spec.ts.snap
src/app/zones/views/__snapshots__/ZoneIngresses.spec.ts.snap
src/app/zones/views/__snapshots__/ZonesView.spec.ts.snap
src/main.ts
src/store/modules/config/config.spec.ts
src/store/modules/config/config.ts
src/utilities/helpers.ts

* fix: learn about certificates link
* fix: missing padding in policies tab
* fix: date time formats missing leading zeroes
* fix: affected DPPs linking to list view
* fix: policy view not updating on selection
* fix: not redirecting to onboarding correctly
Fixes #415
Fixes #422
Fixes #421
Fixes #416
Fixes #417
Fixes #420

fix: testing friday issues

---

.github/workflows/create-gui-pr.yml

This makes the rollup in the changelog script automatic

ci(.github): add Changelog to sync pr

---

.env
package.json
src/api/RestClient.ts
src/store/modules/config/config.ts
vite.config.js

* **fix(api): incorrect base path detection**
Fixes a bug with detecting the appropriate API base path which would fail for GUI instances served from nested URL paths (e.g. `/path/gui`).
* **chore: uses base path during development**
Sets non-root base path during development to be closer to real user scenarios.

fix(api): incorrect base path detection

---

.github/workflows/codeql.yml

Hi !
This is a setup for Codeql for kuma-gui as it is packaged in kuma.
I originally created an issue [in kuma](https://github.com/kumahq/kuma/issues/4646)
And a [pull request](https://github.com/kumahq/kuma/pull/5242).
The use of Codeql in this repository would help complete the coverage of the vulnerabilities detection :) 
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

ci: setup Codeql workflow

---

.eslintrc.js
.github/workflows/main.yml
src/api/RestClient.ts
src/router/router.ts
src/shims-env.d.ts
src/shims-vite.d.ts
src/utilities/getAppBaseUrl.spec.ts
src/utilities/getAppBaseUrl.ts
src/utilities/getAppGuiPath.spec.ts
src/utilities/getAppGuiPath.ts
vite.config.js

Fixes the router base path being incorrect when serving the GUI application from a non-root path.

fix: incorrect router base path

---

CODEOWNERS

Updates CODEOWNERS to use kuma-frontend team for auto review requesting

chore: Update codeowners file to use kuma-frontend

---

src/api/RestClient.ts
src/api/kumaApi.ts
src/api/makeRequest.ts
src/app/common/DataOverview.vue
src/app/common/__snapshots__/DataOverview.spec.ts.snap
src/app/data-planes/components/DataPlaneDetails.spec.ts
src/app/data-planes/components/DataPlaneEntitySummary.vue
src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
src/app/data-planes/views/DataPlaneListView.spec.ts
src/app/data-planes/views/DataPlaneListView.vue
src/app/data-planes/views/__snapshots__/DataPlaneListView.spec.ts.snap
src/app/onboarding/views/AddNewServicesCode.spec.ts
src/app/policies/views/PolicyView.spec.ts
src/app/zones/views/__snapshots__/ZoneEgresses.spec.ts.snap
src/app/zones/views/__snapshots__/ZoneIngresses.spec.ts.snap
src/app/zones/views/__snapshots__/ZonesView.spec.ts.snap
src/store/modules/sidebar/utils.ts

* chore(data-planes): expands test coverage
Expands the test coverage for data plane views.
* chore(api): parameters incorrectly being optional
* chore: removes non-standard public/private fields

chore(data-planes): expands test coverage

---

.github/workflows/create-gui-pr.yml

There are some unit tests that are actually usefull

ci: skip only e2e tests in sync PR

---

src/pathConfigDefault.ts

ci: fix deployment previews

---

.github/workflows/create-gui-pr.yml

ci: add label to auto-merge Kuma PR

---

.github/workflows/create-gui-pr.yml

ci: limit Node version in all workflows

---

src/api/mock-data/dataplane-rules.json
src/app/data-planes/components/DataplanePolicies.vue
src/app/data-planes/components/RuleEntryList.vue
src/app/data-planes/components/__snapshots__/DataplanePolicies.spec.ts.snap
src/types/index.d.ts

Updates the DPP policies tab to handle the new rule format. As part of this, the "On" column was replaced with an "Addresses" column.

feat: updates dpp policies tab to handle new rule format

---

src/app/wizard/components/EntityScanner.vue
src/app/wizard/components/EnvironmentSwitcher.vue
src/app/wizard/components/FormFragment.vue
src/app/wizard/components/StepSkeleton.vue
src/app/wizard/views/DataplaneKubernetes.vue
src/app/wizard/views/DataplaneUniversal.spec.ts
src/app/wizard/views/DataplaneUniversal.vue
src/app/wizard/views/DataplaneUniversalSchema.ts
src/app/wizard/views/MeshWizard.spec.ts
src/app/wizard/views/MeshWizard.vue
src/app/wizard/views/__snapshots__/DataplaneUniversal.spec.ts.snap
src/app/wizard/views/__snapshots__/MeshWizard.spec.ts.snap
src/router/routes.ts

Migrates all wizard-related components to composition API.

refactor(wizards): migrate components to composition API

---

src/app/common/charts/DoughnutChart.vue

chore: reduces chart title font size slightly

---

vite.config.ts

chore: Uses fileURLToPath over node:path

---

DEVELOPER.md

Adds some basic instructions on how to behave during the Kuma stabilization phase (i.e. when a new release is being prepared).

docs: adds instructions for release branch management

---

.github/dependabot.yml

ci: raises open pull request limit for dependabot

---

src/app/onboarding/views/ConfigurationTypes.vue
src/app/onboarding/views/WelcomeView.vue
src/components/index.ts

* fix: using wrong graph for configuration types
Fixes an issue with onboarding using the wrong graphs for the configuration types step.
* refactor: removes WelcomeAnimationSvg injection
Removes the injection of WelcomeAnimationSvg because it no longer needs to account for different uses in other implementations due using custom properties for colors.

fix: using wrong graph for configuration types

---

public/mockServiceWorker.js

MSW upgrades the comments in the worker when you `yarn` a new version in.
Related: https://github.com/kumahq/kuma-gui/pull/656

chore(deps): Upgrade MSW comment

---

.github/workflows/dispatch-merged-pr-notification.yml

ci: removes pr from repository dispatch

---

src/app/common/TagList.vue
src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
src/app/data-planes/components/__snapshots__/DataplanePolicies.spec.ts.snap
src/app/data-planes/views/__snapshots__/DataPlaneListView.spec.ts.snap
src/app/services/components/ServiceSummary.vue
src/assets/styles/_variables.scss
src/utilities/getLabels.spec.ts
src/utilities/getLabels.ts

Switches the TagList style to use KBadge.

refactor: changes tag style to KBadge

---

src/services/utils.ts

Follow up of #703 as detailed in there , this PR adds labelling abilities to our service/di configuration.
This lets us define multiple things and refer to them before we actually define them. For example, routes in multiple modules, mocks in multiple modules, 'api clients' in multiple modules.
From #703:
> More on tagging/labelling:
> I'd like to be able to do things like:
```yaml
policyRoutes:
service: policyRoutes
arguments:
- store
labels:
- routes
dataplaneRoutes:
service: dataplaneRoutes
arguments:
- store
labels:
- routes
```
```javascript
get(TOKENS.routes) // a concatenation of all the services tagged/labelled as routes
```
> This makes it easier to compose things together without the app having to know about what exactly things are composed of, it should also make it easier in …

feat(di): Adds labelling abilities to our di config

---

src/app/wizard/views/MeshWizard.vue
src/app/wizard/views/__snapshots__/MeshWizard.spec.ts.snap

It requires an update to snapshot, but I cannot pass `yarn install` on my M1 Mac for some reason.

fix(wizard): remove unknown parameter in Mesh output YAML

---

src/app/AppHeader.vue
src/app/common/charts/DoughnutChart.vue

* fix: empty charts not rendering a grey arc
* fix: missing gap from app header

fix: empty charts not rendering a grey arc

---

src/app/onboarding/views/MultiZoneView.spec.ts
src/app/onboarding/views/MultiZoneView.vue

chore: fixes flaky MultiZoneView test

---

src/app/AppHeader.vue
src/app/common/charts/DoughnutChart.vue
src/app/wizard/views/MeshWizard.vue
src/app/wizard/views/__snapshots__/MeshWizard.spec.ts.snap

chore: backports release-2.2 changes back into master

---

src/app/wizard/views/DataplaneKubernetes.vue
src/app/wizard/views/DataplaneKubernetesSchema.ts

fix: migrate annotations to labels

---

src/test-support/mocks/src/dataplanes+insights.ts
src/test-support/mocks/src/dataplanes.ts
src/test-support/mocks/src/external-services.ts
src/test-support/mocks/src/global-insights.ts
src/test-support/mocks/src/mesh-insights.ts
src/test-support/mocks/src/mesh-insights/_.ts
src/test-support/mocks/src/meshes.ts
src/test-support/mocks/src/meshes/_/circuit-breakers.ts
src/test-support/mocks/src/meshes/_/dataplanes+insights.ts
src/test-support/mocks/src/meshes/_/external-services.ts
src/test-support/mocks/src/meshes/_/fault-injections.ts
src/test-support/mocks/src/meshes/_/health-checks.ts
src/test-support/mocks/src/meshes/_/meshgatewayroutes.ts
src/test-support/mocks/src/meshes/_/meshgateways.ts
src/test-support/mocks/src/meshes/_/proxytemplates.ts
src/test-support/mocks/src/meshes/_/retries.ts
src/test-support/mocks/src/meshes/_/service-insights.ts
src/test-support/mocks/src/meshes/_/service-insights/_.ts
src/test-support/mocks/src/meshes/_/timeouts.ts
src/test-support/mocks/src/meshes/_/traffic-logs.ts
src/test-support/mocks/src/meshes/_/traffic-permissions.ts
src/test-support/mocks/src/meshes/_/traffic-routes.ts
src/test-support/mocks/src/meshes/_/traffic-traces.ts
src/test-support/mocks/src/service-insights.ts
src/test-support/mocks/src/zoneegressoverviews.ts
src/test-support/mocks/src/zoneingresses+insights.ts
src/test-support/mocks/src/zones+insights.ts
src/test-support/mocks/src/zones.ts

chore: replaces deprecated faker methods

---

src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
src/app/onboarding/views/__snapshots__/AddNewServicesCode.spec.ts.snap
src/app/wizard/views/__snapshots__/DataplaneUniversal.spec.ts.snap
src/app/wizard/views/__snapshots__/MeshWizard.spec.ts.snap

chore: regenerates snapshots for Kongponents update

---

src/app/common/DataOverview.vue
src/app/common/DefinitionListItem.vue
src/app/common/KFilterBar.vue

chore: addresses new linter rules

---

src/index.ts
src/main.ts

This reverts commit 828a4c912dc980efdbb7b3d354fa523f5fe9c07c.

Revert "Revert "fix: triggering global loading when re-running bootstrap (#929)""

---

src/app/policies/views/PolicyListView.vue

Hot fix. Proper fix and more explanation https://github.com/kumahq/kuma-gui/pull/950.

fix: policy list title

---

jest/jest-setup-after-env.ts
src/app/onboarding/views/__snapshots__/ConfigurationTypes.spec.ts.snap
src/app/onboarding/views/__snapshots__/DeploymentTypes.spec.ts.snap

chore: regenerates snapshots for Kongponents

---

src/app/data-planes/components/DataplanePolicies.vue
src/types/index.d.ts

fix: reading gateway listeners unsafely

---

src/app/zones/views/ZoneListView.vue

fix: not determining Zone ingress/egress correctly

---

src/app/services/components/ServiceSummary.vue

fix: service link being part of copy button

---

src/test-support/mocks/src/provision-zone.ts

chore: changes token format in mock data

---

src/app/common/ResourceCodeBlock.vue
src/app/services/components/ServiceSummary.vue

See https://github.com/kumahq/kuma/issues/6780#issuecomment-1582657955

chore: hides copy as kubernetes button for internal service insights

---

src/app/zones/views/ZoneListView.vue

fix: not replacing zone name in delete modal

---

package.json
src/app/common/DataOverview.vue
src/app/common/DeleteResourceModal.vue
src/app/common/__snapshots__/DataOverview.spec.ts.snap
src/app/zones/views/ZoneListView.spec.ts
src/app/zones/views/ZoneListView.vue
src/app/zones/views/__snapshots__/ZoneListView.spec.ts.snap

**fix: not updating Zone CP list view after deleting**
Fixes not updating the Zone CP list view after deleting one.

fix: not updating zone list view after deleting

---

tsconfig.json

See https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CHANGELOG.md#v1800

chore: updates cypress-cucumber-preprocessor paths

---

features/application/Titles.feature
features/zones/Create.feature
public/mockServiceWorker.js
src/app/zones/routes.ts
src/app/zones/views/__snapshots__/ZoneListView.spec.ts.snap

The prefix didn't really make sense
Fix #1030

fix(zone/create): change from /zones/-create to /zones/create

---

src/app/common/charts/DoughnutChart.vue

Backports https://github.com/kumahq/kuma-gui/pull/1073 into `release-2.3`.

fix(charts): avoid NaN error on hover (backports #1073 into release-2.3)

---

src/app/common/charts/DoughnutChart.vue

fix: premature access to chart route data

---

src/app/common/charts/DoughnutChart.vue

fix: premature access to chart route data (#1093)

---

src/services/development.ts
src/services/production.ts

Disables the logger service in prod. Enables the logger service in dev.

chore: disables logger in prod, enables console logger in dev

---

src/app/policies/views/PolicyListView.vue

I keep staring at this and convincing myself this shouldn't be here, but its one of those things where I keep looking at it and thinking "yeah this is wrong right? right? is it? yeah. You sure? yeah sure. Is it? 🤔 mm I think so?" 😆 
I traced it back to here https://github.com/kumahq/kuma-gui/commit/932ef8fb665372fb4b8f3a220a0f4dbf1098afe6#diff-b29a35ea7ea1f70a55d2925c0f7c83417d8c6abe6d18b452e42fb00cf1c64825R17, seems unintentional?

chore: Remove stray > char

---

cypress/support/step_definitions/index.ts

**chore(e2e): adds "requested N times" helper**
**chore(e2e): support clearing input elements**

chore: expands test helpers

---

src/services/testing.ts

chore: disables logger in test setup

---

cypress/support/step_definitions/index.ts

Adds an optional "only" keyword to allow the `the URL "..." was requested with` step to assert exact request contents (e.g. when utilizing PATCH requests).

chore(e2e): adds assertion option for exact request contents

---

src/app/common/ErrorBlock.vue
src/app/zones/views/ZoneCreateView.vue
src/services/kuma-api/ApiError.spec.ts
src/services/kuma-api/ApiError.ts
src/services/kuma-api/makeRequest.spec.ts
src/services/kuma-api/makeRequest.ts

Updates the API error format following https://github.com/kumahq/kuma/issues/6136.

refactor: updates API error format

---

src/app/common/__snapshots__/DataOverview.spec.ts.snap
src/app/common/__snapshots__/EnvoyData.spec.ts.snap
src/app/wizard/views/__snapshots__/DataplaneUniversal.spec.ts.snap
src/app/wizard/views/__snapshots__/MeshWizard.spec.ts.snap

chore(deps): regenerates snapshots for Kongponents

---

features/application/Loading.feature
src/app/App.vue
src/app/AppHeader.vue
src/index.ts
src/main.ts
src/services/production.ts
src/store/modules/config/config.spec.ts
src/store/modules/config/config.ts
src/store/storeConfig.spec.ts
src/store/storeConfig.ts

Whilst this seems to work over here, its causing issues elsewhere so I'm reverting this to come back another time.

chore: Revert Removes last HTTP call to `/` and moves bootstrapping (#1157)

---

src/app/__snapshots__/AppOnboardingNotification.spec.ts.snap
src/app/common/__snapshots__/DataOverview.spec.ts.snap
src/app/common/__snapshots__/UpgradeCheck.spec.ts.snap
src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
src/app/data-planes/components/__snapshots__/DataplanePolicies.spec.ts.snap
src/app/onboarding/views/__snapshots__/CreateMesh.spec.ts.snap
src/app/onboarding/views/__snapshots__/DataplanesOverview.spec.ts.snap

chore: regenerates snapshots

---

src/app/application/components/app-collection/AppCollection.vue
src/app/policies/views/PolicyListView.vue

**feat: adds custom toolbar styles**
Adds custom toolbar styles so that toolbar entries are automatically placed and spaced in the right position above the table.
**refactor: moves cell attributes function into script block**
**chore: aid syntax highlighting by wrapping `as string` in template**
**chore: marks `total` as optional prop**

feat: expand app collection

---

features/mesh/Index.feature
src/app/meshes/routes.ts
src/app/meshes/sources.ts
src/app/meshes/views/MeshListView.vue

Integrates DataSource/AppCollection for Mesh listing

chore: Uses DataSource/AppCollection for Mesh listing

---

features/mesh/services/Index.feature
src/app/services/index.ts
src/app/services/routes.ts
src/app/services/sources.ts
src/app/services/views/ServiceListView.vue
src/locales/en-us/common/index.yaml
src/services/production.ts

Converts Service Listing to use DataSource and AppCollection

chore: Convert Service listing to DataSource / AppCollection

---

features/mesh/policies/Data.feature
features/mesh/policies/Index.feature
src/app/application/components/route-view/RouteView.vue
src/app/policies/routes.ts
src/app/policies/sources.ts
src/app/policies/views/PolicyListView.vue
src/test-support/mocks/src/meshes.ts

Move PolicyListing to use AppCollection
Note summary views have been removed here

chore: Move PolicyListing to use AppCollection

---

src/app/common/StatusBadge.vue
src/app/common/__snapshots__/DataOverview.spec.ts.snap
src/app/data-planes/components/DataPlaneEntitySummary.vue
src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
src/app/data-planes/components/__snapshots__/DataPlaneEntitySummary.spec.ts.snap
src/app/onboarding/views/__snapshots__/DataplanesOverview.spec.ts.snap
src/app/services/components/ServiceSummary.vue

Updates the StatusBadge component to match the design.
**Before**:
**After**:

chore: updates status badge to match design

---

features/application/MainNavigation.feature
features/application/Titles.feature
features/zones/ListViewContent.feature
features/zones/PageNavigation.feature
features/zones/zone-cps/Item.feature
src/app/common/warnings/WarningZoneAndGlobalCPSVersionsIncompatible.vue
src/app/common/warnings/WarningZoneAndKumaDPVersionsIncompatible.vue
src/app/onboarding/components/graphs/MultizoneGraph.vue
src/app/zones/components/ZoneDetails.vue
src/app/zones/locales/en-us/index.yaml

chore(zone-cps): renames control planes to zone control planes

---

src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap

chore: regenerates snapshots for kongponents 10

---

.eslintrc.js

chore: disables no-setup-props-destructure rule

---

features/zones/ListViewContent.feature
src/app/zones/views/ZoneListView.vue

Fixes the Zone Control Plane not being listed with its own environment.

fix(zones): zone type being incorrect

---

features/diagnostics/DetailViewContent.feature
src/app/diagnostics/index.ts
src/app/diagnostics/sources.ts
src/app/diagnostics/views/DiagnosticsView.vue
src/services/production.ts

refactor: use DataSource for diagnostics view

---

src/app/application/components/data-source/DataSource.vue
src/app/application/services/data-source/DataSourcePool.ts
src/app/zones/sources.ts
src/app/zones/views/ZoneDetailView.vue
src/app/zones/views/ZoneEgressDetailView.vue
src/app/zones/views/ZoneIngressDetailView.vue

**feat: adds isLoading state to DataSource**
**refactor: use DataSource for Zone CP detail view**
**refactor: use DataSource for Zone Egress detail view**
**refactor: use DataSource for Zone Ingress detail view**

refactor: use data source for zone views

---

src/app/services/sources.ts
src/app/services/views/ServiceDetailView.vue
src/app/services/views/ServiceListView.vue

refactor: uses DataSource for service detail view

---

src/app/data-planes/sources.ts
src/app/data-planes/views/DataPlaneDetailView.vue
src/app/data-planes/views/DataPlaneListView.vue
src/app/gateways/sources.ts
src/app/gateways/views/GatewayListView.vue
src/app/policies/components/PolicyConnections.vue
src/app/policies/sources.ts
src/app/policies/views/PolicyListView.vue
src/app/services/sources.ts
src/app/services/views/ServiceDetailView.vue
src/app/services/views/ServiceListView.vue

fix: non-unique DataSource paths

---

src/app/policies/views/PolicyListView.vue

fix: incorrect DataSource path

---

src/app/common/ResourceCodeBlock.vue
src/app/data-planes/components/DataPlaneDetails.vue
src/app/data-planes/components/__snapshots__/DataPlaneDetails.spec.ts.snap
src/app/meshes/components/MeshDetails.vue
src/app/policies/components/PolicyDetails.vue
src/app/policies/routes.ts
src/app/policies/sources.ts
src/app/policies/views/PolicyDetailView.vue
src/app/services/components/ServiceSummary.vue

Uses `DataSource` for the fetching of the universal representation of a resource in detail views.

refactor: uses DataSource for main resource in code blocks

---

src/app/policies/views/PolicyDetailView.vue

chore: cleans up some dead code

---

src/app/policies/views/PolicyListView.vue

chore: removes lowercasing of policy docs URL

---

src/app/policies/components/PolicyList.vue

fix(policies): policy type list font size

---

src/app/data-planes/components/DataPlaneDetails.vue
src/app/data-planes/sources.ts
src/app/data-planes/views/DataPlaneDetailView.vue

chore: shows Dataplane config instead of DataplaneOverview

---

src/app/meshes/components/MeshDetails.vue
src/app/meshes/views/MeshDetailView.vue
src/components/index.ts

chore(meshes): makes MeshDetails injectable

---

src/app/meshes/components/MeshDetails.vue
src/app/meshes/locales/en-us/index.yaml
src/test-support/mocks/src/meshes/_.ts

chore(meshes): removes tracing and logging
chore(meshes): only reads enabledBackend
feat(meshes): adds zoneEgress

chore(meshes): removes tracing & logging, adds Zone Egress

---

.github/workflows/main.yml

ci: parallelizes Cypress tests

---

src/app/main-overview/components/ControlPlaneDetails.vue

chore: corrects action bar alignment

---

src/app/zones/locales/en-us/index.yaml
src/app/zones/views/ZoneCreateView.vue
src/assets/styles/_forms.scss
src/assets/styles/_utilities.scss
src/assets/styles/_variables.scss

**chore: adds text gradient utility**
Adds a text-gradient utility class and uses it for the Zone creation title.
**chore(zones): adds content hooks for descriptions and facts to creation view**

chore(zones): adds more content hooks for zone creation

---

src/app/zones/components/ZoneActionMenu.vue
src/app/zones/locales/en-us/index.yaml
src/app/zones/views/ZoneDetailTabsView.vue

Adds an action menu to the Zone detail view that gives access to deleting a Zone.

feat(zones): adds action menu to detail view

---

src/test-support/fake.ts
src/test-support/mocks/src/meshes/_.ts

For if you want to be able to control via a browser if you can see mTLS related things or not.

chore: Adds mTLS env var for in browser previewing

---

src/app/zones/locales/en-us/index.yaml

Adds step descriptions for the zone flow.

feat(zones): add step descriptions

---

features/zones/Delete.feature
src/app/common/DeleteResourceModal.vue
src/app/zones/components/ZoneActionMenu.vue
src/app/zones/locales/en-us/index.yaml
src/app/zones/views/ZoneListView.vue
src/locales/en-us/common/index.yaml

Adds some additional error information to the DeleteResourceModal.

chore: improves DeleteResourceModal

---

src/app/common/LoadingBlock.vue
src/app/services/views/ServiceListView.vue
src/app/zones/components/EntityScanner.vue
src/app/zones/views/ZoneCreateView.vue

chore: cleans up unnecessary icon props

---

src/app/common/DeleteResourceModal.vue
src/app/zones/views/CreateView.vue

chore: uses error.detail for error alerts

---

src/app/data-planes/components/DataPlaneList.vue

chore(dataplanes): removes unused code from list

---

features/mesh/gateways/PageNavigation.feature
src/app/gateways/routes.ts

fix(gateways): config tab missing

---

src/app/common/SummaryView.vue
src/assets/styles/_variables.scss

refactor: provide way to override slideout offset top

---

src/app/common/SummaryView.vue

fix: wrong variable name

---

src/app/zone-egresses/views/IndexView.vue

fix(zones): wrong egress detail link

---

features/mesh/services/Item.feature
src/app/services/views/ServiceDetailTabsView.vue
src/test-support/FakeKuma.ts

fix(services): showing config tab for gateway services

---

cypress/support/step_definitions/index.ts
features/mesh/dataplanes/Index.feature

chore(dataplanes): expand list view coverage

---

src/app/zones/locales/en-us/index.yaml

fix: update helm command

---

src/app/application/components/app-view/AppView.vue

fix: duplicated .app-main-content padding

---

cypress/support/step_definitions/visit.ts
src/app/App.vue

chore: assert against kuma-ready class

---

cypress/support/step_definitions/visit.ts
src/app/App.vue

chore: assert against data-testid-root

---

src/app/common/CopyButton.vue

fix: copy button tooltip not visible

---

src/app/data-planes/views/DataPlaneDetailView.vue
src/test-support/FakeKuma.ts
src/types/index.d.ts

fix(dataplanes): service address and port not always being set

---

.eslintrc.js

chore(linters): simplify ESLint TypeScript integration

---

src/test-support/mocks/src/meshes/_/service-insights/_.ts

Fixes an issue with not correctly determining the service type in the single resource type mock for services.

chore(services): fix single resource mocks

---

.github/dependabot.yml

ci: disable Kongponents updates

---

src/app/common/ErrorBlock.vue

fix(ErrorBlock): badge truncation issue

---

src/app/services/components/ServiceInsightDetails.vue
src/app/services/data/index.spec.ts
src/app/services/data/index.ts
src/app/services/sources.ts
src/app/services/views/ServiceDetailTabsView.vue
src/app/services/views/ServiceDetailView.vue
src/app/services/views/ServiceListView.vue
src/app/services/views/ServiceSummaryView.vue

Set-up data transformations for the services module.

refactor(services): set-up data transformations

---

src/app/policies/components/PolicyConnections.vue
src/app/policies/components/PolicyList.vue
src/app/policies/data/index.ts
src/app/policies/sources.ts
src/app/policies/views/PolicySummaryView.vue

Set-up data transformations for the policies module.

refactor(policies): set-up data transformations

---

src/app/data-planes/data/index.ts
src/app/meshes/components/MeshDetails.vue
src/app/meshes/components/MeshInsightsList.vue
src/app/meshes/data/index.spec.ts
src/app/meshes/data/index.ts
src/app/meshes/sources.ts
src/app/meshes/views/MeshConfigView.vue
src/app/meshes/views/MeshListView.vue
src/app/meshes/views/MeshSummaryView.vue
src/app/policies/components/PolicyList.vue
src/app/services/data/index.ts
src/types/index.d.ts

Set-up data transformations for the meshes module.

refactor(meshes): set-up data transformations

---

src/app/data-planes/data/index.spec.ts
src/app/data-planes/data/index.ts
src/app/data-planes/views/DataPlaneConfigView.vue
src/app/policies/data/index.ts
src/app/policies/views/PolicyDetailView.vue
src/app/policies/views/PolicySummaryView.vue
src/app/services/data/index.spec.ts
src/app/services/data/index.ts
src/app/services/views/ServiceConfigView.vue
src/app/services/views/ServiceSummaryView.vue

fix: showing data-transformed objects as YAML

---

src/app/policies/components/PolicyList.vue

Resolves #1962.
Not sure where/how this was introduced. Could be related to the KCard changes?

fix(policies): policy type list being too wide

---

yarn.lock

Same approach as https://github.com/kumahq/kuma-gui/pull/1887

chore(deps-dev): remove breaking lockfile changes

---

features/mesh/dataplanes/Index.feature
src/app/data-planes/components/DataPlaneList.vue
src/app/data-planes/data/index.spec.ts
src/app/data-planes/data/index.ts
src/app/data-planes/views/DataPlaneListView.vue
src/app/services/views/ServiceDataPlaneProxiesView.vue

Adds a Zone column to Dataplane lists.

feat(dataplanes): add zone column

---

src/app/data-planes/components/RuleEntryList.vue

fix(dataplanes): overflow issues in policies tables

---

src/services/env/Env.ts
vite.config.preview.ts

chore: remove duplicated type definition

---

yarn.lock

chore(deps-dev): remove names from lockfile

---

package.json
yarn.lock

chore(deps): update Kongponents

---

src/app/data-planes/components/RuleEntryList.vue

fix(dataplanes): conf code block being displayed as one line

---

.github/workflows/create-gui-pr.yml

ci: fix create-gui-pr workflow

---

package.json
src/app/common/NavTabs.vue
yarn.lock

fix(NavTabs): tab click target being too small

---

src/app/policies/components/PolicyList.vue

fix(policies): legacy policy types showing

---

src/app/data-planes/components/PolicyTypeEntryList.vue
src/test-support/mocks/src/meshes/_/dataplanes/_/policies.ts

Putting this up in case we decide we need this.

feat(dataplanes): filter out targetRef-based policies

---

.github/workflows/create-gui-pr.yml

ci: add version comment to create-github-app-token action

---

features/zones/Create.feature
src/app/application/components/route-view/RouteView.vue
src/app/application/index.ts
src/app/application/utilities/index.ts
src/app/common/code-block/CodeBlock.vue
src/app/common/filter-bar/FilterBar.vue
src/app/data-planes/components/PolicyTypeEntryList.vue
src/app/data-planes/components/RuleEntryList.vue
src/app/data-planes/components/StandardDataplanePolicies.vue
src/app/data-planes/views/DataPlanePoliciesView.vue
src/app/diagnostics/views/DiagnosticsDetailView.vue
src/app/onboarding/views/OnboardingAddNewServicesCodeView.vue
src/app/policies/views/PolicyDetailView.vue
src/app/zones/components/ZoneCreateKubernetesInstructions.vue
src/app/zones/components/ZoneCreateUniversalInstructions.vue
src/app/zones/views/ZoneConfigView.vue
src/app/zones/views/ZoneCreateView.vue

Removes all instances of non-unique/hardcoded id usage.
Theres a thing I want to explain/ask which I'll note inline.

chore: Remove non-unique HTML id's

---

src/app/common/UpgradeCheck.vue

Backport of https://github.com/kumahq/kuma-gui/pull/2136

fix: prevent a blinking upgrade alert

---

src/app/zone-egresses/sources.ts
src/app/zone-ingresses/sources.ts
src/app/zones/sources.ts

Part of https://github.com/kumahq/kuma-gui/issues/1474 and https://github.com/kumahq/kuma-gui/issues/1817

chore(zones): uses defineSources for zone related sources

---

src/app/data-planes/data/index.spec.ts
src/app/zones/data/index.spec.ts
src/test-support/fake.ts
src/test-support/mocks/src/meshes/_/dataplanes/_/_overview.ts

Refactors our dataplane data reshaping test to use the approach in https://github.com/kumahq/kuma-gui/pull/1910
Also see https://github.com/kumahq/kuma-gui/pull/2151

chore(dataplane): refactor dataplane data reshaping tests

---

.github/workflows/create-gui-pr.yml

Updates the create-gui-pr workflow to include the generation of a syfy SBOM and a grype CVE report.

ci: set-up SBOM generation

---

src/app/common/TagList.vue

Port to `master` of https://github.com/kumahq/kuma-gui/pull/2016

fix(zones): If there are no zone details pages, don't link a tag to one

---

src/app/zones/views/ZoneCreateView.vue
src/assets/styles/_forms.scss

fix(zones): create flow facts layout

---

.github/workflows/create-gui-pr.yml

As talked on slack.
Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits) yes
Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)? yes

ci(update): add team-mesh to team-reviewers on gui update PRs

---

.github/workflows/create-gui-pr.yml

ci: fix team-reviewers name

---

.github/workflows/main.yml
scripts/getPartitionedTestFiles.cjs

Update main.yml workflow to match kong-mesh-gui more closely.
Fix an issue with the Cypress artifact upload failing on account of existing artifact file names.

ci: tweak parallelization logic

---

src/app/control-planes/sources.ts
src/app/me/sources.ts
src/app/meshes/sources.ts
src/app/policies/sources.ts

Closes https://github.com/kumahq/kuma-gui/issues/1817

refactor: moves remaining source definitions to use defineSource

---

features/mesh/Index.feature
features/zones/zone-cps/ingresses/item/Index.feature
src/app/application/components/route-view/RouteView.vue
src/app/common/NavTabs.vue
src/app/data-planes/views/DataPlaneDetailTabsView.vue
src/app/data-planes/views/DataPlaneInboundSummaryView.vue
src/app/data-planes/views/DataPlaneOutboundSummaryView.vue
src/app/external-services/routes.ts
src/app/external-services/views/ExternalServiceDetailTabsView.vue
src/app/external-services/views/ExternalServiceListView.vue
src/app/gateways/views/BuiltinGatewayDetailTabsView.vue
src/app/gateways/views/DelegatedGatewayDetailTabsView.vue
src/app/gateways/views/GatewayListTabsView.vue
src/app/meshes/views/MeshDetailTabsView.vue
src/app/services/locales/en-us/index.yaml
src/app/services/views/ServiceDetailTabsView.vue
src/app/services/views/ServiceListView.vue
src/app/zone-egresses/views/ZoneEgressDetailTabsView.vue
src/app/zone-ingresses/views/ZoneIngressDetailTabsView.vue
src/app/zones/views/ZoneDetailTabsView.vue
src/shims-vue-router.d.ts

Integrate the logic for determining the routes that are to be displayed as navigational tabs into the NavTabs component.

refactor: simplify NavTabs component

---

src/app/data-planes/components/DataPlaneList.vue
src/app/data-planes/views/DataPlaneListView.vue
src/app/gateways/views/DelegatedGatewayDataPlaneProxiesView.vue
src/app/services/views/ServiceDataPlaneProxiesView.vue

fix: unflagged reference to feature-flagged route

---

.github/workflows/create-gui-pr.yml

ci: fail create-gui-pr workflow if vulnerabilities are found

---

yarn.lock

chore(deps-dev): remove name entries from lock file

---

README.md

fix link to GUI docs

---

src/app/zones/locales/en-us/index.yaml

chore: remove deltaKds from zone connection instructions

---

package.json

Define package manager and version in package.json for corepack to pick up.

chore: add packageManager property to package.json

---

.github/workflows/lifecycle.yml

ci(github): fix lifecycle by using the github app

---

src/app/data-planes/views/DataPlaneListView.vue

fix(dataplanes): Make sure we use the dpp.id for "Go to details" link

---

src/app/gateways/views/BuiltinGatewayDataplanesView.vue

Similar to https://github.com/kumahq/kuma-gui/pull/2380

fix(gateways): ensure gateway linking uses ids rather than names

---

src/app/policies/routes.ts
src/app/policies/views/PolicyTypeListView.vue
src/app/x/components/x-action/XAction.vue

Port of https://github.com/kumahq/kuma-gui/pull/2417 to `master`

fix(policies): redirect to first available policy type instead of CBs

---

src/app/connections/views/ConnectionInboundSummaryOverviewView.vue
src/app/connections/views/ConnectionOutboundSummaryOverviewView.vue

fix(connections): rule cards not having gaps

---

cypress.config.ts

Annotates GitHub Actions errors in Cypress tests. There doesn’t seem to be a way to extract the line from the test file that failed. It’s also unfortunate that Cypress doesn’t seem to keep the original errors around and so we can only extract errors from the `displayError` field which has a string of the following kind:
```
"AssertionError: Timed out retrying after 4000ms: expected 'Zone Control Planes | Kuma Manager' to include 'Zone Control Planes NOPE'\n" +
'    at Context.eval (http://localhost:8080/__cypress/tests?p=features/zones/Create.feature:55524:20)\n' +
'    at Registry.runStepDefininition (http://localhost:8080/__cypress/tests?p=features/zones/Create.feature:8576:48)\n' +
'    at Object.fn (http://localhost:8080/__cypress/tests?p=features/zones/Create.feature:15139:43)\n' +
' …
```

ci: annotate GitHub Actions errors

---

.editorconfig
Makefile
mk/build.mk
mk/help.mk
mk/install.mk

chore: add make commands (release-2.7)

---

.editorconfig
Makefile
mk/build.mk
mk/help.mk
mk/install.mk

chore: add make commands (release-2.5)

---

.editorconfig
Makefile
mk/build.mk
mk/help.mk
mk/install.mk

chore: add make commands (release-2.4)

---

.editorconfig
Makefile
mk/build.mk
mk/help.mk
mk/install.mk

chore: add make commands (release-2.3)

---

.syft.yaml

chore: backport syft config (release-2.5)

---

.syft.yaml

chore: backport syft config (release-2.4)

---

.syft.yaml

chore: backport syft config (release-2.3)

---

mk/install.mk

chore(mk: update install makefiles (release-2.3)

---

mk/install.mk

chore(mk: update install makefiles (release-2.5)

---

mk/install.mk

chore(mk: update install makefiles (release-2.6)

---

mk/install.mk

chore(mk: update install makefiles (release-2.7)

---

.github/workflows/create-gui-pr.yml
mk/install.mk

ci: update create-gui-pr workflow to use make commands
chore(mk): update install makefiles

ci: use make commands in create-gui-pr workflow

---

package-lock.json
package.json

chore(deps-dev): remove eslint-plugin-n
chore(deps-dev): remove eslint-plugin-promise 
chore(deps-dev): remove eslint-friendly-formatter 

chore(deps-dev): remove unnecessary eslint dependencies

---

package-lock.json
package.json
src/app/rules/components/RuleList.vue

Address changes from https://github.com/Kong/kongponents/pull/2151

refactor: upgrade kongponents w/KTable changes

---

src/app/application/index.ts
src/app/services/features.ts
src/app/services/index.ts
src/app/services/routes.ts
src/services/env/Env.ts
src/services/env/env.spec.ts

Turn meshservice into a flaggable feature but default it to `true`

chore(meshservice): add feature flag for meshservice

---

package-lock.json
package.json
src/app/data-planes/views/DataPlaneSummaryView.vue

Kongponents/kpop/floating-ui upgrade.

chore(deps): kongponents/kpop/floating-ui upgrade

---

features/mesh/services/mesh-external-services/Index.feature
src/app/services/data/index.ts
src/app/services/locales/en-us/index.yaml
src/app/services/routes.ts
src/app/services/sources.ts
src/app/services/views/MeshExternalServiceConfigView.vue
src/app/services/views/MeshExternalServiceDetailTabsView.vue
src/app/services/views/MeshExternalServiceDetailView.vue
src/app/services/views/MeshExternalServiceListView.vue
src/app/services/views/MeshExternalServiceSummaryView.vue
src/app/services/views/MeshServiceDetailView.vue
src/services/kuma-api/KumaApi.ts
src/test-support/mocks/fs.ts
src/test-support/mocks/src/meshes/_/meshexternalservices.ts
src/test-support/mocks/src/meshes/_/meshexternalservices/_.ts
src/types/index.d.ts

Initial support for MeshExternalService
[Direct Link](https://deploy-preview-2619--kuma-gui.netlify.app/gui/meshes/default/services/mesh-external-services?page=1&size=50)
See https://github.com/kumahq/kuma-gui/issues/2471

feat(services): Adds support for MeshExternalService

---

package-lock.json

Upgrades kongponents to alpha-178 via `npm upgrade`

chore(deps): manually upgrade kongponents

---

features/zones/Delete.feature
package-lock.json
package.json

See https://github.com/Kong/kongponents/pull/2157

chore(deps): Upgrade kongponents 

---

package-lock.json
package.json
src/app/meshes/index.ts
src/app/meshes/locales/en-us/index.yaml
src/app/meshes/views/MeshDetailView.vue
src/assets/styles/main.scss
src/test-support/mocks/src/meshes/_.ts

Port to `master` of https://github.com/kumahq/kuma-gui/pull/2674 and https://github.com/kumahq/kuma-gui/pull/2677

chore(meshes): [port] add warning for when mTLS is enabled but no MTP exists

---

src/app/common/SummaryView.vue
src/app/common/code-block/CodeBlock.vue

Port of https://github.com/kumahq/kuma-gui/pull/2658 to master

fix: [port] makes codeblock sticky toolbar use a variable height

---

src/app/services/views/MeshServiceDetailView.vue
src/app/services/views/MeshServiceListView.vue
src/app/services/views/MeshServiceSummaryView.vue
src/test-support/mocks/src/meshes/_/meshservices.ts
src/test-support/mocks/src/meshes/_/meshservices/_.ts
src/types/index.d.ts

chore(meshservice): move protocol to appProtocol (#2675)

---

src/app/gateways/views/GatewayListTabsView.vue
src/app/services/views/ServiceListTabsView.vue
src/app/x/components/x-action-group/README.md
src/app/x/components/x-action-group/XActionGroup.vue
src/app/x/index.ts

Renames `LinkBox` to `XActionGroup`.

chore: Moves LinkBox to XActionGroup

---

package-lock.json
package.json

Upgrade kongponents to `9.0.0` (i.e. not the alpha)

chore(deps): upgrade kongponents to 9.0.0

---

src/services/kuma-api/RestClient.ts

We are close to moving all our handwritten types to use auto generated types form Kuma's OpenAPI schemas.
This will eventually use the `openapi-fetch` package/HTTP client. This client lets you inject in a fetch implementation to use to make HTTP requests. This fact lets us inject in our existing HTTP functionality to ensure everything keeps working as expected across all projects/applications.
The only issue is we need something `window.fetch`-shaped that pushes any requests through our `client.raw` method.
This PR exposes `client.raw` via something that is shaped the same as `window.fetch`, meaning we can pass this in the `openapi-fetch` client, and therefore keep using the extra functionality we have inside `client.raw`.
It's initially to be used like the following, which is the …

chore: expose fetch-like function from RestClient

---

.env
src/shims-env.d.ts

chore: remove some old, unused env vars

---

src/app/meshes/views/MeshListView.vue
src/app/zones/views/ZoneListView.vue

Most of this was done in https://github.com/kumahq/kuma-gui/pull/2749, but after merging that I did another pass and found these 2 that were outstanding.
One of those were most of the change is down to re-nesting of HTML components.
Closes https://github.com/kumahq/kuma-gui/issues/2388

chore: Ensure every listing uses DataCollection

---

src/app/common/EmptyBlock.vue
src/app/msw/index.ts
src/app/x/components/x-action-group/XActionGroup.vue
src/app/x/components/x-action/XAction.vue
src/app/x/components/x-copy-button/XCopyButton.vue
src/app/x/debug.ts
src/app/x/index.ts
src/app/zone-egresses/views/ZoneEgressListView.vue
src/app/zone-ingresses/views/ZoneIngressListView.vue
src/app/zones/data/index.ts
src/main.ts
vite.config.production.ts

I noticed a bunch of dev-time `console` warnings. This PR cleans them up a little.

fix: silences/fixes some dev-time console warnings

---

src/app/zone-egresses/views/ZoneEgressListView.vue

fix(zones): correct egress documentation link

---

src/app/zones/data/index.ts
src/test-support/FakeKuma.ts

See title
Closes https://github.com/kumahq/kuma-gui/issues/2926

fix(zones): expect `authn` not `auth` in ZoneInsight.config

---

features/mesh/policies/Index.feature
src/app/policies/data/index.ts
src/app/policies/views/PolicyListView.vue
src/app/x/components/x-icon/XIcon.vue
src/test-support/FakeKuma.ts
src/test-support/mocks/src/meshes/_/meshfaultinjections.ts

See title
Closes https://github.com/kumahq/kuma-gui/issues/2930

feat(policies): add icon for producer policies in policy listings

---

package-lock.json
package.json

See title, we no longer use this and it has problematic dependencies

chore(deps): removes vue-docgen-cli

---

src/app/application/components/app-view/AppView.vue

fix(kuma): book icon style updates

---

active-branches.json

chore(ci): add active-branches file

---

src/app/application/components/route-view/RouteView.vue

Adds the ability to inspect the `route` of the previous page, i.e. the history using `RouteView::route.from`.
This is useful for if we need to take the user to a certain page depending on where they came from.
---
We could use native `location.history` to do things like this, but it doesn't give you Vue route information.
The downside is here, we only store the single previous page, i.e. where you came from not the full history. This feels like Vue more seeing as Vue only works with the idea of `from`.
I doubt we'll need to store a full history of routes for anything, so this is fine for the moment. If we ever need to store a full history we can do that under `route.history`, and keep `route.from` as a shortcut to `route.history[0]`.
---
I also changed some naming inside RouteView here. …

chore: add route.from property to RouterView::route

---

packages/kuma-gui/src/test-support/intercept.ts

This reverts commit 23830d4f96d30be76de9f62f65f4b6e33bd05fe6.
Decided this wasn't the right approach, need to re-think it.

Revert "chore(tests): changes cypress to intercept all responses #3212"

---

packages/kuma-gui/src/app/meshes/locales/en-us/index.yaml
packages/kuma-gui/src/app/zones/locales/en-us/index.yaml
packages/kuma-gui/src/app/zones/views/ZoneListView.vue

fix(zones): correct text of Zone CP empty state

---

packages/kuma-gui/src/app/x/components/x-icon/XIcon.vue

The `AddCircleIcon` is a different variant of the `AddIcon`. The change to the `AddCircleIcon` should improve the look and feel of the action button variant that uses this icon.

refactor(x-icon): use AddCircleIcon

---

packages/kuma-gui/public/mockServiceWorker.js

Bumps MSW file see https://github.com/kumahq/kuma-gui/pull/3312#issuecomment-2548732720

chore(deps): bump MSW file

---

packages/kuma-gui/src/app/x/index.ts

Adds alias for KRadio to XRadio

chore: adds aliased XRadio

---

packages/kuma-gui/src/app/connections/locales/en-us/index.yaml
packages/kuma-gui/src/app/connections/sources.ts
packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
packages/kuma-gui/src/app/zone-egresses/views/ZoneEgressDetailView.vue
packages/kuma-gui/src/app/zone-ingresses/views/ZoneIngressDetailView.vue

Closes https://github.com/kumahq/kuma-gui/issues/2977
Related:
- https://github.com/kumahq/kuma-gui/pull/3296

feature(zones): adds a traffic view for zone egress

---

packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailTabsView.vue

Few tiny UX improvements to the "Download Bundle" modal (see https://github.com/kumahq/kuma-gui/pull/3329):
- Disable the download button until at least one checkbox is clicked.
- Only allow checking "Include EDS" is XDS is also checked.
- Close modal when downloading
Best viewed with GH's "Hide Whitespace" option enabled for the diff

chore(dataplanes): improve bundle downloading checkboxes

---

packages/kuma-gui/src/app/data-planes/locales/en-us/index.yaml
packages/kuma-gui/src/app/data-planes/sources.ts
packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailTabsView.vue

Closes https://github.com/kumahq/kuma-gui/issues/3356
Continuation of https://github.com/kumahq/kuma-gui/pull/3329

feat(dataplanes): include rules in dataplane bundle download

---

packages/kuma-gui/src/app/connections/views/ConnectionOutboundSummaryView.vue

Fixes an issue introduced in https://github.com/kumahq/kuma-gui/pull/3406

fix(dataplanes): fix misnamed prop

---

active-branches.json

chore(ci): update active-branches.json

---

packages/kuma-gui/src/app/zones/views/ZoneDetailView.vue

Closes https://github.com/kumahq/kuma-gui/issues/3324

chore(zones): use warning state for displaying version when outdated

---

package-lock.json

chore(deps): upgrade undici via `npm upgrade undici`

---

packages/kuma-gui/src/app/common/StatusBadge.vue
packages/kuma-gui/src/app/x/components/x-icon/XIcon.vue

Follow up of https://github.com/kumahq/kuma-gui/pull/3449#discussion_r1925503614
I also removed the placement prop as we no longer use that anywhere.

fix: use XTooltip instead of KTooltip

---

package-lock.json
packages/kuma-gui/package.json
packages/kuma-gui/vite.config.production.ts

We don't really use this, if we come to start needed/using this we can add it back in.
Also see https://github.com/kumahq/kuma-gui/pull/3428#issuecomment-2605074831

chore(deps): remove @vitest/coverage-istanbul

---

packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryStatsView.vue
packages/kuma-gui/src/app/connections/views/ConnectionOutboundSummaryStatsView.vue
packages/kuma-gui/src/app/connections/views/ConnectionsStatsView.vue
packages/kuma-gui/src/app/connections/views/zones/ConnectionInboundSummaryStatsView.vue
packages/kuma-gui/src/app/connections/views/zones/ConnectionOutboundSummaryStatsView.vue

See https://github.com/kumahq/kuma-gui/pull/3509#discussion_r1942548612

chore: remove some old ts exclamation marks from envoy related views

---

packages/kuma-gui/src/app/x/components/x-empty-state/XEmptyState.vue

- Fixed docs link for new empty state
- Enabled Teleport action for old empty state

fix: added docs fixes

---

packages/kuma-gui/src/app/kuma/locales/en-us/index.yaml

refactor(zones/warnings): rephrase nack-reponse warning to be more informal, remove instruction to restart cp

---

packages/kuma-gui/src/app/meshes/views/MeshListView.vue
packages/kuma-gui/src/app/zones/views/ZoneListView.vue

Removed intro from list pages for new empty states

fix: removed intro text for new empty states

---

active-branches.json

See title, I made it exactly the same as https://github.com/kumahq/kuma/pull/13020/files
Related:
- https://github.com/kumahq/kuma-gui/issues/2428

chore(ci): bump active-branches.json

---

packages/config/src/workflow.schema.json

Previously we only checked `jobs.steps.uses`

chore(ci): adds check on jobs.use and adds exclusion for kumahq/

---

package-lock.json

See title, I split in two commits which shows the result of each.

chore(deps): run npm upgrade and npm dedupe

---

package-lock.json
packages/kuma-gui/eslint.config.cjs
packages/kuma-gui/package.json

See title, I left in some commented out config for future us

chore(deps): unpin kong/shared-entities

---

packages/kuma-gui/src/assets/styles/_utilities.scss
packages/kuma-gui/src/assets/styles/_variables.scss

Removes some global CSS vars and global CSS helper classes we no longer use.

chore: cleanup some unused global css vars/classes

---

packages/kuma-gui/src/app/meshes/locales/en-us/index.yaml

Fix https://github.com/Kong/kong-mesh-gui/issues/86

chore(mtls): fix message

---

packages/kuma-gui/src/app/x/components/x-notification/XNotification.vue

In certain places a notification would appear without the text.
I noticed that the conditionals here where slightly wrong, which fixes the issue

fix(notifications): fix notifications sometimes not appearing

---

.nvmrc
packages/config/src/mk/check.mk
packages/config/src/mk/help.mk

Adds better instructions/info for installing and running `nvm`

chore(docs): adds improved docs for installing nvm

---

.github/workflows/main.yml
package.json

Changes more things to use matrices for CI execution

chore(ci): use workspaces for matrices

---

package-lock.json

fix(deps): runs npm install for some package-lock meta

---

packages/kuma-gui/features/control-planes/DetailView.feature
packages/kuma-gui/features/mesh/Index.feature
packages/kuma-gui/src/app/meshes/data/MeshInsight.ts
packages/kuma-gui/src/app/meshes/sources.ts
packages/kuma-gui/src/app/meshes/views/MeshListView.vue
packages/kuma-gui/src/test-support/mocks/src/mesh-insights.ts

Adds `XSearch` to `MeshListView` in order to let users filter meshes by `name`.
Part of #3757

feat(mesh-list-view): add x-search

---

packages/kuma-gui/src/app/zones/data/index.ts
packages/kuma-gui/src/app/zones/sources.ts
packages/kuma-gui/src/app/zones/views/ZoneListView.vue
packages/kuma-gui/src/test-support/mocks/src/zones/_overview.ts

Adds `XSearch` to `ZoneListView` in order to let users filter zones by `name`.
Part of #3757

feat(zones): add x-search

---

packages/kuma-gui/src/app/gateways/data/MeshGateway.ts
packages/kuma-gui/src/app/gateways/sources.ts
packages/kuma-gui/src/app/gateways/views/BuiltinGatewayListView.vue
packages/kuma-gui/src/app/gateways/views/DelegatedGatewayListView.vue

Adds `XSearch` to both `BuiltinGatewayListView` and `DelegatedGatewayListView`. User can filter
- builtin gateways by `name` and `zone`
- delegated gateways by `name`
Part of #3757

feat(gateways): add x-search

---

packages/kuma-gui/src/app/zone-egresses/data/index.ts
packages/kuma-gui/src/app/zone-egresses/sources.ts
packages/kuma-gui/src/app/zone-egresses/views/ZoneEgressListView.vue
packages/kuma-gui/src/app/zone-ingresses/data/index.ts
packages/kuma-gui/src/app/zone-ingresses/sources.ts
packages/kuma-gui/src/app/zone-ingresses/views/ZoneIngressListView.vue
packages/kuma-gui/src/test-support/mocks/src/zone-ingresses/_overview.ts
packages/kuma-gui/src/test-support/mocks/src/zoneegresses/_overview.ts

Adds `XSearch` to `ZoneIngressListView` and `ZoneEgressListView` in order to let users filter zones by `name`.
Part of #3757

feat(zone-ingress,-egresses): add x-search

---

packages/kuma-gui/src/app/x/index.ts

Adds a temporary fix to unblock https://github.com/kumahq/kuma-gui/pull/3883
There's work ongoing upstream so not totally sure if this will get in or be closed depending on the upstream work, lets see!
https://github.com/Kong/kongponents/issues/2753

fix(kongponents): cast components to Component for KRadio issue

---

renovate.json

chore(deps): change renovate release age to 5 days

---

renovate.json

chore(deps): a minimal renovate config

---

renovate.json

chore(deps): renovate adds bump strategy to replicate dependabot

---

packages/kuma-gui/src/app/common/SummaryView.vue
packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryView.vue
packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailTabsView.vue
packages/kuma-gui/src/app/data-planes/views/DataPlaneInboundSummaryOverviewView.vue
packages/kuma-gui/src/app/data-planes/views/DataPlaneSummaryView.vue
packages/kuma-gui/src/app/gateways/views/DelegatedGatewayDetailTabsView.vue
packages/kuma-gui/src/app/kuma/locales/en-us/index.yaml
packages/kuma-gui/src/app/services/views/MeshServiceDetailTabsView.vue
packages/kuma-gui/src/app/services/views/MeshServiceSummaryView.vue
packages/kuma-gui/src/app/services/views/ServiceDetailTabsView.vue
packages/kuma-gui/src/app/zone-egresses/views/ZoneEgressDetailTabsView.vue
packages/kuma-gui/src/app/zone-egresses/views/ZoneEgressSummaryView.vue
packages/kuma-gui/src/app/zone-ingresses/views/ZoneIngressDetailTabsView.vue
packages/kuma-gui/src/app/zone-ingresses/views/ZoneIngressSummaryView.vue
packages/kuma-gui/src/app/zones/views/ZoneDetailTabsView.vue

Cherry pick of https://github.com/kumahq/kuma-gui/pull/3954

feat: add status badge to titles (#3954)

---

package-lock.json
packages/kuma-gui/src/app/application/components/app-collection/AppCollection.vue

After cutting the branch for 2.11 we want a fresh start for 2.12.

chore: reset lock-file

---

.nvmrc
packages/config/src/mk/check.mk

Looks like renovate chokes on the comments we added in-place here.
I'm moved it back to the Makefile and simplified it a little

chore(deps): move instructions on installing nvm

---

packages/kuma-gui/public/mockServiceWorker.js

In https://github.com/kumahq/kuma-gui/pull/3936 we missed to update the worker script, causing an error. 
---
I'll try to add a post upgrade command to renovate, such that this won't happen again.

chore: update msw worker script

---

packages/kuma-gui/src/app/subscriptions/locales/en-us/index.yaml
packages/kuma-gui/src/app/subscriptions/views/SubscriptionSummaryView.vue
packages/kuma-gui/src/app/zones/locales/en-us/index.yaml
packages/kuma-gui/src/app/zones/views/ZoneConfigView.vue
packages/kuma-gui/src/app/zones/views/ZoneDetailView.vue

Adds several improvements detailed in the below issue.
Note: I have a follow up PR to this which further cleans some things up in the `...View.vue` file
Closes https://github.com/kumahq/kuma-gui/issues/3632

chore(subscriptions): improve nack overview

---

packages/kuma-http-api/index.d.ts
packages/kuma-http-api/openapi.yaml

Updates the types generated from latest oas changes.

chore(kuma-http-api): uppdate oas types

---

.github/renovate.json

chore(renovate): enable security updates

---

packages/kuma-gui/src/app/kuma/debug.ts

See title
Closes https://github.com/kumahq/kuma-gui/issues/3154

chore: only in dev and previews, link docs to /dev

---

packages/kuma-gui/public/mockServiceWorker.js

chore: upgrade MSW script

---

.github/workflows/sync-kuma-oas.yaml

- Uncomment `repository_dispatch`
- add concurrency to only run one sync at a time
- shorten kuma commit hash

chore(sync-kuma-oas): minor amends
