kumahq/kuma-gui

- features/mesh/policies/Index.feature
- src/app/policies/components/PolicyList.vue
Hides the legacy policy types in the policy type list view if there no legacy policies at all. Ignores MeshGateway policies which we always show.
> feat(policies): hide legacy policy types if there are no legacy policies

- .github/workflows/create-gui-pr.yml
Replaces tibdex/github-app-token with actions/create-github-app-token.
> ci: switch to create-github-app-token action

- src/app/data-planes/components/StandardDataplanePolicies.vue
- src/app/data-planes/data/index.ts
- src/test-support/mocks/src/policies.ts
Changes the processing of the _rules API data such that multiple proxyRules can be processed.
Resolve #2035.
> fix(dataplanes): only processing one proxy rule

- features/mesh/dataplanes/DataplaneDetailsStandardProxy.feature
- features/mesh/dataplanes/DataplaneDetailsTraffic.feature
- src/app/data-planes/components/data-plane-traffic/ServiceTrafficCard.vue
- src/app/data-planes/data/stats.ts
- src/app/data-planes/features.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneInboundSummaryOverviewView.vue
- src/services/kuma-api/ApiError.ts
This PR does several things:
1. Adds tags and addresses to the summary panel for an inbound
2. Re-jigs the stitching together of an inbound and its stats so that its possible to show part of the information in the viz without having loaded any `/stats` (or is the stats endpoint responds with an error)
3. Removes the feature flag we were using to show this now that we've replicated the same data in the summary panel
4. Removes the old inbounds table.
5. Adds basic e2e tests for making sure the viz is only visible for sidecars and erroring shows a warning instead of wiping out the viz entirely.
Q: I noticed that we aren't showing health state for the inbounds in the page anymore, you have to click on each of them to see if they are healthy or not. I think this is just a omission from design …
> feat(dataplanes): Traffic errors, remove traffic feature flag

- features/mesh/dataplanes/Index.feature
- package.json
- src/app/common/NavTabs.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/services/views/ServiceDataPlaneProxiesView.vue
- yarn.lock
**chore(KTabs): addresses breaking changes**
Renames `hasPanels` to `showPanels`.
Removes no longer needed styles.
**chore(KSelect): addresses breaking changes**
Removes `appearance` prop.
Renames several data-testid attributes.
Updates the styles of `.filter-select` elements so that the element doesn’t wrap onto a new line in the table actions bar.
---
Previous Kongponents v9 adoption PRs:
- https://github.com/kumahq/kuma-gui/pull/1532
- https://github.com/kumahq/kuma-gui/pull/1853
- https://github.com/kumahq/kuma-gui/pull/1878
> refactor: update Kongponents to KTabs/KSelect milestone

- features/mesh/dataplanes/DataplaneDetailsTraffic.feature
- src/app/data-planes/views/DataPlaneDetailView.vue
Ensure the `/stats` error warning shows even if there are no other warnings.
Expanded the test to make sure we produce this exact scenario. The test we show here was also tweaked as a result of an offine convo.
Just to note I'm waiting to move all the code into its own module before I `i18n` everything.
> fix(dataplanes): Always show stats error even if there are no warnings

- src/app/common/SummaryView.vue
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneInboundSummaryClustersView.vue
- src/app/data-planes/views/DataPlaneInboundSummaryStatsView.vue
- src/app/data-planes/views/DataPlaneOutboundSummaryClustersView.vue
- src/app/data-planes/views/DataPlaneOutboundSummaryStatsView.vue
- src/test-support/mocks/src/meshes/_/dataplanes/_/stats.ts
We noticed that the stats/clusters tabs when in the summary drawers are a little narrow, meaning that it's sometimes difficult to see the values as they are so far over to the right.
Following that we found that repeating the service names in the stats/clusters data in this view didn't really make sense and just led to more noise when trying to see stats/values.
This PR expands the summary drawer slightly only in this view, and also removes the service names from both stats and cluster output making it easier to see through the noise.
Theres potentially more thinking/design/work to be done here to improve this more, but for the moment this improves things.
> feat(dataplanes): removes service names the stats/cluster drawers in viz

- src/app/common/CopyButton.vue
- src/app/common/ResourceCodeBlock.vue
Fixes the copy icon color being wrong here:
> fix(CopyButton): incorrect copy icon color in ResourceCodeBlock

- features/mesh/dataplanes/DataplaneDetailsBuiltinGateway.feature
- features/mesh/dataplanes/DataplaneDetailsDelegatedGateway.feature
- features/mesh/dataplanes/DataplanePolicies.feature
- src/app/data-planes/components/BuiltinGatewayPolicies.vue
- src/app/data-planes/components/StandardDataplanePolicies.vue
- src/app/data-planes/views/DataPlanePoliciesView.vue
Changes the behavior of the Dataplane policies tab to show data based on the /_rules API for built-in gateways (i.e. rules-based data is now shown for _all_ Dataplane types).
Resolves #2034.
> chore(dataplanes): show rules-based policies for built-in gateways

- src/app/data-planes/views/DataPlaneInboundSummaryView.vue
- src/app/data-planes/views/DataPlaneOutboundSummaryView.vue
This ended up wrapped in a `class="stack"` somehow, 🤔 I guess I took the copied this from another summary panel then pasted the NavTabs into that.
At first this made no difference, but since we've upgraded KTabs this is making the space between the tabs and the content too big.
> fix: remove stack class from summary tabs view

- .github/workflows/codeql.yml
- .github/workflows/lifecycle.yml
See https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
> ci: set write permission on job-level only

- src/app/zone-ingresses/data/index.spec.ts
- src/app/zones/data/index.spec.ts
- src/test-support/data/index.ts
- src/test-support/index.ts
Note: we've already discussed this offline why this PR is a little weird and decided this was the best way for review.
---
I've kept 2 test files here:
1. My previous suite of tests for ZoneIngresses that I hadn't yet PRed. This approach had copy/pasted test utils and quite verbose table-like tests for testing the data transformations.
2. A different approach for Zones (that used to use the approach from point 1)
I'd like to use the new approach for the tests for Zones, ZoneIngresses and ZoneInsights for the following reasons (some of them already discussed offline and online here https://github.com/kumahq/kuma-gui/pull/1854#issuecomment-1839009146)
1. We are using our existing mocks for mock generation as our single source of truth.
2. We are avoiding copy pasting over and over our data …
> chore(tests): Reusable data layer test approach

- src/test-support/mocks/src/meshes/_/dataplanes/_/clusters.ts
> fix: fix `/cluster` mocks with newline join

- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/vue/index.ts
In the dataplane viz, if you have a summary drawer already open and you've changed tabs, when you click on a different card/inbound/outbound, keep the active tab the same.
This makes it easier to say click the `[Stats]` tab, and then click around inbounds/outbounds to see the stats without have to keep clicking the `[Stats]` tab.
There is probably more work to come off the back of this to make it more straightforwards to do this sort of thing.
> feat: keep the selected prev selected tab active when clicking 'bounds

- src/app/application/components/data-source/DataSource.spec.ts
- src/app/application/index.ts
- src/app/application/services/data-source/CallableEventSource.ts
- src/app/application/services/data-source/DataSourcePool.spec.ts
- src/app/application/services/data-source/DataSourcePool.ts
- src/app/application/services/data-source/SharedPool.ts
- src/app/application/services/data-source/index.ts
- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneInboundSummaryStatsView.vue
- src/app/data-planes/views/DataPlaneOutboundSummaryStatsView.vue
- src/app/data-planes/views/DataPlaneStatsView.vue
- src/app/me/sources.ts
- src/app/meshes/sources.ts
- src/app/policies/sources.ts
- src/app/services/sources.ts
- src/app/zone-egresses/sources.ts
- src/app/zone-ingresses/sources.ts
This PR ensures that clicking the summary drawer `[Refresh]` button in the dataplane viz will refresh the data both in the drawer and in the main viz.
There is a bit of refactoring work here as I noticed that, in the specific case where you have 2 of the exact same DataSources on the page _and_ you had a refresh button, clicking that button would not refresh. Pretty sure this is the first instance where we have this exact case. So whilst this DataSource syncing wasn't quite functioning correctly in this case, its not currently the source of a bug. But, it did prevent me from getting this working without having to do the work in this PR.
- `SharedPool` now works via a little state machine with distinct `creating`, `acquiring`, `releasing` and `destroying` states, which make this a lot …
> feat: sync refreshing between data viz and drawer

- src/test-support/mocks/src/meshes/_/dataplanes/_/_overview.ts
- src/test-support/mocks/src/meshes/_/dataplanes/_/clusters.ts
- src/test-support/mocks/src/meshes/_/dataplanes/_/stats.ts
Ensure `/stats` `/overview` and `/_overview` mocks are are synced by using the same seed for things we are interested in.
> fix(tests): ensure `/stats` `/overview` and `/_overview` mocks are are synced

- features/mesh/policies/Index.feature
- src/app/policies/components/PolicyList.vue
Fixes a misspelled policy type name in mock data causing a test to behave incorrectly. Also switches the assertion order to first check for element visibility.
> chore(policies): fix policy list test

- features/zones/zone-cps/egresses/Index.feature
- src/app/data-planes/data/index.ts
- src/app/subscriptions/data/index.ts
- src/app/zone-egresses/data/index.spec.ts
- src/app/zone-egresses/data/index.ts
- src/app/zone-egresses/views/ZoneEgressDetailView.vue
- src/app/zone-ingresses/data/index.spec.ts
- src/app/zone-ingresses/data/index.ts
- src/app/zone-ingresses/views/ZoneIngressDetailView.vue
- src/types/index.d.ts
ZoneIngresses and ZoneEgress have been a little behind what we did for the data layer in regards to `Subscriptions` as they were waiting on https://github.com/kumahq/kuma-gui/pull/1910.
This PR uses the work that was done to create `Subscriptions`, in doing this it ensures `subscriptions` are all the same throughout the application.
Note: I noticed that of the 4 `isSet` occurrences mentioned in https://github.com/kumahq/kuma-gui/pull/1918#issuecomment-1887197713, in reusing `Subscriptions` this PR was able to remove 2 of those, leaving just the one duplication.
Closes https://github.com/kumahq/kuma-gui/issues/1674
> chore(zones): fill out zone'gress types and reuse SubscriptionCollection

- .eslintrc.js
- src/app/application/components/data-collection/DataCollection.vue
- src/app/application/components/data-collection/README.md
- src/app/application/components/route-view/RouteView.vue
- src/app/application/index.ts
- src/app/data-planes/components/data-plane-traffic/ServiceTrafficCard.vue
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneInboundSummaryView.vue
- src/app/data-planes/views/DataPlaneOutboundSummaryView.vue
- src/test-support/mocks/src/meshes/_/dataplanes/_/stats.ts
Feature-wise this PR:
- Adds EmptyStates/EmptyBlocks to the DPP viz (which we also use for the "in-viz ErrorState")
- Adds a Loading spinner into the Outbounds column
- Reduces the amount of re-renders of the DPP viz when clicking ono the Cards
To do this I made a new component called `DataCollection` which:
- Provides a component for filtering/finding, sorting (and pagination outside of a AppCollection table should we need that) and also a default EmptyState for empty collections (which is slottable)
- Replaces some of our usage of `<template v-for="">`
I've moved the finding of the exact 'item' we need to show in the drawer to the drawer itself.
I've done this because we need to use `route.params.service` in order to find the 'item'. Moving the find (and the dependency on …
> feature: add DataCollection component and use it for Dataplane viz

- src/app/data-planes/components/data-plane-traffic/ServiceTrafficCard.vue
Fixes an issue where clicking on the on a `<b>` tag within a `<a>` tag (which occurs in our TagList component) could produce an error in the javascript console.
Closes https://github.com/kumahq/kuma-gui/issues/2084
> fix(dataplanes): avoids console.error when clicking a service

- .eslintrc.js
- src/app/application/components/data-collection/DataCollection.vue
- src/app/application/components/data-collection/README.md
- src/app/application/components/route-view/RouteView.vue
- src/app/application/index.ts
- src/app/data-planes/components/data-plane-traffic/ServiceTrafficCard.vue
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneInboundSummaryView.vue
- src/app/data-planes/views/DataPlaneOutboundSummaryView.vue
- src/test-support/mocks/src/meshes/_/dataplanes/_/stats.ts
Backport of #2071 to the 2.6 release branch
---
Feature-wise this PR:
- Adds EmptyStates/EmptyBlocks to the DPP viz (which we also use for the "in-viz ErrorState")
- Adds a Loading spinner into the Outbounds column
- Reduces the amount of re-renders of the DPP viz when clicking ono the Cards
To do this I made a new component called `DataCollection` which:
- Provides a component for filtering/finding, sorting (and pagination outside of a AppCollection table should we need that) and also a default EmptyState for empty collections (which is slottable)
- Replaces some of our usage of `<template v-for="">`
I've moved the finding of the exact 'item' we need to show in the drawer to the drawer itself.
I've done this because we need to use `route.params.service` in order to find the 'item'. …
> backport: feature: add DataCollection component and use it for Dataplane viz

- src/app/data-planes/components/data-plane-traffic/ServiceTrafficCard.vue
Backport of https://github.com/kumahq/kuma-gui/pull/2085 to the 2.6 release branch
---
Fixes an issue where clicking on the on a `<b>` tag within a `<a>` tag (which occurs in our TagList component) could produce an error in the javascript console.
> backport: fix(dataplanes): avoids console.error when clicking a service

- src/app/application/utilities/index.ts
I noticed during conversations on other PRs that the class on our rootNode was changing more frequently than it needed to. 
You can see this is you open web inspector and watch the rootNode `class="kuma-ready"` class whilst clicking around the application.
This PR prevents it "changing" when it doesn't need to.
> fix: unnecessary rootNode class changes

- src/app/data-planes/data/index.ts
- src/app/zones/data/index.ts
- src/utilities/isSet.ts
Moves the status determination logic back into its own function.
Moves the duplicated `isSet` function into its own utility file.
> refactor(dataplanes): clean-up getStatus function

- package.json
- public/mockServiceWorker.js
- src/services/development.ts
- src/test-support/index.ts
- test-support/index.ts
- test-support/main.ts
- yarn.lock
Upgrades MSW to 2.x.x
Whilst doing this I figured I may as well entirely remove our MSW usage in our CLI unit tests. We only used this a while back to get started and now all our tests that need some sort of un-injectable fetch functionality are now using e2e/Cypress/intercept, whereas all our unit tests are injectable with something deeper in than having to use a worker or fetch-shim.
MSW is now only used/available for local development and PR previews.
There's probably some more work I could do here to pull MSW out into its own 'plugin' like we do with `@/app/vue`, but I figured I'd get this in first and look at that later (pulling it out into its own 'plugin' would help with https://github.com/kumahq/kuma-gui/issues/2001)
Note: Probably quite an important change here is that we no …
> chore: upgrade MSW to version 2.x.x

- .github/workflows/codeql.yml
- .github/workflows/create-gui-pr.yml
- .github/workflows/dispatch-merged-pr-notification.yml
- .github/workflows/main.yml
Replaces all version identifiers for third party actions with commit hashes and the appropriate version comment (Dependabot updates the comment as well). This ensures that we get Dependabot updates for new non-major versions of actions instead of silently opting into using them.
> ci: uses commit hashes for third party action versions

- features/mesh/policies/Index.feature
- src/app/policies/views/PolicyListView.vue
Add a content-based assertion in the middle of the "Clicking the link goes to the detail page and back again" so that the "navigate" + "assert URL" + "navigate" chain doesn’t trigger the missing route params error.
Remove the `key` attribute from `PolicyList`. It no longer seems needed to trigger a re-render when switching between policy types.
> chore(policies): fix flaky list view test

- test-support/main.ts
I spotted some more code that we could remove from our unit test runner, plus this code was a little weird when we needed to add it so I good thing to get rid of
> chore(tests): remove some dead code from our unit test runner

- src/app/application/services/data-source/index.ts
A little while back in https://github.com/kumahq/kuma-gui/pull/1525 we added automatic types to our sources
> `"/services/:name": (params) => { params.name }`
The thing I didn't realise at the time was we had lost the return type of the source.
This PR corrects that so now the sources have automatic types for their URI based parameters, plus the resulting return types are correct for each individual source. Now this is correct it means we can start looking at automatically passing these through to our DataSources so that the URIs auto-complete and the emitted data from the DataSources correctly corresponds to the URIs (see https://github.com/kumahq/kuma-gui/issues/1474)
---
I've not gone ahead and rolled this out as yet, but I'd like to after this PR has gone in in a separate PR. In the …
> chore: ensure defineSources returns the correct return types

- src/app/zones/data/index.ts
- src/app/zones/views/ZoneListView.vue
Simplifies the 'knitting' of Zones and their Proxies by using connectedSubscription.
I think this is the last place where we had a subscription inspection without using our new `Subscription` data layer things. See https://github.com/kumahq/kuma-gui/issues/1890
---
Separately, I spent a lot of time trying to get typescript to understand `Object.groupBy` and/or a type safe polyfill for it, which would simplify this even more and use even less of our own code, but I kinda gave up trying. I can come back to that at a later date. edit: I didn't PR this branch straight away for reasons, and luckily I found out today `Object.groupBy` is coming to typescript in the next release in around a month or so, so I'll wait for that. I still have a branch or stash here with the native `Object.groupBy` …
> chore(zones): update zones/proxies to use connectedSubscription

- src/app/application/components/data-source/DataSource.spec.ts
- src/app/application/components/data-source/DataSource.vue
- src/app/application/index.ts
- src/app/application/services/data-source/Router.ts
- src/app/application/services/data-source/SharedPool.ts
- src/utilities/index.ts
- test-support/main.ts
1. Calling `refresh` will now no longer fire off a new request if there is already one in-flight (this is shared, so it could be the same URI but across different instances of a DataSource).
2. data URI support. Sometimes its handy to be able to get the characteristics of a DataSource by just passing it some JSON (via a data URI), i.e. for caching, sharing, tests or docs. Just to note this should mostly only be used for testing/docs purposes.
Part of https://github.com/kumahq/kuma-gui/issues/1474
> chore(datasource): Various DataSource component improvements

- features/zones/Delete.feature
- package.json
- src/app/common/DeleteResourceModal.vue
- src/app/zones/components/ZoneActionMenu.vue
- src/app/zones/views/ZoneCreateView.vue
- src/app/zones/views/ZoneListView.vue
- yarn.lock
**chore(KModal): address breaking changes**
Rename `props.isVisible` to `props.visible`.
Rename `canceled` event to `cancel`.
Remove `header-content` slot use as it’s not needed anymore. The `props.title` string will be used automatically.
Change `body-content` slot to default slot.
Change `action-buttons` slot to `footer-actions` slot.
**chore(KPrompt): address breaking changes**
Rename `props.isVisible` to `props.visible`.
Rename `canceled` event to `cancel`.
Change `body-content` slot to default slot.
**chore(zones): remove divider from single item dropdown item**
---
Previous Kongponents v9 adoption PRs:
- https://github.com/kumahq/kuma-gui/pull/1532
- https://github.com/kumahq/kuma-gui/pull/1853
- …
> refactor: update Kongponents to KModal/KPrompt milestone

- features/main-overview/DetailViewContent.feature
- features/onboarding/dataplanes-overview/Index.feature
- features/zones/zone-cps/egresses/Item.feature
- features/zones/zone-cps/ingresses/item/Index.feature
Add explicit `KUMA_SUBSCRIPTION_COUNT` values to tests mocking `subscriptions` with _partial_ objects. If a mocked API has fewer subscriptions (determined by a faker-js dice roll) than what a test mocks out, we can run into errors like "Cannot read lastUpdateTime from undefined". That happens when the extra objects from the test have partial data (like not mocking out `status` in the case of the above error). I added more variables than necessary (as we usually create at least one subscription object and so tests only adding one don’t flake) so we’re on the safe side.
> chore: fix flaky tests relying on incomplete subscription mock data

- src/app/zones/components/ZoneCreateKubernetesInstructions.vue
- src/app/zones/components/ZoneCreateUniversalInstructions.vue
Whilst this bug doesn't present here it does elsewhere, although even then in a place that doesn't matter.
It gave a me a bit of a fright and I took a while to confirm it was having any user facing effect. Even so I figured that even though it's not a user facing bug it would be best to fix it up.
---
Uses and inline/ternary conditional which makes it very difficult to leave a variable as unset/undefined by accident. I also considered some typescript here, but seeing as this parameter value shouldn't really be here, doing it this way will make it easier to rework at a later date whilst maintaining a similar degree of safety that the inline ternary offers.
> fix(zones): ensure unset ZoneCreate i18n variable is set

- .env.development
- .env.preview
- cypress/support/step_definitions/visit.ts
- features/application/Upgrade.feature
- package.json
- src/app/kuma/components/ApplicationShell.vue
- src/services/env/Env.ts
- src/test-support/mocks/kuma.io/latest_version.ts
- vite.config.preview.ts
The fix and the comment in the code probably explains this PR the best, please ask if its not clear tho.
I'll inline comment the fix as there is also the version bump in here.
Tangent: Ideally this version needs to be in one place (in the package.json file), so I should be moving to do that at some point soonish.
> fix: prevents a blinking upgrade alert

- src/app/application/index.ts
Adds a simplistic structuredClone polyfill using JSON.stringify/parse clone. Purposefully avoids a full fledged polyfill but happy to add that if folks think we need that short term.
Manually tested in Firefox 93.
> fix: adds simplistic structuredClone polyfill

- features/mesh/policies/Index.feature
- src/app/policies/components/PolicyList.vue
- src/app/policies/views/PolicyListView.vue
fix(policies): add regression test for columns not always showing correctly
fix(policies): columns not always showing correctly
Trigger a re-render of AppCollection when the current policy type changes to make sure the table re-renders with the correct columns.
refactor(policies): move route access into list view
> fix(policies): columns not always showing correctly

- yarn.lock
Update the transitive dependency `@badeball/cypress-configuration` from 6.1.0 to 6.1.1 to avoid a dependency on an older esbuild version that has critical vulnerabilities reported. This was done using the following commands:
```sh
yarn add --dev @badeball/cypress-configuration@6.1.1
npx yarn-deduplicate
yarn remove @badeball/cypress-configuration
```
> chore(deps-dev): update transitive cypress-configuration dependency

- src/app/common/TagList.vue
Ideally I'd like TagList to work differently, but for now this prevents any `kuma.io/zone` tags from linking to a potentially non-existent page, a bit surprised we've not seen this earlier, which makes me think I might be missing something 🤔 
I guess in reality, zone tags wouldn't exist on old style standalone, but guessing that in single-zone mode things might be tagged with the name of the single zone.
---
**Edit: 5th Feb**
It looks like my guess here turned out to be correct:
>> but guessing that in single-zone mode things might be tagged with the name of the single zone.
It looks like when in "non-federated zone mode" we do get `kuma.io/zone` tags (set to `default`), which means if we try to link to the Zone detail page (using `default` as the zone name) then we will get an error …
> fix(zones): If there are no zone details pages, don't link a tag to one

- src/app/application/components/data-collection/DataCollection.vue
- src/app/data-planes/components/DataPlaneSummary.vue
- src/app/data-planes/data/index.ts
- src/app/data-planes/data/stats.ts
- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
Various amends for the Dataplane Gateway Viz
- Adds an `inboundName` and `inbound[].name` properties at the data layer level (see https://github.com/kumahq/kuma-gui/pull/2082#discussion_r1466188690)
- Fills in a single inbound for built-in gateways based on inferring the data from the tags of the gateway, again in the data layer. This is only temporary, gateways can have multiple inbounds.
- Using the above, removes the duplication/fork in `DataPlaneDetailView` for showing the Traffic components. This also has the benefit that all the empty/loading/error states work the same as the view when we are viewing a sidecar/standard dataplane.
- Replaces the hardcoded `HTTP` protocol for the current single gateway inbound with the correct protocol from the stats endpoint.
- Replaces instances of …
> chore: various amends for gateway data-viz

- package.json
- src/app/common/code-block/ResourceCodeBlock.vue
- src/app/data-planes/components/DataPlaneSummary.vue
- src/app/data-planes/views/DataPlaneDetailView.vue
- yarn.lock
**chore(KTooltip): address breaking changes**
Replace `label` with `text` prop.
Removes `props.positionFixed` as its default value is now `true`.
---
Previous Kongponents v9 adoption PRs:
- https://github.com/kumahq/kuma-gui/pull/1532
- https://github.com/kumahq/kuma-gui/pull/1853
- https://github.com/kumahq/kuma-gui/pull/1878
- https://github.com/kumahq/kuma-gui/pull/1961
- https://github.com/kumahq/kuma-gui/pull/2118
> refactor: update Kongponents to KTooltip milestone

- .env
- features/mesh/builtin-gateways/Index.feature
- features/mesh/builtin-gateways/Item.feature
- features/mesh/delegated-gateways/Index.feature
- features/mesh/delegated-gateways/Item.feature
- features/mesh/external-services/Index.feature
- features/mesh/external-services/Item.feature
- features/mesh/services/Item.feature
- src/services/production.ts
- src/shims-env.d.ts
Enable the KUMA_GATEWAYS_UI in all environments by default.
Enable all tests relying on `KUMA_GATEWAYS_UI` being enabled and adjust existing tests.
> chore: enable KUMA_GATEWAYS_UI feature flag

- src/app/common/ErrorBlock.vue
- src/app/zones/views/ZoneCreateView.vue
- src/test-support/mocks/src/zones/_/_overview.ts
Change the error handling of the Zone creation flow’s polling step to use our ErrorBlock component. This way, error details of any underlying API error will be surfaced in the UI.
> fix(zones): error handling in creation flow polling

- src/app/data-planes/components/data-plane-traffic/ServiceTrafficCard.vue
- src/app/data-planes/data/stats.spec.ts
- src/app/data-planes/data/stats.ts
- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneInboundSummaryStatsView.vue
- src/app/data-planes/views/DataPlaneInboundSummaryView.vue
Continuation of https://github.com/kumahq/kuma-gui/pull/2151
> All in all while we still don't show multiple inbounds if there are any, and the protocol for the outbounds could be wrong. I figured there was enough improvement here (no duplication, better states, no Cluster protocol etc) to PR something and continue with these issues.
So this is continuing mainly with multiple inbounds on gateways, but also showing non-zero values for the gateways outbounds.
---
Various fixes for the built-in gateway dataplane viz. I've tried to fix by continuing to normalize the way that we figure out stats/inbound/outbounds for both sidecars and gateways. I might add some inline comments 🤔 
- Supports multi inbounds to gateways in the dataplane viz
- Fixes showing any stats in the outbounds cards for …
> chore: various amends for gateway data-viz pt2

- src/app/application/components/route-view/RouteView.vue
- src/app/gateways/locales/en-us/index.yaml
- src/app/gateways/views/GatewayListTabsView.vue
Exposes a `RouteView::route.children` so that we can easily make different types of tab-like UI interfaces automatically based on our route config, which in turn means we can completely define this sort of sub navigation from The Outside.
This PR then uses that for the `LinkBox` in `GatewayListTabsView`, but the functionality could also be re-used for all sorts of similar sub navigation widgets.
Note: Whilst DataCollection `predicate` functionality isn't being used here, as DataCollection shows nothing if `items` is zero length, this means that if we configured our router to have no children here, the tab interface would automatically not show/render at all.
> chore: exposes RouteView::route.children and use for GatewayTabs

- .eslintrc.cjs
- src/app/application/components/data-source/DataLoader.vue
- src/app/application/index.ts
- src/app/data-planes/views/DataPlanePoliciesView.vue
- src/app/diagnostics/views/DiagnosticsDetailView.vue
- src/app/meshes/views/MeshListView.vue
Adds a new `DataLoader` component, which is can be used as a bit of a "DataSource-with-loading-and-error-states" or a "DataSource-with-dependant-data-and-errors" or a mix of the two.
This is a little bit of a WIP in that I 'think' this is the API I want, I've purposefully used it in three areas to try it out and get a feel for it:
1. A simple 'item' view in Diagnostics, where I pretty much just want a DataSource with automatic loading and error states.
2. A listing that has a visual skeleton in our Mesh listing, where I pretty much just want a DataSource with just an error state (the loading state is contained in the visual we feed the data to)
3. A more complex UI (DataPlanePolicy view) where we load in several sets of data which are sometimes dependant on each other but sometimes not, …
> chore: add DataLoader component

- src/app/data-planes/data/index.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
Enables the dataplane viz for delegated gateways.
This was pretty much just removing the guard we had in-place to not show the viz for delegated gateways. I also added an EmptyState message to explain why you don't see any inbounds.
All in all, this PR is one of those ones that looks more than it actually is due to nesting changing.
Closes https://github.com/kumahq/kuma-gui/issues/2134
> feat: add dataplane viz for delegated gateways

- src/app/application/components/route-view/RouteView.vue
- src/app/application/utilities/index.ts
Changes the type of `attrs` values being passed around to `Partial<Record<string, string>>` to make type errors when accessing data based on empty records (i.e. `{}` as opposed to `{ class: '...' }` visible.
Fix the unsafe passing of `flat.class` to the `difference` function leading to a `Cannot read properties of undefined (reading 'includes')` error.
> fix: make attrs utilities more type-safe

- src/app/data-planes/views/DataPlaneInboundSummaryView.vue
- src/app/data-planes/views/DataPlaneOutboundSummaryView.vue
Ensures that the `?inactive` toggle is persisted in the URL when clicking between drawer tabs.
> fix(dataplane): maintain viz inactive state in the URL when changing tabs

- features/mesh/services/Item.feature
- src/app/services/locales/en-us/index.yaml
- src/app/services/sources.ts
- src/app/services/views/ServiceDetailView.vue
- src/services/kuma-api/KumaApi.ts
- src/types/api.d.ts
Add an empty state when not finding the matching ExternalService to the service detail view.
Change the `size` parameter for the ExternalService lookup to 1000 to make it less likely not to find the right resource.
Change the ExternalService lookup to send a tag instead of a name parameter. The name parameter was incorrect anyway (but also not working as the Kuma API in 2.4.x doesn’t support it) as it filters by ExternalService name and not by ExternalService kuma.io/service tag. Note that the Kuma API doesn’t support the `tag` parameter in release-2.4 so this is only a forward-compatibility layer in case we want to fix this issue properly.
Relates to https://github.com/kumahq/kuma/issues/9293.
> fix(services): external service lookup crashing in detail view

- .eslintrc.cjs
- src/app/application/components/app-view/AppView.vue
- src/app/application/components/route-view/RouteView.vue
- src/app/application/components/route-view/index.ts
- src/app/x/components/x-teleport/XTeleportSlot.vue
- src/app/x/components/x-teleport/XTeleportTemplate.vue
- src/app/x/index.ts
- src/services/production.ts
Adds a small eXtra wrapper eXtension around Vue's teleport:
1. Vue's teleport is a bit weird in that one side is JS/Vue and the other is DOM i.e. `:to` is a DOM selector.
2. Having an explicit XTeleportSlot to put things in rather than just a DOM element makes it way clearer that the element is needed (see https://github.com/kumahq/kuma-gui/pull/2184#pullrequestreview-1896198851 and https://github.com/kumahq/kuma-gui/pull/1729).
3. Having a wrapper means we can validate things exist, and probably in the future add get a bit tighter with the coupling of templates/slots (i.e. we could keep a record of existing slots somewhere)
4. I've also made the previous `actions` "DOM based teleport slot" unique per `RouteView`. Previously there could be multiple DOM teleport slots called `actions` (I …
> feat: add XTeleport* components

- features/application/MainNavigation.feature
- src/app/application/components/route-view/RouteView.vue
Fixes a small regression by ensuring that the correct tab is selected.
I took the code we had back in https://github.com/kumahq/kuma-gui/blob/a8550b9aafb6ce2a1dfcef82d981309605bba26d/src/app/application/components/route-view/RouteView.vue#L28 
and also added a couple of extra tests to prevent further regression
> fix: ensure correct tab is selected on page load

- features/application/MainNavigation.feature
- features/mesh/dataplanes/DataplaneSummary.feature
- features/mesh/policies/PolicySummary.feature
- features/zones/zone-cps/egresses/ZoneEgressSummary.feature
- features/zones/zone-cps/ingresses/ZoneIngressSummary.feature
- package.json
- src/app/common/SummaryView.vue
- src/app/common/TagList.vue
- src/app/policies/views/PolicySummaryView.vue
- yarn.lock
This milestone adds a `title` slot to `KSlideout` which we should be making use of. This caused a bit more refactoring work of how we currently handle summary trays.
---
**chore(KTruncate): address breaking changes**
Rename `.k-truncate-container` to `.truncate-container`.
**chore(KSlideout): address breaking changes**
Replace `isVisible` with `visible` prop.
Replace `preventCloseOnBlur` with `:closeOnBlur="false"`.
Update custom styles to address changes in markup and layout.
**refactor(SummaryView): use KSlideout title slot**
Delete unused summary code in the mesh and zone list views.
Move the use of SummaryView from the parent views into the concrete *SummaryView components. The primary reason for this change is that this allows us to use the `title` slot of KSlideout. Not using it …
> refactor: update Kongponents to KSlideout/KTruncate milestone

- features/mesh/builtin-gateways/Item.feature
- src/app/gateways/locales/en-us/index.yaml
- src/app/gateways/routes.ts
- src/app/gateways/views/BuiltinGatewayConfigView.vue
- src/app/gateways/views/BuiltinGatewayDetailView.vue
Follow up to #2211.
Replace the Affected DPPs section in the built-in gateway detail view with a regular Dataplane list.
Resolves #2210.
> feat(builtin-gateways): turn affected DPPs into dataplane list

- src/main.ts
Add a custom error handler to the Vue application that, by default, behaves like the standard error handling (i.e. any Vue realm errors are re-thrown). Specifically for the vue-router errors corresponding to "Matcher not found" errors, it adds a custom error message to the `Error` object because, for some reason, vue-router strips this out in production builds and makes troubleshooting unnecessarily hard.
> chore: add custom error handler for matcher not found router errors

- features/application/MainNavigation.feature
- src/app/connections/data/index.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
Looks at the stats values to try to figure out whether a service is http or not. See inline comments for a little more info.
> chore: sniff the protocol of unknown outbounds

- src/app/application/components/data-collection/DataCollection.vue
- src/app/application/components/data-source/DataLoader.vue
- src/app/application/index.ts
Typo in https://github.com/kumahq/kuma-gui/pull/2126 `errors` > `error`.
DataLoader should export the same shape as DataSource
> fix: DataLoader exported errors > error

- src/app/application/components/app-view/AppView.vue
- src/app/common/SummaryView.vue
Make use of KSlideout's new title slot and gradually remove old CSS.
There's a little CSS left here in SummaryView, but I'm extremely likely to move that into AppView at some point soon, which means SummaryView will have no CSS whatsoever.
> chore: make use of KSlideout's new title slot

- src/app/application/components/data-source/DataLoader.vue
- src/app/gateways/views/BuiltinGatewayDetailView.vue
- src/app/gateways/views/DelegatedGatewayDetailView.vue
**chore(DataLouder): make data and errors optional**
Make the `data` and `errors` prop so users of DataLoader can actually not provide them.
Remove the unused default value from the `src` prop. Providing an empty source should require an explicit action on the usage side.
**refactor(gateways): use DataLoader for detail views**
> refactor(gateways): use DataLoader for detail views

- src/app/application/components/app-collection/AppCollection.vue
- src/app/application/components/data-collection/DataCollection.vue
- src/app/data-planes/components/RuleEntryList.vue
- src/app/data-planes/components/StandardDataplanePolicies.vue
- src/app/data-planes/data/index.ts
- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlanePoliciesView.vue
- src/test-support/mocks/src/meshes/_/dataplanes/_/_rules.ts
Refactors the 'Rule' objects to use a similar `Rule.fromObject/fromCollection` interface of our data layer.
We'll be using these objects in the dataplane viz side panels soon, so wanted to get familiar with the shape of things as well as move things over to our `toObject` interfaces.
The shape of these has changed slightly in that we just produce a big list of `rules` then filter/pick what we want from those in the view.
I guess there will be a file move PR to come after this, but I wanted to avoid renaming and moving files around too much in a PR with this amount of change in it.
> refactor(policies): refactor of the rules API data transformations

- src/app/application/components/route-view/RouteView.vue
- src/app/application/utilities/index.ts
Surfaces the supported attributes for `RouteView::attrs` (we only support `class` right now)
Also see https://github.com/kumahq/kuma-gui/pull/2213
> chore: surface typescript types for RouteView::attrs

- features/application/MainNavigation.feature
- features/mesh/policies/Data.feature
- package.json
- src/app/application/components/app-collection/AppCollection.vue
- src/app/application/components/app-view/AppView.vue
- src/app/application/components/data-collection/DataCollection.vue
- src/app/common/DeleteResourceModal.vue
- src/app/common/DocumentationLink.vue
- src/app/common/EmptyBlock.vue
- src/app/common/ErrorBlock.vue
- src/app/common/LoadingBlock.vue
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneSummaryView.vue
- src/app/kuma/components/ApplicationShell.vue
- src/app/kuma/views/KumaNotFoundView.vue
- src/app/onboarding/components/OnboardingAlert.vue
- src/app/policies/views/PolicySummaryView.vue
- src/app/services/views/ServiceConfigView.vue
- src/app/services/views/ServiceDetailView.vue
- src/app/subscriptions/components/SubscriptionDetails.vue
- src/app/zone-egresses/views/ZoneEgressSummaryView.vue
- src/app/zone-ingresses/views/ZoneIngressSummaryView.vue
- src/app/zones/views/ZoneConfigView.vue
- src/app/zones/views/ZoneCreateView.vue
- src/locales/en-us/common/index.yaml
- yarn.lock
**chore(KAlert): address breaking changes**
Use default slot instead of `alertMessage` slot.
Rename the `is-dismissibile` prop to `dismissible` (also remove two instances that didn’t have the corresponding close handling).
Rename `closed` event to `dismiss`.
Rename the `alertIcon` slot to `icon`.
Remove the `size` prop.
**chore(KPagination): address breaking changes**
**chore(KEmptyState): address breaking changes**
Replace the `cta-is-hidden` prop with `:action-button-visible="false"`.
Remove the use of the `icon` and `iconSize` prop. There is no longer a way to use the Kongponent "state" icons like `stateNoData` with KEmptyState so I removed it from our use of the component.
Replace the use of the `title` slot with providing the `title` prop. This required changing out ErrorBlock and …
> refactor: update Kongponents to KAlert/KEmptyState/KPagination milestone

- src/app/connections/views/ConnectionInboundSummaryOverviewView.vue
Note: This PR may or may not change depending when https://github.com/kumahq/kuma-gui/pull/2276 goes in, as I think https://github.com/kumahq/kuma-gui/pull/2276 gives lets us expand on this easier.
This PR adds the policy rules for standard dataplane inbounds to the summary panel:
Please let me know if there are any other suggestions for presenting this visually.
Similar visuals for policy rules for gateway inbounds are still to come (see above note on https://github.com/kumahq/kuma-gui/pull/2276), as are rules for when you click on outbounds (which I think will need separate information from the service insight endpoint which we don't request as yet)
> feature(dataplanes): add inbound rules to the summary panel

- src/app/data-planes/components/PolicyTypeEntryList.vue
- src/app/data-planes/views/DataPlanePoliciesView.vue
- src/app/policies/sources.ts
Whilst playing around with kuma I spotted a bug when using non-federated/single-zone mode where we show a legacy policies section but we don't show an empty state, and instead its just a blank space which looks broken:
I noticed that this was for "sidecar" dataplanes only, "gateway" dataplanes where showing an empty state, but I decided to add a KCard around the empty state in both places so there is a little change there also to make them consistent.
Theres a question about whether we should show the "Legacy Policies" block at all if its empty, but seeing as we do for gateway dataplanes I decided at least for the moment to continue to show it.
I stopped short of doing a bit more work here as I know there is work in progress that is altering this code for different reasons, but there is …
> fix(policies): ensure legacy policies section has an empty state

- package.json
- src/app/application/index.ts
- src/app/data-planes/components/RuleEntryList.vue
- src/app/data-planes/components/StandardDataplanePolicies.vue
- yarn.lock
Now Typescript comes with built-in declarations for `Object.groupBy` its a little less annoying to polyfill use Javascript's `Object.groupBy`, also see the description in https://github.com/kumahq/kuma-gui/pull/2128.
This PR adds a polyfill and uses it an a couple of places where conversations have arisen lately. most of the change here is as a result of a re-nest, but the code that came up in past conversations is now just a one-liner.
There are a few places I'll be switching this in at some point (including the code in above linked PR)
I tested the polyfill manually in Firefox 118.
> chore: Object.groupBy polyfill

- src/app/data-planes/components/RuleEntryList.vue
In https://github.com/kumahq/kuma-gui/pull/2247 we moved the Rules accordion pane tables to use AppCollection instead of KTable, which mistakenly overrode some specific CSS font/coloring rules.
This PR adds that styling back in.
> fix(policies): fixes specific `!` and `and` CSS coloring for matchers

- src/app/application/components/app-collection/AppCollection.vue
- src/app/connections/views/ConnectionInboundSummaryOverviewView.vue
- src/app/data-planes/components/RuleEntryList.vue
- src/app/rules/components/RuleMatchers.vue
- src/test-support/fake.ts
- src/test-support/mocks/src/meshes/_/dataplanes/_/_rules.ts
~Requires https://github.com/kumahq/kuma-gui/pull/2287 for the `Object.groupBy` polyfill.~ This is now merged
Adds matchers and origins to the rules in the summary panel for sidecar inbounds.
Likely to be some design amends as a follow up.
> feature(dataplanes): adds matchers and origins to rules in panel

- src/app/connections/views/ConnectionInboundSummaryClustersView.vue
- src/app/connections/views/ConnectionInboundSummaryStatsView.vue
- src/app/connections/views/ConnectionInboundSummaryView.vue
- src/app/connections/views/ConnectionOutboundSummaryClustersView.vue
- src/app/connections/views/ConnectionOutboundSummaryStatsView.vue
- src/app/connections/views/ConnectionOutboundSummaryView.vue
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneStatsView.vue
Moves stats/clusters  to use `DataLoader` and `DataCollection`. DataCollection has an "auto empty state", so if no matching lines are found, then instead of getting an empty code editor we can an empty state instead.
I also changed the URI for the DataLoaders to use the `.../stats/ip-address` here so things synced up correctly. This also meant that I had to re-nest some `template`s in `DataPlaneDetailView`. Therefore it looks like there is loads of change in that file when actually its pretty much just a re-nest, there is one tweak in that file but I'll inline comment to point that out.
Closes https://github.com/kumahq/kuma-gui/issues/2303
> chore: moves connection stats/clusters to use DataLoader/DataCollection

- features/mesh/dataplanes/DataplanePolicies.feature
I've spotted a couple of new flakes lately, this test one of them.
The mock here mocked out a HTTP endpoint that didn't seem to be being called at all. So I've removed that and added some `_COUNT` env vars that should always give us the data we are looking for the test.
This seems to stabilise this test, but there are still a couple of others that have popped up. Hopefully I get figure those out after this one which seems to be the most flakey.
I also applied this here https://github.com/kumahq/kuma-gui/pull/2316 after this test flaking multiple times there, and its seems to have fixed the flake.
> fix(tests): unflake built-in gateway policy test

- src/app/application/services/i18n/I18n.ts
- src/locales/en-us/common/index.yaml
- src/services/env/Env.ts
Quite a while back we started using an i18n lib/util for all our strings instead of env vars. We never really finished moving everything seeing as there was no real need/urgency to.
At some point I want to refactor our env util (behind the `env('URI')` interface) and make it easier to work with, so the more I can clean up things that should no longer be in `env` first the better.
> chore: moves UTM query params to i18n

- src/test-support/vite.ts
- vite.config.production.ts
Part of https://github.com/kumahq/kuma-gui/issues/2001
I've been tweaking some rather complicated cross-file synced mocks. Usually, because we use MSW, in order to see the result of any changes you have to find a page that uses your mock, refresh you browser window, open the Web Inspector and then search through the many HTTP requests for the mock you are changing. The last step you have to do again and again and again for every change, which gets a bit tedious.
This PR serves up the mocks via `vite`, this means you can go directly to the URL of the mock you are editing and just refresh the browser to see your changes as you usually would.
---
Notes:
To try this out you need to set `KUMA_API_URL=http://localhost:8080`. `8080` being the port that vite is using, and also set …
> chore: adds vite plugin for serving mocks locally

- src/app/onboarding/components/ControlPlaneStatusWithOnboarding.vue
"You currently have no DPPs" message stays after DPPs are created. It looks like this message was keying off 'meshes' rather than 'dataplanes'?
> fix: onboarding dpp logic

- src/app/connections/views/ConnectionInboundSummaryOverviewView.vue
- src/app/connections/views/ConnectionOutboundSummaryOverviewView.vue
With the dataplane summary drawers we show the rules per inbound/outbound.
This PR groups the rules by rule type, and puts each grouping into an accordion pane.
---
Currently I purposefully used the components we currently have, even thought the design of this is quite what we want.
There'll be a follow-up PR refactoring some of the components used here so we can alter the design a little, but I guess that will effect other areas of the UI that also use these components, so I wanted to do that separately.
> chore(rules): group rules by type

- features/mesh/services/Index.feature
- src/app/application/components/app-collection/AppCollection.vue
Fixes (🤞 ) flakey service insight by mocking the serviceType to be `internal`
---
I found that the above change still produced the flake, then I also remembered that we also have a very similar flake in `policies / index` which made me look for commonalities that might cause both tests to occasionally flake, which points to KTable.
After looking at KTable's source I've tried adding an additional guard in our own `AppCollection` which should avoid any potentially incorrect and/or racey behaviour in KTable. There might not be any, but we won't know if this fixes both flakes or not for a little while I suppose. Thought it was worth a try.
This is green right now, so I would say we merge and let it sit for a while and report if we see either of these flakes types of flakes:
> fix(services): fixes internal service navigation test

- src/app/meshes/views/MeshDetailTabsView.vue
- src/app/meshes/views/MeshDetailView.vue
I've been working on several pieces of work that cross into our Empty and Error states and I noticed that we shouldn't really be showing the clickable tabs for a mesh if we can't load the mesh in the first place, for example in the case of a 404. So, this PR moves the data loading of mesh to the same route as the tabs (and switches to use a DataLoader). MeshInsights are no longer loaded if you land on any other tab apart from `[Overview]`.
I've been considering moving all our top-level dataloading into this level of route anyway, so this was the final reason why I thought it was a good reason to do it, and I'll probably do similar in other areas following this.
> chore: hoist mesh data loading to avoid showing tabs on 404

- features/mesh/Index.feature
- features/mesh/policies/Index.feature
- features/mesh/services/Index.feature
- package.json
- src/app/application/components/app-view/AppView.vue
- yarn.lock
**chore(KBreadcrumbs): address breaking changes**
Replace `.k-breadcrumbs-item` with `.breadcrumbs-item-container`.
---
Previous Kongponents v9 adoption PRs:
- https://github.com/kumahq/kuma-gui/pull/1532
- https://github.com/kumahq/kuma-gui/pull/1853
- https://github.com/kumahq/kuma-gui/pull/1878
- https://github.com/kumahq/kuma-gui/pull/1961
- https://github.com/kumahq/kuma-gui/pull/2118
- https://github.com/kumahq/kuma-gui/pull/2156
- https://github.com/kumahq/kuma-gui/pull/2184
- https://github.com/kumahq/kuma-gui/pull/2270
> refactor: update Kongponents to KBreadcrumbs milestone

- .eslintrc.cjs
- features/onboarding/add-new-services-code/Index.feature
- features/onboarding/multi-zone/Index.feature
- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/kuma/components/ApplicationShell.vue
- src/app/onboarding/components/OnboardingAlert.vue
- src/app/onboarding/locales/en-us/index.yaml
- src/app/onboarding/views/OnboardingAddNewServicesCodeView.vue
- src/app/onboarding/views/OnboardingDataplanesView.vue
- src/app/onboarding/views/OnboardingMultiZoneView.vue
- src/app/zone-ingresses/sources.ts
- src/app/zones/sources.ts
- src/app/zones/views/ZoneConfigView.vue
- src/app/zones/views/ZoneDetailView.vue
- src/services/kuma-api/README.md
Generally our onboarding area is pretty frozen, but it still has older code that we have to continue supporting unless we get rid of it (in this case `kumaApi` usage vs DataSource/DataLoader).
I had a bit of time whilst waiting on other PRs so, this PR switches the remaining areas of onboarding to use DataSource/DataLoader, and in doing so:
1. Removes all the older imperative code from onboarding and replaces it with DataSource
2. Changes some places where we were looking for a count of at least one zone/dataplane/zone-ingress and instead looks for at least a count of one _and_ one is online.
3. Uses the newer `_overview` endpoints for gathering data
4. Removes the last occurrences of us using `useKumaApi()` / `kumaApi` for reading data, which means we are closer to being able to use an …
> chore: removes read usage of kumaApi

- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/x/components/x-action/README.md
- src/app/x/components/x-action/XAction.vue
- src/app/x/components/x-teleport/README.md
- src/app/x/index.ts
Another little PR I had in mind whilst I'm awaiting reviews of others:
Adds an eXtra eXtension to `RouterLink` in the form of an `XAction` component which can be used instead of `RouterLink` (we can eventually take that out of the global scope)
Mainly to paper over the awkward `inactive: route.params.inactive ? null : undefined` things (I included one example of this here) which really should just be `inactive: true | false`. But also adds dynamic node choosing based on existence `href`/`to` properties and I'm sure there'll be more things we might want to add here in future.
> chore: adds XAction component

- package.json
- yarn.lock
Add postcss which was missing. It’s a peer dependency of both autoprefixer and stylelint-config-recommended-scss.
> chore(deps-dev): add missing postcss dependency

- features/mesh/dataplanes/DataplaneDetailsTraffic.feature
- features/mesh/dataplanes/NoSubscriptions.feature
- features/mesh/dataplanes/Warnings.feature
- features/mesh/dataplanes/overview/Connections.feature
- src/app/application/components/app-collection/AppCollection.vue
- src/app/data-planes/data/index.spec.ts
- src/app/data-planes/data/index.ts
- src/app/data-planes/locales/en-us/index.yaml
- src/app/data-planes/views/DataPlaneDetailTabsView.vue
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/data-planes/views/DataPlaneSummaryView.vue
- src/app/gateways/views/BuiltinGatewayDetailView.vue
- src/app/gateways/views/DelegatedGatewayDetailView.vue
- src/app/services/views/ServiceDetailView.vue
- src/test-support/FakeKuma.ts
- src/test-support/mocks/src/dataplanes.ts
- src/test-support/mocks/src/dataplanes/_overview.ts
- src/test-support/mocks/src/meshes/_/dataplanes/_/_overview.ts
- src/test-support/mocks/src/meshes/_/dataplanes/_overview.ts
- src/types/index.d.ts
Uses `kuma.io/display-name` as the dataplane `name` if it exists.
We also always set a new `.id` property, which we use for hrefs instead of `name` now.
I added a couple of places to show the `namespace` of a dataplane based on the namespace label (if it exists), but I didn't add this into our list/table views.
Oh I also removed the HTML `title`s we have in a couple of places, I figured those are less necessary now, but let me know if those should stay.
This PR only applies this to everywhere we have dataplanes (or should do). I noticed we probably could do this for policies also, which I'll do separately.
Closes https://github.com/kumahq/kuma-gui/issues/2051
If you view the preview make sure to set it to use a kubernetes-like environment via your cookies or via this link: …
> chore(dataplanes): use kuma.io/display-name if it exists

- features/mesh/dataplanes/DataplanePolicies.feature
- features/mesh/policies/DetailViewContent.feature
- features/mesh/policies/Index.feature
- src/app/policies/data/index.ts
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/policies/views/PolicySummaryView.vue
- src/test-support/mocks/src/meshes/_/circuit-breakers/_/_resources/dataplanes.ts
- src/types/index.d.ts
Use `display-name` and `namespace` labels for policy listings
---
I noticed that the mock for the affected dataplanes endpoint was static, so I changed that up but also that this endpoint is paged, but we don't offer any paging and we use frontend searching on the single page. I stopped short of doing anything towards changing this tho. Not sure if its on purpose or just an accidental omission? We might want to follow up with changing that soon.
Closes https://github.com/kumahq/kuma-gui/issues/2372
> chore(policies): use display-name label for policy listing

- src/app/common/TextWithCopyButton.vue
Replace the CopyButton in TextWithCopyButton with KCopy as we don’t have more specific needs here.
Note: There’s one more use of CopyButton which we can replaced as part of https://github.com/kumahq/kuma-gui/pull/2374. I think I might also try and use KCopy there so we don’t rely on multiple ways to copy stuff.
> refactor: replace CopyButton with KCopy

- .github/workflows/create-gui-pr.yml
- .syft.yaml
> ci: exclude go-module-binary-cataloger from sbom

- package.json
I noticed CI is using a different Yarn version than we have listed in the package manifest. Since Yarn v1 is no longer being developed, we should use the latest version. I also have a suspicion that might explain lock file differences being produced between CI and local environments.
> chore: require latest yarn version

- src/app/policies/views/PolicyListView.vue
- src/app/policies/views/PolicySummaryView.vue
Similar to https://github.com/kumahq/kuma-gui/pull/2380 and https://github.com/kumahq/kuma-gui/pull/2384
Tests for all these are here https://github.com/kumahq/kuma-gui/pull/2386 but wanted to get this fix in separately as it should be easier to review like this.
> fix(policies): ensure policy detail link uses id

- src/test-support/fake.ts
- src/test-support/index.ts
Firstly, this is a bug in our usage of MSW (local dev and preview sites) and therefore doesn't effect prod, or even our tests seeing as we use Cypress there.
--- 
We barely use `request.body` in our mocks, and I'm guessing this went unnoticed in our upgrade to MSW 2 https://github.com/kumahq/kuma-gui/pull/2110.
MSW now produces a `ReadableStream` as the request body. The fix just parses that out and into JSON. I also made the type a tiny bit better to at least expect something object like.
> fix(msw): request.body is a ReadableStream, convert to an object

- src/app/application/components/app-collection/AppCollection.vue
Addresses a change in Kongponents (https://github.com/Kong/kongponents/pull/2114/files#diff-a04c9b2aff0c872358299a5d13053e25eb987f72be4239623d5e1111b218b250R1180) making the toolbar shrink.
> fix(AppCollection): toolbar shrinking

- src/app/policies/routes.ts
- src/app/policies/views/PolicyTypeListView.vue
- src/app/x/components/x-action/XAction.vue
Instead of always linking to CircuitBreakers when clicking any `[Policies]` link, we choose the first one in the list and redirect you to that one.
Closes https://github.com/kumahq/kuma-gui/issues/2415
> fix(policies): redirect to first available policy type instead of CBs

- src/app/connections/data/index.spec.ts
- src/app/connections/data/index.ts
- src/app/connections/sources.ts
TLDR; This PR also applies a `_` exclusion to inbounds aswell as outbounds
---
We have an ignore/exclude list for cluster names that ignores internal cluster names, and we've recently started prefixing all internal cluster names with `_` and we ignore all `_` prefixed cluster names so moving forwards we can remove the exclude list.
https://github.com/kumahq/kuma-gui/blob/e4d3170edd2e84ea7d6b8260bc721eecd4ab59b5/src/app/connections/sources.ts#L37-L47
Thing is, we only apply this exclude list to outbounds 🙄 😅 
For reasons this wasn't as straightforward as just applying the same exclusion list.
---
For listeners we use the `ip.add.re.ss_port` as a key which we take from `listener.<ip.add.re.ss_port>`. Sometimes these can have a protocol on them followed by the clustername, followed by the …
> fix(dataplanes): ignore inbound/listener with a `_` prefixed clustername

- features/mesh/dataplanes/overview/Inbounds.feature
- src/app/data-planes/views/DataPlaneDetailView.vue
Also added a test for not showing any inbounds for delegated gateways whilst I was there as it was the same sort of test/feature.
Fixes https://github.com/kumahq/kuma-gui/issues/2418
> fix(dataplanes): ignore service-less inbounds in the overview

- .env.development
- .env.preview
- features/docs/Index.feature
- package.json
- src/services/env/Env.ts
> chore: update version to 2.7

- src/app/policies/views/PolicyListView.vue
- src/app/services/views/ServiceListView.vue
- src/app/x/components/x-action/XAction.vue
I'm using this to try and get a flake/error on a couple of tests that commonly flake, whilst it could go in, I want to keep running it until I get a flake. Also, I'm considering adding something on this PR that reruns certain tests multiple times to make any potential flakes more likely to come up in the PR.
~DO NOT MERGE!11!! No honestly, don't 😅~
---
edit: I've run this a few times, and I can't get a flake out of it. I'd rather merge this seeing as it doesn't really change any functionality and uses `XAction` (which we'll probably end up rolling out everywhere) and see if flake continue to appear over time.
> chore: adds additional error message to XAction and use it in service/policy listings

- src/app/application/components/app-view/AppView.vue
- src/app/x/components/x-breadcrumbs/README.md
- src/app/x/components/x-breadcrumbs/XBreadcrumbs.vue
- src/app/x/components/x-icon/XIcon.vue
- src/app/x/index.ts
There are times when we want to eXtend our breadcrumbs centrally or otherwise add eXtra bits to it, whilst we can almost do that as it stands (we only use it once in AppView). We may need to do it in a more inject-y/indirect way.
This adds an eXtra eXtension over KBreadcrumbs allowing us centrally configure it, but also inject into it.
> chore: adds XBreadcrumbs

- features/main-overview/DetailViewContent.feature
- src/app/application/components/data-source/DataLoader.vue
- src/app/control-planes/views/ControlPlaneDetailView.vue
- src/app/meshes/data/index.ts
- src/app/zones/data/index.ts
First stage refactor of the control-plane-detail page (usually our landing page) to use DataLoader/XAction and some of the newer patterns we have in the application:
1. Uses DataLoader instead of DataSource (I think there is a bit of extra detail i need to look into here that might produce a separate PR, I'll detail in that PR if so)
2. Uses XAction over RouterLink
3. Adds DataLoader#loadable slot. This state is `loading` and `loaded`. I'm thinking we can use this instead of the `loading=false` property on `DataLoader`. I'm pretty sure it will allow us to eventually avoid having to use `data!` sometimes, in that the default slot can export `T` and the loadable slot can export `T | undefined`, meaning in a large amount of cases when not using the loadable slot we can use `data` instead of …
> refactor(control-planes): refactors cp-details to use DataLoader

- cypress.config.ts
- cypress/support/e2e.ts
- package.json
- yarn.lock
**ci: add cypress-fail-on-console-error**
**ci: extract application error when annotating**
Make sure we’re handling application errors by stripping of the Cypress text (i.e. "Error: The following error originated from your application code, not from Cypress.") here first: https://github.com/kumahq/kuma-gui/actions/runs/8736436811/job/23971833245
```
Error: The following error originated from your application code, not from Cypress.
> Missing required param "service"
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
```
> ci: extract application error when annotating

- cypress.config.ts
Small tweak to the regexps to properly handle the following error: https://github.com/kumahq/kuma-gui/actions/runs/8752366390/job/24019886566?pr=2402
> ci: tweak Cypress error annotations

- public/mockServiceWorker.js
This is an example for why it’s kind of annoying that Dependabot doesn’t "just" use `yarn install` (evidently) because its updates miss changed files like that.
> chore: update mockServiceWorker file

- .editorconfig
- Makefile
- mk/build.mk
- mk/install.mk
Add the commands `make install`, `make clean-install`, `make clean`, and `make build`. The main purpose of these commands is to provide a wrapper around the package manager-specific commands. This is needed for the create-gui-pr.yml workflow which currently runs `yarn run build`. Since release branches use the file from the `master` branch for this workflow (as it uses `workflow_dispatch`), they use `yarn run build`, too. If we switch to another package manager, create-gui-pr workflow runs triggered from release branches will start failing as they will then call, for example, `npm run build` while actually still using yarn. With the make commands, this can be solved.
Note: If we decide to merge this, I’ll back-port the Makefile …
> chore: add build and install make commands

- package.json
- src/app/application/components/data-source/DataLoader.vue
- src/app/application/components/data-source/DataSource.vue
- src/app/application/components/route-view/RouteView.vue
- src/app/application/index.ts
- src/app/application/services/data-source/index.ts
- src/app/control-planes/sources.ts
- src/app/control-planes/views/ControlPlaneDetailView.vue
- src/app/diagnostics/views/DiagnosticsDetailView.vue
- src/app/meshes/views/MeshDetailView.vue
- yarn.lock
~Putting up in draft for the moment in case folks want to play with it whilst I'm still working on it.~
Small chance of some more work to happen on here but any review comments/questions in the meantime are welcome 
---
Adds `RouteView::uri` for generating `toString`-able typed URIs (i.e. a string but not a string).
Closes https://github.com/kumahq/kuma-gui/issues/2432
See above 'Closes' issue for more information. 
- `DataSource#default` should emit `data: Data | undefined`
- `DataLoader#default` should emit `data: Data`
- `DataLoader#loadable` should emit `data: Data | undefined`
I've tried hard to try to:
- make sure that the entire data structure of the data is presented in the type hint rather than just the name of the alias to the structure
- ensure that you can still use a bare …
> chore: Adds `uri` for generating typed string URIs for optional use with DataSource/Loader

- .syft.yaml
Addressing the create-gui-pr workflow failing on account of the missing syft config yielding critical vulnerabilities in go which we decided to ignore.
> chore: backport syft config (release-2.6)

- src/app/data-planes/index.ts
- src/app/gateways/index.ts
- src/app/meshes/index.ts
- src/app/policies/index.ts
- src/app/services/features.ts
- src/app/services/index.ts
- src/app/services/locales/en-us/index.yaml
- src/app/services/routes.ts
- src/app/services/views/ServiceListTabsView.vue
Adds basic feature flagging for the services module. Mostly prep for upcoming work.
---
There is a fair amount of re-plumbing here for the sub-routes of meshes. In order to plumb through `can` I noticed that the sub-routes for meshes still weren't really using our DI layer like other modules, so I changed this up for services so I could inject `can` through, and also changed the other mesh sub-routes to use the same approach as everywhere else.
I added some place holder routes in here, which in turn add new buttons to the service listing page sub-menu/LinkBox, but the feature is hardcoded to `false` so they don't show up as yet.
> chore(services): adds basic feature flagging for services

- src/app/common/code-block/ResourceCodeBlock.vue
See https://github.com/kumahq/kuma-gui/pull/2374#discussion_r1560807919
Looks like this is one of those cases where we need to make sure we await for a promise and return its result rather than just return the promise to be awaited on elsewhere.
Probably why the original code was like:
https://github.com/kumahq/kuma-gui/blob/6c158bacad13f9562d9c31a300bd16008aaaa0a4/src/app/common/code-block/ResourceCodeBlock.vue#L101-L107
But we've lost that detail through lack some good comments and subsequent upgrades/refactors there. I'll probably either refactor this code slightly to make this clearer or add some clearer comments. Putting the PR up whilst I think about that a little.
As little sidenote: I really wanted to progress the dev time clipboard coping debug I added here …
> fix: Copy as K8s

- src/app/gateways/views/BuiltinGatewayListView.vue
We have a global value to use for our default page size:
https://github.com/kumahq/kuma-gui/blob/d6d20ac1f56975cbaf6b0f1a2207476867135ff3/src/app/me/sources.ts#L10-L12
We expose this via a `/me` DataSource on every listing page.
This PR uses this value for our default page size rather than a hardcoded value of `10`
Closes https://github.com/kumahq/kuma-gui/issues/2540
> fix(gateways): don't hardcode pagesize different to global default

- src/app/gateways/views/BuiltinGatewayListView.vue
Backport of #2541 to `release-2.7`
---
We have a global value to use for our default page size:
https://github.com/kumahq/kuma-gui/blob/d6d20ac1f56975cbaf6b0f1a2207476867135ff3/src/app/me/sources.ts#L10-L12
We expose this via a `/me` DataSource on every listing page.
This PR uses this value for our default page size rather than a hardcoded value of `10`
Closes https://github.com/kumahq/kuma-gui/issues/2540
> fix(gateways): don't hardcode pagesize different to global default (#2541)

- src/app/application/components/data-collection/DataCollection.vue
- src/app/application/services/i18n/I18n.ts
- src/app/common/EmptyBlock.vue
- src/locales/en-us/components/index.yaml
Adds an `item` slot to DataCollection, to be used instead of `:find="true"`
Previously when using `DataCollection:find="true"` you then also needed to do `items[0]` to always refer to the first and only item in the list. Now you can use the `#item="{ item }"` slot instead of `:find="true"`, eventually we can remove `:find` entirely.
---
Adds `EmptyBlock:type` and then uses that and makes use of `t` inside of a reusable component.
DataCollection also has `DataCollection:type` which is just passed through to `EmptyBlock`
There is a fair amount of decisions here based on supporting what we currently/used to have, whilst moving forwards with a different approach.
> chore: add DataCollection#item, EmptyBlock:type

- mk/run.mk
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/x/components/x-breadcrumbs/XBreadcrumbs.vue
- src/app/x/components/x-select/README.md
- src/app/x/components/x-select/XSelect.vue
- src/app/x/index.ts
Adds an eXtra eXtension around KSelect to:
1. Use slots for adding `options` (to make it the same as XTabs)
2. Use `@change` for the event name (to make it the same as DataSource/Loader plus others)
3. Always have a horizontally aligned label (we never use the vertically aligned label and I doubt we ever will)
4. Automatically select the first option if no items are selected (or you specify an option that doesn't exist, such as by typing that into the URL)
> chore: adds XSelect component

- features/application/Titles.feature
- features/mesh/services/mesh-services/Index.feature
- src/app/external-services/views/ExternalServiceListView.vue
- src/app/services/data/index.ts
- src/app/services/index.ts
- src/app/services/locales/en-us/index.yaml
- src/app/services/routes.ts
- src/app/services/sources.ts
- src/app/services/views/MeshServiceListView.vue
- src/app/services/views/MeshServiceSummaryView.vue
- src/app/services/views/ServiceListTabsView.vue
- src/services/kuma-api/KumaApi.ts
- src/test-support/mocks/fs.ts
- src/test-support/mocks/src/meshes/_/meshservices.ts
- src/test-support/mocks/src/meshes/_/meshservices/_.ts
- src/types/index.d.ts
Adds minimal "List plus Summary" views for MeshService. Minimal meaning the list only has a `name`, clicking on which shows a summary containing only the YAML config (which has the same functionality as all our resource YAML views). The plan is to then iterate on this in further PRs.
Note: there is no feature flagging here, all users will see the new `MeshServices` button. Please shout if this isn't desired, there is the possibility of flagging based on the output of `/config` if we wanted to do that.
> feat(meshservice): add mesh service listing and summary panel

- features/mesh/services/mesh-services/Index.feature
- src/app/services/data/index.ts
- src/app/services/views/MeshServiceListView.vue
- src/app/services/views/MeshServiceSummaryView.vue
This change splits the name in the `MeshService` listing into the `name` and the `namespace`. A new column is introduced for the `namespace`.
Closes #2560
> feat(meshservice): add namespace column to listing

- package-lock.json
- package.json
Upgrades kongponents to the latest alpha version
Ideally https://github.com/kumahq/kuma-gui/pull/2559 would go in first, but since the thing that https://github.com/kumahq/kuma-gui/pull/2559 fixes didn't work anyway, it kinda doesn't matter which order they go in.
> chore(deps): upgrade kongponents

- src/app/application/components/route-view/RouteView.vue
- src/app/connections/views/ConnectionInboundSummaryView.vue
- src/app/connections/views/ConnectionOutboundSummaryView.vue
- src/app/data-planes/views/DataPlaneDetailTabsView.vue
- src/app/external-services/views/ExternalServiceDetailTabsView.vue
- src/app/gateways/views/BuiltinGatewayDetailTabsView.vue
- src/app/gateways/views/DelegatedGatewayDetailTabsView.vue
- src/app/gateways/views/GatewayListTabsView.vue
- src/app/meshes/views/MeshDetailTabsView.vue
- src/app/services/views/ServiceDetailTabsView.vue
- src/app/services/views/ServiceListTabsView.vue
- src/app/zone-egresses/views/ZoneEgressDetailTabsView.vue
- src/app/zone-ingresses/views/ZoneIngressDetailTabsView.vue
- src/app/zones/views/ZoneDetailTabsView.vue
Back in https://github.com/kumahq/kuma-gui/pull/2192 we made `route.children` and `route.active()` to make it easier to create sub-child navigation in parent routes (mainly our Tabs). A function was chosen as the interface for `route.active()` as the `active()` function never changes and therefore doesn't trigger a template re-render.
This was then changed to use a property rather than a function in https://github.com/kumahq/kuma-gui/pull/2186/files#r1499072744. but as this is a computed property that depends on the `route.name`, every time the routing changes the entire routing tree is re-rendered (despite what the comment in the above link says)
---
This PR changes `route.active` back to be a function, and also renames it something which describes what it does a little better i.e. I …
> fix: Ensure route.active doesn't force a page re-render

- features/mesh/services/mesh-services/Index.feature
- src/app/data-planes/sources.ts
- src/app/gateways/views/BuiltinGatewayDataplanesView.vue
- src/app/gateways/views/DelegatedGatewayDetailView.vue
- src/app/services/data/index.ts
- src/app/services/locales/en-us/index.yaml
- src/app/services/routes.ts
- src/app/services/views/MeshServiceConfigView.vue
- src/app/services/views/MeshServiceDetailTabsView.vue
- src/app/services/views/MeshServiceDetailView.vue
- src/app/services/views/MeshServiceListView.vue
- src/app/services/views/MeshServiceSummaryView.vue
- src/app/services/views/ServiceDetailView.vue
- src/test-support/mocks/src/meshes/_/meshservices.ts
- src/test-support/mocks/src/meshes/_/meshservices/_.ts
- src/types/index.d.ts
Direct Links:
- [Listing](https://deploy-preview-2564--kuma-gui.netlify.app/gui/meshes/default/services/mesh-services?page=1&size=50)
- [Detail](https://deploy-preview-2564--kuma-gui.netlify.app/gui/meshes/default/services/mesh-services/program-0/overview?page=1&size=50)
New things:
- Ports and Tags in listing rows
- Ports and Tags in the summary drawer
- New Detail > Overview page with Ports, Tags and Dataplane listing with search and summary drawer.
- New Detail > YAML page just repeating the same YAML from the summary drawer
Overall pretty happy we can build all this with almost zero Javascript 🎉 
### Detail with summary
> feat(meshservice): adds MeshService detail page

- src/app/zone-egresses/views/ZoneEgressDetailTabsView.vue
- src/app/zone-ingresses/views/ZoneIngressDetailTabsView.vue
Adds the zone name into the breadcrumbs when in either ingresses or egresses.
(When/if previewing remember to use `KUMA_ZONE_NAME=something` to make sure you get ingress/egresses in the mocks)
Closes https://github.com/kumahq/kuma-gui/issues/2379
> fix(zones): include zone name in the breadcrumbs for zone proxies

- src/app/common/code-block/CodeBlock.vue
Removes `position: sticky` from our CodeBlock wrapper to prevent toolbar stickiness, which was causing issues in certain areas.
It looks like this is based on the CodeBlock always being a certain distance underneath the AppHeader, which we can never guarantee.
> fix: removes CodeBlock toolbar stickiness

- features/zones/zone-cps/Item.feature
- src/app/control-planes/sources.ts
- src/app/subscriptions/components/SubscriptionHeader.vue
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneDetailView.vue
- src/test-support/FakeKuma.ts
- src/test-support/mocks/src/zones/_/_overview.ts
- Adds the latest subscriptions version the main information
- If this is lower than KUMA_VERSION (i.e. the version of the current global cp), we color the version using our 'warning' color and add a tooltip explanation.
- I re-removed the version from the subscription accordion pane titles that were added very recently. I figured the additions in this PR were what we actually wanted, and I can't think of the value/use case for wanting to know the version for every single subscription.
Closes https://github.com/kumahq/kuma-gui/issues/2164
> feat(zones): add zone version and different coloring+tooltip if outdated

- src/app/control-planes/sources.ts
I forgot to export `compare` during https://github.com/kumahq/kuma-gui/pull/2621, which I realized after that I needed to access from elsewhere (See below GH PR links).
> chore: export control-planes compare

- .github/dependabot.yml
- package-lock.json
- package.json
Kongponents is currently going through an alpha series of release which we are following along with, these releases follow a `9.0.0-alpha.000` versioning scheme.
Kongponents also releases PR builds to the npm registry for every single PR, using a versioning scheme of `pr-<gh-pr-number>`.
If you use a range versioning for kongponents' alpha without additional constraints, it will mean that it will get updated to the _PR version_ rather than stay on the alpha version. (`pr-000` is deemed a newer version than `9.0.0-alpha`)
Usually we use caret/range versioning `^9.0.0-alpha.000`, but to prevent us being moving to a PR version for a while now we had used exact versioning for kongponents (`9.0.0-alpha.123` without the caret).
---
Up until now we've fixed this in the wrong place in various …
> fix(deps): use correct semver constraint for kongponents alpha

- src/app/meshes/components/MeshStatus.vue
- src/app/meshes/locales/en-us/index.yaml
- src/app/meshes/views/MeshDetailView.vue
See https://github.com/kumahq/kuma-gui/issues/2413
Changes:
1. Removed showing the modification date, and moved creatojn date to the top right of the page.
2. We show enabled/disabled depending upon existence of MeshMetric, MeshAccessLog and MeshTrace and link to those policy lists (instead of showing Metrics, AccessLogs and Trace enabled/disabled)
3. Removed zoneIngress enabled/disabled
4. Added `0/0` online/total for dataplane count instead of only online.
5. If mtls is not enabled prompt users to set up mtls to get the most out of Kuma
Closes https://github.com/kumahq/kuma-gui/issues/2413
> feature(meshes): rework mesh detail page

- src/app/application/components/data-source/DataSource.vue
- src/app/data-planes/views/DataPlanePolicySummaryView.vue
This change makes sure that there is no extra spacing and scrollbar being added to the `.slideout-container` in the `DataPlanePolicySummaryView`.
The reason for the issue that adds the extra spacing which led to the extra scrollbar, is [an empty span](https://github.com/kumahq/kuma-gui/blob/9691ec3ab7ed877d5b10a802dff29076ba66304d/src/app/application/components/data-source/DataSource.vue#L7). It is part of the `DataSource` component and due to the [absolute positioning](https://github.com/kumahq/kuma-gui/blob/9691ec3ab7ed877d5b10a802dff29076ba66304d/src/app/application/components/data-source/DataSource.vue#L118) it was pulled up style-wise to the next element that has a `position` set, which is the `.slideout-container`'s `position: fixed` in this case. Therefore I've moved and surrounded …
> fix(data-planes/DataPlanePolicySummaryView): extra spacing and scrollbar

- src/app/common/SummaryView.vue
- src/app/common/code-block/CodeBlock.vue
We removed the stickiness on the toolbar here https://github.com/kumahq/kuma-gui/pull/2622 as it was based on a static value.
This lets the place that it sticks at be more configurable. I also added a background color to it using the dark theme (if we ever have a theme-able GUI this will either need to be moved to kongponents or made theme-able here)
> fix: makes codeblock sticky toolbar use a variable height

- package-lock.json
- package.json
- src/app/meshes/index.ts
- src/app/meshes/locales/en-us/index.yaml
- src/app/meshes/views/MeshDetailView.vue
- src/assets/styles/main.scss
- src/test-support/mocks/src/meshes/_.ts
- Warning for when mTLS is enabled but no MeshTrafficPermission exists
- Added MeshTrafficPermission `[enabled]` column plus link
- Used `@kong-ui-public/app-layout` `AppAboutSection` for wrapping container
We purposefully use `@kong-ui-public/app-layout@4.2.5` here instead of its latest version as `4.2.7` is uninstallable on kuma `release-2.8` even though it would work perfectly fine. Luckily I don't think there are any actual code changes between `4.2.5` and `4.2.7`, the only difference between the two is the tightening of the kongponent constraint (which seeing as I can't install this module at its latest version anymore, is probably the introduction of a bug rather than the fixing of one)
> chore(meshes): add warning for when mTLS is enabled but no MTP exists

- package-lock.json
- package.json
- src/app/meshes/views/MeshDetailView.vue
Prevents a double warning showing if you have mTLS disabled and no mTLS related policies.
~I've also pinned kongponents version to the same version as release-2.8 to prevent it automatically moving forwards when to the version we have on `master`~
We don't actually need to do the crossed out kongponents pin, its again another consequence of other dependencies unnecessarily bumping kongponents in their package.json file.
What we do need to do is use a version of app-layout that has a minimum kongponents version that has a constraint that includes our version of kongponents in release-2.8, which is why I've chosen 4.2.3
> fix(meshes): Prevents a double warning for mTLS disabled and no policy

- .vitepress/config.ts
- .vitepress/theme/style.css
- docs/tldr.md
- src/app/application/components/app-view/README.md
- src/app/application/components/data-source/README.md
- src/app/application/components/route-view/README.md
- stylelint.config.cjs
I wanted a single page `TLDR` in our Engineering docs for anyone who quickly wants to get up to speed with adding or working on new features for the GUI.
This PR adds this page and expands/updates the pages that the new `TLDR` page links to.
To view these use `make run/docs`, at some point we'll hook them up to our PR previews.
Note: These docs are for kuma-gui engineers and nothing more.
> chore(docs): add tldr page plus expands on docs linked from tldr

- .github/workflows/main.yml
- mk/install.mk
- mk/test.mk
- tsconfig.json
Some extra dev niceties, the biggest being:
```ts
"noErrorTruncation": true
```
Note the `...6 more...` in the screengrabs below.
All in all our type hinting is getting much more visible compared to just `import MeshService` which wasn't really helpful until you click all the way through to see.
Honestly, I don't know why we haven't had this from the beginning. I can't see a downside, but if there is we can always take it back out.
1. I realized in https://github.com/kumahq/kuma-gui/pull/2582 that aswell as CI performing clean installs (i.e. don't touch package-lock), local devs should also use the same. Dependabot owns package-lock.json so it should be the only one amending it (unless we install a new package). This means one less non-Makefile script in our GHA yamls 🎉 
2. I hit a thing …
> chore: adds better inline type documentation

- src/app/application/services/data-source/DataSourcePool.ts
- src/app/application/services/data-source/index.ts
See TODO removed in the changeset below
```
// TODO(jc) Once we remove all the source.closes in the sources.ts files the
// second argument here can go
```
> chore: stop passing a 'closable' through to all sources

- features/mesh/policies/Data.feature
- features/mesh/policies/Index.feature
- features/mesh/policies/PolicySummary.feature
- src/app/application/components/app-collection/AppCollection.vue
- src/app/policies/locales/en-us/index.yaml
- src/app/policies/sources.ts
- src/app/policies/views/PolicyListView.vue
- src/locales/en-us/common/index.yaml
- src/services/kuma-api/KumaApi.ts
See https://github.com/kumahq/kuma-gui/issues/1639 (not clear whether we should close that seeing as it mentions doing search elsewhere other than policies)
Adds name based searching to the policy listings. Follows exactly the same approach we use for simple searching as elsewhere.
> feat(policies): add name based search to policy listing

- features/mesh/services/mesh-services/Item.feature
- package-lock.json
- package.json
- src/app/application/services/data-source/Router.ts
MeshService `dataplaneTags` keys can contain slashes i.e. `{"k8s.kuma.io/namespace":"kuma-demo"}`.
The MeshService detail page has the first occurrence we have something that we pass into DataSource src's that can contain non-URL safe characters, for example here:
https://github.com/kumahq/kuma-gui/blob/ef9410407bb31299b6e581980fb36e63736ec07a/src/app/services/views/MeshServiceDetailView.vue#L122-L125
`/:tags` can end up being `/{"k8s.kuma.io/namespace":"kuma-demo"}`
The slash in `k8s.kuma.io/namespace` is not being encoded correctly.
---
Our `uri` helper uses `path-to-regexp` which previous to version `7` would throw if you used a parameter containing a non-URL safe character (the problem we are fixing). From `7` onwards `path-to-regexp` url encodes all its parameters, which is what we …
> fix(meshservice): Encode/Decode DataSource parameters

- features/mesh/services/mesh-services/Item.feature
- src/app/application/services/data-source/Router.ts
Port to `master` of #2694, note the upgraded version of `path-to-regexp` is already installed on `master`
---
From: #2694
MeshService `dataplaneTags` keys can contain slashes i.e. `{"k8s.kuma.io/namespace":"kuma-demo"}`.
The MeshService detail page has the first occurrence we have something that we pass into DataSource src's that can contain non-URL safe characters, for example here:
https://github.com/kumahq/kuma-gui/blob/ef9410407bb31299b6e581980fb36e63736ec07a/src/app/services/views/MeshServiceDetailView.vue#L122-L125
`/:tags` can end up being `/{"k8s.kuma.io/namespace":"kuma-demo"}`
The slash in `k8s.kuma.io/namespace` is not being encoded correctly.
---
Our `uri` helper uses `path-to-regexp` which previous to version `7` would throw if you used a parameter containing a non-URL safe …
> fix(meshservice): Encode/Decode DataSource parameters (#2694)

- features/main-overview/DetailViewContent.feature
- src/app/common/EmptyBlock.vue
- src/app/control-planes/views/ControlPlaneDetailView.vue
- src/app/meshes/components/MeshInsightsList.vue
- src/app/meshes/locales/en-us/index.yaml
- src/app/zones/components/ZoneControlPlanesList.vue
- src/app/zones/locales/en-us/index.yaml
- src/test-support/FakeKuma.ts
- src/test-support/mocks/src/mesh-insights.ts
- src/test-support/mocks/src/mesh-insights/_.ts
Part of https://github.com/kumahq/kuma-gui/issues/2388
This PR ended up doing several things:
- Uses DataCollection for the lists on the home/ control plane detail page (Zones and Meshes)
- Refactors the way that a `[+ Create Zone]` is conditionally added to the page. We now use a method which means we can decorate the `ZoneControlPlaneList` component from The Outside to add the button if we want to do that eventually. It's also generally nicer as we define the button once and then add to the DOM in the correct place, instead of defining twice and then wrapping both in slightly different conditionals.
- I noticed that the test we use for this mocks the mesh-insights API response incorrectly. So I amended that in the test and used a more generic method we have for mocking 'partitions of …
> refactor(control-planes): use DataCollection for CP detail page

- src/app/common/filter-bar/FilterBar.vue
- src/utilities/uniqueId.ts
Back in the mists of time, we added a `uniqueId` to out `@/utilities` folder.
We've since moved to use a much more modular approach and we have a `application` module that contains things that are generally needed by the entire application (i.e. any module in the application). This `application` module includes a `uniqueId` function that we now use almost everywhere.
https://github.com/kumahq/kuma-gui/blob/73077f131ff5f22e0801873ead4172130fe010fa/src/app/application/utilities/index.ts#L10-L18
I found one instance of where we were still using the old one, so I removed that and deleted the old file.
Note: There are a few places where we use `uniqueId` where its not really necessary (for legacy reasons), I guess these will be removed also in time.
> chore: Remove old uniqueId from @/utilities

- features/zones/zone-cps/Index.feature
- src/app/application/components/app-collection/AppCollection.vue
- src/app/x/components/x-icon/XIcon.vue
- src/app/zones/components/ZoneControlPlanesList.vue
- src/app/zones/views/ZoneListView.vue
Uses icons/tooltips to show zoneCP type instead of an additional column.
I added them both on the zone listing on the global control plane overview page and the zone listing page.
---
---
> chore(zones): add k8s/universal icons to zone rows instead of type

- src/app/application/components/route-view/RouteView.vue
- src/app/application/index.ts
- src/app/control-planes/views/ControlPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/external-services/views/ExternalServiceListView.vue
- src/app/gateways/views/BuiltinGatewayDataplanesView.vue
- src/app/gateways/views/BuiltinGatewayListView.vue
- src/app/gateways/views/DelegatedGatewayDetailView.vue
- src/app/gateways/views/DelegatedGatewayListView.vue
- src/app/kuma/index.ts
- src/app/me/index.ts
- src/app/me/sources.ts
- src/app/meshes/components/MeshInsightsList.vue
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/policies/views/PolicyTypeListView.vue
- src/app/services/views/MeshExternalServiceDetailView.vue
- src/app/services/views/MeshExternalServiceListView.vue
- src/app/services/views/MeshServiceDetailView.vue
- src/app/services/views/MeshServiceListView.vue
- src/app/services/views/ServiceDetailView.vue
- src/app/services/views/ServiceListView.vue
- src/app/zone-egresses/views/ZoneEgressListView.vue
- src/app/zone-ingresses/views/ZoneIngressListView.vue
- src/app/zones/components/ZoneControlPlanesList.vue
- src/app/zones/views/ZoneListView.vue
Roll out of the code in https://github.com/kumahq/kuma-gui/pull/2625 to all our tables.
All tables should now have resizable columns that remember the sizes through browser refreshes (via `localStorage`)
Whilst the changeset looks big due to the amount of tables we have, the work is basically:
- Remove the `me` `DataSource` in favour of `RouteView::me`
- Add a `@resize` event listener to`AppCollection`
- Splat down the values from `me` i.e. `headers.headerName` onto the header JSON for the table/AppCollection.
There is a lot of green in the changeset due to the removal of the top-level `DataSource` component the the re-nesting that then occurs. I made some inline comments in the place that weren't specifically just rollout of the same thing again and again.
Part of …
> chore: rollout table column resizing everywhere

- features/zones/zone-cps/Warnings.feature
- src/app/control-planes/sources.ts
- src/app/zones/data/index.ts
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/views/ZoneConfigView.vue
- src/app/zones/views/ZoneDetailTabsView.vue
- src/app/zones/views/ZoneDetailView.vue
- src/app/zones/views/ZoneListView.vue
- src/locales/en-us/common/index.yaml
In https://github.com/kumahq/kuma-gui/pull/2621 we added an async DataSource that compares the version of the ZoneCP and the GlobalCP.
We usually just compare using the sync `env('KUMA_VERSION')` (as we do here) but sometimes we need an async interaction.
Previously, we only used the comparison for one warning/tooltip in the page. This PR changes it so we emit whether the relationship between zone and global is outdated, _plus the latest version_. This means we can also use this latest version in other places.
When we need to use an async interaction for this, doing this PR means we can.
---
As I worked on this it made sense to also move the Zone warnings data reshaping into our data layer, so I did that here also.
> fix(zones): use the same version from the DataSource used in the page instead of the env var

- src/app/application/index.ts
- src/app/application/services/data-source/DataSourcePool.ts
- src/app/kuma/index.ts
We found [an error](https://github.com/kumahq/kuma-gui/pull/2697) a few days back which manifested in a user facing scenario, but did not produce a error in the dev console.
This PR adds better error handling to ensure that these sorts of errors are also logged to the dev console.
I did this work against the code previous to #2697 where the bug occurred and with this PR applied it now looks like this:
> chore: add extra error handling

- .vitepress/theme/components/Story.vue
- .vitepress/theme/main.md
- src/app/x/components/x-action-group/README.md
- src/app/x/components/x-action-group/XActionGroup.vue
- src/app/x/components/x-action/README.md
- src/app/x/components/x-action/XAction.vue
- src/app/x/components/x-icon/XIcon.vue
- src/app/x/components/x-provider/README.md
- src/app/x/components/x-provider/XProvider.vue
- src/app/x/index.ts
- src/app/zones-crud/components/ZoneControlPlanesListWithCreate.vue
- src/app/zones/views/ZoneListView.vue
Several improvements to `XAction` and `XActionGroup`
- XActionGroup triggers have a more consistent styling with other applications.
- XAction's have appearance and sizing attributes for customization with KButton's
- I added a new `XProvider` component that lets us add Vue injections in a finer grained way (i.e. around certain slots). We use this to know whether an `XAction` is within a `XActionGroup` or not, but specifically _not_ the trigger/control `XAction`. We only wrap the default slot of `XActionGroup` with `XProvider` so that only buttons within the default slot have access to the injection, the control/trigger slot doesn't.
I used some docs sandboxes for XAction and XAction group to work on these, and I added those in here also.
> chore: XAction and XActionGroup improvements

- DEVELOPER.md
- netlify.toml
- package.json
Back in https://github.com/kumahq/kuma-gui/pull/2691 we moved all our dev scripts to a Makefile and noted:
> Once we've merged this we can update this 'hook' in the Netlify web GUI to use the make file instead, we can then PR one last PR to remove this last package script.
I kinda forgot that we are using the netify.toml file instead of the web GUI, so I could have probably done this in the above PR but 🤷 
As long as the preview site is being deployed here, then it should be fine (seems like it is to me)
I also updated related docs in CONTRIBUTING.md
> chore: change netlify script to use Makefile

- package-lock.json
- package.json
I while ago we removed `semver` from our package.json, and then added it back in again when we realized we were using it in our Vuex `store`.
https://github.com/kumahq/kuma-gui/pull/936
We removed our Vuex `store` entirely a while ago, which means we can remove `semver` from our package.json again and should reduce our dependabot PRs ever so slightly (the one that made me look into this is here https://github.com/kumahq/kuma-gui/pull/2780)
Note: `semver` is still a transitive dev dependency.
> chore(deps): remove semver from package.json

- src/app/zones/views/ZoneConfigView.vue
A teeny while back we removed all our subtitles. I think this one ended up staying in via a rebase.
> fix(zones): remove ZoneConfig subtitle

- package-lock.json
Wanted to do an experiment/put a PR up to illustrate some less ideal behaviour of our upgrading prompted by https://github.com/kumahq/kuma-gui/pull/2783
Previous to this PR we have 2 versions each of `shiki` and `@shikijs/core`
This PR was created by using a mix of `npm upgrade`, `npm why` and `npm prune` and is what we would want to happen ideally.
Note: `shiki` is only used for syntax highlighting within our vitepress engineering documentation.
> chore(deps): upgrade/dedupe shiki and related

- features/mesh/policies/Index.feature
- src/app/x/components/x-action/XAction.vue
Back in https://github.com/kumahq/kuma-gui/pull/2741/files#diff-f7d102cd28d8503b5974afd6eb10e8d34d072370f7802324da3469ecf3c65b82L142 I removed the `mount` functionality we have in `XAction`, at the time I miss-thought that it was an attrinute/functionality we no longer used/required.
Thing is, we do use it in one place to redirect any visits to `/mesh/:mesh-name/policies` through to `/mesh/:mesh-name/policies/:first-policy-type-that-has-entries`.
This PR puts the functionality back. I also added a test for the redirect to make sure I don't accidentally remove this again.
> fix(policies): Ensure visits to /policies are redirected

- src/app/application/components/app-view/AppView.vue
- src/app/kuma/components/ApplicationShell.vue
- src/assets/styles/_base.scss
Decreases default body text ever so slightly to bring it in line with other areas.
I re-upped the size for our side menu to keep the side nav links the same size as previous. Otherwise the only things affected are the new introductory intro sentences and the service type button group, both can be seen in the below screengrabs.
> chore: Amend default font-size to be slightly smaller

- src/app/App.vue
Back in https://github.com/kumahq/kuma-gui/pull/2662 we moved the main navigation in App.vue to use `route.child()` for selection.
I noticed that this is causing a full page re-render whenever the `route` is changed. You can notice this because our Github button in the header flickers on every single navigation (caused by the re-render). When navigating between tabbed sub-pages you shouldn't see a flicker (but you will do when navigation between Home, Zones, Meshes).
Strangely `route.child()` doesn't cause full page re-renders in other areas, in fact it was used/made specifically to avoid full page re-renders.
For the moment I've added a fix straight into `App.vue` that avoids the issue. But I would guess at some point I will come back to try and ensure that `route.child()` or some …
> fix: Alters main menu selection to not cause full re-render

- src/app/zones/locales/en-us/index.yaml
See title
---
A couple of weeks back I moved the warnings inspection over to our data layer, but unfortunately whilst doing so I mixed up the warning messages 🤦 https://github.com/kumahq/kuma-gui/pull/2712/files#diff-b74e52e340de40ac28d9f03911b3150dd6e2a60629b55351d4d160735bda2fcb
> fix(zones): Unmix zone warning texts

- .eslintrc.cjs
I was playing around/experimenting with something and eslint was warning me about some incorrect typescript for something that seemed reasonable.
When I looked into it it seems like this eslint rule is incorrect when using with typescript
https://typescript-eslint.io/rules/no-use-before-define/#how-to-use
```js
module.exports = {
"rules": {
// Note: you must disable the base rule as it can report incorrect errors
"no-use-before-define": "off",
"@typescript-eslint/no-use-before-define": "error"
}
};
```
While I don't need the experiment I was working on when I found this out, I figured I would PR the eslint correction for the future.
---
The default options for the ts rule would require a fair amount of moving code around just to satisfy the linter, so I've amended the default options …
> fix: Disable/replace incorrect eslint rule

- src/app/application/components/route-view/RouteView.vue
- src/app/application/index.ts
- src/app/application/utilities/index.ts
- src/app/x/index.ts
Somewhere around vue language tools `2.0.18 - 2.0.21` all of the types for our `slots` suddenly stopped working.
As this seemed to be a pretty big regression, I've been waiting to see if this would be addresses upstream seeing as various other type related bugs have also been fixed since `2.0.18`.
I've waited for quite a while now, and I decided to take look to see if I could figure out exactly what the issue was, which led me to a fix/upgrade from our end.
1. At the beginning it was very much "anything further than 2.0.18 breaks our types (not knowing exactly why), hold off on upgrading for a bit and see what happens"
2. A few weeks back I'd realized that it seemed to be related to objects that DataSource was emitting via slots. DataSource also uses generic properties and some non-simple …
> fix: Use `vue` instead of `@vue/runtime-core` for registering components

- features/mesh/dataplanes/Index.feature
- src/app/data-planes/views/DataPlaneListView.vue
Back in https://github.com/kumahq/kuma-gui/pull/2749 we changed the remaining DataSource's to use DataLoader and `uri` (`uri`s benefit is it carries through all the types for the resource identifier/data).
Unfortunately we mistakenly omitted a `search` parameter (these params are optional). This PR adds it back in.
Double-y unfortunate is that I thought we had e2e tests on our search, which we do, but for another page (dataplane searching within a service detail) 🤦 .
https://github.com/kumahq/kuma-gui/blob/924c7a597ce785fa5d5cfdef48195181fa02f027/features/mesh/services/Item.feature#L58-L71
I copied the above test over to the DataPlane listing page so we now test this in both places. You'll see that new test in this changeset.
> fix(dataplanes): ensure search parameter is passed to HTTP call

- features/zones/Create.feature
- src/app/application/components/data-source/DataSink.vue
If a DataSink errors, and after another attempt then subsequently succeeds, make sure we unset the error.
e2e test added in Zone Creation for any potential regressions.
> fix(data-sink): unset error on a subsequent success

- src/app/services/data/MeshExternalService.ts
- src/app/services/data/MeshService.ts
- src/app/services/views/MeshExternalServiceDetailView.vue
- src/app/services/views/MeshExternalServiceListView.vue
- src/app/services/views/MeshExternalServiceSummaryView.vue
- src/app/services/views/MeshServiceDetailView.vue
- src/app/services/views/MeshServiceListView.vue
- src/app/services/views/MeshServiceSummaryView.vue
- src/test-support/mocks/src/meshes/_/meshexternalservices.ts
- src/test-support/mocks/src/meshes/_/meshservices.ts
Closes https://github.com/kumahq/kuma-gui/issues/2791
Adds a copy button to all MeshService/MeshExternalService `addresses` in lists, summaries and details....but only when there is a single address (`addresses` is an array, but I'm guessing its most commonly single length)
Personally I'm not super keen on copy buttons, I want to see what I'm copying, but I get why people like them. I am a little cautious though about having a glut of copy buttons in every page of the GUI, mentioning here as I'd like to find a good balance and wanted to note somewhere whilst its at the forefront of my mind.
> chore(mesh-service): add copy button to address when there is only one

- src/app/application/components/app-collection/AppCollection.vue
Prevents a table re-render when the `headers` reference changes but the value doesn't.
This PR also fixes the issue described in https://github.com/kumahq/kuma-gui/pull/2810 but in a different way.
Whilst both separately fix the issue and only one is theoretically needed, both a valuable improvements.
> chore: prevent a re-render if a change of headers has same value

- mk/test.mk
Personally I use `KUMA_TEST_BROWSER` to always open tests in chrome (its good practice to watch e2e tests run through). Therefore, generally, only CI runs in headless mode, and in CI we _always_ pass in a `CYPRESS_SPEC` env var.
But, just the once I wanted to run the tests in headless mode locally whilst trying to chase down a potential CI bug. So I `unset KUMA_TEST_BROWSER`, and found that I also had to set `CYPRESS_SPEC` otherwise the command errors out.
This PR defaults `CYPRESS_SPEC` to `**/*.feature` so you can just run `make test/e2e` with an empty `CYPRESS_SPEC` and it will run all the tests.
> chore(tests): default CYPRESS_SPEC to all feature files

- features/application/Loading.feature
- package-lock.json
- package.json
- src/app/application/components/app-collection/AppCollection.vue
Back in https://github.com/kumahq/kuma-gui/pull/2842 we pinned kongponents due to:
> kongponents 9.4.1 includes a bug somewhere that means the loading skeleton no longer shows for KTables. Therefore I pinned the dependency to anything less than 9.4.1. Guessing dependabot will change that pin anyway. We'll just have to remember not to upgrade when the 9.4.1 dependabot PP comes up
https://github.com/kumahq/kuma-gui/pull/2842#issuecomment-2317217735
I noticed that kongponents' KTable has a manual `:loading` property, so I used that to fix the issue. I also added a new test seeing it was only by chance that I noticed this issue. If it happens again we'll fail.
Following this I could unpin kongponents again.
---
Slight note: https://github.com/kumahq/kuma-gui/pull/2846 <- we are hoping to move …
> fix: fix loading skeleton for KTable @ kongponents:9.4.1

- .husky/pre-commit
Since https://github.com/kumahq/kuma-gui/pull/2841 we'd started seeing this sort of thing:
Screenshot of changelog relevant to this PR:
Relevant links:
- https://github.com/typicode/husky/releases/tag/v9.1.2
- https://github.com/typicode/husky/releases/tag/v9.1.1
> chore: husky pre-commit changes

- src/app/connections/data/index.spec.ts
- src/app/connections/data/index.ts
- src/app/connections/sources.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
During parsing of the Envoy stats responses, if we find a clustername with `_msvc_` (or related), we mark that cluster/outbound as having a `kind` of `MeshService`.
Later on in the view, we can decide whether to add a link to the cards service depending on its `kind`.
Currently we only link cards with empty kinds. i.e. if its not a MeshService, MeshMultiZoneService or a MeshExternalService we don't link the card.
See linked issue for more details https://github.com/kumahq/kuma-gui/issues/2848
> feat(dataplanes): disable linking of new Mesh*Services

- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneSummaryView.vue
- src/app/policies/components/PolicySummary.vue
- src/app/policies/data/index.ts
- src/app/policies/locales/en-us/index.yaml
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/services/data/MeshExternalService.ts
- src/app/services/data/MeshService.ts
- src/app/services/views/MeshExternalServiceDetailView.vue
- src/app/services/views/MeshExternalServiceSummaryView.vue
- src/app/services/views/MeshServiceDetailView.vue
- src/app/services/views/MeshServiceListView.vue
- src/app/services/views/MeshServiceSummaryView.vue
- src/test-support/mocks/src/meshes/_/meshexternalservices/_.ts
Whilst doing this I noticed that lots of our top detail boxes are very overloaded now. For instance DDP detail pages have a possible 7 columns (I split this one into 2 rows here).
Data can often overlap and become unreadable, so at least at a technical level its time to take a look at our `class="columns"` layout to provide something that is more responsive.
There is also possibly an opportunity to say we should look at this from a design perspective as looking at the data in the summary panels often provides a more readable display.
Closes https://github.com/kumahq/kuma-gui/issues/2670
> chore(zones): add zones to all summary and detail pages

- src/app/services/data/MeshMultizoneService.ts
- src/app/services/data/index.ts
- src/app/services/locales/en-us/index.yaml
- src/app/services/routes.ts
- src/app/services/sources.ts
- src/app/services/views/MeshMultizoneServiceConfigView.vue
- src/app/services/views/MeshMultizoneServiceDetailTabsView.vue
- src/app/services/views/MeshMultizoneServiceDetailView.vue
- src/app/services/views/MeshMultizoneServiceListView.vue
- src/app/services/views/MeshMultizoneServiceSummaryView.vue
- src/app/x/components/x-breadcrumbs/XBreadcrumbs.vue
- src/test-support/mocks/fs.ts
- src/test-support/mocks/src/meshes/_/meshmultizoneservices.ts
- src/test-support/mocks/src/meshes/_/meshmultizoneservices/_.ts
- src/test-support/mocks/src/meshes/_/meshservices/_.ts
Initial support for `MeshMultiZoneService`.
This is pretty much a copy/pasta of `MeshService` with some slight tweaks.
The detail page specifically is quite bare as we don't need a listing of `Dataplane`s here.
~We probably do need a listing of `MeshService` here though, although I'd be happy to PR that separately once I find out for definite.~
I added a simple listing of MeshServices / `meshServices` which is just a table with a single name column whose rows link to the MeshService detail page.
Closes https://github.com/kumahq/kuma-gui/issues/2768
> feature(services): initial support for MeshMultiZoneService

- src/app/application/components/app-collection/AppCollection.vue
- src/app/application/components/data-collection/DataCollection.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/external-services/views/ExternalServiceListView.vue
- src/app/gateways/views/BuiltinGatewayDataplanesView.vue
- src/app/gateways/views/BuiltinGatewayListView.vue
- src/app/gateways/views/DelegatedGatewayDetailView.vue
- src/app/gateways/views/DelegatedGatewayListView.vue
- src/app/meshes/components/MeshInsightsList.vue
- src/app/meshes/views/MeshListView.vue
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/rules/components/RuleList.vue
- src/app/services/views/MeshExternalServiceListView.vue
- src/app/services/views/MeshServiceDetailView.vue
- src/app/services/views/MeshServiceListView.vue
- src/app/services/views/ServiceDetailView.vue
- src/app/services/views/ServiceListView.vue
- src/app/zone-egresses/views/ZoneEgressListView.vue
- src/app/zone-ingresses/sources.ts
- src/app/zone-ingresses/views/ZoneIngressListView.vue
- src/app/zone-ingresses/views/ZoneIngressServicesView.vue
- src/app/zones/components/ZoneControlPlanesList.vue
- src/app/zones/views/ZoneListView.vue
Moves pagination to be contained within DataCollection instead of AppCollection.
---
Lots of reasons for this:
- Pagination could be for something that doesn't look like a table
- We had a few little hacks in AppCollection in order to make sure we would refresh the table when pagination things
- Reduces the amount of code to render a table
- We'd like to eventually use a more slimmed down KTable (the new kongponent KTableView) that doesn't include pagination either
There are also a few more finer details added to make our pagination/total counts a little better i.e. we can now choose to only show the `10 of 100` count without the pagination links.
> chore: Refactor AppCollection to not include non-table things

- README.md
> fix(docs): fix URL for README test badge

- src/app/data-planes/views/DataPlanePoliciesView.vue
This made for a very interesting PR. I wanted to write why this was interesting down somewhere for later reference. But firstly the problem:
We noticed that the DataplanePolicies view was calling the `.../_rules` endpoint multiple times on page load. This PR fixes that so it now only calls the `.../_rules` endpoint once.
---
Why it was interesting?:
I looked into why this HTTP endpoint was being called multiple times and, to cut a long story short, our `<DataSource>` component that calls this HTTP endpoint was being added to the DOM, then immediately removed from the DOM, and then re-added again. The repeated add/remove behaviour was what was causing the multiple HTTP requests because every time the `<DataSource>` gets added to the DOM it makes the HTTP call (this is expected).
Why was it …
> fix: fixes DataPlanePolicyView calling _rules multiple times

- src/app/policies/views/PolicyDetailView.vue
The top card here can only contain one item - the zone.
We conditionally gate that depending on whether we find a zone or not, but if we don't show it then the card shows as empty.
This PR move the conditional to the entire card rather than just the zone text.
I also fixed a console warning here regarding a shadowed `data` variable (we used `props.data` _and_ `data` previously in this template, and despite them being different `props.data` vs `data` Vue treats tem as the same variable reference hence they are shadowed)
> fix(policies): don't show a card if we don't find a zone

- src/app/application/components/route-view/RouteView.vue
Shuffles around the components in `RouteView` to ensure we have a proper DOM node as root for if we ever add attributes to the component (`<RouteView data-testid="">`)
Whilst previously `DataSource` was the single root node, `DataSource` itself does not have a wrapping root DOM component. This PR moves the root node here to be a `div` i.e. a proper DOM node.
> chore: Reorders RouteView to have a root node

- src/app/application/services/data-source/index.ts
- src/app/zones/sources.ts
- src/test-support/mocks/src/zones/_/_overview.ts
Whilst finishing yo cleaning up the removal of our `zone-crud` module, I spotted that there could be a case where a erroneous-retrying DataSource will not be closed correctly.
This PR:
- Removes a now unused source (checking the online-ness of a zone) that we used to use in the zone creation flow.
- Checks our retry loop to see if the DataSource is closed, and if it is finish the loop
- Removes a comment suggesting to use a 401 error for checking the creation flows polling mechanism. In some instances 401s are dealt with by other sorts of retries, therefore a 401 can be misleading. If its ever needed, you can mock this just by setting a subscription count to zero, so I switched up the comment to explain that.
> fix: check for closed source on retry

- src/test-support/fake.ts
- src/test-support/index.ts
- src/test-support/intercept.ts
- src/test-support/vite.ts
This PR does two things related to our mocks:
---
Up until now we've only ever really needed to mock out our HTTP API at `http://localhost:5681` or occasionally a full absolute URL such as `https://kuma.io/latest_version`.
There are times when we want to mock out "whereever we are" i.e. `http://localhost:8080` (or :8081, :8082 etc for our local dev server) or maybe our GH PR preview at say `https://deploy-preview-2918--kuma-gui.netlify.app/`.
Usually we would just use `/` to say this, but for ease we've used `/` to say/mean "our HTTP API at `http://localhost:5681`" (as we can set `http://localhost:5681` to be something different we don't want to/can't hardcode that either)
This PR uses `://` instead of `/` to say "use the same protocol and the same host" i.e. "whereever we are". Anything …
> chore(tests): allow relative mocks, allow passthrough via mocks

- src/app/zones/locales/en-us/index.yaml
- src/assets/styles/_base.scss
- Changes `Zone Actions` to just `Actions`
- Allows us to unset `img { height: auto }` without potentially causing damage elsewhere
> chore: Slight text/css amends

- features/zones/zone-cps/Item.feature
- src/app/subscriptions/data/index.ts
- src/app/subscriptions/index.ts
- src/app/subscriptions/locales/en-us/index.yaml
- src/app/subscriptions/routes.ts
- src/app/subscriptions/views/SubscriptionSummaryConfigView.vue
- src/app/subscriptions/views/SubscriptionSummaryOverviewView.vue
- src/app/subscriptions/views/SubscriptionSummaryView.vue
- src/app/zones/index.ts
- src/app/zones/locales/en-us/index.yaml
- src/app/zones/routes.ts
- src/app/zones/views/ZoneDetailView.vue
- src/test-support/FakeKuma.ts
- src/test-support/mocks/src/zones/_/_overview.ts
- src/types/index.d.ts
Changes Zone Subscriptions only to use a table/summary view/interaction.
We decided that there would be far more space to show things if we used our common table/summary panel pattern instead of the accordion where there is very little space to show things:
See:
- https://github.com/kumahq/kuma-gui/issues/2623
- https://github.com/kumahq/kuma-gui/issues/2164
---
~Questions:~
~1. Do we want to show the Subscription YAML, the Subscription JSON config, or both?~
~2. If we want to show both, should we add a separate `[YAML]` tab or use the `Structured/YAML` dropdown?~
Note:
I'm guessing we'll want the same layout for DPP subscriptions, I plan to do this as a follow up and there will some changes made on top of here to make the panel work in both places.
Closes …
> feat(zones): move KDSSubscriptions to use a table/summary

- src/app/policies/components/PolicySummary.vue
- src/app/policies/views/PolicyDetailView.vue
- src/app/policies/views/PolicyListView.vue
- src/test-support/mocks/fs.ts
- src/test-support/mocks/src/mesh-insights/_.ts
- src/test-support/mocks/src/meshes/_/meshfaultinjections.ts
- src/test-support/mocks/src/meshes/_/meshfaultinjections/_.ts
- src/test-support/mocks/src/meshes/_/meshfaultinjections/_/_resources/dataplanes.ts
Adds further info to the policy detail page. Please note this purposefully doesn't add the producer/consumer/system type yet.
I'll be adding that along with the same in the listing page.
Closes https://github.com/kumahq/kuma-gui/issues/2929
Also defaults any empty top-level targetRef to `Mesh`
Closes https://github.com/kumahq/kuma-gui/issues/2934
> feature(policies): add more information to the policy detail page

- src/app/connections/data/index.spec.ts
- src/app/connections/data/index.ts
- src/app/connections/views/ConnectionOutboundSummaryOverviewView.vue
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/rules/data/ResourceRule.ts
- src/app/rules/data/index.ts
- src/types/index.d.ts
Uses `toResourceRules` for rendering Rules/Policies in outbounds drawer.
Please note: Their are no mocks for this yet, until then, please use `KUMA_MOCK_API_ENABLED=false` to point this to a local kuma.
Closes https://github.com/kumahq/kuma-gui/issues/2880
> chore: support toResourceRules in outbounds summary

- src/app/connections/data/index.spec.ts
- src/app/connections/data/index.ts
- src/app/connections/views/ConnectionOutboundSummaryOverviewView.vue
- src/app/rules/data/ResourceRule.ts
Changes how we lookup/match cluster to rule to use the resourceMeta labels instead of the resourceMeta.name.
> fix: amend cluster/rule lookups to use resourceMeta.labels

- .env.development
- package.json
- src/app/application/services/env/Env.ts
For development purposes, we currently hardcode the current Kuma version in 3 separate places.
This version is shown, during development, in the header of the GUI and is used for generating all our documentation links.
In production, the kuma binary feeds a different version in via the `index.html` file.
---
We always forget to bump this for a version and whilst its not super important (we were still on `2.6.0`), its handy for checking links etc.
I vaguely remember suggesting we should set this in one place (the `package.json`) and even better have a way to bump this automatically. Not sure if we made an issue, I'll either link one here if I can find one or make a new one.
edit: I found this https://github.com/kumahq/kuma-gui/issues/2428
> chore: Bump version numbers to 2.9 (affects dev docs links etc)

- .eslintrc.cjs
- src/app/kuma/components/kuma-port/KumaPort.vue
- src/app/kuma/components/kuma-port/README.md
- src/app/kuma/index.ts
- src/app/services/views/MeshExternalServiceDetailView.vue
- src/app/services/views/MeshExternalServiceListView.vue
- src/app/services/views/MeshExternalServiceSummaryView.vue
- src/app/services/views/MeshMultiZoneServiceDetailView.vue
- src/app/services/views/MeshMultiZoneServiceListView.vue
- src/app/services/views/MeshMultiZoneServiceSummaryView.vue
- src/app/services/views/MeshServiceDetailView.vue
- src/app/services/views/MeshServiceListView.vue
- src/app/services/views/MeshServiceSummaryView.vue
- src/app/x/components/x-badge/README.md
- src/app/x/components/x-badge/XBadge.vue
- src/app/x/index.ts
Adds a KumaPort component in order to display ports consistently.
Globally added along with a `Kuma*` namespace as we are likely to use these sorts of thing all over the place (we'll probably end up with others such as `KumaTargetRef`)
> feature: KumaPort component, for displaying a port consistently

- src/app/connections/data/index.ts
- src/app/connections/views/ConnectionOutboundSummaryOverviewView.vue
Removes the 'Resources' link form the rules drawer.
We can't quite know the proper type/name of the thing just yet.
I've also added a little fix for detecting `MeshExternalServices` in the same view
> fix(dataplanes): Remove Resource link from rules drawer

- src/app/data-planes/views/DataPlaneDetailTabsView.vue
- src/app/data-planes/views/DataPlaneDetailView.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/meshes/routes.ts
- src/app/meshes/views/MeshDetailTabsView.vue
- src/app/meshes/views/MeshView.vue
- src/app/services/features.ts
- src/app/services/views/ServiceListTabsView.vue
Removes the `Services` column from the Dataplane listing, and the DataPlane Inbound card links, only when the Mesh is in meshServices Exclusive mode.
> chore(meshservice): removes Services from DDP listing in exclusive

- package-lock.json
Runs `npm audit fix` which fixes an issue with `nise` (it has a dep on `path-to-regexp`) that dependabot doesn't seem to update.
> chore(deps): runs npm audit for nise > path-to-regexp

- src/app/x/components/x-action/XAction.vue
- src/app/x/components/x-icon/XIcon.vue
Adds ProgressIcon to XIcon and XButton, which means we can use conditionals like:
```vue
:action="writing ? 'progress' : 'create'"
```
instead of 
```vue
<ProgressIcon v-if="writing" />
<AddIcon v-else />
```
> chore: adds Progress icon to XIcon/XAction

- src/app/application/index.ts
Looks like typescript will accept a `() => string` in place of a `() => void` 🤷 
I also moved the sub-dependencies added here to the end of the container configuration so that they don't get overwritten in the wrong order.
> fix: Correct DataSource arguments order

- src/app/application/index.ts
- src/app/application/utilities/index.ts
- src/app/meshes/data/Mesh.ts
- src/app/meshes/data/index.spec.ts
- src/app/services/features.ts
- src/types/index.d.ts
Uses `meshServices.mode` with fallback to `meshServices.enabled` (if neither are set fallback to `meshServices.mode = 'Disabled'`
I also added a `runInDebug` function whose contents is removed at build time. This avoids using something `vite` specific (`import.meta.env.PROD`) and its name is meaningful. I then used this to make sure `mesh` is set in our feature flags (static type checking is loose here right now)
Closes https://github.com/kumahq/kuma-gui/issues/3013
> chore(meshes): Use `meshServices.mode` w/fallback `meshServices.enabled`

- src/app/data-planes/sources.ts
- src/app/data-planes/views/DataPlaneXdsConfigView.vue
- src/app/zone-egresses/sources.ts
- src/app/zone-egresses/views/ZoneEgressXdsConfigView.vue
- src/app/zone-ingresses/sources.ts
- src/app/zone-ingresses/views/ZoneIngressXdsConfigView.vue
- src/test-support/mocks/fs.ts
- src/test-support/mocks/src/zoneegresses/_/xds.ts
- src/test-support/mocks/src/zoneingresses/_/xds.ts
Adds a checkbox to all XDS configuraiton pages that controls whether to show eds/endpoints in the XDS config or not.
**I wanted to double check the API URLs for this. I'm pretty sure the API endpoints here are correct, inside `/zoneegresses` and `/zoneingresses`. Just we have API endpoints for Zone Ingresses under `/zone-ingresses` also (note the hypen)**
You can also check this with a local cluster by using `KUMA_MOCK_API_ENABLED=false` so that the we use a local running instance of Kuma.
Closes https://github.com/kumahq/kuma-gui/issues/3031
> feat: add include_eds checkbox for XDS config views

- src/app/data-planes/views/DataPlaneXdsConfigView.vue
- src/app/zone-egresses/views/ZoneEgressXdsConfigView.vue
- src/app/zone-ingresses/views/ZoneIngressXdsConfigView.vue
I wasn't thinking straight for https://github.com/kumahq/kuma-gui/pull/3032 and used Vue refs for the checkbox v-model for the include endpoints option instead of using the URL via our `RouteView::params` 🤦 .
This PR changes that so now your selection of "Include Endpoints" yes/no is included in the URL of your browser.
> fix: include include_eds option in the URL

- .github/dependabot.yml
Removes dependbot PR limits.
---
If there are 100 dependabot PRs, I don't just want to know about the first 10 and then wait for a week. I want to know about all 100 and then choose which ones to merge first (probably ones that are most important)
I really don't mind leaving dependabot upgrade PRs outstanding for a while if they are not important, but I do mind not knowing about dependabot upgrades which might be important.
> chore(deps): removes dependabot PR limit

- .github/dependabot.yml
As this property is called a `-limit`, back in https://github.com/kumahq/kuma-gui/pull/2910 I removed this property, thinking it would that open infinite amounts of PRs (i.e. no limit).
Turns out this property has a default value of `5` meaning I actually reduced the amount of PRs dependabot could open, which is the opposite of what I wanted 😆 
This PR lets dependabot open up to 50 PRs for JS deps, seeing as its JS, we probably need a large figure here 😅 . I bumped the GH actions limit to use the same figure just for consistency really (we only use about 5 actions)
> fix(deps): Tell dependabot to open more PRs

- .github/dependabot.yml
Wrong nesting 🤦 ...
Follow up to https://github.com/kumahq/kuma-gui/pull/3066
---
Could do with a linter here really, but preferably not one thats a JS dependency 🤔
> fix(deps): Fix wrongly nested dependabot config

- features/onboarding/dataplanes-overview/Index.feature
- src/app/onboarding/views/OnboardingDataplanesView.vue
We had a flakey onboarding e2e test, and when I started looking into it I saw another little issue, I fixed that in the end didn't seem related to the flake:
- I noticed that the even when the response was empty, the GUI would say `The following data plane proxies (DPPs) are connected to the control plane:` and show `0` instead of saying `Waiting for DPPs`. This was down to `.some` doing the opposite of what you expect when the array its acting on is empty. There is a small fix in the application code for this.
- I believe the flake was due to the test checking for the `$state-waiting` potentially after the initial request has responded/loaded, meaning it will never exist. As the request could respond either before or after the `$state-waiting` assertion, this causes the test to be …
> fix(onboarding): fixes empty state text and flakey onboarding test

- .github/workflows/main.yml
- .github/workflows/on-dependabot-pr.yml
One of our dependencies is `msw`, which has an [npm post install hook](https://github.com/mswjs/msw/blob/8e173305c143d9281af0010e1dbdb11ca9e62a78/package.json#L88) to amend https://github.com/kumahq/kuma-gui/blob/376ca94362f6342ad52cc561d30ad4e6f013b646/public/mockServiceWorker.js
Generally, the amend is just a bump of this so that the versions match:
https://github.com/kumahq/kuma-gui/blob/376ca94362f6342ad52cc561d30ad4e6f013b646/public/mockServiceWorker.js#L11-L12
As dependabot doesn't perform an install after bumping the version of MSW, the post-install script isn't run and this file isn't amended.
Then, when another user does a local install following the dependabot update, the above file ends up being amended and marked as such in `git`. The user can then either make another PR with …
> chore(deps): add dependabot PR hooks

- .github/workflows/release.yml
This PR changed our "Create GUI PR" workflow:
1. Naming. I changed the name to `release.yaml` / `Build and release to kumahq/kuma` because we are releasing the GUI to the binary/kuma. "Create GUI PR" sounds like I am creating a PR on `kumahq/kuma-gui`
~2. Added a `repository-data` job that fetches all "topics" from the repository~
~3. Uses the `repository-data` output to look for a `auto-release` "topic" which when present (as it is currently) performs a "release" as before.~
~**I plan on merging this with the `auto-release` "topic" applied to prove it works (validate the PR is made). I will then remove the `auto-release` topic temporarily.**~
~Notes:~
- ~I "think" I can't access the secrets in a run because I'm PRing from a forked PR, hence will currently fail until this is on `master`. …
> chore(ci): rename GUI PR GHA to "release"

- .github/workflows/on-dependabot-pr.yml
Continuation of https://github.com/kumahq/kuma-gui/pull/2918
Without this PR we get the below error
> fix(ci): add creds to dependabots label editing

- src/test-support/mocks/fs.ts
- src/test-support/mocks/src/zones/_.ts
In https://github.com/kumahq/kuma-gui/pull/3034 we cleaned up a few mock endpoints we don't use. We mistakenly removed the zone deletion endpoint, which we use elsewhere but the backend code for it is in the kuma binary and as such this mock belongs here.
> fix(mocks): re-add zone HTTP endpoint

- src/app/meshes/data/Mesh.ts
- src/test-support/mocks/src/meshes/_.ts
- src/types/index.d.ts
Removes `enabled` from `meshServices` in favor of `mode`
Closes #3015
> refactor(meshServices): remove enabled

- public/mockServiceWorker.js
When running `make install` from outdated or cleaned `node_modules` the `PACKAGE_VERSION` in `public/mockedServiceWorker.js` gets aligned with the version specified in `package.json`, which causes a diff.
> fix(msw): inconsistent package version in generated file

- src/app/application/components/app-collection/AppCollection.vue
- src/app/common/SummaryView.vue
This PR does two things related to unwanted "synthetic" click events happening in our table rows. Our table rows use a synthetic click event to simulate a HTML anchor click because we use tables for navigation lists and we are unable to wrap anchors around table rows (`<a />`s around `<tr />`s)
The fixes:
1. Our summary drawer has an `onClickOutside` event so that if its open and you click outside the drawer, it then closes. Thing is, if you click outside the drawer on a different table row, we don't want the drawer to close, but instead change to the summary of the row you have clicked. The `.preventDefault()` related code here prevents the drawer from closing if you click a different row.
2. Currently if you select a piece of text that is in a table row (probably in order to copy it to …
> chore: prevents unwanted click events firing

- src/app/application/components/app-view/AppView.vue
- src/assets/styles/_base.scss
Moves the declaration of `font-size: 14px` to somewhere in the code that means it will apply everywhere.
> chore: moves font-size declaration to apply everywhere

- src/app/services/features.ts
- src/app/services/routes.ts
During the development of our MeshService support we added a feature flag (defaulting to `true`) in case we needed to turn it off in a central place for any reason.
We no longer need this ability as we now always want MeshService support enabled.
This PR removes any usage of the feature flag plus the feature flag itself.
(Make sure you use the GH `Hide whitespace` toggle whilst viewing the diff, otherwise the change look much bigger than they actually are)
> chore(services): remove mesh-service feature flag

- vite.config.production.ts
~Important: Do not merge until post 2.9. We would like time for the change in Sass setting to "sit in" in the very slim case that it affects something we haven't noticed.~ This is fine to merge now
---
Mainly fixes Sass deprecation warning
~But also bumps the MSW version in mockServiceWorker (vaguely related https://github.com/kumahq/kuma-gui/pull/2918)~ edit: This was eventually done in https://github.com/kumahq/kuma-gui/pull/3095 which was approved and merged first, so I amended this change out
> chore(deps): MSW and Sass post upgrade fixes

- src/app/common/filter-bar/ShortcutManager.ts
The `code` param for `normalizeKeyCode` can sometimes be `undefined`, e.g. when using browser input autocomplete functionalities.
Closes #2838
> fix(ShortcutManager/normalizeKeyCode): code param can be undefined

- Makefile
- mk/build.mk
- mk/check.mk
- mk/help.mk
- mk/install.mk
- mk/run.mk
- mk/test.mk
- package.json
Changes our approach to Makefile targets to make them more customisable upstream
---
The biggest problem here is that Make make its troublesome to simply override make targets.
Previously we would 'override' targets by not including the file that had the target we had to override, and then including a different file with our customisations in it for the relevant target. The thing is you would also need to override (or just copy) all targets in a file, rather than just the one you wanted to override.
This approach names all consumable make targets prefixed with a `.` i.e. `.install` vs `install`. We than add references to all these in our base `Makefile` (essentially `make`s `main` file). The `Makefile` is specific to each project so we can add what we want in there and it doesn't affect …
> chore(mk): move accessible targets to the "make main file" i.e. Makefile

- src/app/services/locales/en-us/index.yaml
- src/app/services/views/ServiceListTabsView.vue
Moved and rephrased the title of the `ServiceListTabView` to separate explanatory sentences for each service type. For most of the services I included a link to the docs.
Closes #2928
> feat(ServiceListTabsView): add explanatory sentences for service type views

- src/app/services/locales/en-us/index.yaml
Replacing the hardcoded docs base URL with env `KUMA_DOCS_URL` and appending `KUMA_UTM_QUERY_PARAMS`.
> fix(services/locales): hardcoded docs base url in service type descriptions

- src/app/gateways/locales/en-us/index.yaml
- src/app/gateways/views/GatewayListTabsView.vue
Follow up to #3119 
Brings back consistency between services and gateways by adding explanatory sentences to the gateway types and moving everything below the action group.
> feat(gateways/GatewayListTabsView): add explanatory sentences to gateway types

- src/test-support/FakeKuma.ts
- src/test-support/mocks/src/global-insight.ts
I've been looking into some of our test flakes and going through our e2e tests and finding a places that seem strange or are causing or could cause test flakes.
I found an issue here where when setting up a DATAPLANE_COUNT of `1`, you could randomly/occasionally get a value of `0` even though you've said "always give me `1`".
The detail is that the very specific `fake.kuma.healthStatus` method has an optional `min:` argument which defaults to `0`. Meaning if you use `fake.kuma.healthStatus` without setting the `min`, say for example you are trying to guarantee it always returns a total of `1` by using `fake.kuma.healthStatus({max: 1})`, it will actually give you either `0` or `1` because it returns a random between the `min:0` and `max:1`.
I've fixed the issue in the the mock where I …
> fix(mocks): use generic partitionInto instead of healthStatus

- vite.config.production.ts
We use sass for our `@kong/design-tokens` support.
This applies another fix for a recent sass upgrade to prevent `@kong/design-tokens` related console warnings:
Note there are still some deprecation warnings due to our own usage of sass, but this gets rid of the majority of noise:
Whilst we have to use sass in order to consume `@kong/design-tokens`, a the better fix for our own code is to get rid of sass usage entirely. So I hope/plan on doing that in a follow up PR relatively soon. (edit: I made a follow up issue https://github.com/kumahq/kuma-gui/issues/3123)
> chore: replace sass @import with @use to reduce console warnings

- src/app/application/components/app-collection/AppCollection.vue
- src/app/common/filter-bar/FilterBar.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/gateways/views/BuiltinGatewayDataplanesView.vue
- src/app/gateways/views/DelegatedGatewayDetailView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/services/views/MeshServiceDetailView.vue
- src/app/services/views/ServiceDetailView.vue
- src/app/x/components/x-input/XInput.vue
This PR hoists all search/toolbars out of AppCollection and the DataLoader/Collections to its own "standalone component". Meaning it is always visible, throughout loading/erroneous and empty states.
---
There is a little CSS repetition here, but I hope to add a XLayout component pretty soon which I hope will cover this at some point.
Note I also took the `<search>` out of `FilterBar` and used it at the "call site" instead, in some places the `search` should contains the `select` also.
Closes https://github.com/kumahq/kuma-gui/issues/2981
> fix(search): Always show search bars

- src/app/application/components/app-collection/AppCollection.vue
- src/app/application/components/app-view/AppView.vue
- src/app/application/components/data-collection/DataCollection.vue
- src/app/x/components/x-layout/README.md
- src/app/x/components/x-layout/XLayout.vue
- src/app/x/index.ts
- src/assets/styles/_components.scss
Adds a `XLayout` component for laying out multiple components.
`XLayout` currently comes with two `types` of layout: `stack` and `separated`
- `stack` is the same as what `div class="stack"` does, renders the contents vertically with a gap in-between each item.
- `separated` is the same as the layout we use when rendering multiple badges and renders the contents inline/horizontally with a gap in-between each item.
---
We currently use `<div class="stack">` (and others div/class things) to lay out certain components. This uses `<XLayout type="stack">` to do exactly the same thing. But formalises it in the fact that is no longer just a div and a class, its a very simple component that you can use inline in your template with auto-complete-able layouts.
Another advantage is that we are …
> chore: adds XLayout component

- .vitepress/config.ts
- index.html
"Damn you auto-complete" 👎 
---
Back in https://github.com/kumahq/kuma-gui/pull/3049 a closed node snuck in, I'm assuming via auto-complete nonsense. I wondered why this didn't break, but its down to browsers being very forgiving in a standard way.
All in all whilst its not broken functionally, its a fix in that its currently incorrect and not intentional.
> fix: undo closed script node in index.html

- .env
- cypress/services.ts
- src/app/application/services/env/Env.ts
- src/app/application/services/env/env.spec.ts
- src/app/kuma/index.ts
- src/app/kuma/locales/en-us/index.yaml
- src/shims-env.d.ts
Since a long time ago we've had `.env` file support. The `.env` file used to be used for 2 things:
1. Changing several `env` vars at build-time (previous to having support for changing `env` vars at runtime via dev-time browser cookies)
2. Storing strings (sometimes test/copy, sometimes URLs) used throughout the application that we may need to change at build time (previous to having i18n support)
Since then, we added both support for setting env vars at runtime via cookies (removing the need to restart the dev server), and i18n support for storing maps of strings in a KV store mainly for localizing from "machine to human".
Both these additions completely remove the need for storing most of these values in an `.env` file so I've slowly been moving things to not use the `.env` file and …
> chore: clean up some .env file vars

- package-lock.json
- package.json
`cookie` less than `0.7.0` has a low dev time security issue.
I've waited a few days in the hope that this would be resolved upstream, but its seems like the package that includes the dependency have bumped the version (3 weeks ago) but not actually made a release 😭 
Not sure when the release will happen and filter down to us, so I've used an override for now to mirror the version they have used (but not released) in the upstream repo.
Hopefully this should resolve the notification we have about this.
> fix: bump/override cookie dependency to ^0.7.1

- src/app/application/components/route-view/README.md
- src/app/application/index.ts
- src/app/subscriptions/views/SubscriptionSummaryConfigView.vue
- src/app/subscriptions/views/SubscriptionSummaryOverviewView.vue
- src/app/subscriptions/views/SubscriptionSummaryView.vue
- src/app/vue/index.ts
This PR introduces the concept of "route config walkers" to our application.
These walkers allow us to decorate individual route configs in a centralized place. They purposefully mutate the config rather than return the a copy of the config. I've kept the code for this in one place for now, but once I'm totally sure of the API I'll probably re-shuffle things slightly to use our service container labels. I've added code comments/TODOs to this effect in the PR.
---
The walkers/decorators I added here:
Currently we have/use `<RouteView name="the-name-of-the-route">` i.e. we hard code the name of the route associated with this file into the RouteView's name. This means we can't then reuse, or 'mount', the same route component file at another URL and at the very least its error/typo prone …
> feature(routing): adds route config walking, plus several walkers

- src/app/application/components/app-collection/AppCollection.vue
- src/app/common/filter-bar/FilterBar.vue
- src/app/data-planes/views/DataPlaneListView.vue
- src/app/gateways/views/BuiltinGatewayDataplanesView.vue
- src/app/gateways/views/DelegatedGatewayDetailView.vue
- src/app/policies/views/PolicyListView.vue
- src/app/services/views/MeshServiceDetailView.vue
- src/app/services/views/ServiceDetailView.vue
- src/app/x/components/x-input/XInput.vue
Port of #3089 cherry-picked to `master`
---
This PR hoists all search/toolbars out of AppCollection and the DataLoader/Collections to its own "standalone component". Meaning it is always visible, throughout loading/erroneous and empty states.
---
There is a little CSS repetition here, but I hope to add a XLayout component pretty soon which I hope will cover this at some point.
Note I also took the `<search>` out of `FilterBar` and used it at the "call site" instead, in some places the `search` should contains the `select` also.
Closes https://github.com/kumahq/kuma-gui/issues/2981
> fix(search): Always show search bars (#3089)

- features/zones/zone-cps/ingresses/item/Index.feature
- src/app/application/components/route-view/README.md
- src/app/application/components/route-view/RouteView.vue
- src/app/kuma/locales/en-us/index.yaml
- src/app/subscriptions/components/SubscriptionDetails.vue
- src/app/subscriptions/components/SubscriptionHeader.vue
- src/app/subscriptions/components/SubscriptionList.vue
- src/app/subscriptions/data/index.ts
- src/app/subscriptions/locales/en-us/index.yaml
- src/app/subscriptions/routes.ts
- src/app/subscriptions/views/SubscriptionSummaryConfigView.vue
- src/app/subscriptions/views/SubscriptionSummaryOverviewView.vue
- src/app/subscriptions/views/SubscriptionSummaryView.vue
- src/app/vue/index.ts
- src/app/zone-ingresses/routes.ts
- src/app/zone-ingresses/views/ZoneIngressDetailView.vue
- src/app/zones/data/index.ts
- src/app/zones/routes.ts
- src/app/zones/views/ZoneDetailView.vue
- src/test-support/FakeKuma.ts
- src/test-support/mocks/src/zone-ingresses/_/_overview.ts
- src/test-support/mocks/src/zone-ingresses/_overview.ts
- src/test-support/mocks/src/zones/_/_overview.ts
- src/types/index.d.ts
Adds new Subscription Table/Drawer UI to ZoneIngresses (whilst maintaining old-style for Egress and Dataplanes until we change those also)
Part of: https://github.com/kumahq/kuma-gui/issues/2921
---
~Lots of failing tests here, so keeping in draft until I've sorted that. I would guess it's probably chore-like updating of tests but we'll see!~
Turns out we can't use `addRouteName` from https://github.com/kumahq/kuma-gui/pull/3151 due to things being slightly different and weird between dev source and compiled/built source.
Instead I reverted to use route config `props` here, which was second favourite option. I plan to improve on this a little more, and if I ever figure out a more reliable way to add a dynamic global like `$routeName` I can add it at a later date. In the meantime I'd …
> chore: uses new subscriptions table/drawer layout for zoneIngress

- vite.plugins.ts
Following https://github.com/kumahq/kuma-gui/pull/3049 I forgot that our PRs are ever so slightly different.
This PR applies a similar template interpolation to out index.html for a build **but only if build is called with `--mode preview`**
At some point I'd like to add some sort of browser runner test to just ping one page of the GUI on the PR preview to make sure its there and work to prevent this happening again. I'll make an issue - https://github.com/kumahq/kuma-gui/issues/3156
> fix: pr previews

- .github/workflows/release.yml
Follow up of https://github.com/kumahq/kuma-gui/pull/3176
---
The above PR moved files around quite a bit, and in doing so we didn't update the paths correctly for the SBOM moving around when we do a "release" to `kuma`.
GH Actions still run in root, but I changed all of the `run:` GHActions to have a different working directory in order to be able to run our `make` targets easier. Re-looking at the script in this PR, this means the SBOM reports are in root, but we checkout `kuma` into `/packages/kuma-gui/main-application` instead of what it used to be `/main-application`, this means we need to go 2 directories extra up (`kuma-gui` and `packages`) to get to root.
Unfortunately this is a bit hard to test as its not _yet_ in the `Makefile` (I moved most of the CI scripts to our Makefile a …
> fix(ci): correct paths for SBOM moving

- packages/kuma-gui/src/app/x/components/x-icon/XIcon.vue
Hardcodes `decorative="false"` in order to guarantee that `@kong/icons` show (`kong/icons` PR that introduced the issue)
---
Not totally sure how to go about resolving the issue as yet, ideally I'd like to use CSS for all our icons as all icons by their very nature are "decorative". Once we've decided exactly what to do we can revisit this. In the meantime this fix resolves things for our users whilst dodging/avoiding any issues over implementation.
> fix: remove decorative attribute from all icons to fix tooltipping

- packages/kuma-gui/src/app/x/components/x-prompt/XPrompt.vue
The current version of kongponents dropped the support of the prop `type` on the `KPrompt` component. On the `XPrompt` component we want to continue to abstract away the new props that allow more granular control about the appearance and therefore make it easier to use.
Instead of hardcoding `:action-button-appearance="danger"` or `="props.type"` I thought it's better to keep this separated, so whenever we need to add another option for `type` (that is probably not available in kongponents), this should still work as `:action-button-appearance` has to be aligned with the options of [`KButton.appearance`](https://kongponents.konghq.com/components/button.html#appearance). For now the fallback to everything but `danger` is `primary`.
Closes #3178
> fix(kuma-gui/x-prompt): unsupported KPrompt prop type

- packages/kuma-gui/src/app/application/components/data-source/DataLoader.vue
Ideally we wouldn't have to set srcData to `unknown` here and we'd continue to use `TypeOf<T>` which is the type returned by the src from the `sources.ts` file, whatever that is.
Thing is our upgrade to vue 3.5 is breaking in this area (https://github.com/kumahq/kuma-gui/pull/3062).
I was kinda holding off with the hope that it would be sorted upstream, and I wanted to avoid using a `@ts-ignore` in order to upgrade. It's also worth noting that srcError uses the exact same construct, but doesn't cause TS issues, which I think is due to it not using a generic type.
Then I had another idea. Seeing as we mostly cast `srcData` back to a `NonNullable<TypeOf<T>>` in most places anyway, and we don't need to refer to it within the component at all, we may as well treat it as `unknown`, which is …
> fix(deps): sets srcData to unknown only within DataLoader

- packages/kuma-gui/src/app/application/components/route-view/RouteView.vue
We had a flake quite a while now that looks something like this:
But we've never really seen or heard reports of this with real users.
Lately, I have seen reports of this bug (or one with a similar error) happening with 1 or 2 users. On further investigation the error I've seen here relates to this potentially asynchronous code (using `beforePaint`). "asynchronous code you say?! sounds like it could be the cause of a flake" 😅 
I looked back to try to find out why we needed the `beforePaint` and blamed it back to this PR https://github.com/kumahq/kuma-gui/pull/1493:
> We had/have some strange race-y route/URL interactions that are causing confusing issues during testing where user interactions can happen at a much faster rate than usual. This combined with how paging works in …
> fix: remove beforePaint from routeUpdate, its no longer required

- packages/config/src/eslint.cjs
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/dataplanes/_/stats.ts
- packages/kuma-gui/tsconfig.json
Brings back detection of unreachable code. For some reason `no-unreachable` only detects issues in `.js`-files. Probably because with TypeScript this is handed over to the TS compiler.
> chore: detect unreachable code

- packages/kuma-gui/src/app/connections/components/connection-traffic/ConnectionGroup.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/x/components/x-layout/XLayout.vue
I've used `XLayout` to do this and added a `small` variant, (fyi: we also have/had a `.stack-small` previously) Wanted to note I'm still ever so slightly cautious about `XLayout` (and the component first approach) https://github.com/kumahq/kuma-gui/pull/3092#issuecomment-2450324907, happy enough with it to use it to fix this though:
See left-hand inbound top/bottom margins:
**P.S. Be sure to use GHs hide whitespace option when reviewing:**
> fix(dataplanes): Fix margins on inbound cards in dataplane overview

- packages/kuma-gui/src/app/zone-ingresses/data/index.spec.ts
- packages/kuma-gui/src/app/zone-ingresses/data/index.ts
- packages/kuma-gui/src/app/zone-ingresses/sources.ts
- packages/kuma-gui/src/app/zone-ingresses/views/ZoneIngressSummaryView.vue
Adds the `YAML` config to the `ZoneIngressSummaryView`.
I've also removed some of the custom types that are added in the data layer to move further to the point of inferring the type from the return value.
Part of #2922
> feat(zone-ingress/summary-view): add config

- packages/kuma-gui/src/app/zone-egresses/data/index.spec.ts
- packages/kuma-gui/src/app/zone-egresses/data/index.ts
- packages/kuma-gui/src/app/zone-egresses/views/ZoneEgressSummaryView.vue
Adds the `YAML` config to the `ZoneEgressSummaryView`.
I've also removed some of the custom types that are added in the data layer to move further to the point of inferring the type from the return value.
The `config` is aligned with what was added in #3202:
> The `config` that we add to the data for now represents what is currently applied, including all the stuff that gets added by the backend (and potentially k8s). We might revisit this in the future and add only what the user would apply and exclude everything that is added by the backend (and potentially k8s).
Part of #2922
> feat(zone-egresses/summary-view): add config

- package-lock.json
- packages/config/package.json
- packages/config/src/cypress.ts
- packages/kuma-gui/cypress/support/e2e.ts
- packages/kuma-gui/package.json
There are places where we can sometimes have certain HTTP errors swallowed and converted to `console.warn`, currently its up in the air whether we leave them alone or convert them to console.errors (so they fail our tests using `cypress-fail-on-console-error` that we already have installed).
This PR install a further dependency that allows us to log `console.warn`s.
Note there are other things that it allows us to log, but for the moment I'm looking for low noise and just output `console.warn`s. Also, we can't fail on console.warn because we have 3rd party dependencies that use `warn` correctly and for good reason.
---
I confirmed we are seeing console.warns in the tests in GH logs. You can apparently get the plugin to output a txt file so you can make an artifact, but I plan on adding …
> chore(ci): installs cypress-terminal-report for surfacing console.warns

- packages/kuma-gui/src/app/services/data/index.ts
DNS is created in the mesh for `_`-delimited and `.`-delimited hostnames. This PR makes the `.`-delimited the default (as it is the only one in conformance with the RFC). This is a QOL improvement for folks copying/pasting from the UI, and both versions should work identically. The API returns `_`-delimited so in the case anyone was using any kind of automation, this shouldn't break them anyway.
fixes #3098
> feat: default service hosts to period-delimited

- package-lock.json
- packages/kuma-gui/package.json
- packages/kuma-gui/src/app/data-planes/locales/en-us/index.yaml
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneSummaryOverviewView.vue
- packages/kuma-gui/src/app/hostname-generators/views/HostnameGeneratorDetailView.vue
- packages/kuma-gui/src/app/kuma/locales/en-us/index.yaml
- packages/kuma-gui/src/app/meshes/views/MeshDetailView.vue
- packages/kuma-gui/src/app/x/components/x-timespan/README.md
- packages/kuma-gui/src/app/x/components/x-timespan/XTimespan.vue
- packages/kuma-gui/src/app/x/index.ts
- packages/kuma-gui/src/app/zone-egresses/views/ZoneEgressDetailView.vue
- packages/kuma-gui/src/app/zone-ingresses/views/ZoneIngressDetailView.vue
- packages/kuma-gui/src/app/zones/views/ZoneDetailView.vue
- packages/kuma-gui/src/assets/styles/main.scss
Adds `<XTimespan />` component.
See docs (`make run/docs` - see screengrab at the bottom of this description)
We have several areas where we want to consistently show a timespan (or possible a single time value if only a `start` or `end` is set. Importantly we would like to have a single easy-to-use component in order to do this. 
This PR adds this new component, replaces AppAboutSection usage with XTimespan (and removes the repetitive "fix-up" CSS related to that). Additionally, XTimespan copes better in smaller areas (i.e. wrapping) and avoids tangental dependency issues related to `app-layout` (we remove `app-layout` as a dependency here). I also added it in Zones and Zone*gress.
Lastly, there are probably a few other areas where we can now use his, but seeing as we weren't showing …
> feat: adds XTimespan component

- packages/kuma-gui/src/app/x/components/x-teleport/XTeleportSlot.vue
- packages/kuma-gui/src/app/x/components/x-teleport/XTeleportTemplate.vue
Sometimes when you add a teleport to a page, the place where it is supposed to go hasn't quite been rendered yet (the slot) which is just down to Vue/DOM intricacies.
Previously we would just error out if we hit this, but there are some use cases I've found where this is always going to throw. Ideally, it should wait for the corresponding template slot to be available and only then teleport into it, and that is what this PR does.
Just to note: timings wise we are talking milliseconds here.
> feature: enable delayed teleporting

- packages/kuma-gui/src/app/application/components/app-view/AppView.vue
- packages/kuma-gui/src/app/x/components/x-action/XAction.vue
Uses `XAction` as opposed to `KButton` for our docs links, which means all our docs links automatically open in a new tab
> fix: Use XAction for docs links

- packages/kuma-gui/features/application/Loading.feature
- packages/kuma-gui/src/app/application/components/app-collection/AppCollection.vue
- packages/kuma-gui/src/app/application/components/data-source/DataLoader.vue
- packages/kuma-gui/src/app/meshes/views/MeshDetailView.vue
- packages/kuma-gui/src/app/meshes/views/MeshListView.vue
- packages/kuma-gui/src/app/x/components/x-layout/XLayout.vue
This PR is a little mix of things unfortunately, they are small things related to `meshes` refactoring, so happy to leave as is but would be fine to split smaller if thats preferred. The GH "Hide Whitespace" option is probably good for review.
---
We have this little 'wart' in quite a few places:
https://github.com/kumahq/kuma-gui/blob/765d9f5f2ca3fdc44b5998f946064ed9aa725c7b/packages/kuma-gui/src/app/meshes/views/MeshListView.vue#L36
Not only this but we have a lot of weirdness to support the fact that `KTable` is the only component we use that has its own loader embedded in it, for absolutely everything else we use DataLoader to provide loading states and loading visuals.
I gave DataLoader a new `variant="default | list"` attribute, which is shorthand for avoiding providing a full …
> refactor(meshes): refactor meshes to use our newer patterns

- packages/kuma-gui/features/mesh/dataplanes/overview/ClusterNames.feature
- packages/kuma-gui/src/app/connections/data/index.ts
Sometimes clusterNames can have hashes after the port. This means some of our clusterName matching is a little too strict.
This PR remove the "end of line" match from our `_msvc_` regexp matching to make sure we also match services with hashes after the port.
Closes https://github.com/kumahq/kuma-gui/issues/3238
> fix(dataplanes): correct MeshService regexp based matching

- packages/kuma-gui/cypress/support/step_definitions/index.ts
- packages/kuma-gui/features/mesh/dataplanes/overview/summary/Clusters.feature
- packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryClustersView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionOutboundSummaryClustersView.vue
- packages/kuma-gui/src/app/data-planes/data/DataplaneNetworking.ts
- packages/kuma-gui/src/app/data-planes/sources.ts
Previously we were finding lines for inbounds in the cluster response by using the `kuma.io/service` name. We should just be using `localhost_<port>`.
There are few more semi-related things here which I've also noted inline:
- Altered a e2e test step so we can look for non-existence of text
- Upgraded DataSource usage to use `uri` for better type checking.
- Made both Inbound and Outbound views as consistent as possible.
> fix(dataplanes): Correct Dataplane Inbound cluster tab filter

- package-lock.json
- packages/config/package.json
- packages/config/src/eslint.cjs
- packages/config/src/package.schema.json
- packages/kuma-gui/mk/check.mk
- packages/kuma-gui/package.json
Honestly I'm not a huge fan of linting, a lot of rules that people use are either unnecessary or over-zealous. Not only that but it always means depending on lots of things like `eslint`, which you then have to maintain (dependabot PRs etc etc), just for the sake of not caring too much about things like having alphabetically ordered import statements.
Now I've got that off my chest 😅 , I do agree that there are sometimes use cases for specific rules to prevent mistakes that can lead to genuine bugs.
This use case:
Over the past couple of years we've had several issues with duplicate dependencies appearing in our package lock file. They are easy to miss in PR reviews, and a lot of the time people don't realise that hainvg duplicate dependencies can cause very hard to spot issues (in our …
> chore: lint package.json versions to only allow caret semvers

- packages/kuma-gui/src/app/kuma/components/ApplicationShell.vue
This removes a duplicate slot `#notifications` from the `ApplicationShell` component. This caused that when using the slot, the notification would appear twice.
This is probably a leftover from an attempt to resolve conflicts of merge or rebase.
> fix(app-shell): duplicate slot notifications

- packages/kuma-gui/src/app/application/index.ts
- packages/kuma-gui/src/app/data-planes/routes.ts
- packages/kuma-gui/src/app/subscriptions/routes.ts
- packages/kuma-gui/src/app/vue/index.ts
Back in https://github.com/kumahq/kuma-gui/pull/3151 we introduced the concept of 'route walkers'. These walk over every single route in your entire routing tree, giving you the opportunity to mutate or otherwise tweak a piece of routing config from The Outside.
When we made https://github.com/kumahq/kuma-gui/pull/3151, we noted we'd added the 'route walker' concept plus 2 walkers at our 'vue' level (i.e. in our `vue` module), even though the 2 walkers are specific to our `application` module.
This PR splits the concept and the application level implementations using a `$.routeWalkers` dependency injection label. 
This means we can dynamically add/remove different routeWalkers at the service container level, which will be very useful moving forwards.
---
I also added one more walker than …
> chore: Formalize 'route walkers' a little more

- packages/kuma-gui/src/app/x/components/x-tabs/XTabs.vue
See PR preview in https://github.com/kumahq/kuma-gui/pull/3289
The above PR added a little underline on hover/focus to our tabs, this removes it.
---
Ideally we wouldn't have to do this but our "global" stylesheet is a little too "catch all". The fix here fixes the issue without leading to a tonne of churn, but I commented in a note so that if/when we make our global styling different, we can remove this.
> fix: remove underline from KTabs

- packages/kuma-gui/public/mockServiceWorker.js
After installing the updated version of `msw@2.6.8` there are changes in the generated `mockServiceWorker.js` due to `postinstall` script. These are missing in https://github.com/kumahq/kuma-gui/pull/3287 and this PR will backfill them.
> chore(public/msw): update generated msw after version update

- package-lock.json
As reported in https://github.com/kumahq/kuma-gui/security/dependabot/103 both `3.3.8` and `5.0.9` are fixed versions. Using `npm update nanoid` bumps `nanoid` to non-vulnerable versions:
_Before_
```shell
kuma-gui
└─┬ @kumahq/kuma-gui@2.10.0 -> ./packages/kuma-gui
├─┬ @kong/kongponents@9.14.20
│ └── nanoid@5.0.8
└─┬ postcss@8.4.49
└── nanoid@3.3.7
```
_After_
```shell
kuma-gui
└─┬ @kumahq/kuma-gui@2.10.0 -> ./packages/kuma-gui
├─┬ @kong/kongponents@9.14.20
│ └── nanoid@5.0.9
└─┬ postcss@8.4.49
└── nanoid@3.3.8
```
> chore(deps): bump nanoid to non-vulnerable versions

- OWNERS.md
Add Moritz Fleck as Kuma-GUI maintainer.
Moritz Fleck
Email: [moritz.fleck@konghq.com](mailto:moritz.fleck@konghq.com)
Github: schogges
I wish to become a Kuma-GUI project maintainer to better engage in the discussions, contributions, code reviews for substantial time.
Here are my significant contribution PRs and Issues for this project:
- https://github.com/kumahq/kuma-gui/pull/2545
- https://github.com/kumahq/kuma-gui/pull/2565
- https://github.com/kumahq/kuma-gui/pull/3160
- https://github.com/kumahq/kuma-gui/pull/3202
- https://github.com/kumahq/kuma-gui/pull/3203
- https://github.com/kumahq/kuma-gui/pull/3213
> chore: update owners

- packages/kuma-gui/package.json
I remembered to check this thing (see changeset).
Just to note for future-self, this is why we should only use these sorts of things (`resolutions`/`overrides` etc) as an absolute last resort. They are easy to forget about and from what I understand, we could very easily end up being pinned below `0.8.0` for a longer period of time, especially if folks forget why this was ever here in the first place.
---
While triple checking this I also saw some further comment that I'm adding here for future-self, its more recommendation as to using carets should it ever come up again in a hokey cokey type way.
> WHY USING STRICT CONSTRAINT IS BAD?
> Strict constraint (or fully qualified constraint) are those constraints matching only one version. In most case it is a bad idea to use them.
> 
> …
> chore(deps): removes override for cookie

- package-lock.json
- packages/config/package.json
Since we are not using `standard` but `eslint` and `eslint-config-standard`, we can remove the dependency to `standard`.
> chore(deps): remove standard

- packages/config/src/eslint.cjs
- packages/kuma-gui/src/app/x/components/x-code-block/ResourceCodeBlock.vue
We recently noticed that `console` statements are not catched in `.vue` files inside the `template` (although catched in `script`) (xref: https://github.com/kumahq/kuma-gui/pull/3300#discussion_r1887136806).
> chore(config/eslint): add vue/no-console

- packages/kuma-gui/src/app/kuma/components/ApplicationShell.vue
Potentially temporary fix for the main nav appearing during onboarding. There are a few other bits that I've spotted I think but wanted to get this up first.
> fix(onboarding): fix menu appearing during onboarding

- packages/kuma-gui/src/app/data-planes/views/DataPlaneListView.vue
- packages/kuma-gui/src/app/services/views/MeshMultiZoneServiceListView.vue
- packages/kuma-gui/src/app/services/views/MeshMultiZoneServiceSummaryView.vue
- packages/kuma-gui/src/app/services/views/MeshServiceListView.vue
- packages/kuma-gui/src/app/services/views/MeshServiceSummaryView.vue
- packages/kuma-gui/src/app/x/components/x-layout/XLayout.vue
We recently found out that `KTruncate` also applies a margin/gap the same as `XLayout` (and we want to keep the same value for gap whether we are using `KTruncate` or not).
Therefore I felt it made sense to combine `KTruncate` with `XLayout` via a `:truncate` property.
Therefore whether you have elements require truncation or not, you use the same component and they will have the same gap spacing
> chore: merges KTruncate into XLayout

- .github/workflows/dispatch-merged-pr-notification.yml
There's no reason not to use push here.
> ci(github): use push for dispatching new commits

- .github/workflows/dispatch-merged-pr-notification.yml
Backport of https://github.com/kumahq/kuma-gui/pull/3355 to release-2.9
> ci(github): [backport/2.9] use push for dispatching new commits (#3355)

- .github/workflows/dispatch-merged-pr-notification.yml
Backport of https://github.com/kumahq/kuma-gui/pull/3355 to release-2.8
> ci(github): [backport/2.8] use push for dispatching new commits (#3355)

- .github/workflows/dispatch-merged-pr-notification.yml
Backport of https://github.com/kumahq/kuma-gui/pull/3355 to release-2.7
> ci(github): [backport/2.7] use push for dispatching new commits (#3355)

- .github/workflows/dispatch-merged-pr-notification.yml
Backport of https://github.com/kumahq/kuma-gui/pull/3355 to release-2.6
> ci(github): [backport/2.6] use push for dispatching new commits (#3355)

- .github/workflows/dispatch-merged-pr-notification.yml
Backport of https://github.com/kumahq/kuma-gui/pull/3355 to release-2.5
> ci(github): [backport/2.5] use push for dispatching new commits (#3355)

- .github/workflows/dispatch-merged-pr-notification.yml
Backport of https://github.com/kumahq/kuma-gui/pull/3355 to release-2.4
> ci(github): [backport/2.4] use push for dispatching new commits (#3355)

- .github/workflows/dispatch-merged-pr-notification.yml
Backport of https://github.com/kumahq/kuma-gui/pull/3355 to release-2.3
> ci(github): [backport/2.3] use push for dispatching new commits (#3355)

- .github/workflows/dispatch-merged-pr-notification.yml
Backport of https://github.com/kumahq/kuma-gui/pull/3355 to release-2.2
> ci(github): [backport/2.2] use push for dispatching new commits (#3355)

- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsBuiltinGateway.feature
- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsStandardProxy.feature
- packages/kuma-gui/features/mesh/dataplanes/DataplanePolicies.feature
- packages/kuma-gui/src/test-support/FakeKuma.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/dataplanes/_/_overview.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/dataplanes/_/policies.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/dataplanes/_overview.ts
We've had a couple of minor CSS bugs lately that have arisen because the randomized mocks weren't ever giving us certain states (generally we try to make the mocks return all types or data randomly so we see things like these bugs happen during development).
See:
- https://github.com/kumahq/kuma-gui/pull/3298
- https://github.com/kumahq/kuma-gui/pull/3326
This improves the mocks by:
- Further removing usage of the `.dataplaneNetworking()` function, that does too much and hides things away from where you are (i.e. Loss of Locality) This also makes it easier to use synced state across multiple HTTP requests using the faker seed.
- Adds missing variations of data so the variation that caused these issue becomes noticeable.
> chore(mocks): improves mocking for dataplane.networking

- .github/workflows/dispatch-merged-pr-notification.yml
Follow up of https://github.com/kumahq/kuma-gui/pull/3355
I think because we changed the event type, we no longer need the conditional/guard here.
> ci: remove old notification merge guard

- package-lock.json
- packages/config/package.json
See title
Missed to install `@eslint/js` and `globals` in #3373
> chore(config/deps): explicitely install globals, @eslint/js

- .github/workflows/main.yml
- Makefile
- mk/index.mk
- package-lock.json
- packages/config/.lintstagedrc.json
- packages/config/Makefile
- packages/config/eslint.config.cjs
- packages/config/package.json
- packages/config/scripts/ci.cjs
- packages/config/src/eslint.cjs
- packages/config/src/stylelint.cjs
- packages/kuma-gui/mk/check.mk
- packages/kuma-gui/mk/install.mk
The main goal of this change is to add linting for the `config` package. While doing this I wanted to take the chance and add a few more things:
1. Root `Makefile` for root operations `install` and `clean` for easy cleaning and reinstallation of dependencies
2. Add rule `import/no-extraneous-dependencies` to error in case we make use of a module without installing it beforehand. This caused some issues already and a first fix was added with #3381. But also here I have to install `glob` as it wasn't listed in the config's dependency list, but is imported in [packages/config/scripts/ci.cjs#L1](https://github.com/kumahq/kuma-gui/blob/36911e6e113bdf823e98233d2eac4543acb588b4/packages/config/scripts/ci.cjs#L1).
3. Linting of staged files in `packages/config`
4. Auto-fixing some linting issues …
> chore: lint config package

- packages/kuma-gui/src/app/data-planes/locales/en-us/index.yaml
- packages/kuma-gui/src/app/data-planes/sources.ts
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailTabsView.vue
Adds another few minor amends to bundle downloading:
- Text amends
- Default most options to ticked
- Add JSON whitespace to downloaded XDS config file so you have a chance of reading it when you open it
> chore(dataplanes): minor amends to dataplane download bundling

- package-lock.json
- package.json
FYI: You will only see a warning for the issue here if you run `make install` with completely clean `node_modules`
---
I chose to put the override in the root package.json, I also had to run `npm dedupe` several times to get it to "stick" so unfortunately quite a lot of churn in the package-lock.json.
I just looked at it myself, and there are lots of downgrades of some transitive dependencies here (as well as upgrades). I would assume these still satisfy the semver ranges for everything and are a consequence of the dedupe's.
Ideally I'd like less churn here though, so if there are any suggestions/ideas for trying to get a smaller changeset I'd be very grateful. Otherwise I think this is probably still good as it seems like the changed deps are mostly (at least) dev/tooling deps.
> chore(deps): upgrade reflect-metadata

- packages/kuma-gui/features/application/MainNavigation.feature
- packages/kuma-gui/features/mesh/dataplanes/overview/summary/Clusters.feature
- packages/kuma-gui/src/app/connections/routes.ts
- packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryClustersView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryStatsView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryXdsConfigView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionOutboundSummaryClustersView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionOutboundSummaryStatsView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionOutboundSummaryView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionOutboundSummaryXdsConfigView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionsClustersView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionsStatsView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionsXdsConfigView.vue
- packages/kuma-gui/src/app/data-planes/routes.ts
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailTabsView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneInboundSummaryOverviewView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneOutboundSummaryOverviewView.vue
This PR has no user visible changes, and is purely moving files around in order to make them more reusable. Its a piece of work working towards https://github.com/kumahq/kuma-gui/issues/3321
All changes are related to making any XDS Config, Stats and Clusters pages resuable across Dataplanes and ZoneIngress/Egress areas.
- Use `<RouteView name="prop.routeName" />` in views I'm planning to reuse in several routes.
- Uses route prefixing in related route configuration.
- Moves remaining `DataPlaneStatsView` etc into `ConnectionStatsView`, these will be reusable across DPPs/Zones.
- Moves `ConnectionInbound/OutboundSummaryOverview` back to `DataPlaneInbound/OutboundSummaryView`. These files are very specific to DDPs only as they display Rules. These therefore belong in the dataplane module, …
> chore(dataplanes): refactor out reusable routes

- .github/workflows/release.yml
Remove some indirections using branches for checkout when we have a SHA and extract params as env vars.
This also makes the workflows more secure
> ci(github): simplify release.yaml

- packages/kuma-gui/src/app/application/components/route-view/RouteView.vue
- packages/kuma-gui/src/app/application/index.ts
- packages/kuma-gui/src/app/application/services/storage/index.ts
- packages/kuma-gui/src/app/me/index.ts
- packages/kuma-gui/src/app/me/sources.ts
This PR allows us to source certain parameters from localStorage to use for defaults for a page. This functionality isn't used as yet, as in this PR we don't actually save any parameters to localStorage (we will add these later)
For example, if you set your page to `75` on one listing, chances are you probably want that to say as `75` throughout the application for all listings.
There are several interesting things that we backwards and forwards with a bit (even this morning), so I'll try detail a little bit.
- Preferably, we want to always use declarative `DataSource` to access external data, this includes localStorage data which is external to the main Javascript execution.
- We want it to be as easy as possible to use as a consumer, ie. someone building features for our application.
- …
> feat(application): source default URL params from storage

- Makefile
- packages/config/Makefile
- packages/config/scripts/ci.cjs
- packages/config/src/index.cjs
- packages/config/src/mk/help.mk
- packages/config/src/mk/install.mk
- packages/config/src/mk/release.mk
- packages/config/src/mk/test.mk
- packages/kuma-gui/Makefile
I stumbled across quite a few things whilst fixing up our `clean` script so:
1. It can be run from any sub-package (like `make install`)
2. It didn't echo the warning message twice in certain environments
I have a longer term goal of making our "wiring root" Makefiles easier to maintain (there might end up being lots of them) and possibly creating them from a template. This goal means that the less path differences etc (`../` over here, `./` over there) the better. This has influenced some decisions here.
In order to run `make clean` from anywhere and it automatically do this from root, we need to know where root is, from wherever we are. This led me to using `npm prefix` for `NPM_WORKSPACE_ROOT`. This led me to realize a `NPM_WORKFLOW_CONFIG_PATH` that I'd not noticed in a previous PR, …
> chore(ci): various makefile improvements

- Makefile
- packages/config/Makefile
- packages/config/scripts/ci.cjs
- packages/config/scripts/prune.cjs
- packages/config/src/index.cjs
- packages/config/src/mk/help.mk
- packages/config/src/mk/release.mk
- packages/kuma-gui/Makefile
Follow up of https://github.com/kumahq/kuma-gui/pull/3410
---
Turns out `npm query` requires your `node_modules` to be present, I've no idea why 🤷 , and we have a target that we sometimes run that needs to run before a `make install` (`make release/prune`) 🤦 .
I saw that you can add a `npm --package-lock-file-only query` to get it to use the lock file instead of needing access to `node_modules`. This works when running from workspace root without `node_modules`, but when you run a Makefile from a sub project without `node_modules` adding this arg/flag still fails 🤷 
I've fallen back to just jq-ing the package-lock.json myself at least for the moment so we can unblock the release workflow. If I find a slightly nicer way to do this in the future I'll replace, but I really want to stick to …
> fix(ci): fix release/prune which runs before make install

- packages/config/scripts/prune.cjs
- packages/config/src/mk/release.mk
Last two little amends to the pruning we do for release:
- Prettify the JSON
- `rm` and replace package.json instead of using a single command (can cause issues elsewhere)
> fix(ci): fix release/prune amends

- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsStandardProxy.feature
- packages/kuma-gui/features/mesh/dataplanes/Index.feature
- packages/kuma-gui/features/mesh/dataplanes/NoSubscriptions.feature
- packages/kuma-gui/features/onboarding/dataplanes-overview/Index.feature
Over the past weeks we have noticed some flakes of our browser tests where the assertion was mainly about a state being `online`. I have traced it down to a mismatch of our payload type. In our tests we always set the state that we want to assert for in `dataplane.inbound.health.state`, but according to our type in [data-planes](https://github.com/kumahq/kuma-gui/blob/26976933fb563768d5f09099f2d7d28c11545bcd/packages/kuma-gui/src/app/data-planes/data/DataplaneNetworking.ts#L13) there is no entry `health`. The `state` can be found in `dataplane.inbound.state`.
Example:
Closes #3376
> fix: flaky tests due to mismatch of payload type

- packages/kuma-gui/cypress/support/step_definitions/index.ts
- packages/kuma-gui/features/zones/zone-cps/ingresses/ZoneIngressSummary.feature
- packages/kuma-gui/src/app/x/components/x-layout/XLayout.vue
- packages/kuma-gui/src/app/zone-ingresses/locales/en-us/index.yaml
- packages/kuma-gui/src/app/zone-ingresses/views/ZoneIngressSummaryView.vue
This is part of the efforts to allow the user using the preferred format of showing the config: `structured` vs `yaml` and adds a dropdown menu to select between `structured` and `yaml` in the `ZoneIngressSummaryView`.
Part of #3283
> feat(zone-ingress-summary-view): use dropdown to select config format

- packages/kuma-gui/src/app/application/components/app-collection/AppCollection.vue
- packages/kuma-gui/src/app/application/components/app-view/AppView.vue
- packages/kuma-gui/src/app/application/components/data-source/DataLoader.vue
- packages/kuma-gui/src/app/common/ErrorBlock.vue
- packages/kuma-gui/src/app/common/ResourceStatus.vue
- packages/kuma-gui/src/app/kuma/components/ApplicationShell.vue
- packages/kuma-gui/src/app/x/components/x-about-card/XAboutCard.vue
- packages/kuma-gui/src/app/x/components/x-action-group/XActionGroup.vue
- packages/kuma-gui/src/app/x/components/x-alert/XAlert.vue
- packages/kuma-gui/src/app/x/components/x-breadcrumbs/XBreadcrumbs.vue
- packages/kuma-gui/src/app/x/components/x-code-block/XCodeBlock.vue
- packages/kuma-gui/src/app/x/components/x-empty-state/XEmptyState.vue
- packages/kuma-gui/src/app/x/components/x-i18n/XI18n.vue
- packages/kuma-gui/src/app/x/components/x-modal/XModal.vue
- packages/kuma-gui/src/app/x/components/x-select/XSelect.vue
- packages/kuma-gui/src/app/x/components/x-tabs/XTabs.vue
Required for https://github.com/kumahq/kuma-gui/pull/3336
I got a bit more time to look at https://github.com/kumahq/kuma-gui/pull/3336 and it looks like Vue folks are moving more and more to macro-based `defineSlots` for defining slots.
Moving everything to use defineSlots worked in most areas and I only had to define the types also for areas where we actually need the type information, otherwise defineSlots is a `Record<string, any>` (see https://vuejs-language-tools.vercel.app/features/slots#how-to-handle-indeterminate-slot-types)
There 'may' be some other places where it would be advantageous to define our slots as more than `Record<string, any>` but for the moment this is enough to unblock the upgrade. We can add any more type information if required in later PRs.
Also see …
> fix(deps): uses defineSlots macro over useSlots

- packages/kuma-gui/src/app/application/components/data-collection/DataCollection.vue
This is actually a bug/incorrect configuration/usage of `XLayout` within `DataCollection`.
I made sure the immediate children of `XLayout` are within the `DataCollection`. i.e. I added two divs, the second one isn't necessary as KPagination is a single block level element, but I wanted to keep _both_ immediate children visible within `DataCollection`.
> fix(policies): fixes padding for policy type list

- packages/kuma-gui/docs/1-tldr.md
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/kuma/views/KumaNotFoundView.vue
- packages/kuma-gui/src/app/x/README.md
- packages/kuma-gui/src/app/x/components/x-empty-state/XEmptyState.vue
- packages/kuma-gui/src/app/x/components/x-icon/XIcon.vue
- packages/kuma-gui/src/app/x/components/x-tooltip/README.md
- packages/kuma-gui/src/app/x/components/x-tooltip/XTooltip.vue
- packages/kuma-gui/src/app/x/index.ts
- packages/kuma-gui/src/app/zones/views/ZoneDetailView.vue
I went through and moved (almost) any remaining K components to use X components instead.
We still use K components in two instances:
1. In Onboarding (we are removing onboarding soon https://github.com/kumahq/kuma-gui/issues/3386 so I didn't bother doing this here)
2. KTable usage in a view in the Policy module. There are ongoing ideas for how we go about possibly doing something with KTable and AppCollection which may or may not end up being `XTable` and `<XCollection :variant="table">`
I noticed a couple of other things whilst doing this and amended here seeing as this is one of those "random bits" PRs, please ask if anything isn't clear 👍
> chore: Several small cleanup amends around K named components

- package-lock.json
- packages/config/package.json
- packages/config/src/eslint.cjs
- packages/kuma-gui/.vitepress/theme/components/Story.vue
- packages/kuma-gui/src/app/application/components/route-view/RouteView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneListView.vue
- packages/kuma-gui/src/app/gateways/views/GatewayListTabsView.vue
- packages/kuma-gui/src/app/hostname-generators/views/HostnameGeneratorListView.vue
- packages/kuma-gui/src/app/kuma/components/ApplicationShell.vue
- packages/kuma-gui/src/app/meshes/views/MeshDetailView.vue
- packages/kuma-gui/src/app/meshes/views/MeshListView.vue
- packages/kuma-gui/src/app/onboarding/components/OnboardingAlert.vue
- packages/kuma-gui/src/app/onboarding/views/OnboardingMultiZoneView.vue
- packages/kuma-gui/src/app/policies/views/PolicyListView.vue
- packages/kuma-gui/src/app/services/views/MeshExternalServiceListView.vue
- packages/kuma-gui/src/app/services/views/ServiceListTabsView.vue
- packages/kuma-gui/src/app/x/components/x-code-block/XCodeBlock.vue
- packages/kuma-gui/src/app/x/components/x-code-block/highlightElement.ts
- packages/kuma-gui/src/app/x/components/x-empty-state/README.md
- packages/kuma-gui/src/app/x/components/x-empty-state/XEmptyState.vue
- packages/kuma-gui/src/app/x/components/x-i18n/XI18n.vue
- packages/kuma-gui/src/app/zone-egresses/views/ZoneEgressListView.vue
- packages/kuma-gui/src/app/zone-ingresses/views/ZoneIngressListView.vue
- packages/kuma-gui/src/app/zones/views/ZoneConfigView.vue
- packages/kuma-gui/src/app/zones/views/ZoneDetailTabsView.vue
- packages/kuma-gui/src/app/zones/views/ZoneDetailView.vue
- packages/kuma-gui/src/app/zones/views/ZoneListView.vue
Part of https://github.com/kumahq/kuma-gui/issues/2813
This PR uses `<XI18n />` (https://github.com/kumahq/kuma-gui/pull/3420) throughout the application in place of `v-html`. 
I also turned our `vue/no-v-html` to `error` (it only warns by default)
This means we can start using "non-DNS safe" terms/vars for our i18n texts if we need to do that.
---
I also switched some usages of `innerHTML` to use `textContent` which, aside from other things, is apparently more performant, so may help further speed up our CodeBlock component.
Finally, I added `eslint-plugin-no-unsanitized`, i.e. if we are linting for `v-html` we should also lint for `innerHTML`, can't really depend on one without the other.
There'll be a separate PR to start using `<XI18n v-slot="{ t }" />` within non-route component (in …
> chore: uses XI18n component pt1

- package-lock.json
- packages/kuma-gui/package.json
- packages/kuma-gui/src/app/application/components/app-navigator/AppNavigator.vue
Removes autoprefixer and manually adds a prefix `-webkit-mask-image` in the only place where we weren't manually adding a `-webkit` prefix where potentially necessary.
Configuration for `autoprefixer` was removed back here https://github.com/kumahq/kuma-gui/pull/384/files#diff-05ed1c7f99e45b485708115502a1e0f28c8547e9a9a29c1b8664f79103cf7873, but the dependency wasn't, this means we've not been using autoprefixer for quite a while but [dutifully upgrading it in dependabot](https://github.com/kumahq/kuma-gui/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Fdependabot+autoprefixer).
All in all its less hassle to manually prefix than to support the dependency, especially considering that as prefixing is now generally frowned upon by browser vendors we are less and less likely to need to add vendor …
> chore(deps): remove autoprefixer

- package-lock.json
- packages/config/src/eslint.cjs
- packages/kuma-gui/.vitepress/config.ts
- packages/kuma-gui/.vitepress/theme/main.md
- packages/kuma-gui/package.json
- packages/kuma-gui/src/app/App.vue
- packages/kuma-gui/src/app/application/components/data-source/DataSource.vue
- packages/kuma-gui/src/app/application/index.ts
- packages/kuma-gui/src/app/vue/index.ts
- packages/kuma-gui/src/app/x/components/x-action-group/README.md
- packages/kuma-gui/src/app/x/components/x-action/README.md
- packages/kuma-gui/src/app/x/directives/style/README.md
- packages/kuma-gui/src/app/x/directives/style/index.ts
- packages/kuma-gui/src/app/x/index.ts
Adds a `v-style` directive to allow us to set occasional inline styles within a strict CSP environment.
Additionally makes it easy to add simple CSS transitions that often require waiting a tick before applying a rule.
Note: There are a couple of unrelated changes here that I bumped into whilst working on this. Happy to split those off if necessary.
~**P.S. I need to add some sort of `Set.difference` polyfill here, its a bit new at the moment.**~ 👈 this is done
~**P.P.S. Cypresses ~Chrome~ Electron (ooooh it uses Electron 🤔 ) doesn't support Set.difference either so it also failed our tests 🎉  **~
> feature: adds v-style directive

- packages/kuma-gui/src/app/common/TagList.vue
Introduced in https://github.com/Kong/kongponents/pull/2585
I've mentioned a few times I kinda have a different approach to solve this sort of stuff completely, I might put up a draft PR soon.
Related to:
- https://github.com/Kong/kongponents/issues/2559
- https://github.com/kumahq/kuma-gui/pull/3323
- https://github.com/kumahq/kuma-gui/pull/3317
> fix: maintain tag anchor and key:value styling in KBadges

- packages/kuma-gui/src/app/application/components/route-view/RouteView.vue
I noticed that our GH Star button was flickering again, which means we are re-rendering parts of the application that don't need re-rendering.
The fix here adds a wrapping function which needs calling in order to access the value, meaning we don't get unnecessary re-renders.
> fix: wrap RouteView::from in a function to prevent it causing a rerender

- .github/dependabot.yml
In order to reduce the amount of individual dependabot PRs and to update companion packages in one go, we can group them. With this we are now starting to group all `@typescript-eslint/*` dependencies.
> chore(dependabot): group all @typescript-eslint dependencies

- packages/kuma-gui/src/app/services/views/MeshMultiZoneServiceListView.vue
The MeshMultizoneService listing was not showing paging correctly. Turns out this section was missed in the original PR for this refactor around pagination:
https://github.com/kumahq/kuma-gui/pull/2846
> fix(services): adds missing paging to MeshMultizoneService

- packages/kuma-gui/src/app/data-planes/views/DataPlaneListView.vue
- packages/kuma-gui/src/app/gateways/views/GatewayListTabsView.vue
- packages/kuma-gui/src/app/hostname-generators/views/HostnameGeneratorListView.vue
- packages/kuma-gui/src/app/kuma/locales/en-us/index.yaml
- packages/kuma-gui/src/app/meshes/views/MeshListView.vue
- packages/kuma-gui/src/app/policies/views/PolicyListView.vue
- packages/kuma-gui/src/app/services/views/ServiceListTabsView.vue
- packages/kuma-gui/src/app/x/components/x-empty-state/XEmptyState.vue
- packages/kuma-gui/src/app/x/components/x-i18n/XI18n.vue
- packages/kuma-gui/src/app/zone-egresses/views/ZoneEgressListView.vue
- packages/kuma-gui/src/app/zone-ingresses/views/ZoneIngressListView.vue
- packages/kuma-gui/src/app/zones/views/ZoneListView.vue
We noticed this:
which is the thing we are fixing here, but its a bit of a longer story due to what Xi18n should be doing.
---
The bug is that we aren't using a `:` here:
https://github.com/kumahq/kuma-gui/blob/603c39571c34fcdfad9eeafccf02ee4453fdc17b/packages/kuma-gui/src/app/policies/views/PolicyListView.vue#L68
At first I was like "I can just add the `:` and job done", but then I was like "wait a second that means I can pass unencoded text into `default-message` using a normal `t` and `XI18n` will blindly render it, therefore bypassing any encoding.
This means we can't give `XI18n` a `default-message` prop, because we can't guarantee that its encoded correctly (i.e. sometimes we can use `t` which will encode it, but if we need some HTML in the string that `t` returns, then we can't …
> fix: changes Xi18n's default-message prop to default-path

- Makefile
- packages/config/src/mk/decorators.mk
This target calls a Makefile target on all packages within the workspace:
i.e. `make ws/lint` will run `make lint` on all packages. If the target doesn't exist, the command will fail only for that sub-package.
> feat(tools): adds "execute on all workspaces" Makefile decorator

- packages/kuma-gui/src/app/x/components/x-tabs/XTabs.vue
Several people have reported issue with being able to click on our tab component i.e. you have to click exactly on the text instead of being able to click on the entire button.
A recent kongponent update (https://github.com/Kong/kongponents/pull/2532) changed the padding of certain HTML elements, which removed the padding from our anchor links and added it to the surrounding div instead, meaning whilst it looked like you could click on the entire button to click the anchor, you where actually clicking the div, meaning the anchor wasn't navigating.
Also see https://github.com/Kong/kongponents/pull/2532/files#diff-01f83cc2092a263bfd47c1d0a4ba5e96dea98264d85282662a63f4fa18c44dedR177
This PR rearranges the padding using some overwrites to return the anchor its previous padded state.
There is …
> fix: removes extra padding adding via kongponents update

- packages/kuma-gui/src/app/x/components/x-select/XSelect.vue
I found that KSelect `select` event would fire twice if you change the `items` as a result of the the first `select` event.
I would guess that KSelect could do something like firing a select event as a result of a non-user-interaction if you change the `selected` property of an `item`. So even though the menu has already been changed/selected by the user, if you change `items` immediately after to be the same as the user selection, it re-fires the same event. But kinda just guessing.
I moved XSelect to use a different approach which avoids using `items[].selected`, which fixes the issue, and I no longer see the double events.
From my investigation this issue doesn't seem to be affecting anything currently, but it'd best if our XSelect component didn't fire `change` twice.
> fix: prevents KSelect/XSelect from firing events twice

- packages/kuma-gui/src/app/me/sources.ts
The preferences stored on a route level did not get merged after splitting up sources and storage of `me` in #3408 . Using `merge` only allows to merge two objects. To merge more than two objects we have to use `merge.all` ([ref](https://www.npmjs.com/package/deepmerge#mergeallarrayofobjects-options)).
TypeScript would have catched that if we would have added another object, because of too many parameters. Unfortunately the options object is not strongly typed enough to catch `object` as `deepmerge.Options`.
> fix(me/sources): preferences stored on route level not merged

- packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryClustersView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryStatsView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryXdsConfigView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionOutboundSummaryClustersView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionOutboundSummaryStatsView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionOutboundSummaryXdsConfigView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionsClustersView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionsStatsView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionsXdsConfigView.vue
- packages/kuma-gui/src/app/data-planes/routes.ts
- packages/kuma-gui/src/app/data-planes/views/DataPlaneConfigView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailTabsView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneInboundSummaryOverviewView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneListView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneOutboundSummaryOverviewView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlanePoliciesView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneSummaryView.vue
- packages/kuma-gui/src/app/gateways/views/BuiltinGatewayDataplanesView.vue
- packages/kuma-gui/src/app/gateways/views/DelegatedGatewayDetailView.vue
- packages/kuma-gui/src/app/policies/views/PolicyDetailView.vue
- packages/kuma-gui/src/app/services/views/MeshServiceDetailView.vue
- packages/kuma-gui/src/app/services/views/ServiceDetailView.vue
Ideally we want to reuse some views used in dataplanes with some views used in zone-ingress/egrees (i.e. ZoneProxies). 
If we stand any chance of doing this without making some serious changes elsewhere, we need to make some more things similar.
This PR changes all instances of the `route.params.dataPlane` route parameter to instead use `route.params.proxy`. Back in https://github.com/kumahq/kuma-gui/pull/3509 we changed all the "zone proxy" views to also use the same name. At the end of the day Zone Proxies are just dataplanes i.e. they are essentially the same thing (an instance of Envoy).
I'm honestly not totally sure to what extent we'll be able to reuse still (edit: I found doing this is very helpful 😸 ), but at the very least this change gets rid of an awkward casing of `dataPlane`. …
> chore(dataplanes): change all refs of route.dataPlane > route.proxy

- packages/kuma-gui/src/app/application/components/route-view/RouteView.vue
- packages/kuma-gui/src/app/application/utilities/index.ts
- packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionOutboundSummaryView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionsXdsConfigView.vue
- packages/kuma-gui/src/app/connections/views/zones/ConnectionInboundSummaryView.vue
- packages/kuma-gui/src/app/connections/views/zones/ConnectionOutboundSummaryView.vue
- packages/kuma-gui/src/app/connections/views/zones/ConnectionOutboundSummaryXdsConfigView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/me/sources.ts
- packages/kuma-gui/src/app/zone-egresses/views/ZoneEgressDetailView.vue
- packages/kuma-gui/src/app/zone-ingresses/views/ZoneIngressDetailView.vue
Builds on the work we did in https://github.com/kumahq/kuma-gui/pull/3457 to allow us to persist default values of a `boolean` type.
I then used this for `inactive` (used in traffic views) and `includeEds` (used in XDSConfig views)
> chore: add boolean default storage route.params

- package-lock.json
After running `make install` I've noticed a diff in the lock-file. When running `npm ci` (clean install), I got the following result indicating that our lock-file is not in sync with versions specified in package.json files.
```shell
$ npm ci
...
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Invalid: lock file's typescript-eslint@8.21.0 does not satisfy typescript-eslint@8.23.0
npm ERR! Invalid: lock file's @typescript-eslint/utils@8.21.0 does not satisfy @typescript-eslint/utils@8.23.0
npm ERR! Invalid: lock file's @typescript-eslint/scope-manager@8.21.0 does not satisfy …
```
> chore(deps): sync lock-file

- .github/workflows/codeql.yml
- .github/workflows/dispatch-merged-pr-notification.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- packages/kuma-http-api/Makefile
- packages/kuma-http-api/eslint.config.cjs
Integrates work from https://github.com/kumahq/kuma-gui/pull/3545 into CI.
Also, while I was there I did a few nitty cleanup things:
- made 99.9% of arrays a uses linewise YAML arrays consistently (i.e. `-` vs `[]`)
- consistently moved `concurrency:` to the same places in all workflows
- changed the name of the `main.yml` workflow to `main` (the name is used for cross-referencing in another workflow). It seemed to me to be a good idea to keep the name of the workflow the same as the name of the file.
- ...possibly another couple of teensy tiny nitty things.
> chore(ci): integrates further package linting

- package-lock.json
- package.json
Adds an override for esbuild, then runs `npm dedupe` which dupes quite a few deps most importantly dedupes `esbuild` to 0.25.0.
I tried just using `npm install` but even with the override it wasn't sticking, `npm dedupe` on the otherhand did the trick.
> chore(deps): overrides esbuild and runs npm dedupe

- packages/kuma-gui/src/app/data-planes/locales/en-us/index.yaml
- packages/kuma-gui/src/app/data-planes/sources.ts
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailTabsView.vue
- packages/kuma-gui/src/app/zone-egresses/locales/en-us/index.yaml
- packages/kuma-gui/src/app/zone-egresses/sources.ts
- packages/kuma-gui/src/app/zone-egresses/views/ZoneEgressDetailTabsView.vue
- packages/kuma-gui/src/app/zone-ingresses/locales/en-us/index.yaml
- packages/kuma-gui/src/app/zone-ingresses/sources.ts
- packages/kuma-gui/src/app/zone-ingresses/views/ZoneIngressDetailTabsView.vue
Similar to https://github.com/kumahq/kuma-gui/pull/3329 this PR adds downloadable "bundles" to both Zone Ingresses and Zone Egresses.
Pretty much a copy/pasta of the Dataplanes view. But I changed the Dataplanes view to use the key `proxies` instead of `dataplane` for consistency. Also, zone proxies don't have policies as an option to download.
Closes https://github.com/kumahq/kuma-gui/issues/3523
> feat(zones): Add downloadable bundles to zone proxies

- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailTabsView.vue
- packages/kuma-gui/src/app/x/components/x-download/README.md
- packages/kuma-gui/src/app/x/components/x-download/XDownload.vue
- packages/kuma-gui/src/app/x/index.ts
Adds a new `XDownload` component for downloading file blobs easily.
I've currently used it/provided an example in our Dataplanes downloading functionality, but it will also be rolled out to ZoneProxies (also see https://github.com/kumahq/kuma-gui/pull/3547)
This PR can go in before (and https://github.com/kumahq/kuma-gui/pull/3547 be rebased) or after https://github.com/kumahq/kuma-gui/pull/3547.
---
One thing I was unsure of was the name of the `start` event. I went through MDN looking for a name that felt HTML-like, and came up with `start` if anyone has suggestions for a name, that I like better than `start`, please lemme know!
> feat: add XDownload component for downloading blobs

- packages/kuma-gui/features/main-overview/DetailViewContent.feature
- packages/kuma-gui/src/app/common/DefinitionCard.vue
- packages/kuma-gui/src/app/common/ResourceStatus.vue
- packages/kuma-gui/src/app/control-planes/components/ControlPlaneStatus.vue
- packages/kuma-gui/src/app/control-planes/data/index.ts
- packages/kuma-gui/src/app/control-planes/locales/en-us/index.yaml
- packages/kuma-gui/src/app/control-planes/sources.ts
- packages/kuma-gui/src/test-support/FakeKuma.ts
- packages/kuma-gui/src/test-support/mocks/src/global-insight.ts
This introduces `Mesh*Services` to our vcp stats. As it can happen that we have a mix of `Mesh*Services` and legacy services in the meshes, I added the possibility to show both in the same `ResourceStatus` including a `#description`.
To achieve this I've made the `#title`-slot optional and added an optional `#description`-slot. With this it's possible to nest multiple `ResourceStatus` in a "main" `ResourceStatus` which keeps the same layout and styling and also the declarative approach of rendering things.
In case there are no `Mesh*Services` it only renders the number of the legacy services. In case there are no legacy services, but `Mesh*Services` it renders the number of `Mesh*Services` only.
Only in case there is a mix of both it renders the `description` for both including an info …
> feat(cp-stats): add mesh-services

- packages/kuma-gui/vite.plugins.ts
Adds stricter CSP headers to our development vite server.
Whilst this is dev time only, it ensures that our GUI runs on a similarly configured server (such as https://github.com/kumahq/kuma/issues/12553)
---
As mentioned in other places, it would be good to add work so we can remove the `style-src 'unsafe-inline'`. This will require a globally available `v-style` directive which adds/removes/modifies styles imperatively behind the scenes.
Testing:
Using `make run`, add the following or similar anchor with an inline script and click it.
> feature: adds dev-time CSP headers

- packages/kuma-gui/src/app/policies/views/PolicyTypeListView.vue
Make the `PolicyTypeListView` sticky to the top. This is a minor improvement to UX as the `PolicyTypeListView` serves as a navigation bar and opens a nested route to the right, which is another potentially large table. When scrolling the table it can happen that the `PolicyTypeListView` scrolls out of the viewport. To reach the navigation again, the user might have to scroll up again.
As there is currently nothing else rendered below the `PolicyTypeListView`, there is nothing that potentially interferes.
> feat(policy-type-list-view): make sticky

- packages/kuma-gui/features/application/Warnings.feature
- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsBuiltinGateway.feature
- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsDelegatedGateway.feature
- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsStandardProxy.feature
- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsTraffic.feature
- packages/kuma-gui/features/mesh/dataplanes/Warnings.feature
- packages/kuma-gui/features/onboarding/Index.feature
- packages/kuma-gui/features/zones/zone-cps/Warnings.feature
- packages/kuma-gui/src/app/application/components/app-view/AppView.vue
- packages/kuma-gui/src/app/application/services/storage/index.ts
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/kuma/components/ApplicationShell.vue
- packages/kuma-gui/src/app/me/sources.ts
- packages/kuma-gui/src/app/meshes/data/Mesh.ts
- packages/kuma-gui/src/app/meshes/data/index.spec.ts
- packages/kuma-gui/src/app/meshes/views/MeshDetailView.vue
- packages/kuma-gui/src/app/onboarding/components/OnboardingAlert.vue
- packages/kuma-gui/src/app/services/locales/en-us/index.yaml
- packages/kuma-gui/src/app/services/views/MeshExternalServiceListView.vue
- packages/kuma-gui/src/app/x/components/x-alert/XAlert.vue
- packages/kuma-gui/src/app/x/components/x-notification/README.md
- packages/kuma-gui/src/app/x/components/x-notification/XNotification.vue
- packages/kuma-gui/src/app/x/components/x-notification/XNotificationHub.vue
- packages/kuma-gui/src/app/x/index.ts
- packages/kuma-gui/src/app/zones/data/index.ts
- packages/kuma-gui/src/app/zones/views/ZoneConfigView.vue
- packages/kuma-gui/src/app/zones/views/ZoneDetailView.vue
This PR completely rebuilds our notifications and replaces all instances of our current ones to use the new approach. (I would guess there will be a further PR to amend where we put certain notifications, user-wise I've tried to keep things exactly the same for now)
---
The biggest question I have is surround notification dismissal.
For example, if I dismiss a notification about using the memory store for the `default` Mesh, I would guess I still would need to see a warning if I then created a new mesh called `johns-mesh`? If you carry this on, what about dismissal of notifications for a specific MeshExternalService?
I've tried to not to overthink it too much for now, and namespaced certain warnings (for example the Mesh example I gave above)
Closes …
> feat: add XNotification component

- packages/kuma-gui/src/app/policies/components/PolicySummary.vue
- packages/kuma-gui/src/app/policies/locales/en-us/index.yaml
- packages/kuma-gui/src/app/x/components/x-code-block/ResourceCodeBlock.vue
This is the first part and in a follow-up I'll add more view types for the config. Here I added the spec in a code block to the structured view, so the user can still get all information in this view and doesn't need to switch to YAML.
---
I added a prop to hide the `Copy as K8s` button from the code block. I think the spec is agnostic to universal and k8s.
---
Part of #3489
> feat(policy-summary): add spec to structured view

- packages/kuma-gui/features/zones/zone-cps/egresses/Index.feature
- packages/kuma-gui/features/zones/zone-cps/ingresses/Index.feature
- packages/kuma-gui/src/app/kuma/services/kuma-api/RestClient.ts
- packages/kuma-gui/src/app/zone-egresses/sources.ts
- packages/kuma-gui/src/app/zone-egresses/views/ZoneEgressListView.vue
- packages/kuma-gui/src/app/zone-ingresses/sources.ts
- packages/kuma-gui/src/app/zone-ingresses/views/ZoneIngressListView.vue
- packages/kuma-gui/src/test-support/mocks/src/zone-ingresses/_overview.ts
- packages/kuma-gui/src/test-support/mocks/src/zoneegresses/_overview.ts
- packages/kuma-gui/src/types/api.d.ts
Following https://github.com/kumahq/kuma/pull/12840 this PR adds support for proper paging of Zone Proxies via the GUI. Previousy we would just request a large number of Zone Proxies and filter for the ones we were interested in, with no paging (max of 100 proxies)
The GUI now pages Zone Ingresses and Zone Egresses just like any other resource in the GUI
Closes https://github.com/kumahq/kuma-gui/issues/3521
> feat(zones): adds filter based pagination to zone proxies

- packages/kuma-gui/features/zones/zone-cps/Warnings.feature
- packages/kuma-gui/src/app/kuma/locales/en-us/index.yaml
- packages/kuma-gui/src/app/zones/data/index.ts
When we receive a non-zero `total.responsesRejected` i.e. NACKs shows the following notification:
Note: I've implemented this using the same approach as before. Once I've added some other notifications in I aim to go through and re-organize at least the i18n a little more consistently.
Closes https://github.com/kumahq/kuma-gui/issues/2153
> feat(zones): show warning when NACKs are received

- packages/kuma-gui/src/app/data-planes/locales/en-us/index.yaml
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
When we've detected that you have a non-zero amount of outbounds with traffic, we show the following info level message, with links to documentation.
Closes https://github.com/kumahq/kuma-gui/issues/3513
> feat(data-planes): add recommendation to to use reachable-services

- packages/kuma-gui/src/app/meshes/locales/en-us/index.yaml
- packages/kuma-gui/src/app/meshes/views/MeshDetailView.vue
- packages/kuma-gui/src/test-support/FakeKuma.ts
- packages/kuma-gui/src/test-support/mocks/src/mesh-insights/_.ts
- packages/kuma-gui/src/test-support/mocks/src/resources.ts
Refactors the MTP notification we have when you have mTLS enabled but no MeshTrafficPermission.
---
While I was doing this I noticed that the faker `policyNames` code wasn't quite the same interface as faker, and I think the randomness wasn't quite working because max was defaulting to a super big value (which I think meant a low chance of getting low numbers) so I made some slight changes there after I looked in fakers code to see exactly how they do this and then made a `maxmin` helper to replicate fakers types/functionality so we keep the same interface everywhere.
This meant:
1. Altering slightly the `{ min, max }` args and how they are defaulted.
2. Using `Number.MAX_SAFE_INTEGER` over `Number.MAX_VALUE` as a "give me all the things" placeholder
3. If you use …
> refactor(meshes): slightly refactors MTP notification

- packages/kuma-gui/.env
- packages/kuma-gui/src/app/application/services/env/Env.ts
- packages/kuma-gui/src/app/application/services/env/env.spec.ts
- packages/kuma-gui/src/app/application/services/i18n/I18n.ts
- packages/kuma-gui/src/app/application/utilities/index.spec.ts
- packages/kuma-gui/src/app/application/utilities/index.ts
- packages/kuma-gui/src/app/control-planes/sources.ts
- packages/kuma-gui/src/app/kuma/index.ts
- packages/kuma-gui/src/app/kuma/locales/en-us/index.yaml
Closes https://github.com/kumahq/kuma-gui/issues/2431
Moves or removes the last of our "strings" to i18n:
- `KUMA_KDS_URL` we no longer need here
- `KUMA_DOCS_URL` I've moved to i18n. The "re-shaping" from `2.9.0` to `2.9.x` is now controlled via i18n, so its an application level concern rather than a framework concern.
We have 2 non-index.html derived env vars left:
- `KUMA_MOCK_API_ENABLED` - actual env var
- `KUMA_VERSION_URL` - whilst this isn't index.html derived, and is a "string" we use it programatically i.e. we don't just "print the thing out to the screen", so I'm a little unsure about putting it in i18n. I'll likely move it/hardcode it directly into `main.ts` at some point or something similar. In any case its not a 100% i18n-able string.
> chore: move some older env vars (strings) over to locales

- packages/kuma-gui/src/app/rules/components/RuleList.vue
I noticed we had an unnecessary XAction import. `X` components are global and therefore injectable, unless of course they are explicitly imported like in this instance.
> chore: remove unnecessary XAction import

- .github/workflows/release.yml
- packages/config/src/mk/build.mk
- packages/config/src/mk/install.mk
- packages/config/src/mk/release.mk
- packages/kuma-gui/Makefile
- packages/kuma-http-api/.gitignore
~**DO NOT MERGE at least until the code marked `DO NOT MERGE` is removed**~ 👈 These have been removed
Further iterates on our `release.yml` workflow. The intention here is to simplify it enough so it literally calls `make build` and `make release`. The only reason we split these in two is so we can use GH Actions to generate an SBOM instead of the Makefile itself.
This approach means that we can potentially loop through several packages in our workspace building and releasing each one with scripts controlled by the Makefile itself, not CI YAML (which for reasons cannot be totally versioned)
Separately I also added a similar Makefile target so you can test verify the SBOM locally using `syft`. Note: This is not what we use in CI and is only for testing/verification purposes.
Lastly, this …
> chore(ci): iterative improvements to releasing

- packages/config/src/mk/test.mk
When running `test/e2e` always check for Cypress and install. If Cypress is already installed then skip
We need to add this because we disabled automatically running npm scripts on install during https://github.com/kumahq/kuma-gui/pull/3607
> fix(ci): always check for Cypress and install

- package-lock.json
- packages/kuma-gui/package.json
- packages/kuma-http-api/package.json
Bumps master branch to next version of kuma/kuma-gui i.e. `2.11.0`
Related:
- https://github.com/kumahq/kuma-gui/issues/3154
- https://github.com/kumahq/kuma-gui/issues/2428
> chore: bump packages to 2.11

- package-lock.json
Fixes https://github.com/kumahq/kuma-gui/security/dependabot/107 via `npm update axios`.
> chore(deps): bump axios to 1.8.2, CVE-2025-27152

- packages/kuma-gui/src/app/data-planes/locales/en-us/index.yaml
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/types/index.d.ts
Shows a slightly different info message on the Dataplane Viz page depending on your `meshServices.mode`
> chore(dataplanes): switch reachable link based on meshServices.mode

- package-lock.json
Cherry-pick of https://github.com/kumahq/kuma-gui/pull/3650 for master.
> chore(deps): bump axios to 1.8.2, CVE-2025-27152 (master)

- package-lock.json
When cherry-picking the fix of https://github.com/kumahq/kuma-gui/pull/3650 for master, I noticed that the wrong version of `@kong-ui-public/entities-shared` is installed
```shell
kuma-gui@
└─┬ @kumahq/kuma-gui@2.11.0 -> ./packages/kuma-gui
└── @kong-ui-public/entities-shared@3.18.0 invalid: "^3.19.2" from packages/kuma-gui
```
The version got bumped in the manifest in https://github.com/kumahq/kuma-gui/pull/3636, but not properly added to the lock-file.
> chore(deps): @kong-ui-public/entities-shared incorrect version installed

- package-lock.json
Fixing CVE-2025-27789 using `npm audit fix`
> chore(deps): bump babel modules to 7.26.10 and -.9, CVE-2025-27789

- .github/dependabot.yml
Both `eslint` and `@eslint/js` are released from the same repo and always using the same version, so I think we can create a group to reduce the noise.
> chore(deps): create dependabot eslint group

- .github/dependabot.yml
- package-lock.json
- packages/kuma-gui/package.json
- packages/kuma-gui/src/app/x/components/x-code-block/XCodeBlock.vue
- packages/kuma-gui/tsconfig.json
As part of the version bump of shiki I changed some things:
- bump `shiki` to `3.2.1`
- changed the theme to `catppuccin-latte` (light) and `catppuccin-mocha` (dark) 
- changed [`moduleResolution`](https://www.typescriptlang.org/tsconfig/#moduleResolution) to `bundler`. Previous `node` is deprecated.
> feat(x-code-block): update shiki version, theme

- packages/kuma-gui/src/app/x/components/x-code-block/XCodeBlock.vue
In https://github.com/kumahq/kuma-gui/pull/3660 we spotted that there is a little additional scrollbar showing up on Mac if the system scrollbar setting is **not** set to `Always`.
https://github.com/user-attachments/assets/597d523f-63b7-47d8-9fd5-a71a84e96ae0
---
I've also moved the `background-color: unset` to the global `shiki, shiki span` ruleset.
> fix(x-code-block): highlighted codeblock additional scrollbar

- packages/config/src/workflow.schema.json
One last change here, this allows `./filepath/local-workflow.yml`
Sorry for the noise!
Oh I also reordered the possibilities to be the same as the comment
> chore(ci): allow filenames (with no @) in `uses:`

- package-lock.json
- packages/kuma-gui/eslint.config.cjs
- packages/kuma-gui/package.json
We've noticed that various kong dependencies are being published with the string `"workspace:^"` in their `peerDependencies`. This is causing npm install to fail.
We've seen this specifically happening in `@kong-ui-public/entities-shared@3.20.0` but it could also be happening in other modules/version.
So at the very least we are pinning our version to not go past 3.19.3 until a fix is pushed upstream.
> fix(deps): pin entities-shared to 3.19.3 due to bad 3.20.0

- package-lock.json
- packages/kuma-gui/src/app/data-planes/locales/en-us/index.yaml
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneInboundSummaryOverviewView.vue
- packages/kuma-gui/src/app/kuma/locales/en-us/index.yaml
- packages/kuma-gui/src/types/index.d.ts
See title
---
My personal opinion on these is still that during the release period, we should still work off of master and backport/cherry-pick back to the release branch.
Basically any approach that means we get to keep the separate commits in the git history, I believe this will need to be squashed and therefore we lose all the individual commits (I could be wrong, we'll see now)
---
In the meantime I need to figure out how to sort the DCO failures
> chore: merges release-2.10 branch into master finishing off the 2.10 release cycle

- packages/kuma-gui/src/app/x/components/x-anonymous/XAnonymous.vue
Removes a bunch of Vue dev time warnings, which also show up in Cypress tests (I found this when working on something else soon to be PRed)
> chore: ignore attrs on XAnonymous

- package-lock.json
- package.json
- packages/config/package.json
- packages/config/src/cypress/e2e.ts
- packages/fake-api/package.json
- packages/kuma-gui/cypress/support/e2e.ts
- packages/kuma-gui/package.json
- packages/kuma-http-api/package.json
When we made `@kumahq/config` we started adding peerDependencies to define the version of the "hosts" that we provide config/plugins for.
The thing is as dependbot (rightly) doesn't touch peerDependencies, and the node ecosystem can sometimes move quite fast (major bumps are a common occurrence), this means that our peerDependencies can quite quickly get out of sync with what we have defined as root/application/host dependencies. This is causing issues and unnecessary work to keep these in sync manually (no dependbot).
Moreover, we are in total control of the `@kumahq/config` _and_ our host app, and we don't publicly publish `@kumahq/config`, so in reality whenever we bump the dependency in our host app (that needs to be in sync with the peerDependencies) we should be bumping the …
> fix(deps): don't use peerDependencies, we don't have consumers

- package-lock.json
- packages/kuma-gui/package.json
- packages/kuma-gui/src/app/connections/views/ConnectionsClustersView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionsStatsView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionsXdsConfigView.vue
- packages/kuma-gui/src/app/x/components/x-code-block/ResourceCodeBlock.vue
- packages/kuma-gui/src/app/x/components/x-code-block/XCodeBlock.vue
- packages/kuma-gui/src/app/x/components/x-window/README.md
- packages/kuma-gui/src/app/x/components/x-window/XWindow.vue
- packages/kuma-gui/src/app/x/index.ts
Also see https://github.com/kumahq/kuma-gui/issues/3152, specifically https://github.com/kumahq/kuma-gui/issues/3152#issuecomment-2758069136
---
Looks like the line numbers we render here can cause a massive slowdown in re-renders, specifically when typing to search large configs.
The upstream KCodeBlock that we use for this does have a virtual scroller for the line numbers built in, but because of the nature of some virtual scrollers, and definitely in this case, you need to fix the height of the container of the thing that contains the virtual scroller. This means that the KCodeBlock now controls the scrolling, not the browser window.
Note: I only implemented this in the "full page" XDS Config pages for now, so if you are viewing the PR preview make sure you are looking at it on this …
> fix(codeblock): fix height of codeblock to use DOM recycling scrolling

- packages/kuma-gui/src/app/application/components/app-collection/AppCollection.vue
Overwrites kongponents setting KTable headers to `z-index: 2` in https://github.com/Kong/kongponents/pull/2629 which causes the following to happen:
I also filed an issue upstream https://github.com/Kong/kongponents/issues/2678
> fix: reset z-index of KTable headers to auto

- packages/kuma-gui/features/application/Warnings.feature
- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsBuiltinGateway.feature
- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsDelegatedGateway.feature
- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsTraffic.feature
- packages/kuma-gui/features/mesh/dataplanes/Warnings.feature
- packages/kuma-gui/features/zones/zone-cps/Warnings.feature
- packages/kuma-gui/src/app/control-planes/locales/en-us/index.yaml
- packages/kuma-gui/src/app/data-planes/data/DataplaneInsight.ts
- packages/kuma-gui/src/app/data-planes/data/DataplaneOverview.ts
- packages/kuma-gui/src/app/data-planes/index.ts
- packages/kuma-gui/src/app/data-planes/locales/en-us/index.yaml
- packages/kuma-gui/src/app/data-planes/sources.ts
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneListView.vue
- packages/kuma-gui/src/app/gateways/views/BuiltinGatewayDataplanesView.vue
- packages/kuma-gui/src/app/gateways/views/DelegatedGatewayDetailView.vue
- packages/kuma-gui/src/app/hostname-generators/data/HostnameGenerator.ts
- packages/kuma-gui/src/app/kuma/components/ApplicationShell.vue
- packages/kuma-gui/src/app/kuma/locales/en-us/index.yaml
- packages/kuma-gui/src/app/services/views/MeshServiceDetailView.vue
- packages/kuma-gui/src/app/services/views/ServiceDetailView.vue
- packages/kuma-gui/src/app/subscriptions/data/index.ts
- packages/kuma-gui/src/app/zones/data/index.ts
- packages/kuma-gui/src/app/zones/locales/en-us/index.yaml
- packages/kuma-gui/src/app/zones/views/ZoneConfigView.vue
- packages/kuma-gui/src/app/zones/views/ZoneDetailView.vue
- packages/kuma-gui/src/app/zones/views/ZoneListView.vue
- packages/kuma-gui/src/test-support/mocks/src/hostname-generators/_/_overview.ts
- packages/kuma-gui/src/test-support/mocks/src/hostname-generators/_overview.ts
- packages/kuma-gui/src/types/index.d.ts
- Changes all out notifications to use lowercase i18n keys that all live on a `<module-name>.notifications` property.
- Simplifies notifications so that are "calculated" in place instead of some in the data layer and some in the view layer. They are now all in the view layer. This means we can be more intentional about what notifications are shown where. The is a small bug here where we try to show a NACK warning on the zone listing page when we shouldn't.
- Due to the above point, I made some amends to the dataplane data layer
- Noticed a few tiny things in HostnameGenerators data mainly around using the generated types in the mocks rather than our application types.
Note tests are gonna fall on their face here, I wanted to put up a draft PR to share progress, my next steps is fixing up …
> chore(notifications): normalize notification keys

- packages/kuma-gui/cypress/support/step_definitions/index.ts
We've recently had queries around our test approach and as to whether it is the root of several issues we are seeing lately.
Despite the fact that we are seeing these issues totally outside of Cypress testing, I wanted to do the due diligence, listen to this opinion and do anything I personally could do to act on it. So I spent some time reviewing our Cypress steps specifically looking for any potential issues.
---
One good thing about our declarative (and purposefully restrictive) approach is that I didn't have to review all our tests to look for potential issues. As long as our ~20 or so steps are good then we know its highly likely that all our tests are also.
---
I went through each step and checked that any steps that contained loops are actually waiting on each iteration by adding a …
> chore(ci): review of Cypress steps

- packages/kuma-gui/src/app/application/components/app-collection/AppCollection.vue
A better fix for https://github.com/kumahq/kuma-gui/pull/3729. It also means that if we ever need bulk actions with a max-height (this is the only configuration of KTable that requires the  z-index on the thead), the Kongponent will still be displayed as intended.
We might want to add this to every single X component to isolate ourselves from Kongponent z-index related side effects.
Note: I have a much better branch hanging around that has much better isolation of Kongponents which would prevent us from having these sorts of issues, I keep meaning to resurrect it 🤔 
Probably a good FYI to keep in mind from when I was looking into this:
The whole issue is caused by Kongponents providing custom/non-native icons for checkboxes:
Lastly, we are due to change our dropdown filterbar thingie here …
> chore: use CSS isolation to avoid z-index battles

- package.json
I actually thought I'd done this a little while back, this PR removes the overrides for esbuild and cucumber/messages.
The esbuild override in particular is causing issues for dependabot:
Overrides are generally bad and as we all know should only be used in the very rare case that we are blocked because of an upgrade somewhere (not for using as a replacement for incorrectly configured dependencies upstream).
In this case (from what I remember at the time) we were using them for the exact usecase, but as dependabot doesn't update them, they get forgotten about. Vaguely considering adding something that pesters us whenever we have something in overrides so we don't totally forget, something to think about.
> chore(deps): removes overrides for esbuild etc

- packages/kuma-gui/src/app/x/components/x-disclosure/XDisclosure.vue
We were playing around making things better and we noticed that this import was missing, I figured I may aswell PR it now rather than just reset my local clone
> chore: import KToggle into XDisclosure

- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/kuma/components/ApplicationShell.vue
- packages/kuma-gui/src/app/meshes/views/MeshDetailView.vue
- packages/kuma-gui/src/app/services/views/MeshExternalServiceListView.vue
- packages/kuma-gui/src/app/x/components/x-notification/XNotification.vue
- packages/kuma-gui/src/app/zones/views/ZoneConfigView.vue
- packages/kuma-gui/src/app/zones/views/ZoneDetailView.vue
Part of https://github.com/kumahq/kuma-gui/issues/3605
In the above issue we said:
> We need the dismissal actions to not only track when you have dismissed a notification and store that, but also remove that storage once the logic that showed the notification is reversed.
In order to know whether to show the notification we were using a `v-if` to show choose whether to show the notification or not. But given the above requirement we also need to remove the fact that you dismissed a notification if the conditional logic is reversed. This means if we continue to use `v-if` we can't do anything extra (like remove the localstorage value) from within the XNotification if we don't even render it.
This PR moves all notifications to use a `:notify` property, and moves the v-if inside the …
> chore: move XNotification to use :notify vs v-if

- packages/fake-api/src/cypress.ts
- packages/fake-api/src/index.ts
- packages/fake-api/src/msw.ts
- packages/fake-api/src/vite.ts
- packages/kuma-gui/cypress/services.ts
- packages/kuma-gui/cypress/support/step_definitions/index.ts
- packages/kuma-gui/features/mesh/dataplanes/DataplanePolicies.feature
- packages/kuma-gui/src/app/data-planes/views/DataPlanePoliciesView.vue
Refactors some more of fake-api, mostly:
- Reduce everything down to a reusable `createFetch`/`createFetchSync`, that returns something that is very fetch-like (i.e. very recognisable). Note: `createFetchSync` is needed for Cypress which is notorious weird with async things.
- I moved the YAML/JSON merging we do for overwriting responses during tests out of fake-api entirely. If you aren't doing tests like we are then you wouldn't need this in order to build basic fake-apis.
Probably a few other little bits. Unfortunately the PR is a little large, if it was me I'd look at/compare this locally to get a better feel for the improvement here.
We are still not quite done here, but with what we did before extracting things out into its own module, and what is here, I'm far happier with this …
> chore(ci): reduce the majority of fake-api to a createFetch function

- packages/fake-api/src/cypress.ts
- packages/fake-api/src/index.ts
- packages/fake-api/src/msw.ts
- packages/fake-api/src/vite.ts
- packages/kuma-gui/cypress/services.ts
- packages/kuma-gui/cypress/support/step_definitions/index.ts
- packages/kuma-gui/features/mesh/dataplanes/DataplanePolicies.feature
- packages/kuma-gui/src/app/data-planes/views/DataPlanePoliciesView.vue
Reverts kumahq/kuma-gui#3734
This causes issues elsewhere, which I'm not sure if are due to our GithubActions or not. I don't want to block further work today so I'm reverting this for now. Will bring it back later.
In the meantime I'm gonna start taking a look at those GitHubActions and make them a little easier to work with, they are the last ones we have totally refactored so I may as well bite the bullet and finish up these last ones.
> Revert "chore(ci): reduce the majority of fake-api to a createFetch function"

- packages/kuma-gui/src/app/data-planes/views/DataPlaneListView.vue
- packages/kuma-gui/src/app/gateways/views/BuiltinGatewayDataplanesView.vue
- packages/kuma-gui/src/app/gateways/views/DelegatedGatewayDetailView.vue
- packages/kuma-gui/src/app/services/views/MeshServiceDetailView.vue
- packages/kuma-gui/src/app/services/views/ServiceDetailView.vue
- packages/kuma-gui/src/app/x/components/x-i18n/XI18n.vue
- packages/kuma-gui/src/app/x/components/x-icon/XIcon.vue
- packages/kuma-gui/src/app/x/components/x-search/README.md
- packages/kuma-gui/src/app/x/components/x-search/XSearch.vue
- packages/kuma-gui/src/app/x/locales/en-us/index.yaml
Adds a dropdown to the `XSearch` component which displays some more information about the filter/search logic, i.e. the actual search query.
In order to make the component more reusable in different places, I've turned the props into optional and provide fallbacks and defaults within the component.
I've added `formatList` (coming from our i18n, `formatjs createIntl().formatList`) to `XI18n` such that we have the dependency to i18n only in one place.
I might change the internal behaviour of `defaultKey`, but first want to see how this component will be used in other places. Probably will change it to fall back to `keys[0]` instead of fixed `name`, since there might be places where we don't have a `name` but still don't want set a `defaultKey` 🤔 
~In order to make the `XI18n` usable inline, …
> feat(x-search): add dropdown

- packages/kuma-gui/src/app/x/components/x-about-card/XAboutCard.vue
- packages/kuma-gui/src/app/x/components/x-action/XAction.vue
- packages/kuma-gui/src/app/x/components/x-code-block/XCodeBlock.vue
- packages/kuma-gui/src/app/x/components/x-input/XInput.vue
- packages/kuma-gui/src/app/x/components/x-prompt/XPrompt.vue
- packages/kuma-gui/src/app/x/components/x-tabs/XTabs.vue
I spotted some more tiny bits in our `x` module that will affect our ability to make it into a completely zero dependency module in the future.
- Missing Kongponents imports where we were depending on kongponents being available globally.
- one instance I spotted of direct usage of `@kong-ui-public/i18n`, we should try and use `XI18n` exclusively within `x`. I hope to provide a very simple but injectable instance of i18n eventually making `x` zero dependency.
> chore: minor X cleanup

- packages/kuma-gui/features/mesh/Warnings.feature
- packages/kuma-gui/src/app/meshes/locales/en-us/index.yaml
- packages/kuma-gui/src/app/meshes/views/MeshDetailView.vue
In case `meshServices` mode has not been configured or set to `Disabled`, we want to inform the users to migrate to `MeshService`s. Includes a link to [meshservice/migration](https://kuma.io/docs/2.10.x/networking/meshservice/#migration).
Closes #3161
> feat(mesh): add info to activate meshServices

- package-lock.json
- packages/config/package.json
- packages/config/src/mk/check.mk
- packages/kuma-gui/package.json
TLDR; Adds a "node resolver" to our Makefile scripts
---
We've moved all of our CI/dev utility scripts over to Makefiles, because:
- Its overly difficult writing scripts inside JSON files (package.json)
- Makefiles are sharable, package.json scripts aren't
- All other benefits of Make
The one downside is, Make does not use node import/modules or node resolution for its binaries.
This means that if we install something in `@kumahq/config` and run one of `@kumahq/config`s Make scripts that uses a node binary it isn't necessarily looked up properly because Make uses its `cwd` and `$PATH` as a "path".
We've been using `npx` which relies on the executable being installed in root for a Make call.
So from `/packages/kuma-gui` to find an executable in `/`.
Whereas if we install the executable in …
> chore(ci): adds resolver to resolve node execs from @kumahq/config

- packages/kuma-gui/src/app/App.vue
- packages/kuma-gui/src/app/application/routes.ts
- packages/kuma-gui/src/app/application/services/data-source/Router.spec.ts
- packages/kuma-gui/src/app/control-planes/routes.ts
- packages/kuma-gui/src/app/control-planes/views/ControlPlaneDetailView.vue
- packages/kuma-gui/src/app/control-planes/views/ControlPlaneRootView.vue
- packages/kuma-gui/src/app/hostname-generators/index.ts
- packages/kuma-gui/src/app/hostname-generators/routes.ts
- packages/kuma-gui/src/app/kuma/components/ApplicationShell.vue
- packages/kuma-gui/src/app/kuma/views/KumaNotFoundView.vue
- packages/kuma-gui/src/app/meshes/index.ts
- packages/kuma-gui/src/app/meshes/routes.ts
- packages/kuma-gui/src/app/zones/index.ts
- packages/kuma-gui/src/app/zones/routes.ts
Closes https://github.com/kumahq/kuma-gui/issues/3570
After this goes in I'll probably make some immediate amends ontop of https://github.com/kumahq/kuma-gui/pull/3789, so ideally this would go in first.
I probably should have done this PR first tbf. The plan is to put the notification about "control-plane using a memory store" in the control-plane module where it belongs. The only reason we haven't done that already is because we had no where to put it that meant its always visible, so it ended up going in App.vue.
> chore(control-planes): move routing to be a child of control-planes

- packages/kuma-http-api/index.d.ts
Updates our types after the following changes to kuma OAS. Changes are mainly about adding `DataplaneOverview` types for endpoints `/meshes/{mesh}/dataplanes/_overview` and `/meshes/{mesh}/dataplanes/{name}/_overview`
- https://github.com/kumahq/kuma/pull/13479
- https://github.com/kumahq/kuma/pull/13483
Adoption will happen in a separate PR as it may become a larger effort. Also note that most of the dataplane types are optional and we will need to see where we have to provide fallbacks.
> feat(kuma-http-api): update oas types

- package-lock.json
Updates lockfile from package change made in https://github.com/kumahq/kuma-gui/pull/3820 that was missed in the original PR.
If you look at the diff this has zero consequential changes, its just moving the dep from one place to another, but I noticed this during https://github.com/kumahq/kuma-gui/pull/3825 and I would like that PR to be clean.
> chore(deps): update package-lock for lockfile-lint change

- packages/kuma-gui/src/app/App.vue
- packages/kuma-gui/src/app/application/components/app-view/AppView.vue
- packages/kuma-gui/src/app/control-planes/views/ControlPlaneRootView.vue
- packages/kuma-gui/src/app/kuma/components/ApplicationShell.vue
- packages/kuma-gui/src/app/me/sources.ts
- packages/kuma-gui/src/app/x/components/x-notification/XNotification.vue
- packages/kuma-gui/src/app/x/components/x-notification/XNotificationHub.vue
At a general level this PR adds a dismissal button to all our notifications.
If you dismiss a an alert box, all notifications within that box are saved to localStorage as dismissed for 7 days at which point it is "un-dismissed" meaning you will see the notification again if you haven't resolved what it is warning you about.
localStorage values also be removed i.e. "un-dismissed" if we detect that you have resolved the reason for the warning, meaning if you then remove whatever you did to resolve the warning, you will be warned again.
Further notes:
- I moved around AppView a little so I could put all the notification display all in one place in AppView (instead of also in ApplicationShell), this also meant I could remove some CSS that we no longer need (we are now using XLayout for the …
> feat(notifications): adds dismissal, GC and resetting to notifications

- .github/workflows/main.yml
- packages/config/src/mk/help.mk
Automatically discover packages that need CI testing.
- adds several new make targets to:
- print a JSON of all packages (i.e. workspaces plus the root package)
- print a JSON of all workspaces (i.e. minus the root package)
- print a JSON of workspaces that have `.feature` files
- print a JSON of workspaces that have `.spec.ts` files
- using the above targets, we can figure out the matrices for each of our `cli-tests` and `browser-tests` jobs, plus pass _all_ packages to `lint-tests`
All in all this is prep work I've been wanting to do for preparing to split all our modules out into separate packages. This PR means that we can just add new ones and they'll all automatically be picked up by CI. i.e. zero config.
There might be a tiny bit of tweaking/renaming or something at some point in …
> chore(ci): dynamic matrices

- packages/kuma-gui/features/mesh/policies/Index.feature
- packages/kuma-gui/src/app/policies/data/index.ts
- packages/kuma-gui/src/app/policies/sources.ts
- packages/kuma-gui/src/app/policies/views/PolicyListView.vue
- packages/kuma-gui/src/app/resources/data/Resource.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/circuit-breakers.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/fault-injections.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/health-checks.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/meshfaultinjections.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/meshgatewayroutes.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/meshgateways.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/meshhttproutes.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/timeouts.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/traffic-logs.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/traffic-permissions.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/traffic-routes.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/traffic-traces.ts
Replaces the current custom implementation of a search field with the new `XSearch` component and allow filtering for `name`, `namespace` and `zone` (in case it's supported by the respective policy type). I've updated the mocks to reflect the filter query.
As discussed in https://github.com/kumahq/kuma-gui/pull/3821, in order to DRY the parsing of the `search` string and as suggested I've added a `Resources.search` to `resources/data/Resource` to be shared with other modules.
Part of #3757
> feat(policy-list-view): use x-search

- package-lock.json
- packages/kuma-gui/package.json
After creating the `kuma-http-api` package in https://github.com/kumahq/kuma-gui/pull/3516 to house the openapi-typescript types generated from the kuma oas, we don't need the `openapi-typescript` dependency in the `kuma-gui` package anymore. This removes the dependency from `kuma-gui` and leaves it in `kuma-http-api`.
> chore(deps/kuma-gui): remove openapi-typescript

- packages/kuma-gui/.vitepress/theme/main.md
- packages/kuma-gui/src/app/vue/index.ts
- packages/kuma-gui/src/main.ts
Changes `vue` service container so that the `app` service returns a function that requires the result of `createApp()` passed to it, instead of doing that itself.
This means that you have access to the result of `createApp` outside of the service contain and you don't need to build the container to get a reference to it.
It also makes it clearer where `createApp` is being called.
---
We'd already vaguely planned on reconfiguring it like this a very long time ago (see the temporary comment in the vitepress code I removed here)
I also spotted some more error wrapping code that we never use, so I removed that here also
> chore: alters vue service container to require an app argument

- packages/kuma-gui/src/app/x/components/x-search/XSearch.vue
We hit a flake a couple of times `ResizeObserver loop completed with undelivered notifications` which could be the result of not cleaning up the resize observer we register in `XSearch.onMounted`. While thinking of creating a custom hook to prevent us running into this case again, we decided to leverage one of `@vueuse`'s exported hooks `useResizeObserver` which should already include everything we need instead of reinventing the wheel.
> refactor(x-search): use useResizeObserver

- packages/kuma-gui/features/control-planes/DetailView.feature
We spotted a flake appearing due to changed mocks which seems to be because the mesh count can sometimes be less than 3.
This PR ensures that we always get 3 meshes in order to partially overwrite 3 meshes in the response
> fix(tests): ensures KUMA_MESH_COUNT is 3 for control-planes test

- packages/kuma-gui/src/app/x/components/x-code-block/ResourceCodeBlock.vue
- packages/kuma-gui/src/app/x/components/x-code-block/XCodeBlock.vue
- packages/kuma-gui/src/app/x/components/x-i18n/XI18n.vue
- packages/kuma-gui/src/app/x/components/x-icon/XIcon.vue
- packages/kuma-gui/src/app/x/index.ts
Removes the majority of "internal dependencies" of `x`.
"internal dependencies" meaning any of our own dependencies of `x` such as `@/app/application`.
3rd party dependencies (for the moment at least) we are fine with.
Note: The last YAML dependency we have here could either use `js-yaml` straight, or by just removing the `ResourceCodeBlock` component entirely. I'd rather do the latter seeing as we have https://github.com/kumahq/kuma-gui/issues/3673 as an issue already
Also, this one is probably a good "Hide Whitespace" in GH one.
> chore(x): reduce "internal dependencies" in x

- .github/workflows/main.yml
- Makefile
- packages/config/src/mk/help.mk
I figured we probably want these targets as "dot targets" so we can overwrite them if we need to.
I also exposed the entire package.json to CI instead of just the name, path and 'slug'. This means that if we want to add any meta data to our package.json's just for CI we can.
I also added a `meta/preview` based on whether a workspace has a `index.html` that we don't use as yet, but I would love to be able to deploy multiple PR preview sites based on this.
Just to note, there may be a little more related work in a few days on top of this, I'm just taking little nibbles at this until I get to a point where I can pull it all together.
> chore(ci): turn Makefile meta targets into dot targets

- packages/config/src/mk/install.mk
`npm dedupe` can sometimes break overtime, we added it to our CI so we could notice when it breaks and therefore investigate. I've investigated some more and realized a few more things.
~I think that because we sometimes have a a nested package-lock.json _aswell_ as our root JSON, and I'm guessing that `npm` uses the position of a `package-lock.json` as the root folder where it will install everything by default is in some cases making certain packages eventually be installed a sub folder other than root. This eventually contributes to npm finding it difficult to install non-duplicated packages and then eventually getting into a state where `npm dedupe` fails to work. This is my theory anyway. I'm hoping we can do something to prevent this nested package-lock.json from being there when we …
> fix(ci): remove dedupe from sync target

- packages/config/src/mk/help.mk
`-depth` seems to work differently on macOS, `-maxdepth` seems to be the more crossplatform/correct thing to use for restricting `find`s depth 🤦 
This doesn't affect us here yet, which explains why this issue was non-blocking, but I found it when trying things out elsewhere.
> fix(ci): use crossplatform -maxdepth for meta/preview

- packages/config/src/mk/check.mk
If you try and run any of our Make targets without the correct version of node installed it now looks like this:
> chore(docs): adds some colouring to our Make errors

- packages/kuma-gui/src/app/application/services/can/README.md
We were discussing `can` and its usages, and we figured a better way to explain case when you would use it, so we worked on the docs whilst we thought about it to improve that a little.
> chore(docs): improve `can`s docs slightly

- packages/config/src/mk/build.mk
- packages/config/src/mk/run.mk
- packages/kuma-gui/Makefile
Makes `.deploy/preview` a "dot target" so it can be overridden per project.
Netlify is only used currently for `kuma-gui` so we only copy the `_redirects` file into the deploy/distribution for `kuma-gui`
> chore(ci): moves deploy/preview to be a dot target

- packages/kuma-gui/src/app/resources/data/Resource.spec.ts
I spent quite a bit of time poking our new search logic whilst reviewing and I found a search case that our new search implementation covers but our old one didn't 🎉  (old implementation isn't quite totally removed yet but thats on our list)
I figured it would be good to keep a test for this case
> chore(tests): add `name` search test

- packages/kuma-gui/features/mesh/dataplanes/Index.feature
- packages/kuma-gui/features/mesh/services/Item.feature
- packages/kuma-gui/src/app/common/TagList.vue
- packages/kuma-gui/src/app/resources/data/Resource.spec.ts
- packages/kuma-gui/src/app/resources/data/Resource.ts
Follow-up to #3948 
Initially I thought we will drop support for `tag`s and move all over to `label`s. At least for dataplanes we need to keep supporting `tag`s for a while. This change makes sure that we can use short filters (i.e. `zone` => `kuma.io/zone`) for both `label`s and `tag`s.
To cover that I've added some more cases to the unit test and reverted the changes made in the browser tests.
> refactor(resource/search): reuse short filters for both labels and tags

- packages/config/src/eslint.cjs
Instead of guessing where the root pakcage.json is in order to figure out workspace info, use `npm query :root` instead
> chore(ci): use npm query :root to figure out the workspace root

- packages/kuma-gui/features/mesh/policies/Index.feature
- packages/kuma-gui/src/app/policies/views/PolicyTypeListView.vue
- packages/kuma-gui/src/app/x/components/x-action/XAction.vue
I also switched/remove XActions `:mounted` prop to use Vue's `@vue:mounted` instead now we have that.
Closes https://github.com/kumahq/kuma-gui/issues/3730
> chore(ci): fix flake-y policies redirect test

- packages/config/src/cypress/e2e.ts
Sounds like this is a common thing with Cypress, I guess it can happen also real-life. We have seen it in real-life and added a fix and not seen it in real-life since then, but we keep getting flakes with it quite often.
Not super keen on this PR myself, so this might be a temporary thing, but if we want to remove this ignore we should find a way to stop it causing flakes first.
> fix(ci): adds an ignore for ResizeObserver errors in Cypress

- .github/renovate.json
In https://github.com/kumahq/kuma-gui/pull/3993 I've added a `postUpgradeTasks` for `msw`, but I've overseen the fact that this is a feature only for self-hosted renovate instances.
I've only removed the part of the renovate config, as we can still further utilize the make target.
> chore(renovate): revert post-upgrade-task for msw

- .github/workflows/lifecycle.yml
- .github/workflows/main.yml
Actions need to be pinned on SHA version. Taken from https://github.com/kumahq/kuma/blob/release-2.9/.github/workflows/lifecycle.yml
Also bumped actions/cache to latest version, similar to #3998
> chore: pin actions (release-2.9)

- .github/workflows/lifecycle.yml
- .github/workflows/main.yml
Actions need to be pinned on SHA version. We've put common actions sourced from kumahq on the allowList, but this seems to be colliding with https://github.com/kumahq/.github/blob/75f72db331df298cdb92be152a3eccce93350a67/.github/workflows/wfc_lifecycle.yml#L102
> chore: pin actions (master)

- packages/config/src/cypress/e2e.ts
After merging https://github.com/kumahq/kuma-gui/pull/3989 we hit another flake in https://github.com/kumahq/kuma-gui/actions/runs/15558790036/job/43805766147?pr=3993 `ResizeObserver loop completed with undelivered notifications.`. So in order to prevent fails on this I've adjusted the exception handler to ignore any `ResizeObserver loop` error.
> chore(config/cypress/e2e): ignore any ResizeObserver loop related error

- packages/kuma-gui/features/zones/zone-cps/Item.feature
- packages/kuma-gui/src/app/zones/data/index.ts
I faced a new flake https://github.com/kumahq/kuma-gui/actions/runs/15676714259/job/44158981105?pr=4019 which got introduced most likely with https://github.com/kumahq/kuma-gui/pull/3987.
```sh
AssertionError: Timed out retrying after 4000ms: Expected to find content: 'Universal' within the element: <div.route-view> but never did.
```
We noticed that the data-layer did not consider that subscriptions can be disconnected and we always use the first subscription in the list to extract the config. We should rather prefer the `connectedSubscription` (has no `disconnectTime`) and only fall back to the first subscription that has a config in case there is no `connectedSubscription`.
> fix(zone-detail): preferred disconnected subscription config

- .github/renovate.json
Some more minor tweaks:
- Removing the grouping for major updates as I think I was too eager trying to reduce the noise but I actually think it'd be better to address them separately and the potential breaking changes
- Reordering the package rules to make sure that `npm` and `node` are grouped separately and not with the other dependencies. Order matters as last one wins and overrides previous that have the same matchers.
> chore(renovate): reorder package-rules, only group patch and minor

- packages/kuma-gui/src/app/application/services/data-source/index.ts
- packages/kuma-gui/src/app/kuma/services/kuma-api/makeRequest.spec.ts
- packages/kuma-gui/src/app/kuma/services/kuma-api/makeRequest.ts
There are a few things I would like to know when we get an unknown status type error from our HTTP client, are couple are:
1. What was the URL for the request?
2. Is the user still on our page for 3 seconds after the error occurred?
Number one is out of curiosity, and to verify exactly where the request was going.
Number two is to investigate whether its worth us trying to retry the request
I have a suspicion some of these errors happen because the user navigates to another page (via a traditional link, not a JS `pushState` i.e. a page refresh) whilst a request is in-flight. In this case it would be pointless retrying. Whereas if we can see via this console.error that the user is still on the page, it would be worth retrying.
> chore: adds more information when we get a client HTTP error

- .github/renovate.json
We want to deal with `@kong` dependencies separately due to past issues we've encountered.
> chore(renovate): separately group @kong dependencies

- packages/kuma-gui/src/app/policies/data/index.ts
- packages/kuma-gui/src/app/policies/views/PolicyListView.vue
- packages/kuma-gui/src/app/x/components/x-icon/XIcon.vue
- packages/kuma-gui/src/types/index.d.ts
Extends the icon set for policy roles with `consumer, `system` and `workload-owner`.
Closes #3893
> feat(policy-list): extend policy roles icon with consumer and system

- packages/config/src/mk/install.mk
Follow up of https://github.com/kumahq/kuma-gui/pull/4035
Importantly, as before, we need to not run this in CI unless `node_modules` doesn't exist at all.
The `find` command is as quick as I could get it, hence the `maxdepth` etc.
> chore: make `make install` also check `package.json`s

- packages/kuma-gui/src/app/application/components/app-collection/AppCollection.vue
Back in https://github.com/kumahq/kuma-gui/pull/4036 I enabled the dev-time only runtime error to help me to find DataLoaders that are being used for lists but not using a list skeleton.
There are still a few tho that are more complicated to sort out and involve more complex DataSource/DataLoader interactions that aren't done yet (work is currently in progress).
Considering this, I think I uncommented this a tad early (sorry!), and I wanted to soften it so that there was less DX urgency (its only a devtime error) to figure out the more complex interactions.
I've changed this to a `console.error` so its an even softer error, still only dev-time, but still apparent where things need improving, so we can resolve as we go.
> chore(fix): soften DataLoader dev-time error

- packages/kuma-gui/src/app/application/services/data-source/index.ts
This expands our "catch a HTTP0 and retry" to catch slightly more TypeErrors, I'm still being cautious to open this up to just catch _all_ TypeErrors, and whilst checking the error message ain't great, its achieves what we want for now.
> chore: catch more load failures

- packages/kuma-gui/src/test-support/FakeKuma.ts
- packages/kuma-gui/src/test-support/mocks/src/dataplanes/_overview.ts
- packages/kuma-gui/src/test-support/mocks/src/mesh-insights.ts
- packages/kuma-gui/src/test-support/mocks/src/mesh-insights/_.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/dataplanes/_.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/service-insights.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/service-insights/_.ts
First of all this removes the `@deprecated` fake utilities and inlines the results into the fs mocks. But this also removes the dependency to `@/types/index.d`, which is a preparation to be able to move the mocks and `FakeKuma` out of `kuma-gui`.
Closes #3126
> refactor(fake-kuma, mocks): remove deprecated fakes and types

- packages/kuma-gui/features/mesh/builtin-gateways/Item.feature
- packages/kuma-gui/src/app/gateways/data/MeshGateway.ts
- packages/kuma-gui/src/app/gateways/views/BuiltinGatewayDataplanesView.vue
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/dataplanes/_overview.ts
In case a builtin gateway is deployed to a specific zone, we have to filter the dataplanes by that zone to only show the dataplanes that are in the same zone as the gateway.
Closes #2982
> fix(builtin-gateways/dataplanes): filter by zone

- packages/kuma-gui/src/app/connections/components/connection-traffic/ConnectionCard.vue
- packages/kuma-gui/src/app/data-planes/locales/en-us/index.yaml
We decided this isn't something that is feasible to do correctly from the frontend.
See original issue https://github.com/kumahq/kuma-gui/issues/2974
> Revert "chore: add mTLS related stats to ConnectionCards (#4067)"

- package-lock.json
Addresses https://github.com/kumahq/kuma-gui/security/dependabot/115
Bumps `@eslint/plugin-kit` to `0.3.4` according to https://github.com/advisories/GHSA-xffm-g5w8-qvg7 via `npm audit fix`.
> chore(deps): bump transitive @eslint/plugin-kit

- packages/kuma-gui/src/app/gateways/locales/en-us/index.yaml
- packages/kuma-gui/src/app/gateways/views/BuiltinGatewaySummaryView.vue
The structured view of the builtin-gateway summary view is pretty empty. This fills it up with some more information.
Closes #4100
> feat(builtin-gateway): enrich content structured view

- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsTraffic.feature
- packages/kuma-gui/src/app/data-planes/data/DataplaneNetworking.ts
- packages/kuma-gui/src/app/data-planes/sources.ts
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/kuma/locales/en-us/index.yaml
- packages/kuma-gui/src/test-support/FakeKuma.ts
- packages/kuma-gui/src/test-support/mocks/fs.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/dataplanes/_/_layout.ts
Adds back the traffic listing that uses the data returned by the new `_layout`-endpoint:
- the traffic listing is shown at the same place as before, but for now only displays the `inbounds` and `outbounds` data returned by `/_layout` (no summary view and no passthrough yet)
- tests ensure that inbounds show the contextual kri and outbounds the full kri. Everything else is as before and it uses the same components under the hood (`ConnectionGroup`, `ConnectionCard`, ...)
- adds a the new `_layout` endpoint to the mocks and new fake methods `kri` and `conextualKri` to generate kri
Example
Closes #4119
> feat(data-planes): add back traffic listing

- packages/kuma-gui/src/app/application/services/data-source/index.ts
- packages/kuma-gui/src/app/kuma/index.ts
In some cases we want to validate user inputs. The validation happens in the data source layer, so we could potentially move the validation to the backend with few changes necessary. But this also causes errors being thrown unnecessarily. This PR mutes these errors but still let the error being displayed to the user, i.e. below an input field that is being validated.
> feat: mute validation errors

- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsBuiltinGateway.feature
- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsDelegatedGateway.feature
- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsStandardProxy.feature
- packages/kuma-gui/features/mesh/dataplanes/DataplaneDetailsTraffic.feature
- packages/kuma-gui/features/mesh/dataplanes/DataplaneSummary.feature
- packages/kuma-gui/features/mesh/dataplanes/Navigation.feature
- packages/kuma-gui/features/mesh/dataplanes/NoSubscriptions.feature
- packages/kuma-gui/features/mesh/dataplanes/Subscriptions.feature
- packages/kuma-gui/features/mesh/dataplanes/Warnings.feature
- packages/kuma-gui/features/mesh/dataplanes/overview/Policies.feature
- packages/kuma-gui/features/mesh/dataplanes/overview/Traffic.feature
- packages/kuma-gui/features/mesh/dataplanes/overview/summary/Clusters.feature
- packages/kuma-gui/features/mesh/dataplanes/overview/summary/Inbound.feature
- packages/kuma-gui/features/mesh/dataplanes/overview/summary/Outbound.feature
- packages/kuma-gui/features/mesh/dataplanes/overview/summary/Policy.feature
- packages/kuma-gui/src/app/data-planes/features.ts
- packages/kuma-gui/src/app/legacy-data-planes/features.ts
- packages/kuma-gui/src/app/legacy-data-planes/views/DataPlaneRouteGuard.vue
- packages/kuma-gui/src/app/legacy-data-planes/views/RootView.vue
We've noticed that when `meshServices.mode` is disabled on the mesh, we can't use `feature-unified-resource-naming`. Until this condition is fully considered on the backend, we are going to check for the `meshServices.mode` being set to `Exclusive`. The backend will work on exposing a new field `dataplaneInsights.features` which will either include the feature flag or not by taking into account if mesh services are enabled or not.
> feat(data-planes): check for mesh-services mode to use unified-naming

- packages/kuma-gui/src/app/data-planes/locales/en-us/index.yaml
- packages/kuma-gui/src/app/zones/locales/en-us/index.yaml
The following links are currently out-of-date.
For the `gateway` link I'm "almost sure" that its not even used, but felt it was easier to replace it anyway. But if anyone can confirm for me that they can't see it being used in our code also, I'd be happy to just totally remove it from the locales files. I'm pretty sure its just left over from an older version. lmk
> feat(docs): several docs links amends

- packages/kuma-gui/src/app/data-planes/features.ts
- packages/kuma-gui/src/app/legacy-data-planes/views/DataPlaneRouteGuard.vue
Whilst working on https://github.com/kumahq/kuma-gui/pull/4194 I found that one side of `can` was expecting the DataplaneOverview from `@/app/data-planes/data` and the other side was using our old DataPlaneOverview from `@/types`.
This makes them the same.
https://github.com/kumahq/kuma-gui/pull/4194 goes some way to prevent this from happening, although this wasn't the reason for me working on that.
> fix(types): fixup DataplaneOverview type in DataplaneRouteGuard

- packages/kuma-gui/src/app/application/components/app-collection/AppCollection.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneListView.vue
- packages/kuma-gui/src/app/legacy-data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/meshes/components/MeshInsightsList.vue
- packages/kuma-gui/src/app/policies/views/PolicyListView.vue
- packages/kuma-gui/src/app/zone-egresses/views/ZoneEgressDetailView.vue
- packages/kuma-gui/src/app/zone-ingresses/views/ZoneIngressDetailView.vue
- packages/kuma-gui/src/app/zones/components/ZoneControlPlanesList.vue
- packages/kuma-gui/src/app/zones/views/ZoneDetailView.vue
A long time ago we used to just say "the first cell in a table is the link to _the thing_", but then we needed to have links in non-first cells, so we added a `data-action` "tag" that you could use on the links to _the thing_.
The old CSS is still in the app in several places, but its no longer needed (unless there are places where we don't use `data-action`), so I've removed it all.
The removed CSS was also causing issues in relation to https://github.com/kumahq/kuma-gui/pull/4200
> chore: remove old scoped app-collection related CSS

- packages/kuma-gui/features/mesh/Item.feature
- packages/kuma-gui/features/mesh/MeshIdentity.feature
- packages/kuma-gui/features/mesh/services/mesh-services/Item.feature
- packages/kuma-gui/src/app/meshes/views/MeshDetailView.vue
- packages/kuma-gui/src/test-support/index.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/meshidentities/_.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/meshtrusts/_.ts
The mtls warning in the `MeshOverview` should only show up if mtls is not configured. With `MeshIdentity` as issuer the `mtls` field in `/meshes/{mesh}` is not set, so we also have to check for `MeshIdentity`s.
This also needs to go into 2.12
---
We've decided to take this a little further. We want to move the list of `MeshIdentity`s to the `mTLS` part of the about section. Also the `MeshTrust` listing will only be rendered conditionally in case there is at least one `MeshTrust` resource.
> fix(mesh): mtls warning shows up with mesh identity

- packages/kuma-gui/features/mesh/dataplanes/overview/Tls.feature
- packages/kuma-gui/src/app/data-planes/routes.ts
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
cherry-pick of https://github.com/kumahq/kuma-gui/commit/4badeedb3711854b265b95dc1c1a6f9f6c6de48d
>In case the issuer for mTLS is `MeshIdentity` we show the `kri` of the `MeshIdentity` in the DP's TLS section. We use to link from the `kri` to the `MeshIdentitySummaryView`, which turns out is not possible as we cannot reconstruct the correct `name` parameter for `/meshes/{mesh}/meshidentities/{name}` to fetch the config. So until we can potentially use the full `kri` as the `name` parameter we have to remove the linking and therefore just display the `kri` as is.
> feat(data-plane): remove link to MeshIdentity (#4204)

- packages/kuma-gui/src/app/meshes/locales/en-us/index.yaml
- packages/kuma-gui/src/app/x/components/x-empty-state/XEmptyState.vue
- packages/kuma-gui/src/app/zones/locales/en-us/index.yaml
The `XEmptyState` component is auto-filling some content in case the correct locales keys are present. It should only support `x-empty-state`-keys and therefore I've moved everything from `x-growth-empty-state` to `x-empty-state`.
Also there was a tiny typo of the `types`: it should be `zones-crud`, not `zone-crud`.
As next steps we also want to remove everything around crud.
> refactor: remove x-growth-*, improve x-empty-state

- packages/kuma-gui/features/mesh/Item.feature
- packages/kuma-gui/features/mesh/MeshIdentity.feature
- packages/kuma-gui/features/mesh/services/mesh-services/Item.feature
- packages/kuma-gui/src/app/meshes/views/MeshDetailView.vue
- packages/kuma-gui/src/test-support/index.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/meshidentities/_.ts
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/meshtrusts/_.ts
Cherry-pick of https://github.com/kumahq/kuma-gui/commit/3bc1ff4cc3406071b1dad69f39cdcb249a13ab94
>The mtls warning in the `MeshOverview` should only show up if mtls is not configured. With `MeshIdentity` as issuer the >`mtls` field in `/meshes/{mesh}` is not set, so we also have to check for `MeshIdentity`s.
>
><img width="2688" height="600" alt="image"
>src="https://github.com/user-attachments/assets/154ae3d0-ec12-429c-97b1-d2fd72b1c379" />
>
>---
>
>We've decided to take this a little further. We want to move the list of `MeshIdentity`s to the `mTLS` part of the about >section. Also the `MeshTrust` listing will only be rendered conditionally in case there is at least one `MeshTrust` resource.
> fix(mesh): mtls warning shows up with mesh identity (#4203)

- .github/renovate.json
Moves node to always require dashboardApproval, this hopefully always means its in a separate PR on its own and we choose when it gets updated.
> chore(deps): move node to always require separate approval

- .github/renovate.json
See title.
I think the grouping will be fixed by this reordering because
>packageRules is a collection of rules, that are all evaluated. If multiple rules match a dependency, configurations from matching rules will be merged together. **The order of rules matters, because later rules may override configuration options from earlier ones, if they both specify the same option.**
https://docs.renovatebot.com/configuration-options/#packagerules
Still not 100% sure though... 🤞
> chore(renovate): reorder packageRules

- packages/kuma-gui/features/mesh/MeshIdentity.feature
- packages/kuma-gui/features/mesh/MeshTrust.feature
- packages/kuma-gui/src/app/legacy-data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/meshes/views/MeshDetailView.vue
- packages/kuma-gui/src/app/resources/data/MeshIdentity.ts
- packages/kuma-gui/src/app/resources/data/MeshTrust.ts
- packages/kuma-gui/src/app/resources/routes.ts
- packages/kuma-gui/src/app/resources/sources.ts
- packages/kuma-gui/src/app/resources/views/MeshIdentitySummaryView.vue
- packages/kuma-gui/src/app/resources/views/MeshTrustSummaryView.vue
- packages/kuma-gui/src/test-support/mocks/src/meshes/_/meshtrusts/_/_.ts
We decided to use `kri`s as is whenever possible. The first and probably easiest places where we can do this is the new resources `MeshIdentity` and `MeshTrust` which have been lately being added within the context of `kri`s.
There are still some places that require the `name` instead of the `kri`, but at the very least we are trying to remove the parsing of `kri`s from the views and only keep it in the data-layer and sources.
The following routes now expect a `kri`:
- `mesh-identity-summary-view`: `/meshes/:mesh/meshidentities/:mid` - `:mid` is expected to be a `kri`
- `mesh-trust-summary-view`: `/meshes/:mesh/meshtrusts/:mtrust` - `:mtrust` is expected to be a `kri`
For both `MeshTrust` and `MeshIdentity` I've added to build a `kri` from the provided data and add it to the returned data …
> refactor(resources/routes): use kri for routing of mid and mtrust

- packages/kuma-gui/src/app/application/index.ts
- packages/kuma-gui/src/app/control-planes/features.ts
- packages/kuma-gui/src/app/data-planes/features.ts
- packages/kuma-gui/src/app/external-services/features.ts
- packages/kuma-gui/src/app/external-services/index.ts
- packages/kuma-gui/src/app/legacy-data-planes/views/DataPlaneRouteGuard.vue
- packages/kuma-gui/src/app/services/features.ts
- packages/kuma-gui/src/app/services/index.ts
- packages/kuma-gui/src/app/services/routes.ts
- packages/kuma-gui/src/app/zones/features.ts
- packages/kuma-gui/src/app/zones/routes.ts
- packages/settings/src/can/index.spec.ts
- packages/settings/src/can/index.ts
`can()` has always accepted any strings (and number of arguments), if a 'feature'/'ability' didn't exist then we would return `false` i.e. non-existence meant not enabled.
This PR uses declarations to make `can` autocompletable/type-checked instead by using composable TS interfaces and `declare` to amend `can`s definition after initial declaration.
My main goals here are:
- Add typechecking etc to `can` from The Outside
- Keep our existing composable nature of `can`
- Make it as automatic as possible, I shouldn't have to repeat all the feature declarations, hence the utility type.
I eventually plan on re-building `env()` to use a similar approach, thus finally making env composable also.
- There is a ts-ignore here https://github.com/kumahq/kuma-gui/pull/4194/files#diff-5fd72b2766aa02f5cdb …
> chore: improve typing of can utility

- packages/kuma-gui/src/app/kuma/components/ApplicationShell.vue
The main content element currently doesn't fill up the viewport if there is not enough content. This leads to some UX issues when it comes to closing a summary drawer via clicking outside of the summary container element.
> fix(application-shell): main content element doesnt fill up viewport

- packages/kuma-gui/features/mesh/dataplanes/Subscriptions.feature
- packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryClustersView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryStatsView.vue
- packages/kuma-gui/src/app/connections/views/ConnectionInboundSummaryXdsConfigView.vue
- packages/kuma-gui/src/app/data-planes/data/DataplaneNetworking.ts
- packages/kuma-gui/src/app/data-planes/views/DataPlaneDetailView.vue
- packages/kuma-gui/src/app/data-planes/views/DataPlaneTrafficSummaryView.vue
- packages/kuma-gui/src/app/data-planes/views/DataplanePolicyConfigSummaryView.vue
- packages/kuma-gui/src/app/legacy-data-planes/views/DataPlaneDetailView.vue
- packages/kuma-http-api/mocks/src/meshes/_/dataplanes/_/_layout.ts
- packages/kuma-http-api/mocks/src/meshes/_/dataplanes/_/_overview.ts
https://github.com/kumahq/kuma-gui/pull/4228 added a new XDl component, one of the reasons for having this was to have a simpler/more-grokkable way to author `dl` type lists.
One area of code where I thought it might prove helpful was our new DataPlaneDetailView.vue, so I figured I'd do an initial rollout here to get a feel for it. Once I'd done this I kinda went a bit further after realizing a few things, and because of this I've split this PR up into commits so its easier to see the other refactors/reorgs.
All in all we've discussed this page a little in regards to it being a little more grokkable and I wanted to see if it could be improved without resorting to splitting things up into a number of smaller single-use somponents.
Rough list of changes:
- Move DefinitionCard usage to XDl …
> chore: integrate XDl into DataPlaneDetailView

- packages/kuma-gui/src/app/policies/components/PolicyActionGroup.vue
- packages/kuma-gui/src/app/policies/index.ts
- packages/kuma-gui/src/app/policies/locales/en-us/index.yaml
- packages/kuma-gui/src/app/policies/views/PolicyDetailTabsView.vue
- packages/kuma-gui/src/app/policies/views/PolicyListView.vue
A while back we decided to put all menu like "ActionGroups" into their own individual component per resource (or "resource collection" in the case of "policies")
This PR adds a PolicyActionGroup for policies
> chore: adds PolicyActionGroup
